### ISSUE TITLE
userscloud.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#10]
### Basic Information

**Test link:** `http://userscloud.com/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.36

**Comment by jspenguin2017** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/44435286-7d2dba80-a56c-11e8-98a6-c6886a1e9971.png)
