### ISSUE TITLE
gamerevolution.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1003]
### Basic Information

**Test link:** `https://www.gamerevolution.com/guides/507233-devil-may-cry-5-how-to-change-costumes-unlock#/slide/1`
**Category:** anti-adblock
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.128

**Comment by jspenguin2017** [comment]
@mapx- That breaks the page.

**Comment by mapx-** [comment]
What is broken ? some gallery ?

**Comment by jspenguin2017** [comment]
The gallery is still not working correctly. You need to click the button twice for the image to move.

**Comment by mapx-** [comment]
now seems working fine

**Comment by jspenguin2017** [comment]
Yea, it's working now.
