### ISSUE TITLE
lezpop.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1006]
### Basic Information

**Test link:** `https://www.lezpop.it/diavoletta87-ovvero-chiara-ferragni-10-anni-unantenata-khy-ri-ovvero/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
This may need some generic solutions treatment.
