### ISSUE TITLE
soccershows.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1008]
### Basic Information

**Test link:** `http://www.soccershows.xyz/events-match-12216438.php`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 11895.58.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.68 Safari/537.36
**Extension:** Nano Defender 15.0.0.129

**Comment by okiehsch** [comment]
Fixed.
