### ISSUE TITLE
email.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1011]
### Basic Information

**Test link:** `https://www.email.it/mail.php`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.127

### Additional Message

Advice discardable until 09/05/2019 then adblock removal mandatory to access the mailbox

**Comment by jspenguin2017** [comment]
@mapx- @okiehsch This comes up every time and they say it'll become hard anti-adblock later.

**Comment by mapx-** [comment]
Now it's fixed, do you still get anti adb messages ?

**Comment by okiehsch** [comment]
I think he means that it is fixed in annoyances and not in uBO-filters.

**Comment by mapx-** [comment]
oh .. could be they will change the current trick !?

**Comment by okiehsch** [comment]
Don't you get the message after every page load even if you dismiss the message?
Maybe it is different if one has an account but if not it should be fixed in uBO-filters.

**Comment by mapx-** [comment]
moved to ublock filters
