### ISSUE TITLE
memoryhackers.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1012]
### Basic Information

**Test link:** `https://memoryhackers.org/adblock/`
**Category:** ads
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.105 Safari/537.36 Vivaldi/2.4.1488.38
**Extension:** Nano Defender 15.0.0.129

**Comment by okiehsch** [comment]
Fixed.
