### ISSUE TITLE
mopo.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1014]
### Basic Information

**Test link:** `https://www.mopo.de/hamburg/polizei/drohen-hamburg-heftige-krawalle--pegida-chef-will-vor-roter-flora-demonstrieren-32389536`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Adblocker 1.0.0.103

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/90e2110c46bdeeb9f0049f2b7fc15fbe8045b162
