### ISSUE TITLE
youmath.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1018]
### Basic Information

**Test link:** `https://www.youmath.it`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

Original URL: `https://www.youmath.it/lezioni/analisi-matematica.html`

**Comment by mapx-** [comment]
no anti-adblock for me

**Comment by jspenguin2017** [comment]
`t: other`: anti-select

**Comment by jspenguin2017** [comment]
I can't reproduce anti-adblock neither. 
![image](https://user-images.githubusercontent.com/7283682/56330692-6e70c500-6146-11e9-82e3-e8569ae988d5.png)
