### ISSUE TITLE
haaretz.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1019]
### Basic Information

**Test link:** `https://www.haaretz.com/hblocked?returnTo=http%3A%2F%2Fwebcache.googleusercontent.com%2Fsearch%3Fq%3Dcache%253Ahttps%253A%252F%252Fwww.haaretz.com%252Fisrael-news%252F.premium-rabbinical-high-court-reinstates-revoked-conversion-1.5430693%26rlz%3D1C1CHBF_enGB840GB840%26oq%3Dcache%253Ahttps%253A%252F%252Fwww.haaretz.com%252Fisrael-news%252F.premium-rabbinical-high-court-reinstates-revoked-conversion-1.5430693%26aqs%3Dchrome..69i57j69i58.2998j0j4%26sourceid%3Dchrome%26ie%3DUTF-8`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.129

### Additional Message

Google cache of haaretz.

**Comment by okiehsch** [comment]
Fixed.
