### ISSUE TITLE
berliner-zeitung.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1020]
### Basic Information

**Test link:** `https://www.berliner-zeitung.de/berlin/verkehr/keine-starts-und-landungen-defekter-luftwaffen-jet-blockiert-flugverkehr-in-schoenefeld-32385002`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.129

### Additional Message

New anti-adblock is operational on berliner-zeitung.de.

**Comment by okiehsch** [comment]
Fixed.
