### ISSUE TITLE
eplfootballmatch.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1021]
### Basic Information

**Test link:** `https://eplfootballmatch.com/serie-a-highlights-show-15-april-2019/`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.129

**Comment by okiehsch** [comment]
Fixed.
