### ISSUE TITLE
usgamer.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1023]
### Basic Information

**Test link:** `https://www.usgamer.net/articles/nintendo-switch-pro-delay-lite-dock-report`
**Category:** anti-adblock
**Reported from:** Costa Rica
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 9; SM-G950U1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.90 Mobile Safari/537.36
**Extension:** Nano Defender 15.0.0.132

### Additional Message

When Adblock is on

**Comment by jspenguin2017** [comment]
Works fine for me. Although there's an ads placeholder. 
![image](https://user-images.githubusercontent.com/7283682/56477176-e2211380-645f-11e9-9f65-c4a3f66f3d52.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.usgamer.net/articles/why-some-super-mario-maker-2-players-are-thinking-about-going-back-to-the-original`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.153

### Additional Message

**Comment by jspenguin2017** [comment]
Still can't reproduce anti-adblock.

**Comment by DandelionSprout** [comment]
No current placeholders that I can see. One thing that looked like a large placeholder, turned out to be a YouTube embed which `USgamer` was refusing to load until cookies had been accepted; I've reported it to *I Don't Care About Cookies*.
