### ISSUE TITLE
breviewofd.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1027]
### Basic Information

**Test link:** `http://breviewofd.com/e58lsk5tT4`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 8.0.0; F8331) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 YaBrowser/19.3.6.275.00 Mobile Safari/537.36
**Extension:** Nano Adblocker 1.0.0.104

### Additional Message

anti adblock

**Comment by okiehsch** [comment]
Fixed.
