### ISSUE TITLE
dlkoo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1028]
### Basic Information

**Test link:** `https://www.dlkoo.com/down/downfile.asp?did=275665`
**Category:** anti-adblock
**Reported from:** China
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.132

**Comment by jspenguin2017** [comment]
@okiehsch Popup?

**Comment by okiehsch** [comment]
Is this not fixed in the regional list?

**Comment by jspenguin2017** [comment]
Ops, forgot to check that. 

Fixed by Chinese regional filters.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.dlkoo.com/down/downfile.asp?did=392972`
**Category:** anti-adblock
**Reported from:** China
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.137

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.dlkoo.com/down/index.asp?act=search&movskey=%E6%81%90%E6%80%96`
**Category:** anti-adblock
**Reported from:** China
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.140

### Additional Message

**Comment by jspenguin2017** [comment]
@okiehsch These should be numbers. Russian regional filters did not help. 
![image](https://user-images.githubusercontent.com/7283682/57268176-125fd900-7040-11e9-858e-606c3d4fc43c.png)

**Comment by jspenguin2017** [comment]
@okiehsch Popup on homepage (`https://www.dlkoo.com/down/`), regional filters no longer work.

**Comment by okiehsch** [comment]
Fixed.
