### ISSUE TITLE
heslydoge.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1029]
### Basic Information

**Test link:** `http://www.heslydoge.xyz/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.132

**Comment by okiehsch** [comment]
Fixed.
