### ISSUE TITLE
autocar.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1032]
### Basic Information

**Test link:** `https://www.autocar.co.uk/car-news/motorsport/jamie-chadwick-qa-why-she%E2%80%99s-racing-w-series`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.129

### Additional Message

Anti adblock still working ont the website, even with nano defender

**Comment by mapx-** [comment]
fixed
