### ISSUE TITLE
boycracked.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1034]
### Basic Information

**Test link:** `https://boycracked.com/`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.129

### Additional Message

Original URL: `https://boycracked.com/2017/05/24/official-gapps-for-android-4-1-2-jellybean-flashable-zip/`

**Comment by okiehsch** [comment]
Fixed.
