### ISSUE TITLE
minecraft-schematics.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1041]
### Basic Information

**Test link:** `https://www.minecraft-schematics.com/schematic/5334/download/`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.133

### Additional Message

Will not download if adblock is on.

**Comment by okiehsch** [comment]
Fixed.
