### ISSUE TITLE
shortlink.win

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1044]
### Basic Information

**Test link:** `http://shortlink.win/eT4aSO`
**Category:** ads
**Reported from:** Denmark
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.91 Safari/537.36
**Extension:** Nano Defender 15.0.0.133

### Additional Message

popup

**Comment by mapx-** [comment]
fixed
