### ISSUE TITLE
discordemoji.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1045]
### Basic Information

**Test link:** `https://discordemoji.com/packs`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.133

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/56477986-99ba2380-6468-11e9-801d-0bb4925997a2.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://discordemoji.com/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.137

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://discordemoji.com/packs`
**Category:** anti-adblock
**Reported from:** Croatia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3800.0 Safari/537.36 Edg/76.0.172.0
**Extension:** Nano Defender 15.0.0.150

### Additional Message

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://discordemoji.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Original URL: `https://discordemoji.com/category/13/pepe`

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://discordemoji.com/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Original URL: `https://discordemoji.com/category/4/anime`

The webiste is using an Anti-adblock.

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://discordemoji.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.169

### Additional Message

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://discordemoji.com/emoji/5617_SleepingKirby`
**Category:** anti-adblock
**Reported from:** Ukraine
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
**Extension:** Nano Defender 15.0.0.177

### Additional Message

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://discordemoji.com/emoji/bongocat`
**Category:** anti-adblock
**Reported from:** Ukraine
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by jspenguin2017** [comment]
Ads placeholder fixed, can't reproduce anti-adblock.
