### ISSUE TITLE
husseinezzat.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1047]
### Basic Information

**Test link:** `https://www.husseinezzat.com/`
**Category:** anti-adblock
**Reported from:** Algeria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.132

### Additional Message

Original URL: `https://www.husseinezzat.com/2018/06/bittorrent-pro-7103.html`

**Comment by jspenguin2017** [comment]
Also blocks right-click and hotkeys

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click and anti-select
