### ISSUE TITLE
macombdaily.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#105]
### Basic Information

**Test link:** `https://www.macombdaily.com/news/local/warren-mayor-fouts-seeks-state-of-emergency-declaration-over-i/article_2e5116fa-bb7e-11e8-b5e9-d71ceaed4c03.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.45

**Comment by jspenguin2017** [comment]
@okiehsch Comes up every refresh. 
![image](https://user-images.githubusercontent.com/7283682/45720131-4ee9cd80-bb60-11e8-9ffe-d4aab4fa1087.png)

**Comment by okiehsch** [comment]
Fixed.
