### ISSUE TITLE
linuxliteos.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1051]
### Basic Information

**Test link:** `https://www.linuxliteos.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.91 Safari/537.36
**Extension:** Nano Defender 15.0.0.133

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance banner.

**Comment by okiehsch** [comment]
Fixed.
