### ISSUE TITLE
villatalk.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1056]
### Basic Information

**Test link:** `https://www.villatalk.com/topic/16528-john-terry/page/202/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.137

### Additional Message

still get adblock warning even after clicking ok and then going to another thread and adblock warning pops up again

**Comment by okiehsch** [comment]
Fixed.
