### ISSUE TITLE
hdstreams.club

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1057]
### Basic Information

**Test link:** `http://hdstreams.club/hd/ch1.php`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.91 Safari/537.36
**Extension:** Nano Defender 15.0.0.137

### Additional Message

Popup on page refresh/load

**Comment by mapx-** [comment]
fixed
