### ISSUE TITLE
kolumbus.fi

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1059]
### Basic Information

**Test link:** `http://www.kolumbus.fi/leif.snellman/`
**Category:** breakage
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

Blocks the visitor counter.

**Comment by mapx-** [comment]
fixed
