### ISSUE TITLE
dell.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1060]
### Basic Information

**Test link:** `https://www.dell.com/en-ca/learn/finance-and-rewards/rewards-details?~ck=mn`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3772.0 Safari/537.36
**Extension:** Nano Defender 15.0.0.137

### Additional Message

page appears incorrect

**Comment by jspenguin2017** [comment]
I don't see what's wrong. 
![image](https://user-images.githubusercontent.com/7283682/57054783-f7622300-6c53-11e9-9e76-da78bdc5b6ac.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.dell.com/en-au/shop/partsbytype/batteryselector`
**Category:** breakage
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message
