### ISSUE TITLE
mundo-azbox.forumeiros.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1066]
### Basic Information

**Test link:** `http://mundo-azbox.forumeiros.com/t3546-azamerica-s1001-v1-09-14742-05`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.104

### Additional Message

ads placeholders

**Comment by jspenguin2017** [comment]
@okiehsch A red floating box, regional filter does not handle it.

**Comment by okiehsch** [comment]
`mundo-azbox.forumeiros.com###topbar`

**Comment by DandelionSprout** [comment]
Placeholders:
```
! https://mundo-azbox.forumeiros.com/t3546-azamerica-s1001-v1-09-14742-05
mundo-azbox.forumeiros.com##script[src^="https://partner.googlead"]:upward(1)
mundo-azbox.forumeiros.com###topbar:upward(2)
mundo-azbox.forumeiros.com##script[src*="boo-box"]:upward(2)
mundo-azbox.forumeiros.com###main-content > .module
mundo-azbox.forumeiros.com##a[href*="azbox.w.pw"]:upward(1)
mundo-azbox.forumeiros.com##h9:upward(2)
```

**Comment by llacb47** [comment]
```
mundo-azbox.forumeiros.com##script[src*="googleadservices"]:upward(.module)
mundo-azbox.forumeiros.com###topbar
mundo-azbox.forumeiros.com##script:upward([class^="main"]):not(.paged):not(>form)
```
