### ISSUE TITLE
warszawawpigulce.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#107]
### Basic Information

**Test link:** `https://warszawawpigulce.pl/nowa-biedronka-w-scislym-centrum-warszawy/`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
**Extension:** Nano Defender 15.0.0.45

### Additional Message

It removes content of the article, only title is preserved.

**Comment by jspenguin2017** [comment]
@okiehsch Broken if regional filters are enabled.

**Comment by okiehsch** [comment]
Fixed.

@MajkiIT
`warszawawpigulce.pl##.code-block-5, .eklama, #undermenu-block, .code-block-6`
breaks the site

**Comment by jspenguin2017** [comment]
Closing in 4 days.

**Comment by MajkiIT** [comment]
@jspenguin2017 I fixed it.
