### ISSUE TITLE
myfreeblack.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1074]
### Basic Information

**Test link:** `https://www.myfreeblack.com/wanking-xxx-videos/p/7`
**Category:** anti-adblock
**Reported from:** China
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.137

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
If you viewed the link and see that I'm missing the `nsfw` tag, can you let me know? 
I'm trying to get NanoMeow to automatically tag it but so far I don't see an easy way to implement it...

**Comment by okiehsch** [comment]
Sure, no problem.
