### ISSUE TITLE
auto-data.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1075]
### Basic Information

**Test link:** `https://www.auto-data.net/it/toyota-auris-ii-facelift-2015-1.6-d-4d-112hp-start-stop-edit-22618`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.137

**Comment by okiehsch** [comment]
Fixed.
