### ISSUE TITLE
payeer-gift.ru

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1077]
### Basic Information

**Test link:** `http://payeer-gift.ru/?r=877`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.104

### Additional Message

ads placeholders

**Comment by jspenguin2017** [comment]
@okiehsch Non-trivial amount of placeholders, also sometimes a few ads are not blocked. Tried regional filter.

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholders:
```
! http://payeer-gift.ru/?r=877
payeer-gift.ru##.banner
payeer-gift.ru###hidden_link
payeer-gift.ru##.rbrocks
payeer-gift.ru###surfbe
payeer-gift.ru##.linkslot-h
```

**Comment by llacb47** [comment]
```
payeer-gift.ru##[id^="linkslot_"]:upward(2)
payeer-gift.ru##div[style^="width:468px; "]
payeer-gift.ru###hidden_link1:style(display:block!important)
```
