### ISSUE TITLE
open-live.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1078]
### Basic Information

**Test link:** `https://www.open-live.org/it/rai-1-in-diretta-estero/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.137

### Additional Message

ads placeholders

**Comment by okiehsch** [comment]
Fixed popup, site won't load properly on my end, so more filters could be needed.

**Comment by mapx-** [comment]
The channel is running well for me

**Comment by jspenguin2017** [comment]
It has some ads placeholders. Not very important, we'll worry about them later.

**Comment by jspenguin2017** [comment]
Ads placeholders split into another issue.

**Comment by jspenguin2017** [comment]
https://github.com/NanoMeow/QuickReports/issues/3569
