### ISSUE TITLE
descarga-animex.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#108]
### Basic Information

**Test link:** `https://descarga-animex.blogspot.com/`
**Category:** anti-adblock
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
**Extension:** Nano Defender 15.0.0.45

**Comment by jspenguin2017** [comment]
Also anti-right click.
