### ISSUE TITLE
asianhobbyist.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1081]
### Basic Information

**Test link:** `https://www.asianhobbyist.com/`
**Category:** anti-adblock
**Reported from:** Venezuela
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.104

**Comment by okiehsch** [comment]
Fixed.
