### ISSUE TITLE
hackingleaks.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1084]
### Basic Information

**Test link:** `https://hackingleaks.com/forum/`
**Category:** anti-adblock
**Reported from:** Thailand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.137

### Additional Message

Original URL: `https://hackingleaks.com/forum/29-other-dumps/?sortby=start_date&sortdirection=desc&page=1`

**Comment by okiehsch** [comment]
Fixed in annoyances.
