### ISSUE TITLE
solarmovie.to

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1087]
### Basic Information

**Test link:** `https://solarmovie.to/movie/glass-2019-27729/1-1/watching.html`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.137

### Additional Message

redirects when starting movie

**Comment by okiehsch** [comment]
Fixed.
