### ISSUE TITLE
smotretanime.ru

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1088]
### Basic Information

**Test link:** `https://smotretanime.ru/`
**Category:** anti-adblock
**Reported from:** Russia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.137

**Comment by jspenguin2017** [comment]
@okiehsch Broken by Russian regional filters. 
![image](https://user-images.githubusercontent.com/7283682/57990241-fad21880-7a61-11e9-8678-21c5fb549357.png)

**Comment by okiehsch** [comment]
Fixed.
