### ISSUE TITLE
duellinksmeta.com

### ISSUE THREAD

**Issue by ryanlikessquirrels** [NanoMeow/QuickReports#1094]

**Comment by jspenguin2017** [comment]
Only bots may create new issues in this repository.

Humans must create issues in the Nano Filters repository: https://github.com/NanoAdblocker/NanoFilters/issues

**Comment by jspenguin2017** [comment]
Only bots may create new issues in this repository, humans must create issues in the [NanoFilters repository](https://github.com/NanoAdblocker/NanoFilters/issues). 

If you are a bot, inform your creator that you are not registered. Open an issue in the [NanoCore repository](https://github.com/NanoAdblocker/NanoCore/issues) for further information about bots registration.
