### ISSUE TITLE
tutorialrepublic.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#11]
### Basic Information

**Test link:** `https://www.tutorialrepublic.com/faq.php`
**Category:** other
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.36

### Additional Message

Leftover ads placeholders

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/44435267-68512700-a56c-11e8-8b26-72ca693d55de.png)

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets#uassets
````
If an issue can be fixed without using extended syntax, i.e. script:inject, redirect or procedural cosmetic filters the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

Issues involving

anti-adblock
ad-reinsertion
popups/popunders
site breakage
will always be fixed in uAssets even if they don't require extended syntax.
````

**Comment by okiehsch** [comment]
````
tutorialrepublic.com##.leaderboard
tutorialrepublic.com##.sidebar
````
fixes the issue.

**Comment by jspenguin2017** [comment]
OK, looks like it's good.

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/44613321-22e06400-a7cf-11e8-9d7f-be08818e436c.png)
