### ISSUE TITLE
viralnewsdigger.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1102]
### Basic Information

**Test link:** `https://viralnewsdigger.blogspot.com/2017/12/2018s-biggest-fitness-trends-tried-and.html`
**Category:** ads
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.105

### Additional Message

ads space

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholders:
```
viralnewsdigger.blogspot.com##div[name="Header Ads"]
viralnewsdigger.blogspot.com##.HTML:has(span:has-text(/^Sponsor$/))
```
