### ISSUE TITLE
depositfiles.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1105]
### Basic Information

**Test link:** `https://depositfiles.org/files/cgo3j9i2g`
**Category:** anti-adblock
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.139

**Comment by okiehsch** [comment]
Fixed.
