### ISSUE TITLE
iptvtools.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1106]
### Basic Information

**Test link:** `http://www.iptvtools.net/`
**Category:** anti-adblock
**Reported from:** Pakistan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.139

### Additional Message

Only recently I have encountered this. Previously was working fine.

**Comment by okiehsch** [comment]
Fixed.
