### ISSUE TITLE
vidlox.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1109]
### Basic Information

**Test link:** `https://vidlox.tv/apiwh2ihkt43`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.139

### Additional Message

popups when click play

**Comment by okiehsch** [comment]
Fixed.
