### ISSUE TITLE
live.bleacherreport.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#111]
### Basic Information

**Test link:** `https://live.bleacherreport.com/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.45

### Additional Message

Nothing appears to load/possibly all blocked

**Comment by ZaphodBeebblebrox** [comment]
`@@||ugdturner.com^$script,domain=live.bleacherreport.com` for breakage and `@@||v.fwmrm.net/crossdomain.xml$xmlhttprequest,domain=live.bleacherreport.com` for the anti-adblock? With those filters I get a your preview has expired message, so I am not certain if  everything works.

**Comment by jspenguin2017** [comment]
I have too much homework this week, I hope I can come around to flush the backlog by the end of the month.

**Comment by jspenguin2017** [comment]
I don't see anything wrong with the fix.
