### ISSUE TITLE
dailycamera.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1112]
### Basic Information

**Test link:** `https://www.dailycamera.com/2019/04/27/one-year-later-a-look-back-at-the-intertwined-lives-and-deaths-of-two-boulder-county-residents/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.137

**Comment by okiehsch** [comment]
Fixed.
