### ISSUE TITLE
nodkey.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1113]
### Basic Information

**Test link:** `https://www.nodkey.xyz/`
**Category:** anti-adblock
**Reported from:** Peru
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.139

**Comment by mapx-** [comment]
fixed
