### ISSUE TITLE
dcdirtylaundry.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1114]
### Basic Information

**Test link:** `https://dcdirtylaundry.com/`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.139

### Additional Message

Just noticed the website knew I was using an adblocker.

**Comment by mapx-** [comment]
fixed as annoyance
