### ISSUE TITLE
bestlink.ovh

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1115]
### Basic Information

**Test link:** `https://bestlink.ovh/CBrfu4zjinx`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.139

**Comment by okiehsch** [comment]
Fixed.
