### ISSUE TITLE
software-on.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1119]
### Basic Information

**Test link:** `https://software-on.com/DownloadON/aHR0cHM6Ly93d3cuZmlsZS11cC5vcmcvanM5dWowODQzeTRj`
**Category:** anti-adblock
**Reported from:** Algeria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.139

**Comment by okiehsch** [comment]
Fixed.
