### ISSUE TITLE
loadvid.online

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#112]
### Basic Information

**Test link:** `https://loadvid.online/v/5ae8812049161`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
**Extension:** Nano Defender 15.0.0.45

**Comment by jspenguin2017** [comment]
One missed ads. 
![image](https://user-images.githubusercontent.com/7283682/46053235-25501980-c0ff-11e8-98c3-79b196499526.png)
![image](https://user-images.githubusercontent.com/7283682/46053332-94c60900-c0ff-11e8-9532-dcb72faf945a.png)

**Comment by jspenguin2017** [comment]
Need to clear cookies to reproduce. 
![image](https://user-images.githubusercontent.com/7283682/46053387-d48cf080-c0ff-11e8-9d4c-bb4d4e0e9f42.png)

**Comment by jspenguin2017** [comment]
@okiehsch Anti-right click annoyance.

**Comment by okiehsch** [comment]
Fixed,

**Comment by jspenguin2017** [comment]
@ryanbr Overlay ads: `loadvid.online###overlay-vcplayer`

**Comment by okiehsch** [comment]
I don't get any overlay ads.
![image](https://user-images.githubusercontent.com/16838044/46908545-a80d0d00-cf24-11e8-81d5-297b1fb55718.png)

**Comment by jspenguin2017** [comment]
It only show up once. Try incognito mode.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/46908579-29fd3600-cf25-11e8-9067-052557267541.png)

**Comment by jspenguin2017** [comment]
Weird... I can still reproduce it. The image is from Imgur, `https://i.imgur.com/SpJhKYa.jpg`. 

Imgur ToS forbid uploading ads, so I'll just report the image and hope that it'll be taken down 😄

**Comment by jspenguin2017** [comment]
Image no longer exists. Closing.
