### ISSUE TITLE
torontosun.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1125]
### Basic Information

**Test link:** `https://torontosun.com/2012/08/28/missing-woman-unwittingly-joins-search-party-for-herself/wcm/5384079e-011f-439e-84eb-049d87c33b32`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.139

**Comment by okiehsch** [comment]
Fixed.
