### ISSUE TITLE
turbogvideos.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1130]
### Basic Information

**Test link:** `http://turbogvideos.com/next-door-studios-1/2019/05/derek-hart.html`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.139

### Additional Message

When UBO is turned on and after clicking the Player 1 button, the following screenshot will appear. After adblock is turned off, the playback is normal.

`https://i.loli.net/2019/05/03/5ccb83c6b7c2d.png`

**Comment by okiehsch** [comment]
This is NSFW.

**Comment by okiehsch** [comment]
Fixed.
