### ISSUE TITLE
aboutchromebooks.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1136]
### Basic Information

**Test link:** `https://www.aboutchromebooks.com/news/chrome-os-72-dev-channel-usb-sd-card-support-project-crostini-chromebooks-android-9-pie/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 11803.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3713.0 Safari/537.36
**Extension:** Nano Defender 15.0.0.139

**Comment by okiehsch** [comment]
Fixed in annoyances.
