### ISSUE TITLE
watplan.waw.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1138]
### Basic Information

**Test link:** `http://www.watplan.waw.pl/index.php?group=H6D2S1`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.139

**Comment by okiehsch** [comment]
Fixed.
