### ISSUE TITLE
eazycheat.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1154]
### Basic Information

**Test link:** `https://www.eazycheat.com/2017/09/pewdiepies1122.html`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Defender 15.0.0.139

**Comment by mapx-** [comment]
fixed
