### ISSUE TITLE
moat.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1157]
### Basic Information

**Test link:** `https://moat.com/`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.139

### Additional Message

The website detects that I am using an ad blocker

**Comment by mapx-** [comment]
fixed
