### ISSUE TITLE
armadaboard.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1159]
### Basic Information

**Test link:** `https://www.armadaboard.com/viewtopic.php?t=57679`
**Category:** ads
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.18 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.106

### Additional Message

ads placeholder

**Comment by jspenguin2017** [comment]
Ads placeholder.

**Comment by DandelionSprout** [comment]
Placeholder: `armadaboard.com##td[style*="theme_orig"] > table:has(strong:has-text(Генеральный спонсор))`
