### ISSUE TITLE
dielochis.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#116]
### Basic Information

**Test link:** `https://dielochis.de/mediathek/w/d73f540e-a37f-4d27-8c7f-24c20ebea4fa`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.45

**Comment by ZaphodBeebblebrox** [comment]
@monzta Broken video player.
```
@@||media.oadts.com/www/delivery/video.php$script,domain=dielochis.de
@@||media.oadts.com/www/delivery/afv.php$subdocument,domain=dielochis.de
```
