### ISSUE TITLE
skysportaustria.at

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1160]
### Basic Information

**Test link:** `https://www.skysportaustria.at/bundesliga-at/sturm-gewinnt-in-unterzahl-in-st-poelten/`
**Category:** breakage
**Reported from:** Austria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.18 Safari/537.36 Edg/75.0.139.4
**Extension:** Nano Adblocker 1.0.0.104

### Additional Message

Videos are not shown

**Comment by jspenguin2017** [comment]
@okiehsch Tried Germany regional filters.

**Comment by okiehsch** [comment]
Fixed.
