### ISSUE TITLE
linnk.info

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1161]
### Basic Information

**Test link:** `https://linnk.info/f1/?h=d108f6bd376eedc4dc83b57ad4358555&id=b0QzOVJtbDIrWkdkYVFrYk5TZmx2bkVrRFpSZ2g4MXNhWnc1S3ZyZ08zTnhhR0ZuVFhwb2QxaGFkSE00VERBd1Iza3lVMlkzY2t4amRIVkRSWE0yU1RKM2VuUlphVzFoVm5oUWExRmpObkpGWkdkdksydEtiRVV3Y0ROa1RrTmo=`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 9; Mobile; rv:66.0) Gecko/66.0 Firefox/66.0
**Extension:** Nano Defender 15.0.0.139

### Additional Message

Infinite reloading by cloudflare ddos protection.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://linnk.info/f1/?h=48c686e840732bc2a590c134768e20fd&id=eW5DR1dTODNLYnErN01xMmRkWG5ZUDRudkVXTGRyTFk2c295UkZPSEJ5eFlPRUY0VkdsTmFIbFdaVTlxYVc5RlIxWmtZVk5ETTNFdmVFSjRjMDk2VlhWdWRVd3dibU5IVjIxdFdXUjNaMWh0TTNsQmFsSjJkbWN3ZURFNWEwWnM=`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Defender 15.0.0.140

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://linnk.info/f1/?h=d108f6bd376eedc4dc83b57ad4358555&id=L1p5TnRZZk5iU3F3eERHZW92RDlOTG9WU0phRG9UUlhveWpQOHlJNVczMVFSbVYyVjNkWWJsWllabVIzTTBkQ1ZFaHdiVkl2ZWxCVFNtcFdXR0ZXU1dOM04yTTJTSGQ2TkdKMU9YWnhTbEY1TUVkeWVrdDNUbWs1YWpFM1RrNTQ=`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 9; Mobile; rv:66.0) Gecko/66.0 Firefox/66.0
**Extension:** Nano Defender 15.0.0.139

### Additional Message

**Comment by jspenguin2017** [comment]
@okiehsch Can you have a look, does `bab-defuser.js` break Cloudflare? The links here are probably expired, but in guest mode the Cloudflare screen passes.

**Comment by okiehsch** [comment]
Yes.
![image](https://user-images.githubusercontent.com/16838044/57421147-e47ac000-720a-11e9-90c3-05f02a2bc66d.png)

I will change the filter.

**Comment by okiehsch** [comment]
Fixed.
