### ISSUE TITLE
hastingsobserver.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1162]
### Basic Information

**Test link:** `https://www.hastingsobserver.co.uk/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Defender 15.0.0.140

**Comment by okiehsch** [comment]
Fixed.
