### ISSUE TITLE
sung-ji.tistory.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1163]
### Basic Information

**Test link:** `https://sung-ji.tistory.com/114`
**Category:** anti-adblock
**Reported from:** South Korea
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Whale/1.5.71.15 Safari/537.36
**Extension:** Nano Defender 15.0.0.140

### Additional Message

configuration:
nano configured with uBlock Origin 1.18.16

Adblock Warning Removal List​​​​​649개 중 642개 사용 중​​​​
Nano Defender Integration​​​​​2,654개 중 2,544개 사용 중​​​​
Nano Filters​​​​​210개 중 206개 사용 중​​​​
Nano Filters - Whitelist​​​​​1개 중 0개 사용 중​​​​
        userResourcesLocation `https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt`

**Comment by okiehsch** [comment]
Fixed.
