### ISSUE TITLE
warszawa.naszemiasto.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1176]
### Basic Information

**Test link:** `http://warszawa.naszemiasto.pl/artykul/budowa-drugiej-linii-metra-12-maja-rozpocznie-sie-powolny,5111817,art,t,id,tm.html`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Defender 15.0.0.140

### Additional Message

anti adblock

**Comment by krystian3w** [comment]
Fixed with:  https://github.com/olegwukr/polish-privacy-filters/blob/4ebefe7c2cf7e6833099cb25e83969d21e3b221e/anti-adblock-suplement.txt#L39-L40

```
dziennikbaltycki.pl,dzienniklodzki.pl,dziennikpolski24.pl,dziennikzachodni.pl,echodnia.eu,expressbydgoski.pl,expressilustrowany.pl,gazetakrakowska.pl,gazetalubuska.pl,gazetawroclawska.pl,gk24.pl,gloswielkopolski.pl,gol24.pl,gp24.pl,gra.pl,gs24.pl,kurierlubelski.pl,motofakty.pl,naszemiasto.pl,nowiny24.pl,nowosci.com.pl,nto.pl,polskatimes.pl,pomorska.pl,poranny.pl,sportowy24.pl,strefaagro.pl,strefabiznesu.pl,stronakobiet.pl,telemagazyn.pl,to.com.pl,wspolczesna.pl##+js(set-constant.js, pp_adblock_is_off, trueFunc)
||s-pt.ppstatic.pl/*/reklama.js$script,redirect=noopjs,important
````
