### ISSUE TITLE
exprestream.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1178]
### Basic Information

**Test link:** `https://exprestream.com/stream/1/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12105.25.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.19 Safari/537.36
**Extension:** Nano Defender 15.0.0.140

**Comment by okiehsch** [comment]
Fixed.
