### ISSUE TITLE
tivtok.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1179]
### Basic Information

**Test link:** `https://tivtok.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Defender 15.0.0.140

### Additional Message

Displays "It looks like you're using an ad blocker. That's okay. Who doesn't?"

**Comment by okiehsch** [comment]
Fixed.
