### ISSUE TITLE
aporn.webcam

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1181]
### Basic Information

**Test link:** `http://aporn.webcam/location/Yeah`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
**Extension:** Nano Defender 15.0.0.139

**Comment by okiehsch** [comment]
Fixed.
