### ISSUE TITLE
merrell-link.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1183]
### Basic Information

**Test link:** `https://merrell-link.net/e5y0Pmw`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 9; Mobile; rv:66.0) Gecko/66.0 Firefox/66.0
**Extension:** Nano Defender 15.0.0.139

### Additional Message

Captcha won't appear

**Comment by jspenguin2017** [comment]
Can't reproduce breakage, final link `https://www.file-up.org/rrro9y1kfsvs`.

**Comment by jspenguin2017** [comment]
@okiehsch Seems to have a popup when clicking `get link`, can you reproduce?

**Comment by okiehsch** [comment]
Fixed.
