### ISSUE TITLE
hentaifox.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1185]
### Basic Information

**Test link:** `https://hentaifox.com/`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3790.0 Safari/537.36
**Extension:** Nano Defender 15.0.0.140

### Additional Message

anti adblock when detected can not change page when reading comic

**Comment by okiehsch** [comment]
Fixed popup and site breakage.
