### ISSUE TITLE
laluzulfakar.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1186]
### Basic Information

**Test link:** `https://laluzulfakar.com/berita/windows-10-linux-kernel-built-in-wsl-2/?fbclid=IwAR2XvWEY-T0vnAhK2AUakFC-mvYxqkyQPTv-vkZ6-NaK89QogkGKHmWI4B0`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Defender 15.0.0.140

### Additional Message

anti adblock
nano + defender

**Comment by okiehsch** [comment]
Fixed.
