### ISSUE TITLE
arobasenet.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1189]
### Basic Information

**Test link:** `https://www.arobasenet.com/`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.140

**Comment by jspenguin2017** [comment]
@okiehsch
