### ISSUE TITLE
belapendidikan.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1190]
### Basic Information

**Test link:** `https://belapendidikan.com/motivasi-seberapa-tangguhnya-dirimu`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.27 Safari/537.36
**Extension:** Nano Defender 15.0.0.140

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/issues/5489#issuecomment-491151984
```
belapendidikan.com##.majalahpro-core-floatbanner
```

**Comment by jspenguin2017** [comment]
@okiehsch @gmarcher
