### ISSUE TITLE
journalstar.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1193]
### Basic Information

**Test link:** `https://journalstar.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.140

### Additional Message

Anti adblock is quite effective!

**Comment by mapx-** [comment]
```
@@||journalstar.com^$generichide
journalstar.com##.tnt-ads
```
or (general filter):
`||fundingchoicesmessages.google.com^$3p`

to be decided ..
