### ISSUE TITLE
bitarka.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1204]
### Basic Information

**Test link:** `http://bitarka.com/intercultural-poetry-performance-library/`
**Category:** ads
**Reported from:** Switzerland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.27 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.107

### Additional Message

ads placeholder

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholders on frontpage:
```
! https://bitarka.com/
bitarka.com##.penci-adsense-below-slider
bitarka.com##.penci-featured-cat-custom-ads
```

**Comment by jspenguin2017** [comment]
Test link: `http://bitarka.com/`
