### ISSUE TITLE
cinemablend.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1209]
### Basic Information

**Test link:** `https://www.cinemablend.com/television/2471637/stargate-sg-1s-richard-dean-anderson-and-amanda-tapping-have-us-hyped-for-a-comeback`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.140

### Additional Message

It detects as AdBlocker, I hope this helps improve your program.  :D  Good luck

**Comment by mapx-** [comment]
fixed as annoyance (you can click `Continue without supporting`)
