### ISSUE TITLE
firefaucet.win

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#121]
### Basic Information

**Test link:** `https://firefaucet.win/`
**Category:** anti-adblock
**Reported from:** Chile
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.45

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://firefaucet.win/`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

Nano defender is not blocking the detection of Adblock

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://firefaucet.win/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.118

### Additional Message

It detects that I am using an adblocker

**Comment by llacb47** [comment]
Test credentials: 
Username and password: `testacct`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
