### ISSUE TITLE
torrentfunk.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1210]
### Basic Information

**Test link:** `https://www.torrentfunk.com/user/rutor.html?x=n`
**Category:** breakage
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.107

### Additional Message

blocking pages navegation 1,2,3,4...

**Comment by jspenguin2017** [comment]
@okiehsch Breakage. 
![image](https://user-images.githubusercontent.com/7283682/57589359-ecbf4d80-74df-11e9-90b4-29fc2419e8e5.png)

**Comment by okiehsch** [comment]
Fixed.
