### ISSUE TITLE
cyclismactu.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1211]
### Basic Information

**Test link:** `http://www.cyclismactu.net/news-tour-d-italie-viviani-declasse-gaviria-gagne-devant-demare-82987.html`
**Category:** anti-adblock
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.140

**Comment by okiehsch** [comment]
Fixed.
