### ISSUE TITLE
replaytvstreaming.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1213]
### Basic Information

**Test link:** `https://replaytvstreaming.com/`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.140

**Comment by okiehsch** [comment]
Fixed.
