### ISSUE TITLE
vod.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1215]
### Basic Information

**Test link:** `https://vod.pl/playerpl-promocja/programy-online/co-nas-truje-odcinki,10160/odcinek-9,S01E09,97557`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.132
**Extension:** Nano Adblocker 1.0.0.109

### Additional Message

Player is blocked

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/uBlockProtector/commit/85a83ca871d406601422d3a236bbc03df26ec0e2
