### ISSUE TITLE
dnsperf.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1217]
### Basic Information

**Test link:** `https://www.dnsperf.com/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.109

### Additional Message

Original URL: `https://www.dnsperf.com/#!dns-resolvers`

Page content does not properly load with enabled, works fine when disabled.

**Comment by jspenguin2017** [comment]
@okiehsch Breakage.

**Comment by okiehsch** [comment]
Fixed.
