### ISSUE TITLE
javqd.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1218]
### Basic Information

**Test link:** `https://www5.javqd.com/movie/h0930-ki181002-horny-0930-yoshiko-aizawa-44-years-old.html`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Defender 15.0.0.145

**Comment by okiehsch** [comment]
Fixed.
