### ISSUE TITLE
dailythanthi.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1221]
### Basic Information

**Test link:** `https://www.dailythanthi.com/adblock`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.142

**Comment by okiehsch** [comment]
Fixed.
