### ISSUE TITLE
windowcleaningforums.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1222]
### Basic Information

**Test link:** `https://windowcleaningforums.co.uk/topic/12279-painting-window-ledges/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Defender 15.0.0.145

**Comment by okiehsch** [comment]
Fixed.
