### ISSUE TITLE
playstationlifestyle.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1224]
### Basic Information

**Test link:** `https://www.playstationlifestyle.net/2019/03/29/torchlight-2-ps4-launch-fall-2019/#/slide/1`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 9; Tablet; rv:66.0) Gecko/66.0 Firefox/66.0
**Extension:** Nano Defender 15.0.0.142

**Comment by okiehsch** [comment]
Fixed.
