### ISSUE TITLE
muzlan.top

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1225]
### Basic Information

**Test link:** `https://muzlan.top/en/`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 9; ASUS_X00TD) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.136 Mobile Safari/537.36
**Extension:** Nano Defender 15.0.0.145

### Additional Message

Ad blocker detected overlay prompt.

**Comment by okiehsch** [comment]
Fixed.
