### ISSUE TITLE
i-dont-care-about-cookies.eu

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1226]
### Basic Information

**Test link:** `https://www.i-dont-care-about-cookies.eu/`
**Category:** ads
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.27 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.109

### Additional Message

espace vide pour les publicités
EasyList ne veut pas le bloquer

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.i-dont-care-about-cookies.eu/`
**Category:** other
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Adblocker 1.0.0.141

### Additional Message

Hello,
thank you so very much for your great add-on. It might be the best there ist at the moment.
I would like to suggest an option, that automatically accepts the cookies. If you can choose, maybe the plugin automatically chooses the smallest cookie with least data to be submitted. 
As I like to surf with do not track, I have to accept every cookie on nearly every site. Even my own ones. That is so annoying.
thank you
johann weinzierl

**Comment by jspenguin2017** [comment]
https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/50

**Comment by jspenguin2017** [comment]
For https://github.com/NanoMeow/QuickReports/issues/1226#issuecomment-605675163 : 
I need specific test links.

**Comment by DandelionSprout** [comment]
Placeholder: `i-dont-care-about-cookies.eu##.mt-5:has(.adsbygoogle)`

**Comment by DandelionSprout** [comment]
I also get the personal impression that https://github.com/NanoMeow/QuickReports/issues/1226#issuecomment-605675163 managed to mistake Nano's report form for that of IDCAC's.

**Comment by jspenguin2017** [comment]
Hum... When the user clicks the dropdown for "issues type", it should be pretty obvious which extension the form is for. So I think that's unlikely.
