### ISSUE TITLE
beatricedailysun.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1227]
### Basic Information

**Test link:** `https://beatricedailysun.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
**Extension:** Nano Defender 15.0.0.145

**Comment by okiehsch** [comment]
Fixed.
