### ISSUE TITLE
raiplayradio.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1235]
### Basic Information

**Test link:** `https://www.raiplayradio.it/programmi/adaltavoce/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 9; Mobile; rv:66.0) Gecko/66.0 Firefox/66.0
**Extension:** Nano Defender 15.0.0.145

**Comment by okiehsch** [comment]
Fixed.
