### ISSUE TITLE
beautypageants.indiatimes.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1236]
### Basic Information

**Test link:** `https://beautypageants.indiatimes.com/miss-world/this-iranian-model-resembles-aishwarya-rai-bachchan/eventshow/69342364.cms`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.145

### Additional Message

it displays a message that adblocker is detected and blocks the whole page with this message. the message activates if i try to scroll down the page

**Comment by okiehsch** [comment]
Fixed.
