### ISSUE TITLE
freebcc.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1239]
### Basic Information

**Test link:** `https://freebcc.org/about/wDCk`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.145

### Additional Message

Site is using "Block Adblock": `http://blockadblock.com/`

**Comment by okiehsch** [comment]
Fixed.
