### ISSUE TITLE
honeyhunterworld.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1243]
### Basic Information

**Test link:** `https://honeyhunterworld.com/mhwb/?257,114,72,114,86,114,23,health,0,0,4,0,0,0,77,0,49,49,4,50,26,96,14,96,0,4,96,94,3,Close,Close,Shield`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.145

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://honeyhunterworld.com/mhwb/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
**Extension:** Nano Defender 15.0.0.146

### Additional Message

Stops loading the builder when it detects an adblock extension.


>It seems you're using AdBlock or similar browser extension. Please whitelist honeyhunterworld.com and refresh the page.

**Comment by jspenguin2017** [comment]
@okiehsch Anti-adblock.

**Comment by okiehsch** [comment]
Fixed.
