### ISSUE TITLE
quora.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1256]
### Basic Information

**Test link:** `https://www.quora.com/Why-do-people-say-I-could-just-eat-you-up`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.100

### Additional Message

header ad above artcle

**Comment by jspenguin2017** [comment]
I don't see any issues with that webpage.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.quora.com/`
**Category:** breakage
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
**Extension:** Nano Defender 15.0.0.155

### Additional Message

Not able to login

**Comment by jspenguin2017** [comment]
Requires account.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.quora.com/The-U-S-no-longer-possesses-clear-military-technical-dominance-and-China-is-rapidly-emerging-as-a-would-be-superpower-in-science-and-technology-said-Elsa-B-Kania-and-what-do-you-say`
**Category:** other
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.124

### Additional Message

Not blocking ad on here why?

**Comment by jspenguin2017** [comment]
For https://github.com/NanoMeow/QuickReports/issues/1256#issuecomment-527207878 : 
Can't reproduce. I don't see any ads.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.quora.com`
**Category:** other
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

Original URL: `https://www.quora.com/Do-lobsters-and-roaches-taste-the-same`

Hello there, upon clicking to another link within Quora, it displays a blur overlay. I tried using element picker to select the blur overlay to no avail. Any help would be appreciated, thank you!

**Comment by jspenguin2017** [comment]
@okiehsch uBlock filters hides the login model but rules to unblur the page is in the uBlock annoyance filter.

**Comment by okiehsch** [comment]
I can't reproduce. I can see the login model.
![image](https://user-images.githubusercontent.com/16838044/87610330-5ac75c00-c705-11ea-83d4-b09e0e505b77.png)

**Comment by jspenguin2017** [comment]
@okiehsch Try navigating to `https://www.quora.com/Do-lobsters-and-roaches-taste-the-same` then click one of the links on the right sidebar. I can reproduce: 
![image](https://user-images.githubusercontent.com/7283682/87610475-aa386880-c6c2-11ea-8941-90b706cce20c.png)

**Comment by okiehsch** [comment]
I can reproduce. So you think the filter should be in the annoyances list?

**Comment by jspenguin2017** [comment]
@okiehsch It definitely shouldn't be in the base filter, but as for the annoyance filter, you should ask `gorhill`.
