### ISSUE TITLE
piasecznonews.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1257]
### Basic Information

**Test link:** `https://piasecznonews.pl/`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.145

**Comment by jspenguin2017** [comment]
@okiehsch Breakage, image not loading. 
![image](https://user-images.githubusercontent.com/7283682/57986283-3653ef00-7a30-11e9-8288-72389172786a.png)

**Comment by mapx-** [comment]
fixed

**Comment by krystian3w** [comment]
@majkiit?
