### ISSUE TITLE
viu.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1261]
### Basic Information

**Test link:** `https://www.viu.com/ott/hk/zh-hk/vod/142875/1O1Ocsl%E5%91%88%E7%8D%BB-PTU%E6%A9%9F%E5%8B%95%E9%83%A8%E9%9A%8A%E7%B2%B5%E8%AA%9E`
**Category:** breakage
**Reported from:** Hong Kong
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.110

### Additional Message

cannot watch any video while adblocker is enabled.

**Comment by jspenguin2017** [comment]
Requires account.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.viu.com/ott/id/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.155

### Additional Message

vpn from supported country maybe needed to access it

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.viu.com/ott/hk/zh-hk/vod/234167/%E9%91%BD%E7%9F%B3%E7%8E%8B%E7%89%8C-actII`
**Category:** other
**Reported from:** Hong Kong
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

it generate like 2k blocks per second and causing the browser to lag
