### ISSUE TITLE
safebrowsing.google.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1262]
### Basic Information

**Test link:** `https://safebrowsing.google.com/`
**Category:** breakage
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.38 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.110

### Additional Message

the icon for "Ads" is blocked looool

**Comment by jspenguin2017** [comment]
@okiehsch Minor breakage, the AdSense icon is blocked by EasyList generic filter.

**Comment by okiehsch** [comment]
Fixed.
