### ISSUE TITLE
roya.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1263]
### Basic Information

**Test link:** `https://roya.tv/videos/61718`
**Category:** anti-adblock
**Reported from:** Hashemite Kingdom of Jordan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
**Extension:** Nano Defender 15.0.0.147

### Additional Message

i cant open video buz im don't Stop Ad

**Comment by jspenguin2017** [comment]
@okiehsch Anti-adblock. Not caught by regional filters.

**Comment by mapx-** [comment]
fixed
