### ISSUE TITLE
freefaucet.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1264]
### Basic Information

**Test link:** `https://freefaucet.io/ad_block/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3700.0 Iron Safari/537.36
**Extension:** Nano Defender 15.0.0.147

**Comment by okiehsch** [comment]
Fixed.
