### ISSUE TITLE
yesmangasbr.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1266]
### Basic Information

**Test link:** `https://www.yesmangasbr.com/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.147

### Additional Message

Original URL: `about:blank`

The site detects that I'm using an Adblock.

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e9e532b36c2f1ca3fb39933cd0a1972c39d402ec
