### ISSUE TITLE
livesport.ws

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1268]
### Basic Information

**Test link:** `https://livesport.ws/en`
**Category:** ads
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.147

### Additional Message

Background ads.

**Comment by okiehsch** [comment]
Fixed.
