### ISSUE TITLE
myzilina.sme.sk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1276]
### Basic Information

**Test link:** `https://myzilina.sme.sk/c/22127796/tinedzerka-obvinena-z-vrazdy-kamarata-ide-do-vazby.html?ref=njct`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.147

### Additional Message

uBlock detected on firefox
Can I expect Nano defender to work on sme.sk ? Thanks.

**Comment by jspenguin2017** [comment]
See also: https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/43

**Comment by okiehsch** [comment]
Fixed.
