### ISSUE TITLE
ferrovie.info

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1278]
### Basic Information

**Test link:** `https://www.ferrovie.info/index.php/it/34-correva-l-anno/2578-15-marzo-1988-l-alta-velocita-ha-una-nuova-locomotiva-la-e-402-001-video`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 9; Mobile; rv:67.0) Gecko/67.0 Firefox/67.0
**Extension:** Nano Defender 15.0.0.147

**Comment by okiehsch** [comment]
Fixed.
