### ISSUE TITLE
synonyme.woxikon.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1280]
### Basic Information

**Test link:** `https://synonyme.woxikon.de/synonyme/generieren.php`
**Category:** anti-adblock
**Reported from:** Switzerland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Defender 15.0.0.147

**Comment by okiehsch** [comment]
Fixed.
