### ISSUE TITLE
gratisaftehalen.nl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1285]
### Basic Information

**Test link:** `https://www.gratisaftehalen.nl/`
**Category:** anti-adblock
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.147

### Additional Message

Original URL: `https://www.gratisaftehalen.nl/a/tweepersoonsmatras/134129?location=&term=matras`

Anti-adblock is triggered and as a result pictures are not displayed, you get punished for using an ablocker.

**Comment by jspenguin2017** [comment]
@okiehsch Soft anti-adblock.
