### ISSUE TITLE
mysostech.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1298]
### Basic Information

**Test link:** `https://mysostech.com/2018/08/licence-eset-nod-32-cle-activation.html`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109
**Extension:** Nano Defender 15.0.0.147

**Comment by okiehsch** [comment]
Fixed.
