### ISSUE TITLE
kiss-anime.ws

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1300]
### Basic Information

**Test link:** `https://www.kiss-anime.ws/Anime-tate-no-yusha-no-nariagari-episode-20`
**Category:** breakage
**Reported from:** Finland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.112

### Additional Message

While using the flashplayer player, nano blocks the video stream

**Comment by jspenguin2017** [comment]
@okiehsch New domain?

**Comment by okiehsch** [comment]
I can't test anything flash related.

**Comment by jspenguin2017** [comment]
The HTML5 player doesn't work neither.

**Comment by okiehsch** [comment]
The HTML5 Player does not work no matter what on my end.

**Comment by jspenguin2017** [comment]
`t: lesser`: Breakage affecting websites using Flash

**Comment by mapx-** [comment]
fixed
