### ISSUE TITLE
extrafreetv.me

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1305]
### Basic Information

**Test link:** `http://extrafreetv.me/match/sports122.php`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.54 Safari/537.36
**Extension:** Nano Defender 15.0.0.147

### Additional Message

countdown timer to unlock play button, then popup window on click play

**Comment by okiehsch** [comment]
Fixed.
