### ISSUE TITLE
daddylive.live

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1306]
### Basic Information

**Test link:** `https://daddylive.live/channels/stream-13.php`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.54 Safari/537.36
**Extension:** Nano Defender 15.0.0.147

### Additional Message

Popup when click play

**Comment by okiehsch** [comment]
Fixed.
