### ISSUE TITLE
gamersheroes.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1310]
### Basic Information

**Test link:** `http://www.gamersheroes.com/game-guides/where-to-find-crafting-materials-in-assassins-creed-origins/#`
**Category:** breakage
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.147

### Additional Message

I am using Nano Adblocker 1.0.0.112 and Nano Defender 15.0.0.147 with Firefox 67 64-bit. On the page mentioned above the collapsible menus are not able to be opened while adblock is on. As soon as I disable it, the menus work.

**Comment by jspenguin2017** [comment]
@okiehsch 
Breakage. Slideshow not loading on home page `http://www.gamersheroes.com/`. 
![image](https://user-images.githubusercontent.com/7283682/58675192-6f357300-8310-11e9-8728-d0e1fa4ba9ad.png)

Also, `Game Guides` entry on the menu bar should show a dropdown when hovered.

**Comment by okiehsch** [comment]
The site uses yavli, I can remove the csp causing the breakage but you will see reinsertion ads at the link of the OP as a result.

**Comment by jspenguin2017** [comment]
Hum... Can ads reinsertion be blocked with scriptlets?

**Comment by okiehsch** [comment]
Sure I can disable the reinsertion with a scriptlet, the problem is finding one that does not break the page which is more time consuming.
We already have a scriptlet  for yavli sites
`##+js(set-constant.js, String.fromCharCode, noopFunc)`
but that does not work anymore.

**Comment by okiehsch** [comment]
Fixed, for now.

**Comment by dumbusernameidk** [comment]
`http://www.gamersheroes.com/game-guides/where-to-play-blackjack-in-red-dead-redemption-2/`

Ads are back.

**Comment by llacb47** [comment]
Also ads on https://github.com/NanoMeow/QuickReports/issues/4215

**Comment by jspenguin2017** [comment]
See: https://github.com/NanoMeow/QuickReports/issues/4219
