### ISSUE TITLE
medicalnewstoday.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1311]
### Basic Information

**Test link:** `https://www.medicalnewstoday.com/articles/325329.php`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 9; Redmi Note 4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.136 Mobile Safari/537.36
**Extension:** Nano Defender 15.0.0.149

### Additional Message

Website detects adblock when using mobile phone browser (kiwi browser) 
Same problem in Firefox mobile too with same setup. 
Screenshot :- `https://ibb.co/TLWgm8q`
Adding these in my filters removed them for me. 
```
www.medicalnewstoday.com###mmr1_container
www.medicalnewstoday.com##.sticky_ad_container
```

**Comment by mapx-** [comment]
fixed as annoyance
