### ISSUE TITLE
vladan.fr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1312]
### Basic Information

**Test link:** `https://www.vladan.fr/how-to-install-android-kitkat-in-vmware-workstation/`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.112

**Comment by okiehsch** [comment]
Fixed.
