### ISSUE TITLE
animedao.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1314]
### Basic Information

**Test link:** `https://animedao.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.112

### Additional Message

Original URL: `https://animedao24.stream/view/1828744302/`

video player is being ad-block blocked (site changes URLs on videos frequently use the link to get directory then select any video from there)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://animedao.com/`
**Category:** anti-adblock
**Reported from:** Philippines
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Defender 15.0.0.149

### Additional Message

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/58765337-56ef6f00-852f-11e9-875c-92d6a239511a.png)
![image](https://user-images.githubusercontent.com/7283682/58765342-5bb42300-852f-11e9-9ec5-50cbdfebdbdb.png)

**Comment by arnoldsecret** [comment]
![Untitled](https://user-images.githubusercontent.com/41223243/58950577-b2389000-87c1-11e9-9be9-b7b3426c8642.png)

**Comment by mapx-** [comment]
yeah, now is `animedao25` 
try `@@||animedao*.stream^$script,1p`

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e4eaba82c3d553672be526a9e402761accd4e74c
