### ISSUE TITLE
british-birdsongs.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1315]
### Basic Information

**Test link:** `https://www.british-birdsongs.uk/`
**Category:** anti-adblock
**Reported from:** Russia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.147

### Additional Message

Original URL: `https://www.british-birdsongs.uk/white-wagtail/`

Firefox 67.0 + uBlock Origin v1.19.6
Configured using this guide: `https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin`

**Comment by okiehsch** [comment]
Fixed.
