### ISSUE TITLE
adsrt.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#132]
### Basic Information

**Test link:** `https://adsrt.com/RkvlN2`
**Category:** anti-adblock
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.45

**Comment by ZaphodBeebblebrox** [comment]
uBlockOrigin/uAssets@4b537b5
