### ISSUE TITLE
vipstand.se

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1321]
### Basic Information

**Test link:** `https://www.vipstand.se/football-live-sports-stream`
**Category:** other
**Reported from:** Ireland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3800.0 Safari/537.36 Edg/76.0.167.1
**Extension:** Nano Adblocker 1.0.0.112

### Additional Message

Original URL: `chrome://newtab/`

This i think would be an app mechanic , while nano does block pop ups,if you can please allow just the first pop only per site.blocking the rest. (edge chromium). Thx great app.less is more.

**Comment by jspenguin2017** [comment]
@okiehsch Breakage, can't open dropdown. 
![image](https://user-images.githubusercontent.com/7283682/58752594-f3057180-846e-11e9-8abd-0a5af9c61b7b.png)
