### ISSUE TITLE
loskatchorros.com.br

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1322]
### Basic Information

**Test link:** `https://www.loskatchorros.com.br/forum/index.php?ct=1559392036`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109
**Extension:** Nano Adblocker 1.0.0.112

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.loskatchorros.com.br/forum/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

**Comment by jspenguin2017** [comment]
Looks like GitHub API glitched out again... Either way, this still works fine for me.
