### ISSUE TITLE
upload-earn.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1323]
### Basic Information

**Test link:** `https://upload-earn.com/ebFgowChEA`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.149

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/58752600-129c9a00-846f-11e9-9ca8-b659768fd5f7.png)

**Comment by adctea** [comment]
It displays a popup when you complete the captcha and click on the next page

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://upload-earn.com/ebFgowChEA`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.149

### Additional Message

It displays a popup when you complete the captcha and click on the next page

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/58843946-19273f00-8632-11e9-8894-10c0a6430d9d.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://upload-earn.com/ebFgowChEA`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.149

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://upload-earn.com/7vdJOsXHZP`
**Category:** ads
**Reported from:** Romania
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4101.0 Safari/537.36 Edg/83.0.474.0
**Extension:** Nano Defender 15.0.0.197

### Additional Message
