### ISSUE TITLE
thestar.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1329]
### Basic Information

**Test link:** `https://www.thestar.com/calgary/2019/02/12/jason-kenney-proposes-separate-minimum-wages-for-youth-and-alcohol-servers.html`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.113

**Comment by jspenguin2017** [comment]
Ads placeholders.
