### ISSUE TITLE
anime.eroterest.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1330]
### Basic Information

**Test link:** `https://anime.eroterest.net/`
**Category:** ads
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.66 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.113

### Additional Message

ads spaces

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholders:
```
! https://anime.eroterest.net/
||okbp.xyz^
```
