### ISSUE TITLE
varmatin.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1336]
### Basic Information

**Test link:** `https://www.varmatin.com/`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.149

**Comment by okiehsch** [comment]
Fixed.
