### ISSUE TITLE
siouxcityjournal.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1337]
### Basic Information

**Test link:** `https://siouxcityjournal.com/news/local/govt-and-politics/sioux-city-unlikely-to-reactivate-traffic-cameras-in-wake-of/article_1e37666a-dd3f-52c2-b9b1-ddd3abcf0728.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109
**Extension:** Nano Defender 15.0.0.149

### Additional Message

not working for this site.

**Comment by jspenguin2017** [comment]
@okiehsch Looks familiar... 
![image](https://user-images.githubusercontent.com/7283682/58843904-db2a1b00-8631-11e9-9a0b-dccfc2518a1d.png)

**Comment by jspenguin2017** [comment]
This comes up a lot hey? Might need some generic solution treatment.

**Comment by okiehsch** [comment]
It's https://fundingchoices.google.com/start/

**Comment by okiehsch** [comment]
Fixed.
