### ISSUE TITLE
buienradar.nl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1338]
### Basic Information

**Test link:** `https://www.buienradar.nl/`
**Category:** anti-adblock
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.149

### Additional Message

Actively blocks ad-block users from website features that are available to the public. It detects nano and displays a warning.

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance + ads placeholders.

**Comment by okiehsch** [comment]
Fixed.
