### ISSUE TITLE
loveawake.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1340]
### Basic Information

**Test link:** `https://www.loveawake.com/`
**Category:** anti-adblock
**Reported from:** Thailand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Defender 15.0.0.149

### Additional Message

adblock warning

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/58922575-c6648a80-86f8-11e9-9722-9a98d4695237.png)

**Comment by okiehsch** [comment]
Fixed.
