### ISSUE TITLE
jojosrew.site

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1345]
### Basic Information

**Test link:** `https://jojosrew.site/how-to-monitor-and-troubleshoot-server-health/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.149

**Comment by okiehsch** [comment]
Fixed.
