### ISSUE TITLE
mangarock.dev

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1352]
### Basic Information

**Test link:** `https://mangarock.dev/`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
**Extension:** Nano Defender 15.0.0.150

### Additional Message

Detected

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mangarock.dev/manga/mrs-serie-100265693`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Defender 15.0.0.150

### Additional Message

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/59140040-ce6d3600-8955-11e9-9eb2-4527dc377df7.png)

**Comment by okiehsch** [comment]
I can reproduce.
![image](https://user-images.githubusercontent.com/16838044/59140192-bb308980-899a-11e9-905a-1f767cc5398d.png)

**Comment by okiehsch** [comment]
Fixed.
