### ISSUE TITLE
tonton.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1353]
### Basic Information

**Test link:** `https://tonton.tv/`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.150

### Additional Message

anti adblock message poped up after the page completely loaded for few seconds

**Comment by jspenguin2017** [comment]
@okiehsch BAB.

**Comment by okiehsch** [comment]
Fixed.
