### ISSUE TITLE
https://pilot.wp.pl/tv

### ISSUE THREAD

**Issue by radzi143** [NanoMeow/QuickReports#1354]
https://pilot.wp.pl/tv

Please, turn off AdBlock / uBlock

Thanks to commercials, you have access to free channels. Disable the ad blocker and refresh the page to view.

Win 10 1903
Mozilla 67.01 
on chrome nano defender works on this site

**Comment by jspenguin2017** [comment]
Only bots may create new issues in this repository, humans must create issues in the [NanoFilters repository](https://github.com/NanoAdblocker/NanoFilters/issues). 

If you are a bot, inform your creator that you are not registered. Open an issue in the [NanoCore repository](https://github.com/NanoAdblocker/NanoCore/issues) for further information about bots registration.
