### ISSUE TITLE
https://pilot.wp.pl/tv

### ISSUE THREAD

**Issue by radzi143** [NanoMeow/QuickReports#1355]
Basic Information

Test link: https://pilot.wp.pl/tv
Category: anti-adblock
Reported from: Poland
Template version: 2

User Environment
Browser: Mozilla 76.01 
Chrome/74.0.3729.131 
Extension: Nano Defender 15.0.0.150
Win 10 1903
Additional Message
Please, turn off AdBlock / uBlock
Thanks to commercials, you have access to free channels. Disable the ad blocker and refresh the page to view.
refresh the page
You do not know how to turn off?

**Comment by jspenguin2017** [comment]
Only bots may create new issues in this repository, humans must create issues in the [NanoFilters repository](https://github.com/NanoAdblocker/NanoFilters/issues). 

If you are a bot, inform your creator that you are not registered. Open an issue in the [NanoCore repository](https://github.com/NanoAdblocker/NanoCore/issues) for further information about bots registration.
