### ISSUE TITLE
jqueryte.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#136]
### Basic Information

**Test link:** `http://jqueryte.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.46

**Comment by sigtus** [comment]
Works fine for me.

**Comment by jspenguin2017** [comment]
Works fine for me, placeholders should be cleared: `jqueryte.com##.advert` @ryanbr FYI
