### ISSUE TITLE
realclearscience.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1360]
### Basic Information

**Test link:** `https://www.realclearscience.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Adblocker 1.0.0.113

### Additional Message

Between Nano Defender and Nano Adblocker neither blocked the Anti-Adblocker notification.
I discovered that by blocking rcp.evolok.net it prevented the Anti-Adblocker pop-up.

thanks!

**Comment by okiehsch** [comment]
Fixed.
