### ISSUE TITLE
kiss-anime.ws

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1361]
### Basic Information

**Test link:** `https://www.kiss-anime.ws/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.149

### Additional Message

episodes don't show up with ublock origins enabled.

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/59152730-670fbe80-8a07-11e9-8dc6-645ec06afaa6.png)

**Comment by okiehsch** [comment]
Fixed.
