### ISSUE TITLE
effedupmovies.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1365]
### Basic Information

**Test link:** `https://www.effedupmovies.com/tetsuo-2-body-hammer-1992/`
**Category:** anti-adblock
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
**Extension:** Nano Defender 15.0.0.149

### Additional Message

Anti-Adblock on weirdmovies.xyz embedded frames of all movies (Option 1 player). Strangely this happens 90% of the time,rather than every time..

**Comment by okiehsch** [comment]
Fixed.
