### ISSUE TITLE
techonthenet.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1367]
### Basic Information

**Test link:** `https://www.techonthenet.com/sql/update.php`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
**Extension:** Nano Defender 15.0.0.150

### Additional Message

ads placeholders

**Comment by jspenguin2017** [comment]
Soft anti-adblock and ads placeholders. 

@okiehsch FYI.

**Comment by jspenguin2017** [comment]
Actually never mind, it's fixed in the annoyance filter already.

**Comment by jspenguin2017** [comment]
Does still have a few ads placeholders though, not sure if you want to update the filters.

**Comment by okiehsch** [comment]
I will update them, thanks. 
There are already filters for the site in `annoyances`, so it makes sense to add them.

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
Also `techonthenet.com##.left_slot`?

**Comment by okiehsch** [comment]
Done.
