### ISSUE TITLE
filesupload.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1376]
### Basic Information

**Test link:** `https://www.filesupload.org/0ed7064c2d07a41117a4ebbe3ca69355/A7ZJQ4ANGJ.part2.rar`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.151
**Extension:** Nano Defender 15.0.0.151

**Comment by okiehsch** [comment]
Fixed.
