### ISSUE TITLE
forums.automobile-propre.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1378]
### Basic Information

**Test link:** `https://forums.automobile-propre.com/forums/`
**Category:** breakage
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Defender 15.0.0.152

**Comment by jspenguin2017** [comment]
@okiehsch Broken by French regional filter.

**Comment by okiehsch** [comment]
I assume the breakage is obvious on your end, if so I can't reproduce.

**Comment by jspenguin2017** [comment]
Eh... For some reason publishing through GAPI doesn't go through right away anymore...
