### ISSUE TITLE
ohmymag.com.br

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#138]
### Basic Information

**Test link:** `https://www.ohmymag.com.br/planta/7-plantas-que-atraem-energias-positivas-para-a-sua-casa-ou-escritorio_art6023.html`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.46

**Comment by jspenguin2017** [comment]
@mapx- Same as https://github.com/NanoMeow/QuickReports/issues/137

**Comment by okiehsch** [comment]
I added
`@@||googletagservices.com/tag/js/gpt.js$script,domain=ohmymag.com.br`
The video won't start with Firefox without that filter.
