### ISSUE TITLE
allkpop.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1382]
### Basic Information

**Test link:** `https://www.allkpop.com`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.152

### Additional Message

Original URL: `chrome://newtab/`

anti-adblock

**Comment by jspenguin2017** [comment]
@okiehsch FYI.
