### ISSUE TITLE
wpcolt.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#139]
### Basic Information

**Test link:** `https://wpcolt.com/wordpress-reference-error-is-not-defined/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.47

**Comment by okiehsch** [comment]
Fixed.
