### ISSUE TITLE
glamourmagazine.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1390]
### Basic Information

**Test link:** `https://www.glamourmagazine.co.uk/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.25 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.115

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/b9e13875d94fdcc6a1786bc7cc3f583677533ad2
