### ISSUE TITLE
latimes.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1397]
### Basic Information

**Test link:** `https://www.latimes.com/local/lanow/la-me-costco-shooting-explainer-narrative-20190619-story.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.115

**Comment by jspenguin2017** [comment]
Not really anti-adblock, the paywall shows even if I have no extensions enabled. The wall seems to be fake though, as part of the content shows underneath the overlay.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.latimes.com/local/la-xpm-2012-dec-08-la-me-da-cooley-legacy-20121209-story.html`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.185

### Additional Message

**Comment by jspenguin2017** [comment]
For https://github.com/NanoMeow/QuickReports/issues/1397#issuecomment-584871866 : 
Can't reproduce.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.latimes.com/business/technology/story/2020-02-18/uber-shuts-down-its-downtown-la-customer-support-office`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.187

### Additional Message

**Comment by jspenguin2017** [comment]
For https://github.com/NanoMeow/QuickReports/issues/1397#issuecomment-588338691 : 
Can't reproduce.

**Comment by llacb47** [comment]
@mapx- @okiehsch 
Current filter `latimes.com##+js(nostif, f.parentNode.removeChild(f), 100)` is too specific. 
![image](https://user-images.githubusercontent.com/16567977/79512160-d7677300-800e-11ea-8c91-76cefe6caad5.png)

**Comment by okiehsch** [comment]
I can't reprosuce any anti adblock message even if I disable the existing filter.
What filter would you suggest?

**Comment by llacb47** [comment]
The problem is that the variable names are different:
on latimes:
`uBO: setTimeout("function(){a?(0!==a.offsetHeight&&0!==a.offsetWidth?n():t(),a.parentNode&&a.parentNode.removeChild(a)):t()}", 100)`
on ign: (as example)
`uBO: setTimeout(function(){f?(0!==f.offsetHeight&&0!==f.offsetWidth?b():a(),f.parentNode&&f.parentNode.removeChild(f)):a()}" ,100)`

could use a regex - or since it seems to be static per site you could change to
`latimes.com##+js(nostif, a.parentNode.removeChild(a), 100)`
