### ISSUE TITLE
tanked.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#14]
### Basic Information

**Test link:** `https://tanked.io/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.37

### Additional Message

Click "play"

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
