### ISSUE TITLE
mangarock.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#140]
### Basic Information

**Test link:** `https://mangarock.com`
**Category:** anti-adblock
**Reported from:** New Zealand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.47

### Additional Message

the issue only occurs after going into the individual manga chapters themselves. If I use adblock the screen goes completely white and I can't access it, which doesn't happen normally.

**Comment by jspenguin2017** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/46238276-8cf8a580-c347-11e8-8ab0-f02c351f9b0a.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mangarock.com/manga/mrs-serie-100390176`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
**Extension:** Nano Defender 15.0.0.112

### Additional Message

When access this url, a popup warning adblock appear at bottom.

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. Ads placeholder fixed.
