### ISSUE TITLE
spectorshockey.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1400]
### Basic Information

**Test link:** `https://www.spectorshockey.net/2019/06/what-will-the-montreal-canadiens-do-this-nhl-off-season/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Defender 15.0.0.153

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/59895690-c922d900-93a2-11e9-806e-1cd969d92f82.png)

**Comment by okiehsch** [comment]
Fixed.
