### ISSUE TITLE
creditcardrush.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1411]
### Basic Information

**Test link:** `https://www.creditcardrush.com/virtualbox-vs-vmware-comparison/`
**Category:** anti-adblock
**Reported from:** China
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.153

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/59967578-435d7580-94e9-11e9-9835-aaf4f8f716e4.png)

**Comment by okiehsch** [comment]
Fixed.
