### ISSUE TITLE
tomahawknation.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1412]
### Basic Information

**Test link:** `https://www.tomahawknation.com/2019/5/28/18641995/florida-state-football-recruiting-news-logan-tyler-weapon-punting-2019-season`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.153

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance. 
![image](https://user-images.githubusercontent.com/7283682/59970154-7d943a80-951c-11e9-8486-f995c322bd85.png)

**Comment by okiehsch** [comment]
Fixed.
