### ISSUE TITLE
chimica-online.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1417]
### Basic Information

**Test link:** `https://www.chimica-online.it/fisica/legge-di-stevino.htm`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.153

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. 
Anti-select annoyance fixed (see commit linked above).
