### ISSUE TITLE
flyertalk.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#142]
### Basic Information

**Test link:** `https://www.flyertalk.com/forum/air-canada-aeroplan/1853031-exclusive-sfo-near-miss-might-have-triggered-greatest-aviation-disaster-history-62.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
**Extension:** Nano Defender 15.0.0.47

**Comment by okiehsch** [comment]
Fixed in `uBO-annoyances`.
