### ISSUE TITLE
kenkenpuzzle.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1424]
### Basic Information

**Test link:** `https://www.kenkenpuzzle.com/game`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.153

### Additional Message

`https://www.kenkenpuzzle.com/game`
Adblock Detected
To continue playing KenKen
please disable your ad blocker for this domain

**Comment by okiehsch** [comment]
Fixed.
