### ISSUE TITLE
collater.al

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1427]
### Basic Information

**Test link:** `https://www.collater.al/fabio-consoli-illustration-art/?fbclid=IwAR3L4KkaoRN5wngXzi0tuCQ-l-Ud-swTUQzV9EgAVKz8s4lmIXXH_TJHTPk`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.153

**Comment by okiehsch** [comment]
Fixed.
