### ISSUE TITLE
whynotceviri.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1428]
### Basic Information

**Test link:** `http://whynotceviri.com/sheltered-v1-8-1-son-surum-turkce-yama/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.153

**Comment by okiehsch** [comment]
Fixed.
