### ISSUE TITLE
miniurl.pw

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1441]
### Basic Information

**Test link:** `https://miniurl.pw/KEAa`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.46 Safari/537.36
**Extension:** Nano Defender 15.0.0.153

### Additional Message

Original URL: `chrome://newtab/`

Please add timer/countdown script reset like currently done for ouo.io links.

**Comment by mapx-** [comment]
fixed anti adb stuff, `bad request` on killing countdown
