### ISSUE TITLE
cnet.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1442]
### Basic Information

**Test link:** `https://www.cnet.com/news/the-best-antivirus-protection-of-2019-for-windows-10/`
**Category:** anti-adblock
**Reported from:** Russia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.153

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.cnet.com/news/amazon-alexa-keeps-your-data-with-no-expiration-date-and-shares-it-too/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message

has autoplaying video on the botton right corner

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.cnet.com/news/pixel-3a-dumbed-down-my-phone-didnt-last-24-hours/`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

some images in the article do now show

**Comment by jspenguin2017** [comment]
@okiehsch Breakage. 

---

Can't reproduce other issues.

**Comment by okiehsch** [comment]
The videos are still broken.
https://www.cnet.com/videos/cnet-news/

**Comment by okiehsch** [comment]
Fixed.
