### ISSUE TITLE
arcadeprehacks.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1443]
### Basic Information

**Test link:** `http://www.arcadeprehacks.com/game/33202/superfighters-2-ultimate.html`
**Category:** anti-adblock
**Reported from:** Philippines
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.118

**Comment by llacb47** [comment]
No anti-adblock, just ads.
```
||fun1.arcadeprehacks.com^
arcadeprehacks.com##+js(abort-current-inline-script.js, Math.random, zonefile)
```

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
