### ISSUE TITLE
bestescapegames.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1444]
### Basic Information

**Test link:** `https://bestescapegames.com/escape-from-bewilder-house`
**Category:** breakage
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Adblocker 1.0.0.119

**Comment by jspenguin2017** [comment]
@okiehsch Breakage. 
![image](https://user-images.githubusercontent.com/7283682/60405364-e9098800-9b6c-11e9-9cf1-65cf5624e581.png)

**Comment by okiehsch** [comment]
````
@@||video.a4g.com/www/delivery/video.php$script,domain=bestescapegames.com
bestescapegames.com##.add_divbig
bestescapegames.com##.add_div3
````
can you test if the flash player works or if more filters are needed?

**Comment by jspenguin2017** [comment]
Flash is reaching End of Life pretty soon, no need to spend more time testing it.
