### ISSUE TITLE
jolyday.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1446]
### Basic Information

**Test link:** `https://jolyday.com/profile/elenoire_ferruzzi/photo/1846310639771295176_1388067740`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.118

**Comment by okiehsch** [comment]
Fixed.
