### ISSUE TITLE
rolyads.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1448]
### Basic Information

**Test link:** `https://rolyads.com/FdYT6`
**Category:** breakage
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36 OPR/62.0.3331.18
**Extension:** Nano Defender 15.0.0.153

**Comment by jspenguin2017** [comment]
@okiehsch Has a few issues, including fake button, popup, and anti-adblock.

**Comment by okiehsch** [comment]
Fixed.
