### ISSUE TITLE
gameguardian.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#145]
### Basic Information

**Test link:** `https://gameguardian.net/forum/`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.48

### Additional Message

It's detected

**Comment by mapx-** [comment]
already fixed in uBo

**Comment by jspenguin2017** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/46266354-ba7e5400-c4eb-11e8-82c8-1a50ffd08688.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://gameguardian.net/forum/topic/21185-root-to-emulator/`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.54

### Additional Message

not working

**Comment by jspenguin2017** [comment]
@okiehsch Broke. Comes up every refresh.

**Comment by okiehsch** [comment]
Fixed.
