### ISSUE TITLE
boxwares.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1452]
### Basic Information

**Test link:** `https://boxwares.net/9edcd7b7d3c457b7c6aab9c29bb52845/T380DXU2ARF2_ENG_boot_BoxWares.tar.md5`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.153

**Comment by okiehsch** [comment]
Fixed.
