### ISSUE TITLE
essexlive.news

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1454]
### Basic Information

**Test link:** `https://www.essexlive.news/news/essex-news/instagram-facebook-messenger-whatsapp-down-3050287`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3829.0 Safari/537.36 Edg/77.0.197.1
**Extension:** Nano Defender 15.0.0.153

### Additional Message

ads space

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholders:
```
essexlive.news##body:style(margin-top: 0px !important)
essexlive.news##.sovrn-onetag-ad
essexlive.news###taboolaRightRailsResponsive
```
