### ISSUE TITLE
theoaklandpress.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#146]
### Basic Information

**Test link:** `https://www.theoaklandpress.com/sports/college/osu-penn-state-to-light-up-happy-valley/article_1f5f971c-c37f-11e8-84ca-07a8f9c3d1a9.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.48

**Comment by okiehsch** [comment]
Fixed.
