### ISSUE TITLE
switchbounty.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1464]
### Basic Information

**Test link:** `https://switchbounty.com/nsp-what-remains-of-edith-finch/`
**Category:** anti-adblock
**Reported from:** Portugal
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3829.0 Safari/537.36 Edg/77.0.197.1
**Extension:** Nano Defender 15.0.0.153

**Comment by okiehsch** [comment]
Fixed.
