### ISSUE TITLE
anisearch.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1470]
### Basic Information

**Test link:** `https://www.anisearch.com/`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
**Extension:** Nano Defender 15.0.0.153

**Comment by okiehsch** [comment]
Fixed in annoyances.
