### ISSUE TITLE
oranhightech.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1474]
### Basic Information

**Test link:** `https://www.oranhightech.com/search/label/%D8%AA%D8%AD%D8%AF%D9%8A%D8%AB%D8%A7%D8%AA?&max-results=10`
**Category:** anti-adblock
**Reported from:** Algeria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.153

**Comment by okiehsch** [comment]
Fixed.
