### ISSUE TITLE
freetutorialsus.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1475]
### Basic Information

**Test link:** `https://www.freetutorialsus.com/tag/react/`
**Category:** anti-adblock
**Reported from:** Switzerland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.154

### Additional Message

It blocks after a few seconds

**Comment by okiehsch** [comment]
Fixed.
