### ISSUE TITLE
miamiherald.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1477]
### Basic Information

**Test link:** `https://www.miamiherald.com/news/state/florida/article232385422.html`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.154

### Additional Message

Page loads and then gets eaten and displays as blank.

Related McClatchy sites with same issue (tested on a few domains): bellinghamherald.com,bnd.com,bradenton.com,centredaily.com,charlotteobserver.com,elnuevoherald.com,fresnobee.com,heraldonline.com,heraldsun.com,idahostatesman.com,islandpacket.com,kansas.com,kansascity.com,kentucky.com,ledger-enquirer.com,macon.com,mcclatchydc.com,mercedsunstar.com,miamiherald.com,modbee.com,myrtlebeachonline.com,newsobserver.com,sacbee.com,sanluisobispo.com,star-telegram.com,sunherald.com,theolympian.com,thenewstribune.com,thestate.com,tri-cityherald.com

**Comment by okiehsch** [comment]
Fixed.
After updating `uBO-unbreak` you may need to bypass the cache one time.
