### ISSUE TITLE
nosey.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1480]
### Basic Information

**Test link:** `https://www.nosey.com/watch/channel/series_series/14-c3al0cgz1ub4-stunning-secrets-revealed`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.154

### Additional Message

Nosey.com streams still detect adblocker using Nano Defender.

**Comment by okiehsch** [comment]
Fixed.
