### ISSUE TITLE
lapresse.ca

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1481]
### Basic Information

**Test link:** `https://www.lapresse.ca/arts/musique/201907/03/01-5232610-dr-dre-orchestral-au-tour-de-lonjm.php`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 OPR/62.0.3331.43
**Extension:** Nano Defender 15.0.0.154

**Comment by okiehsch** [comment]
Fixed.
