### ISSUE TITLE
marketwatch.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1484]
### Basic Information

**Test link:** `https://www.marketwatch.com/story/this-midwestern-millennial-couple-needs-help-making-ends-meet-on-500000-a-year-2019-07-09?mod=MW_story_top_stories`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.120

### Additional Message

ads placeholder

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.marketwatch.com/story/bill-gates-im-happy-to-pay-20-billion-in-taxes-but-warrens-plan-will-make-me-do-a-little-math-on-what-i-have-left-over-2019-11-07?mod=newsviewer_click`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.29 Safari/537.36
**Extension:** Nano Defender 15.0.0.169

### Additional Message
