### ISSUE TITLE
volksfreund.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1487]
### Basic Information

**Test link:** `https://www.volksfreund.de/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.154

**Comment by okiehsch** [comment]
Fixed.
