### ISSUE TITLE
ja.hentai-image.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1489]
### Basic Information

**Test link:** `https://ja.hentai-image.com/image/some-kind-of-hentai-bath-thing-i-dont-facking-know-dont-judge-me-30-min-1/`
**Category:** ads
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.62 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.120

### Additional Message

nsfw ads placeholders

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholder: `hentai-image.com###display_image_detail > span` (Site is multilingual.)

**Comment by llacb47** [comment]
or `hentai-image.co##span[style^="width:300px; height:250px;"]`
