### ISSUE TITLE
vvvvid.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#149]
### Basic Information

**Test link:** `https://www.vvvvid.it/adblock.html`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
**Extension:** Nano Defender 15.0.0.50

**Comment by jspenguin2017** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/46319829-caa03d00-c598-11e8-99b6-7927e2b148d2.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.vvvvid.it/channel/0/You/502049/video/le-bizzarre-avventure-di-jojo-il-coraggio-di-domani-s01e06`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

Original URL: `https://web.whatsapp.com/`

**Comment by jspenguin2017** [comment]
Fixed by Italian regional filters.

**Comment by jspenguin2017** [comment]
@okiehsch Anti-adblock fixed by Italian regional filters, but has ads.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.vvvvid.it/show/895/cautious-hero/1008/541050/questo-prode-guerriero-e-un-po-troppo-egoista`
**Category:** ads
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

La pubblicità viene visualizzata comunque

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.vvvvid.it/adblock.html?h=https%3A%2F%2Fwww.vvvvid.it%2Fshow%2F895%2Fcautious-hero%2F1008%2F541182%2Fquesta-dea-e-un-po-troppo-inquietante`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/b6fdc0ffaeff23a5bf59e61570b20553bb4d9d96

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.vvvvid.it/show/892/sword-art-online-alicization-war-of-underworld/1005/541195/la-vigilia-della-guerra`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

**Comment by jspenguin2017** [comment]
This needs to be triaged again.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.vvvvid.it/adblock.html?h=https%3A%2F%2Fwww.vvvvid.it%2Fchannel%2F0%2Fyou%26r%26r%2F541223%2Fvideo%2Fcautious-hero-questa-regina-dei-draghi-e-un-po-troppo-ingiusta-e06`
**Category:** anti-adblock
**Reported from:** Switzerland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.169

### Additional Message

Nano ADBLOCKER + Nano DEFENDER = the page says that I've to disable my ADBLOCKER to continue
