### ISSUE TITLE
bc.vc

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1491]
### Basic Information

**Test link:** `https://bc.vc/83pNdk?rand_seed=6EYrr#`
**Category:** anti-adblock
**Reported from:** Ukraine
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.154

**Comment by okiehsch** [comment]
Fixed.

**Comment by dumbusernameidk** [comment]
site is using a third party script to send fake push notifications. original link in op works.

**Comment by llacb47** [comment]
```
||bcvc.live/dist/js/po_v9.js$script
||punosy.top^$3p
```

If you proceed from the page ("Get link") in https://github.com/NanoMeow/QuickReports/issues/1491#issue-467645833 then you must allow scripts from `punosy.com` and allow push notifications to continue.

```
ouo.today###wait
ouo.today###msgBox:style(display:block!important)
```
