### ISSUE TITLE
thestreet.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1498]
### Basic Information

**Test link:** `https://www.thestreet.com/investing/index-funds-vs-mutual-funds-14836608`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.62 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.120

### Additional Message

video blocked

**Comment by jspenguin2017** [comment]
@okiehsch Breakage.

**Comment by okiehsch** [comment]
Fixed.
