### ISSUE TITLE
asiansister.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#15]
### Basic Information

**Test link:** `https://www.asiansister.com/index.php`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
**Extension:** Nano Defender 15.0.0.37

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
