### ISSUE TITLE
abola.pt

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1505]
### Basic Information

**Test link:** `https://abola.pt/`
**Category:** anti-adblock
**Reported from:** Portugal
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.154

**Comment by okiehsch** [comment]
Fixed in annoyances.
