### ISSUE TITLE
nl.hardware.info

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1508]
### Basic Information

**Test link:** `https://nl.hardware.info/`
**Category:** anti-adblock
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.154

**Comment by okiehsch** [comment]
Fixed in annoyances.

**Comment by jspenguin2017** [comment]
Maybe also `nl.hardware.info##.sidebar_right_top, .sidebar_right_bottom`?

**Comment by okiehsch** [comment]
Done.

**Comment by okiehsch** [comment]
@jspenguin2017 
You have to change the filter to 
`nl.hardware.info##body > div:nth-of-type(1) > div:has-text(adblocker)`
my filter broke the cookie banner of the site which renders it unusable.
https://github.com/uBlockOrigin/uAssets/issues/5974

**Comment by jspenguin2017** [comment]
Thanks. Updated.
