### ISSUE TITLE
blindhypnosis.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1511]
### Basic Information

**Test link:** `https://blindhypnosis.com/watership-down-pdf-richard-adams.html`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Adblocker 1.0.0.120

**Comment by okiehsch** [comment]
Fixed.
