### ISSUE TITLE
rollingstone.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1518]
### Basic Information

**Test link:** `https://www.rollingstone.it/opinioni/opinioni-tv/temptation-island-innamorarsi-perdutamente-di-ilaria-teolis/468748/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.154

### Additional Message

the anti-adblock is recognized by the site

**Comment by okiehsch** [comment]
Fixed.
