### ISSUE TITLE
teemo.gg

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1521]
### Basic Information

**Test link:** `https://teemo.gg/model-viewer`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.2.11
**Extension:** Nano Defender 15.0.0.154

**Comment by okiehsch** [comment]
I get the message even if I disable `uBO`.
Fixed the deliberately broken site functionality.
