### ISSUE TITLE
ifc.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1522]
### Basic Information

**Test link:** `https://www.ifc.com/shows/brockmire/full-episodes/season-03/episode-01/clubhouse-cancer-2`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.154

**Comment by okiehsch** [comment]
`ifc.com##+js(abort-on-property-read.js, _sp_._networkListenerData)`
the video player does not work for me, so I need somebody to check the filter before I add it.

**Comment by llacb47** [comment]
@okiehsch your filter breaks the player

**Comment by okiehsch** [comment]
Thanks.
`@@||ifc.com^$generichide`
should work.

**Comment by llacb47** [comment]
Wait, never mind. I had another filterlist that was affecting it.

**Comment by okiehsch** [comment]
Well, if `@@||ifc.com^$generichide` works for you I will call it fixed anyway.

**Comment by llacb47** [comment]
That works for me too.
