### ISSUE TITLE
uploadrar.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1523]
### Basic Information

**Test link:** `https://uploadrar.com/x8i7jq3s34ql`
**Category:** ads
**Reported from:** Peru
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 5.1.1; SM-J110M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.101 Mobile Safari/537.36
**Extension:** Nano Adblocker 1.0.0.121

### Additional Message

Advertising at the bottom of the page

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://uploadrar.com/ogev139xb7bk`
**Category:** anti-adblock
**Reported from:** Denmark
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message


Start URL

You may want to disable/block these addresses:

the subdomains belonging to: adsenseguard.com

and these addresses in HTML:

<script src="//pushazam.com/ntfc.php?p=2741020" data-cfasync="false" async="" onerror="_aixgfvg()" onload="_ghynqxzw()"></script>

**Comment by mapx-** [comment]
commit above => against redirecting on clicking download
