### ISSUE TITLE
mentalmars.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1527]
### Basic Information

**Test link:** `https://mentalmars.com/game-news/borderlands-vip-season-rewards/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.62 Safari/537.36
**Extension:** Nano Defender 15.0.0.155

**Comment by okiehsch** [comment]
Fixed in annoyances.
