### ISSUE TITLE
calendarpedia.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1528]
### Basic Information

**Test link:** `http://www.calendarpedia.co.uk/calendar-2019-excel-templates.html`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.155

### Additional Message

adblock detected

**Comment by okiehsch** [comment]
Fixed in annoyances.
