### ISSUE TITLE
techhx.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1529]
### Basic Information

**Test link:** `https://techhx.com/2019/07/13/intel-plans-to-take-down-amd-with-a-new-processor/`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.154

**Comment by okiehsch** [comment]
Fixed.
