### ISSUE TITLE
stream.golfchannel.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1531]
### Basic Information

**Test link:** `http://stream.golfchannel.com/ra-the-open-watch-live-rd1`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.62 Safari/537.36
**Extension:** Nano Defender 15.0.0.155

### Additional Message

Streak broken when uBO enabled

**Comment by jspenguin2017** [comment]
Need a better test link. 
![image](https://user-images.githubusercontent.com/7283682/61504856-11c9b400-a99a-11e9-9f5d-9835e2e02866.png)

**Comment by yourduskquibbles** [comment]
Live test link `http://stream.golfchannel.com/ra-the-open-watch-live-rd2`

Either filter below seems to work. 
`@@||v.fwmrm.net^$domain=stream.golfchannel.com` 
or
`@@||v.fwmrm.net^$xmlhttprequest,domain=stream.golfchannel.com`

@okiehsch which would be preferred filter to add?

**Comment by okiehsch** [comment]
The latter.

**Comment by yourduskquibbles** [comment]
Thanks @okiehsch 

@jspenguin2017 should be fixed now
