### ISSUE TITLE
javfinder.sh

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1533]
### Basic Information

**Test link:** `https://javfinder.sh/`
**Category:** ads
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.155

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#known-issues`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0befd500976539d0da95e89e4374d6577649081e
