### ISSUE TITLE
polskieszlaki.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1537]
### Basic Information

**Test link:** `https://www.polskieszlaki.pl/jura-krakowsko-czestochowska.html`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3854.3 Safari/537.36
**Extension:** Nano Defender 15.0.0.155

**Comment by okiehsch** [comment]
Fixed.
