### ISSUE TITLE
watchgameofthrones.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1538]
### Basic Information

**Test link:** `https://watchgameofthrones.tv/`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.155

### Additional Message

Nano defender not circumventing anti adblocker on this site. Please help!

**Comment by llacb47** [comment]
BlockAdBlock (BAB)
`@@||watchgameofthrones.tv^$generichide`
Also add this cosmetic for an annoying empty space: `watchgameofthrones.tv###keeper2`

**Comment by okiehsch** [comment]
Fixed.

**Comment by okiehsch** [comment]
Forgot to add `watchgameofthrones.tv###keeper2`
