### ISSUE TITLE
gamespot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1540]
### Basic Information

**Test link:** `https://www.gamespot.com/gallery/the-big-ps4-games-coming-in-2019-and-beyond-may-up/2900-2044/`
**Category:** breakage
**Reported from:** Thailand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Adblocker 1.0.0.120

### Additional Message

blocks non-ad images too

**Comment by jspenguin2017** [comment]
@okiehsch Breakage.

**Comment by llacb47** [comment]
Blocking `https://c.evidon.com/geo/country.js` fixed the problem for me.

**Comment by okiehsch** [comment]
To fix the site it is either blocking
`||c.evidon.com/geo/country.js$script,domain=gamespot.com`
and breaking the cookie notice and the cookie manager
or allowing
````
@@||securepubads.g.doubleclick.net/gpt/pubads_impl$script,domain=gamespot.com
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=gamespot.com
````

**Comment by okiehsch** [comment]
Fixed.
