### ISSUE TITLE
hentaifox.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1541]
### Basic Information

**Test link:** `https://hentaifox.com/`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.154

### Additional Message

Can't move to next page

**Comment by jspenguin2017** [comment]
Ads placeholder removed, can't reproduce breakage.
