### ISSUE TITLE
dailylocal.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1543]
### Basic Information

**Test link:** `https://www.dailylocal.com/news/local/parkesburg-police-to-roll-out-body-worn-cameras-this-fall/article_f12e24ea-aa2c-11e9-9f71-a7f4afd16155.html`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.155

**Comment by okiehsch** [comment]
Fixed.
