### ISSUE TITLE
neowin.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1544]
### Basic Information

**Test link:** `https://www.neowin.net/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.154

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.neowin.net/news/oppo-reno-10x-zoom-review-jack-of-all-trades-master-of-some`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.154

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

Works on any news article on neowin.net (but not the home page).

**Comment by yourduskquibbles** [comment]
Related report: https://github.com/uBlockOrigin/uAssets/issues/6017

**Comment by krystian3w** [comment]
first https://github.com/ryanbr/fanboy-adblock/issues/1106#issue-470468254 and second https://github.com/uBlockOrigin/uAssets/issues/5979

**Comment by jspenguin2017** [comment]
Current rules still works for me.
