### ISSUE TITLE
gsurl.co

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1545]
### Basic Information

**Test link:** `http://gsurl.co/gCQM`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.71 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.121

### Additional Message

popup

**Comment by jspenguin2017** [comment]
@okiehsch Popup.
