### ISSUE TITLE
adzsafe.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1549]
### Basic Information

**Test link:** `https://www.adzsafe.com/immediate-test`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3859.0 Safari/537.36
**Extension:** Nano Defender 15.0.0.155

### Additional Message

Sites that use the adzsafe.com detection script are able to bypass Nano Defender's guards. The page linked here is the site's own "test" page for that script.

**Comment by jspenguin2017** [comment]
@okiehsch 
This has anti-select and anti-right-click. 
`adzsafe.com##+js(noeval.js)` breaks the demo BTW.

**Comment by jspenguin2017** [comment]
Also don't forget to report `https://chrome.google.com/webstore/detail/free-internet-protection/dilkfdbleihhdklpjlldmmnjnmhgofed` for obfuscated code 😉

**Comment by okiehsch** [comment]
> This has anti-select and anti-right-click.

I can't reproduce.

**Comment by jspenguin2017** [comment]
Actually, only the block screen has those. Never mind then.
