### ISSUE TITLE
wilmaa.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#155]
### Basic Information

**Test link:** `https://www.wilmaa.com/watch`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.51

**Comment by jspenguin2017** [comment]
The website is not working on a browser without extensions.

**Comment by jspenguin2017** [comment]
@okiehsch A bit hard to reproduce. 

1. Fill the form
2. Refresh
3. If you can't reproduce, clear cookies and LocalStorage, refresh, and go to step 1

---

![image](https://user-images.githubusercontent.com/7283682/46908253-89375800-cedd-11e8-97be-7f6110b046c2.png)

**Comment by okiehsch** [comment]
I can't reproduce, does 
`wilmaa.com##+js(set-constant.js, wlm.adsNotBlocked, true)`
work for you?

**Comment by jspenguin2017** [comment]
Yep, that does work. 
Whitelisting the bait script should work too.

**Comment by okiehsch** [comment]
Fixed.
