### ISSUE TITLE
documentarymania.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1551]
### Basic Information

**Test link:** `http://www.documentarymania.com/player.php?title=Queen%3A+Days+of+Our+Lives`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.154

**Comment by okiehsch** [comment]
Fixed.
