### ISSUE TITLE
fuwaost.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1553]
### Basic Information

**Test link:** `https://fuwaost.net/kobasolo-full-album-discography-download/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.155

**Comment by okiehsch** [comment]
Can't reproduce anti-adblock. Fixed file hosting links redirecting to ads.

**Comment by theinstantmatrix** [comment]
Anti-Adblock Script

No way to close it, also disables right click

![Screenshot_2019-11-22 Kobasolo Full Album Discography  Download  - Fuwaost](https://user-images.githubusercontent.com/24980766/69402454-dcc1cb00-0cc5-11ea-9833-1318d95fbe28.png)

**Comment by okiehsch** [comment]
Fixed.
