### ISSUE TITLE
reactgo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1557]
### Basic Information

**Test link:** `https://reactgo.com/how-to-titlecase-javascript/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.155

### Additional Message

blockadblock script

**Comment by okiehsch** [comment]
Fixed.
