### ISSUE TITLE
javfinder.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1559]
### Basic Information

**Test link:** `https://javfinder.id/movie/watch/ai-uehara-gets-her-pretty-nice-ass-worked-on.html`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.155

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ac6f97cdc11bbabb7a56e2ced89750468c080f99
Fixed pre-roll ads.
