### ISSUE TITLE
cryptomininggame.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#156]
### Basic Information

**Test link:** `https://cryptomininggame.com/mining`
**Category:** anti-adblock
**Reported from:** Greece
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
**Extension:** Nano Defender 15.0.0.51

### Additional Message

It seems you use AD BLOCKER, who doesn't?

This faucet game is based and stay alive thanks to the advertising. Please disable AD Blocker and refresh the page in order to be able to play.

CRYPTO MINING GAME thank you for your comprehension and wish you good profit using this game!

**Comment by jspenguin2017** [comment]
Requires account, see also: https://github.com/NanoAdblocker/NanoFilters/issues/84

**Comment by jspenguin2017** [comment]
@ZaphodBeebblebrox There is no point fixing ads when there is anti-adblock. Can we have a private chat group or private repo so we can share test accounts among trusted maintainers?

**Comment by okiehsch** [comment]
> Can we have a private chat group or private repo so we can share test accounts among trusted maintainers?

Creating an [organization](https://help.github.com/articles/creating-a-new-organization-from-scratch/) and enabling [team discussions](https://help.github.com/articles/creating-a-team-discussion/) is probably the most private discussion you will get on github.

**Comment by ryanbr** [comment]
Either Slack or even discord might be an option.

**Comment by jspenguin2017** [comment]
I think Discord is a good idea, because we want users to have a way to supply test accounts.

**Comment by ryanbr** [comment]
Gauging the interest for a discord/discussion server, https://forums.lanik.us/viewtopic.php?f=23&p=141801

**Comment by jspenguin2017** [comment]
@ryanbr I don't think we are looking for a generic Discord server, as I don't think anyone wants to deal with issue reports flying in Discord chat.

**Comment by jspenguin2017** [comment]
@okiehsch Leftover ads / ads placeholders: 
```
cryptomininggame.com##a[href^="https://coinad.com/?a=Buy"]
cryptomininggame.com##a[href^="https://priximini.com/?affiliates="]
cryptomininggame.com###sticky_bot_right

cryptomininggame.com##.panel-success.panel:has(.bg_ads)
cryptomininggame.com##.panel-warning:has(.bg_ads)
```

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://cryptomininggame.com/missions`
**Category:** anti-adblock
**Reported from:** South Africa
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.57

### Additional Message

Much thx for a brilliant app!

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://cryptomininggame.com/mining`
**Category:** anti-adblock
**Reported from:** Greece
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
**Extension:** Nano Defender 15.0.0.70

### Additional Message
