### ISSUE TITLE
jyra.online

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1561]
### Basic Information

**Test link:** `https://jyra.online/the-barbecue/`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 OPR/62.0.3331.72
**Extension:** Nano Defender 15.0.0.155

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://jyra.online/glazed-chicken-wings-with-blue-cheese-dip/`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.156

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://jyra.online/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.157

### Additional Message

Original URL: `https://jyra.online/the-basil-avocado-cheese-spread/`

The following script seems to be detecting nano adblock:

function whenCaptchaChecked() { 
  jQuery('#invisibleCaptchaShortlink').removeClass('disabled').removeAttr('disabled');
}
function adBlockNotDetected() {
}
function adBlockDetected() {
    $("#adb_detected").html("Please disable Adblock to proceed to the destination page.").css('display', 'inline-block').addClass("alert alert-danger");
	$(".g-recaptcha").hide();
	$(".btn-captcha").hide();
	$(".captcha-check").hide();
}
if(typeof fuckAdBlock !== 'undefined' || typeof FuckAdBlock !== 'undefined') {
    adBlockDetected();
} else {
    var importFAB = document.createElement('script');
    importFAB.onload = function() {
        fuckAdBlock.onDetected(adBlockDetected)
        fuckAdBlock.onNotDetected(adBlockNotDetected);
    };
    importFAB.onerror = function() {
        adBlockDetected();
    };
    importFAB.integrity = 'sha256-xjwKUY/NgkPjZZBOtOxRYtK20GaqTwUCf7WYCJ1z69w=';
    importFAB.crossOrigin = 'anonymous';
    importFAB.src = 'https://cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js';
    document.head.appendChild(importFAB);
}

**Comment by jspenguin2017** [comment]
See: https://github.com/NanoMeow/QuickReports/issues/1593

**Comment by jspenguin2017** [comment]
Fixed here: https://github.com/uBlockOrigin/uAssets/commit/652889d497a3278595cf93da711587baa2c428f0 https://github.com/uBlockOrigin/uAssets/commit/5f9e812bb94597be89b6831da14a89644f791da5
