### ISSUE TITLE
puzzles.msn.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1565]
### Basic Information

**Test link:** `https://puzzles.msn.com/en-gb/games/classic-solitaire?arkpromo=july_msrewards_classicsolitaire&rnoreward=1`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.155

**Comment by okiehsch** [comment]
Fixed.
