### ISSUE TITLE
novelgo.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1570]
### Basic Information

**Test link:** `https://novelgo.id/novel/the-novels-extra/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 9; POCO F1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.101 Mobile Safari/537.36
**Extension:** Nano Defender 15.0.0.156

**Comment by okiehsch** [comment]
Fixed.
