### ISSUE TITLE
solarmoviefree.ac

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1572]
### Basic Information

**Test link:** `https://solarmoviefree.ac/movie/final-space-season-2-2019-1080p/watching.html?episode_id=131191`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.156

**Comment by mapx-** [comment]
fixed
