### ISSUE TITLE
myfreecourses.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1573]
### Basic Information

**Test link:** `https://myfreecourses.com/udemy-paid-courses-free/?fbclid=IwAR1aXQWWnUreFI2bQw0Jrnl-jFpMxy9GNt_w7AYP3DDsJPzuYj_LQ9aZP3c`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.156

**Comment by mapx-** [comment]
fixed
