### ISSUE TITLE
turkanime.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1575]
### Basic Information

**Test link:** `https://www.turkanime.tv/index`
**Category:** ads
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.121

**Comment by okiehsch** [comment]
Fixed.
