### ISSUE TITLE
lyricsongation.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1576]
### Basic Information

**Test link:** `https://www.lyricsongation.com/%D9%83%D9%84%D9%85%D8%A7%D8%AA-%D8%A7%D8%BA%D9%86%D9%8A%D8%A9-%D8%B3%D8%B1-%D8%A7%D9%84%D8%AD%D9%8A%D8%A7%D8%A9-%D8%A7%D8%B5%D9%8A%D9%84-%D9%87%D9%85%D9%8A%D9%85/`
**Category:** anti-adblock
**Reported from:** Bahrain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.155

**Comment by okiehsch** [comment]
Fixed.
