### ISSUE TITLE
vidtodu.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1577]
### Basic Information

**Test link:** `https://vidtodu.com/183jskb8w8mk`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.155

### Additional Message

no play button

**Comment by okiehsch** [comment]
Fixed popup.

**Comment by jspenguin2017** [comment]
Can't reproduce breakage, play button shows fine for me.
