### ISSUE TITLE
finalboss.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1578]
### Basic Information

**Test link:** `https://finalboss.io/what-titles-are-4k-hdrdolby-vision-on-netflix-and-amazon/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 9; Tablet; rv:68.0) Gecko/68.0 Firefox/68.0
**Extension:** Nano Defender 15.0.0.155

**Comment by okiehsch** [comment]
Fixed.
