### ISSUE TITLE
cbox.turkdown.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1579]
### Basic Information

**Test link:** `https://cbox.turkdown.com/checkBeta/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.155

**Comment by llacb47** [comment]
Bait: `https://cbox.turkdown.com/checkBeta/advertisement.js`

**Comment by okiehsch** [comment]
Fixed.
