### ISSUE TITLE
tred.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1580]
### Basic Information

**Test link:** `https://www.tred.com/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.121

**Comment by okiehsch** [comment]
Fixed.
