### ISSUE TITLE
lci.fr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1581]
### Basic Information

**Test link:** `https://www.lci.fr/insolite/canicule-aux-etats-unis-cuire-des-biscuits-dans-une-voiture-pour-prevenir-des-dangers-2128129.html`
**Category:** breakage
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 OPR/62.0.3331.72
**Extension:** Nano Defender 15.0.0.156

**Comment by jspenguin2017** [comment]
@okiehsch Video player disappears after a few seconds. 
![image](https://user-images.githubusercontent.com/7283682/62002397-6b2f9280-b0c0-11e9-9961-1962a5d44959.png)

**Comment by okiehsch** [comment]
Fixed.
