### ISSUE TITLE
pipocamoderna.com.br

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1582]
### Basic Information

**Test link:** `https://pipocamoderna.com.br/2019/07/carnival-row-ganha-novo-trailer-repleto-de-efeitos-visuais/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.156

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

**Comment by okiehsch** [comment]
Fixed.
