### ISSUE TITLE
independent.ie

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1588]
### Basic Information

**Test link:** `https://www.independent.ie/irish-news/climate-change-and-you/the-power-of-one-how-greta-thunberg-is-changing-the-world-37890648.html`
**Category:** anti-adblock
**Reported from:** New Zealand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Defender 15.0.0.156

**Comment by mapx-** [comment]
fixed as annoyance
