### ISSUE TITLE
chess.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1589]
### Basic Information

**Test link:** `https://www.chess.com/forum/view/daily-puzzles/7-28-2019-forever-entrapped`
**Category:** other
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.155

### Additional Message

Ads placeholders on chess.com (the issue URL ist just one example): There is still some empty space from the blocked ad and a "remove ads"-button. When you click on the button, it recommends you to buy a premium account to get rid of the ads but you don't need this when ads are already blocked. I think this issue has quite a low priority but it would be nice if you could add a filter to the nano placeholder list.

**Comment by jspenguin2017** [comment]
Ads placeholders.
