### ISSUE TITLE
fc.lc

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1593]
### Basic Information

**Test link:** `https://fc.lc/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.157

### Additional Message

Clicking on any encrypted link which uses this domain now redirects to jyra.online page which displays "Please disable Adblock to proceed to the destination page." at the top.

**Comment by llacb47** [comment]
Redirect doesn't seem to work.
```
jyra.online##+js(abort-on-property-read.js, fuckAdBlock)
jyra.online##.adz
```

**Comment by llacb47** [comment]
Also discussed here: https://github.com/uBlockOrigin/uAssets/issues/5495

**Comment by jspenguin2017** [comment]
@okiehsch 
Test: `https://fc.lc/2NjI`
Old solution no longer works.

**Comment by okiehsch** [comment]
Fixed.
