### ISSUE TITLE
nxload.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1594]
### Basic Information

**Test link:** `http://nxload.com/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.157

**Comment by llacb47** [comment]
Can't reproduce anti-adblock. There are popups though. Block these domains:
```
reberr.pro
raterst.pro

```

**Comment by jspenguin2017** [comment]
Works fine for me. Can't reproduce anti-adblock. No popup for me. 
![image](https://user-images.githubusercontent.com/7283682/62176552-39f0d580-b2ff-11e9-8d5e-b01dc36f491d.png)

**Comment by jspenguin2017** [comment]
@okiehsch 
Test: `https://nxload.com/embed-3bovavpfya6s.html`
Fake notification prompt and popup.

**Comment by okiehsch** [comment]
Fixed.

**Comment by ghajini** [comment]
Video player blank

`https://nxload.com/v/ARnG0UPYUA3f`

**Comment by ghajini** [comment]
Antiadblock just appeared
![IMG_20200417_170053](https://user-images.githubusercontent.com/20338483/79565042-7bafef00-80cd-11ea-9c51-e0fb515ad32b.jpg)

**Comment by ghajini** [comment]
`https://nxload.com/v/ARnG0UPYUA3f `
Popup ads

**Comment by llacb47** [comment]
I get no popups

**Comment by mapx-** [comment]
it should work
`nxload.com##+js(aeld, , pop)`

@llacb47  lastly, there are a lot of pages (on my side) without popups in chrome but kicking in FF
(I see the popups code in the page - for example the famous `zfgloaded` but .. no popup in chrome )

**Comment by ghajini** [comment]
URL =
`https://nxload.com/v/DpYQCMRAKWJz`

For firefox

`||rotdubboy.com^`
`nxload.com##+js(acis, String.fromCharCode, 'shift')`
`nxload.com##+js(aeld, , _0x)`

**Comment by jspenguin2017** [comment]
@ghajini Can't reproduce any issue with that test link.

**Comment by ghajini** [comment]
`https://nxload.com/v/9VYSbwuJReLT`

Popup ads in opera browser stable
Ublock origin 1.28.5b1
