### ISSUE TITLE
onlystream.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1595]
### Basic Information

**Test link:** `https://onlystream.tv/e/u5kvwcmi8nh0`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.157

### Additional Message

Original URL: `https://www.youtube.com/watch?v=naWZ2xVuF30&list=PLIHume2cwmHdFsJRo5oYG7yQ4NyUx43ql`

adblock detected

`https://onlystream.tv/e/u5kvwcmi8nh0`

**Comment by okiehsch** [comment]
Fixed.
