### ISSUE TITLE
rankedboost.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1596]
### Basic Information

**Test link:** `https://rankedboost.com/apex-legends/best-characters-tier-list/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

ads placeholders

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by llacb47** [comment]
`rankedboost.com##div:has(>.InsertTitle-Updated):has([id^="div-gpt-ad"])`
