### ISSUE TITLE
habbokritik.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1597]
### Basic Information

**Test link:** `https://www.habbokritik.de/board/thread/21305`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.157

### Additional Message

AdBlocker Detection

**Comment by okiehsch** [comment]
Fixed.
