### ISSUE TITLE
megahfilmeshd.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#16]
### Basic Information

**Test link:** `https://www.megahfilmeshd.net/filme/viking-destiny/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.37

**Comment by jspenguin2017** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/44498236-884f1c00-a63a-11e8-949c-0a66f25b243b.png)

**Comment by jspenguin2017** [comment]
@okiehsch May need to refresh 1~2 times. Tried regional filter. 
![image](https://user-images.githubusercontent.com/7283682/44498302-debc5a80-a63a-11e8-8cb4-80d881c0c3ae.png)

**Comment by okiehsch** [comment]
Fixed.
