### ISSUE TITLE
lodz.wyborcza.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1600]
### Basic Information

**Test link:** `http://lodz.wyborcza.pl/lodz/7,35136,25044880,absurd-na-widzewie-kibice-odbieraja-karnety-w-okienko-na-wysokosci.html?utm_source=facebook.com&utm_medium=SM&utm_campaign=FB_Lodz_Wyborcza&fbclid=IwAR1Ps38Mk-r3YQ8pM_rA7aTlVtGX1Bh0fjxLZ4WjDuHZ6-zCAo3HB4kZnI0`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.59 Safari/537.36 Vivaldi/2.7.1609.4
**Extension:** Nano Defender 15.0.0.157

**Comment by llacb47** [comment]
Not anti-adblock, if you whitelist the site a paywall nag modal is visible.

**Comment by jspenguin2017** [comment]
@okiehsch Breakage.

**Comment by okiehsch** [comment]
Fixed.
