### ISSUE TITLE
topsport.bg

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1605]
### Basic Information

**Test link:** `https://topsport.bg/tennis/grigor-dimitrov-zagubi-ot-guido-peya-v-los-kabos-s-4-6-2-6.html?sort=desc&page=2#comment-section`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page.

**Comment by llacb47** [comment]
![Modal](https://user-images.githubusercontent.com/16567977/62336473-7444a900-b49e-11e9-985c-ca3a19cab095.png)

**Comment by llacb47** [comment]
`||fundingchoicesmessages.google.com^$domain=topsport.bg`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
