### ISSUE TITLE
watchdoctorwhoonline.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1606]
### Basic Information

**Test link:** `https://watchdoctorwhoonline.com/episodes/doctor-who-4x10/`
**Category:** anti-adblock
**Reported from:** New Zealand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.157

**Comment by llacb47** [comment]
Can't reproduce, add `watchdoctorwhoonline.com###keeper2` for ads placeholder.

Apparent sister site's issue: https://github.com/NanoMeow/QuickReports/issues/1538

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. 

@okiehsch You added the placeholder removal rule for the other domain, do you want to add it for this one as well?

**Comment by okiehsch** [comment]
I will add it.
