### ISSUE TITLE
bilasport.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1608]
### Basic Information

**Test link:** `http://bilasport.net/game/new-york-yankees-vs-boston-red-sox-18245.html`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12239.57.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.157

### Additional Message

fake watch fake video at bottom. link to `topperformance.xyz`

**Comment by okiehsch** [comment]
Fixed.
