### ISSUE TITLE
acronymfinder.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1612]
### Basic Information

**Test link:** `https://www.acronymfinder.com/LOL.html`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.157

### Additional Message

Empty ad boxes with changing class names based on inline script not blocked. Not sure if advanced filter not possible in EasyList is needed so reporting here first

**Comment by llacb47** [comment]
Server side changing?

**Comment by jspenguin2017** [comment]
Ads placeholders.
