### ISSUE TITLE
gelderlander.nl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1617]
### Basic Information

**Test link:** `https://www.gelderlander.nl`
**Category:** other
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

Original URL: `https://myprivacy.persgroep.net/?siteKey=Oom2kBLTny5zJUeO&callbackUrl=https%3a%2f%2fwww.gelderlander.nl%2fprivacy-gate%2faccept%3fredirectUri%3d%252f`

cookie notice

**Comment by jspenguin2017** [comment]
Cookie wall.

**Comment by llacb47** [comment]
Isn't this fixed by `myprivacy.persgroep.net##+js(nanop-click-elements-onready.js, button.fjs-set-consent)` from https://github.com/LiCybora/NanoCoreFirefox/issues/26?
