### ISSUE TITLE
wallpaperplay.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1619]
### Basic Information

**Test link:** `https://wallpaperplay.com/board/blue-android-wallpapers`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

Unable to download images

**Comment by jspenguin2017** [comment]
@okiehsch Breakage.

**Comment by mapx-** [comment]
fixEd
