### ISSUE TITLE
godt.no

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#162]
### Basic Information

**Test link:** `https://www.godt.no/artikkel/24454884/ti-ting-du-kanskje-ikke-visste-inneholdt-gluten`
**Category:** anti-adblock
**Reported from:** Norway
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
**Extension:** Nano Defender 15.0.0.51

**Comment by mapx-** [comment]
annoyance
```
godt.no##.adblock-info-box
godt.no##[class^="advert"]
```
@DandelionSprout
