### ISSUE TITLE
airbnbhell.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1620]
### Basic Information

**Test link:** `https://www.airbnbhell.com/hotel-rooms-will-always-be-preferable-to-airbnb/`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.157

### Additional Message

Persistent reminder (can be x'd out) at every page load to disable Adblock

**Comment by mapx-** [comment]
added as annoyance
