### ISSUE TITLE
themelock.online

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1621]
### Basic Information

**Test link:** `https://themelock.online/brizy-pro-v0-0-25-wordpress-builder-plugin/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.157

**Comment by llacb47** [comment]
Reproduced, try `themelock.online##+js(setTimeout-defuser.js, deblocker)`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Also blocks right click functionality.

**Comment by okiehsch** [comment]
Fixed both issues with one filter.

**Comment by jspenguin2017** [comment]
`t:other`: Anti-right-click.
