### ISSUE TITLE
accuweather.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1622]
### Basic Information

**Test link:** `https://www.accuweather.com/en/us/merchantville-nj/08109/weather-forecast/2192134`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.157

**Comment by llacb47** [comment]
I can reproduce with my settings but not default settings.

**Comment by jspenguin2017** [comment]
Can't reproduce on default: 
![image](https://user-images.githubusercontent.com/7283682/62419246-e650f580-b638-11e9-84a0-9e854802ab95.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.accuweather.com/en/us/philadelphia/19102/hourly-weather-forecast/350540`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message

Site intentionally interfering with display of site when adblock is active

**Comment by llacb47** [comment]
Can't reproduce, ads placeholders are present.
