### ISSUE TITLE
mma-core.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1625]
### Basic Information

**Test link:** `https://www.mma-core.com/videos/Colby_Covington_vs_Robbie_Lawler_Full_Fight_UFC_on_ESPN_5_Part_2/10314864`
**Category:** anti-adblock
**Reported from:** Ireland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.157

### Additional Message

After plaing a few videos, ad block detector stops you from playing the video unless you turn off adblocker

**Comment by llacb47** [comment]
Can reproduce sometimes.

Relevant script: `https://www.mma-core.com/vidjs.js?v=125300`

`mma-core.com##+js(set-constant.js, displayAdBlockedVideo, noopFunc`

Filter for ads: `www.mma-core.com##[href^="/banner/"]`

**Comment by mapx-** [comment]
fixed
