### ISSUE TITLE
player.tubia.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1627]
### Basic Information

**Test link:** `https://player.tubia.com/index.html?publisherid=88e25571535d4aeb8842e9e2c6150513&title=Grindcraft&gameid=2593&colormain=%23fed90f&coloraccent=%234c9fd5&langcode=en-us&keys=%7B%22ch%22%3A%220%22%2C%22ch_date%22%3A%220_0%22%7D&url=https%3A%2F%2Fkizi.com%2Fgames%2Fgrindcraft&href=https%3A%2F%2Fkizi.com%2Fgames%2Fgrindcraft`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.158

### Additional Message

`https://github.com/GameDistribution/tubia-walkthrough-videos/blob/master/src/scripts/plyr/adblocker.js`

**Comment by okiehsch** [comment]
Fixed.
