### ISSUE TITLE
upload.ac

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1628]
### Basic Information

**Test link:** `https://upload.ac/2evrugdgirfh`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.158

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://upload.ac/73ah3kmwejq9`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

1st time detecting adblocker

**Comment by mapx-** [comment]
fixed

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://upload.ac/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

detecting ad-blocker
