### ISSUE TITLE
zambrow.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#163]
### Basic Information

**Test link:** `https://zambrow.org/artykul/wybory-samorzadowe-2018/508806`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.51

**Comment by mapx-** [comment]
@MajkilT

`zambrow.org##+js(abort-current-inline-script.js,document.getElementById, block)`

**Comment by MajkiIT** [comment]
@mapx- Thanks
https://github.com/MajkiIT/polish-ads-filter/commit/16abd39d315aa2dfebd78a5c2131ec38853cccc8#diff-ca815c4f5fe404637a9387f434740d25
