### ISSUE TITLE
odkrywamyzakryte.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1630]
### Basic Information

**Test link:** `https://www.odkrywamyzakryte.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by mapx-** [comment]
fixed as suggested

**Comment by krystian3w** [comment]
by `okiehsch`:

`odkrywamyzakryte.com##+js(fuckadblock.js-3.2.0)`

or by `Bogachenko` and `AdamWr` / `F4z`:

`odkrywamyzakryte.com##+js(abort-on-property-write.js, adBlockDetected)`

or

`@@||odkrywamyzakryte.com^$generichide`
