### ISSUE TITLE
atv.pw

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1633]
### Basic Information

**Test link:** `https://atv.pw/post/how-to-start-a-business-online?1bgV`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.158

### Additional Message

safelink

**Comment by llacb47** [comment]
```
atv.pw###arlinablock
! or
||googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=atv.pw,redirect=noopjs

**Comment by okiehsch** [comment]
Fixed.
