### ISSUE TITLE
breitbart.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1636]
### Basic Information

**Test link:** `https://www.breitbart.com/clips/2019/08/05/fncs-rove-trump-needs-to-do-better-than-his-raw-and-dangerous-race-rhetoric/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.158

### Additional Message

Broken video (loaded from `foxnews.com`)

Seems to be fixed for me with adding `@@||s0.2mdn.net/instream/video/client.js$script,domain=video.foxnews.com`

**Comment by okiehsch** [comment]
@jspenguin2017 can you try 
`||2mdn.net/instream/video/client.js$script,redirect=noopjs,domain=video.foxnews.com`
the video only  works on my end after I click the empty video box.
Same issue if I allow that request.

**Comment by llacb47** [comment]
You referenced the wrong issue, should've been `https://github.com/NanoMeow/QuickReports/issues/1637`

**Comment by llacb47** [comment]
I think the site is broken... I can reproduce even with adblock disabled. I have to click 5 or 6 times on the video player area and then the video will load and play. Even then, there are no controls.

**Comment by okiehsch** [comment]
> You referenced the wrong issue

Thanks https://github.com/uBlockOrigin/uAssets/commit/db580624fb6a8fb0e3b6a8c10343de931b331624

> I think the site is broken

The thing is if I delete cookies don't redirect or allow `2mdn.net/instream/video/client.js` clicking the empty video player does nothing.
If I redirect the request the video starts.
