### ISSUE TITLE
interfans.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1637]
### Basic Information

**Test link:** `https://interfans.org/forum/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.158

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

Anti ablocker in function

**Comment by okiehsch** [comment]
Fixed.

**Comment by llacb47** [comment]
`interfans.org##+js(abort-current-inline-script.js, $, AdBlock)`

Never mind, it's fixed already :)

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/73f04aaa1563822fa412a6764669bfbb56e7c1a1
