### ISSUE TITLE
rapidvideo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1638]
### Basic Information

**Test link:** `https://www.rapidvideo.com/v/G33YZ26BXF`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.158

### Additional Message

Can't change video quality (with ublock/nano adblocker enabled)

```
https://www.rapidvideo.com/v/G33YZ26BXF
https://www.rapidvideo.is/v/G33YZ26BXF
https://www.rapidvid.to/v/G33YZ26BXF
```

The player should look like this.
`https://i.vgy.me/JCwj8R.png`

**Comment by mapx-** [comment]
this should work:
```
@@||rapidvideo.com/assets/$css,script,1p
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=rapidvideo.com
```
