### ISSUE TITLE
citationmachine.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#164]
### Basic Information

**Test link:** `http://www.citationmachine.net/bibliographies/355379408?new=true`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.51

### Additional Message

Div element can be blocked but it seems to be dynamically generated each time

**Comment by jspenguin2017** [comment]
Requires account, see also: https://github.com/NanoAdblocker/NanoFilters/issues/152

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://www.citationmachine.net/items/new?item_type=chapter`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 10895.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.95 Safari/537.36
**Extension:** Nano Defender 15.0.0.58

### Additional Message

Website detected my adblock.

Also, thanks for all you do, you're a hero.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://www.citationmachine.net/items/884874684/copy`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.66

### Additional Message

After the second citation, the website requires you to disable the ad blocker before you can copy the citation.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.citationmachine.net/apa/cite-a-book`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
**Extension:** Nano Defender 15.0.0.205

### Additional Message
