### ISSUE TITLE
topflix.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1642]
### Basic Information

**Test link:** `https://topflix.tv/filmes/assistir-online-john-wick-3-parabellum/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.158

**Comment by llacb47** [comment]
I can reproduce. To do so, click on the image that looks like this.


![play-vd](https://user-images.githubusercontent.com/16567977/62817121-362f3100-baff-11e9-9bbc-ec035fd5722c.png)

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/62817305-8674b600-bb34-11e9-8ce5-40be6f049171.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://topflix.tv/filmes/assistir-online-quarteto-fantastico/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
**Extension:** Nano Defender 15.0.0.205

### Additional Message

**Comment by okiehsch** [comment]
Fixed.
