### ISSUE TITLE
tiktokplay.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1644]
### Basic Information

**Test link:** `https://tiktokplay.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.158

**Comment by llacb47** [comment]
BlockAdblock `https://tiktokplay.com/js/ba.js?v=4`

Also can be found on `tikvid.com`:

`/ba.js$domain=tiktokplay.com|tikvid.com`

**Comment by okiehsch** [comment]
`tikvid.com` is already fixed in `uBO-filters`.

**Comment by okiehsch** [comment]
Fixed.
