### ISSUE TITLE
razorlink.us

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1645]
### Basic Information

**Test link:** `https://www.razorlink.us/p/is-catering-good-business.html?url=IyN5JTE4eiU3Qm0lN0R4JTE4JTA3WkslMDZaQUUlMDclMDclMTIlNUJYJTVDJTVDJTQwIyM%3D`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.158

### Additional Message

safelink

**Comment by llacb47** [comment]
Can't reproduce, add `www.razorlink.us##+js(nano-sib)` for timer annoyance

**Comment by okiehsch** [comment]
https://github.com/jspenguin2017/uBlockProtector/issues/1075

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/14057cc5a95b77aae5aa16fd180ae9a0ddd1fcda
