### ISSUE TITLE
lolinime.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1648]
### Basic Information

**Test link:** `https://lolinime.net/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.159

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by mapx-** [comment]
fixed
