### ISSUE TITLE
jolygram.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#165]
### Basic Information

**Test link:** `https://jolygram.com/profile/asuna_yuuki_undine_/photo/1867711818744977407_4065665766`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.51

### Additional Message

It doesn't block this adblock killer on Ublock.

**Comment by mapx-** [comment]
fixed
