### ISSUE TITLE
linuxandubuntu.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1651]
### Basic Information

**Test link:** `http://www.linuxandubuntu.com/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/75.0.3770.90 Chrome/75.0.3770.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.159

**Comment by llacb47** [comment]
One sidebar ad: `www.linuxandubuntu.com##.widget_media_image:has(a)`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
`linuxandubuntu.com##[href^="https://www.cloudways.com/"]`
for the ad.
Fixed the annoyance.

**Comment by jspenguin2017** [comment]
@ryanbr

**Comment by jspenguin2017** [comment]
Ads seem to be gone, splitting off another issue for breakage: https://github.com/NanoMeow/QuickReports/issues/2259
