### ISSUE TITLE
shop.bbc.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1652]
### Basic Information

**Test link:** `https://shop.bbc.com/planet-earth-i-ii-gift-set-blu-ray-21017.html`
**Category:** breakage
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

Have to set bbc.com to "allow" to show images

**Comment by jspenguin2017** [comment]
@okiehsch Breakage.

**Comment by mapx-** [comment]
fixed
