### ISSUE TITLE
bitblokes.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1655]
### Basic Information

**Test link:** `https://www.bitblokes.de/linux-mint-19-1-tessa-cinnamon-4-0-neuerungen/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.158

### Additional Message

Two little issues on this website:
- Adblock warning and adblocker detection. It doesn't really matter because you still have access to the website, but the adblock warning is a bit annoying.
- On top of the main page (`https://www.bitblokes.de/`) is an undetected ad

**Comment by mapx-** [comment]
uBo annoyances list

**Comment by jspenguin2017** [comment]
There's quite a few other ads and ads placeholders.
