### ISSUE TITLE
streamplay.to

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1659]
### Basic Information

**Test link:** `https://streamplay.to/94csb1bxm4dq`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.160

**Comment by mapx-** [comment]
it's only a red text message appearing even disabling any adblocker

`If you can not see the captcha, it times up or can not connect, please disable your AdBlock for this step`

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://streamplay.to/384cq6g7kx31`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 13020.44.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.50 Safari/537.36
**Extension:** Nano Defender 15.0.0.198

### Additional Message

`proceed to video` does not work without whitelisting site after latest uassets update for this domain

**Comment by mapx-** [comment]
broken by easylist filter `||streamplay.*/jquery-`

**Comment by jspenguin2017** [comment]
Anti-adblock is gone.
