### ISSUE TITLE
vipbox.live

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#166]
### Basic Information

**Test link:** `https://www.vipbox.live/`
**Category:** anti-adblock
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
**Extension:** Nano Defender 15.0.0.51

### Additional Message

I was looking for new ways sites use to block adblockers, and this one seems to be able to do it.
Trying any sort of stream results in "Invalid Request, if you are using anykind of adblock disable and refresh the page."

**Comment by jspenguin2017** [comment]
Test: `http://www.vipbox.live/tulane-vs-cincinnati-5-live`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
sawlive does not work on my end, never has, the detection is triggered by `uBO-filters`
`vipbox.live#@#.position-relative` should fix it, but there could be issues with the video, as I recall that filter was added to enable fullscreen capability.

**Comment by okiehsch** [comment]
OK, I found a site that works for me.
`https://www.vipbox.live/manchester-united-vs-newcastle-united-fc-1-live`
````
vipbox.live#@#.position-relative
@@||camlive.pw/js/cnads.js$xmlhttprequest,first-party
```` 
"works" but playback is still not possible on my end, hmm.

**Comment by ZaphodBeebblebrox** [comment]
It works fine for me with just `vipbox.live#@#.position-relative`

**Comment by mapx-** [comment]
it works on my end adding the filters here:
https://github.com/uBlockOrigin/uAssets/commit/79c214cc9c57780a1c4ca37cb853574c0a573a19

**Comment by jspenguin2017** [comment]
@mapx- `vipbox.live##.position-relative` is part of uBlock filters, remove the broken rule instead?

**Comment by okiehsch** [comment]
@mapx- no need for an exception `vipbox.live##.position-relative` is part of `uBO-filters`, so just remove it.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/46574311-92866900-c9a1-11e8-8fec-e5c26ad85b69.png)

I also need to add `@||camlive.pw/js/cnads.js$xmlhttprequest,first-party` 
for `https://www.vipbox.live/manchester-united-vs-newcastle-united-fc-1-live` to work on my end.

**Comment by jspenguin2017** [comment]
`@@`?

**Comment by mapx-** [comment]
right, done

**Comment by jspenguin2017** [comment]
Is this good now?

**Comment by jspenguin2017** [comment]
Confirmed working.

**Comment by okiehsch** [comment]
Not for me but I appear to be the only one so it may be something ony my side.
