### ISSUE TITLE
reverso.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1661]
### Basic Information

**Test link:** `http://www.reverso.net/spell-checker/english-spelling-grammar/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

**Comment by llacb47** [comment]
`reverso.net###vdasection`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
ad-reinsertion fixed,

**Comment by kjaerlige** [comment]
Sorry, not sure if this is the right filter, but I have an issue with context reverso net - when you're trying to translate any obscene words, reverso shields the screen by blurring the translations and offering a button to reveal the content. With uBlock I can see the blurring, but not the button, so I can't un-blur the page.

**Comment by jspenguin2017** [comment]
@kjaerlige That is out of scope of this project.
