### ISSUE TITLE
jspell.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1662]
### Basic Information

**Test link:** `https://www.jspell.com/public-spell-checker.html`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

**Comment by llacb47** [comment]
`www.jspell.com##.hideonmobile:has(img)`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
