### ISSUE TITLE
camera.aeonax.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1666]
### Basic Information

**Test link:** `https://camera.aeonax.com/`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 9; Redmi Note 4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.101 Mobile Safari/537.36
**Extension:** Nano Defender 15.0.0.160

### Additional Message

`https://ibb.co/4RtBx3y`
Open website click on download.

**Comment by mapx-** [comment]
right, so adding this filter fixes again the issue
`||googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect=googlesyndication_adsbygoogle.js,domain=aeonax.com`
