### ISSUE TITLE
lazada.com.my

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1668]
### Basic Information

**Test link:** `https://www.lazada.com.my/shop/microsoft-flagship-store/Surface-Accessories.htm?spm=a2o6s.10415192.0.0.53f43d05h7HBkx&wh_weex=true`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.19 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

products not showing

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
