### ISSUE TITLE
dogecatch.website

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#167]
### Basic Information

**Test link:** `https://dogecatch.website/d-eth/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.51

### Additional Message

uBO only

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/46573940-72cb5280-c959-11e8-95b0-e38b104bc407.png)

Classic reverse FAB. 
![image](https://user-images.githubusercontent.com/7283682/46573947-94c4d500-c959-11e8-9435-64b7bcb774f4.png)

**Comment by okiehsch** [comment]
Fixed.
