### ISSUE TITLE
kachelmannwetter.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1670]
### Basic Information

**Test link:** `https://kachelmannwetter.com/de/site/adblockuser`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.160

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/183d74f89578cbc3cce02cdc814ba811f83f4b77
