### ISSUE TITLE
eyes-health.win

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1671]
### Basic Information

**Test link:** `https://eyes-health.win/2Xi6P2x`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.160

**Comment by okiehsch** [comment]
Fixed.
