### ISSUE TITLE
shorter.akatsukisubs.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1673]
### Basic Information

**Test link:** `https://shorter.akatsukisubs.com/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.160

### Additional Message

Original URL: `https://shorter.akatsukisubs.com/H6wbY`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
