### ISSUE TITLE
goal.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1677]
### Basic Information

**Test link:** `https://www.goal.com/`
**Category:** breakage
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

**Comment by jspenguin2017** [comment]
Has ads placeholders but can't reproduce breakage.

**Comment by llacb47** [comment]
It's Instart

**Comment by jspenguin2017** [comment]
I do see the IL code, but I don't think it's reinjecting ads.

**Comment by jspenguin2017** [comment]
I do see the IL code, but I think the ads placeholder shows even without IL kicking in.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.goal.com/en`
**Category:** breakage
**Reported from:** Thailand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

When the default Easylist filter is activated, all media and images on the website would not load at all

**Comment by jspenguin2017** [comment]
For https://github.com/NanoMeow/QuickReports/issues/1677#issuecomment-551157913 : 
Can't reproduce.

**Comment by DandelionSprout** [comment]
Gambling widget at `https://www.goal.com/en/news/womens-footballs-existential-crisis-isnt-now-its-when-the-season-/1k77raovfu2fv1um6v7z4f3enq`:
```
||goal.com/betting-widget-proxy/
goal.com##.bw-betting-widget
```

Additionally, I can't determine if one card is either an incorrectly blocked article, or should have its placeholder be removed, since the article it's meant to link to is not an ad by any definition of the word: 
![image](https://user-images.githubusercontent.com/22780683/81459484-70b61f00-91a0-11ea-8fc9-d9017a678a9a.png)

**Comment by jspenguin2017** [comment]
Why is that not an ad? The HTML clearly indicates that it is a sponsored article.

**Comment by jspenguin2017** [comment]
I'm not sure what is the gambling widget that you mentioned, I don't see it. Other placeholders fixed.

**Comment by DandelionSprout** [comment]
As for the article: That's what confuses me too. There's nothing about `https://www.goal.com/en/news/trinche-carlovich-argentina-mourns-the-maverick-maradona/18xitssgl25w513otw4qm1ki6s` that would indicate that it's a sponsored article in any capacity.

As for the gambling widget: 
![image](https://user-images.githubusercontent.com/22780683/81461427-f4c1d400-91ab-11ea-8570-16a83f8238e0.png)

**Comment by jspenguin2017** [comment]
I still don't see the gambling widget. And I still think that blank spot was an ad. 
![image](https://user-images.githubusercontent.com/7283682/81461490-75abac00-9169-11ea-97f7-091d269c4975.png)

**Comment by DandelionSprout** [comment]
It's plausible the widget may be regionally triggered for European audiences, since online gambling in the US is heavily restricted.

But thanks for showing me that the card was an ad after all.

**Comment by jspenguin2017** [comment]
I tried an European IP and I still can't reproduce the said widget. Do you have your filters up to date? 

Also, yea, I noticed all cards say `data-sponsorship`, but only one is an ad. The blank card says `data-role="ad"` which is a dead giveaway.

**Comment by DandelionSprout** [comment]
After further research, I see AdGuard Base has an unnecessary `$generichide` for it, but even deactivating that list doesn't remove the widget entirely.

On the other hand, seeing as it has a `.is-country-no` class name, it could very well be an ad triggered for Norwegian/Nordic audiences only, such that it deserves being added to my Nordic list. 
![image](https://user-images.githubusercontent.com/22780683/81461814-96e2bb80-91ae-11ea-93b0-5a12223c30d8.png)
