### ISSUE TITLE
tokubatch.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1678]
### Basic Information

**Test link:** `https://www.tokubatch.com/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.160

### Additional Message

Original URL: `https://www.tokubatch.com/#!`

**Comment by okiehsch** [comment]
Fixed.
