### ISSUE TITLE
trendlouds.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1679]
### Basic Information

**Test link:** `http://trendlouds.com/RhEblGh`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0 IceDragon/65.0.2
**Extension:** Nano Defender 15.0.0.158

**Comment by okiehsch** [comment]
I get redirected to `exe.io`
Fixed.

**Comment by dumbusernameidk** [comment]
also has an annoyance when you solve the captcha and click get link a popup says "Are you sure you want to leave this page?"

**Comment by jspenguin2017** [comment]
These domains are usually short lived, probably not worth fixing that.
