### ISSUE TITLE
dousyoko.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1681]
### Basic Information

**Test link:** `http://www.dousyoko.net/catlist2`
**Category:** ads
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.35 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

nsfw  ads space

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholders:
```
dousyoko.net###text-3
dousyoko.net##.floatbox2
```
