### ISSUE TITLE
ftuforums.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1686]
### Basic Information

**Test link:** `https://www.ftuforums.com/`
**Category:** anti-adblock
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3840.0 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

Original URL: `https://www.ftuforums.com/page/2/`

**Comment by okiehsch** [comment]
Fixed.
