### ISSUE TITLE
idalponse.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1687]
### Basic Information

**Test link:** `https://idalponse.blogspot.com/?kareeI=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MTFTMXRSSndpbzlwLURBaUFXT0JaMU9mUlVvS0pyamtlfHxHZW5lcmF0ZSBMaW5rfHx8fF9zZWxmfHx0cnVlfHx0cnVlfHx0cnVlfHw=`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.160

### Additional Message

safelink

**Comment by okiehsch** [comment]
Fixed.
