### ISSUE TITLE
coolsoft.altervista.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1689]
### Basic Information

**Test link:** `https://coolsoft.altervista.org/en/virtualmidisynth`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3886.0 Safari/537.36
**Extension:** Nano Defender 15.0.0.160

**Comment by mapx-** [comment]
fixed
