### ISSUE TITLE
bitcoinfaucet.tk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#169]
### Basic Information

**Test link:** `http://bitcoinfaucet.tk/`
**Category:** anti-adblock
**Reported from:** South Africa
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.52

**Comment by jspenguin2017** [comment]
@okiehsch Need to wait 20 seconds. 
![image](https://user-images.githubusercontent.com/7283682/46575200-0870dd00-c96e-11e8-989e-715aee8ebe8a.png)

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/7a8357373a6d329d30c091b71a6826a639e7ed79
