### ISSUE TITLE
refoblog.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1690]
### Basic Information

**Test link:** `https://refoblog.xyz/6-kunci-p%d0%b5nt%d1%96ng-untuk-hidupkan-semangat-b%d0%b5r%d0%bel%d0%b0hr%d0%b0g%d0%b0-buat-si-mager/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.160

**Comment by okiehsch** [comment]
Fixed.
