### ISSUE TITLE
thesaurus.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1692]
### Basic Information

**Test link:** `https://www.thesaurus.com/browse/as%20a%20result`
**Category:** anti-adblock
**Reported from:** Bahrain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.158

**Comment by llacb47** [comment]
```
@@||thesaurus.com^$generichide
! placeholder
thesaurus.com##aside.em66cyi0.css-1xdhyk6:nth-of-type(2)
```

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance.

**Comment by okiehsch** [comment]
Fixed.
