### ISSUE TITLE
tatsumi-crew.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1693]
### Basic Information

**Test link:** `https://www.tatsumi-crew.net/2019/05/cara-bypass-shortlinksafelink.html?m=1`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 5.1.1; A37f) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.101 Mobile Safari/537.36
**Extension:** Nano Defender 15.0.0.160

**Comment by llacb47** [comment]
```
tatsumi-crew.net##+js(noeval)
! placeholder
tatsumi-crew.net###HTML2
```

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
