### ISSUE TITLE
jmusic.me

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1699]
### Basic Information

**Test link:** `https://jmusic.me/`
**Category:** anti-adblock
**Reported from:** Israel
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.160

**Comment by okiehsch** [comment]
@IsraeliUser 
````
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,redirect=nooptext,domain=jmusic.me
````
works on my end.

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by llacb47** [comment]
for easylist - doesn't need uBo syntax:

`||jmusic.me/wp-content/plugins/deblocker/js/deblocker.min.js`

maybe:

`/wp-content/plugins/deblocker/*$script`

@ryanbr

**Comment by okiehsch** [comment]
`EasyList` does not add  filters for anti adblock issues.

@IsraeliUser
`jmusic.me##+js(aopr, mdp_deblocker)`
works for me.

**Comment by llacb47** [comment]
Oops, forgot. Isn't network filter a more desirable solution though?

**Comment by okiehsch** [comment]
It depends, in this case the site can simply rename the request and it will fire.
It is a custom anti adblock solution, so the site can't change the script itself and the scriptlet will work even if they rename the request.
It is up to `EasyList Hebrew` both solutions work.

**Comment by okiehsch** [comment]
Thinking about it adding 
`/wp-content/plugins/deblocker/*$script,1p`
to `uBO-filters` does make sense.

**Comment by krystian3w** [comment]
> 
> 
> for easylist - doesn't need uBo syntax:
> 
> `||jmusic.me/wp-content/plugins/deblocker/js/deblocker.min.js`
> 
> maybe:
> 
> `/wp-content/plugins/deblocker/*$script`

bad on:

```
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=zobacz.ws,redirect=noopjs,important
@@/wp-content/plugins/deblocker/*$script,domain=zobacz.ws
```

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/80ef4ca6c771abddb2238cfbceb8a4bb05149ef2
