### ISSUE TITLE
flashgirlgames.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1712]
### Basic Information

**Test link:** `https://www.flashgirlgames.com/games/princesseschillinatthepool`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.158

**Comment by mapx-** [comment]
fixed
