### ISSUE TITLE
woof.tube

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1715]
### Basic Information

**Test link:** `https://woof.tube/stream/aMzPBs5296N/Little_Italy_-_Pizza_amore_e_fantasia_%5BHD%5D_%282018%29_Bluray_1080p.mp4`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.158

**Comment by mapx-** [comment]
fixed
