### ISSUE TITLE
devdrive.cloud

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1718]
### Basic Information

**Test link:** `https://devdrive.cloud/abf3312e2ddbd382/Z6_Lite+EN+Recovery.zip`
**Category:** anti-adblock
**Reported from:** New Zealand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0
**Extension:** Nano Defender 15.0.0.158

**Comment by mapx-** [comment]
fixed
