### ISSUE TITLE
mobil.derstandard.at

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#172]
### Basic Information

**Test link:** `https://mobil.derstandard.at/2000088842587/Bobos-Proleten-und-die-wahren-Veraechter-der-einfachen-Leute#`
**Category:** anti-adblock
**Reported from:** Austria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 8.1.0; Mobile; rv:62.0) Gecko/62.0 Firefox/62.0
**Extension:** Nano Defender 15.0.0.51

**Comment by jspenguin2017** [comment]
Could be related to https://github.com/NanoAdblocker/NanoFilters/issues/149

**Comment by llacb47** [comment]
Issue fixed? https://github.com/NanoAdblocker/NanoFilters/issues/149#issuecomment-468134738

**Comment by jspenguin2017** [comment]
Yea, the domain is no longer in use. It redirects to the main domain now. Looks like the new design is responsive.
