### ISSUE TITLE
dramaz.se

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1721]
### Basic Information

**Test link:** `http://www2.dramaz.se/sky-castle-%e5%a4%a9%e7%a9%ba%e5%9f%8e%e5%a0%a1-episode-01/`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.161

**Comment by mapx-** [comment]
fixed
