### ISSUE TITLE
tiktokview.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1722]
### Basic Information

**Test link:** `https://tiktokview.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.161

**Comment by llacb47** [comment]
Clone of https://github.com/NanoMeow/QuickReports/issues/1644

**Comment by mapx-** [comment]
fixed
