### ISSUE TITLE
imggram.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1723]
### Basic Information

**Test link:** `https://imggram.org/media/ask_x_and_four/1918180979080584590_8886660184?hl=ja`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.161

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. Has ads placeholders though.

**Comment by llacb47** [comment]
`imggram.org##div:has(>div[data-ad])`
