### ISSUE TITLE
thesilphroad.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1725]
### Basic Information

**Test link:** `https://thesilphroad.com/`
**Category:** ads
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.42 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

```
Why Ads? TheSilphRoad.com's research tools generate massive traffic - and it costs money to keep the Silph lights on!
```

visible on other pages: 
```
https://thesilphroad.com/catalog
https://thesilphroad.com/egg-distances
https://thesilphroad.com/raid-bosses
etc...
```

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by llacb47** [comment]
```
thesilphroad.com###keepinTheLightsOn
thesilphroad.com##.light
thesilphroad.com##p:has-text(lights on)
```

**Comment by jspenguin2017** [comment]
That hides the login form BTW.
