### ISSUE TITLE
permadihermawan.site

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1734]
### Basic Information

**Test link:** `https://www.permadihermawan.site/2019/07/tips-for-successfully-advertising.html#?o=80cc030ddaaff8eda5e8cb2dcc1702c4fb73dc59300aea540380724a37028adba3ded56b73819363f047d24eebd19077df1bebbf657c0271c32676f2ffdd93b8102df14a8f562f55`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.162

### Additional Message

Adblock Detected

**Comment by okiehsch** [comment]
Fixed.
