### ISSUE TITLE
secretsdujeu.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1736]
### Basic Information

**Test link:** `https://www.secretsdujeu.com/foot/loto-foot-resultat-7`
**Category:** ads
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

Using multiple "nth-of-type" css rules with random numbers inside

**Comment by okiehsch** [comment]
Fixed.
@smed79 fyi ad-reinsertion, not sure how you handle such issues in your own list, i.e. if you add `script:injections`
