### ISSUE TITLE
roanoke.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1738]
### Basic Information

**Test link:** `https://www.roanoke.com/sports/college/va_tech/the-ncaa-process-is-horrible-brock-hoffman-s-family-blindsided/article_c5089c78-c931-11e9-a864-535f669b7652.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12239.67.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.102 Safari/537.36
**Extension:** Nano Defender 15.0.0.163

### Additional Message

Detects I am using nano.

**Comment by okiehsch** [comment]
Fixed.
