### ISSUE TITLE
sangrembulan.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1742]
### Basic Information

**Test link:** `http://sangrembulan.net/manfaat-tidur-siang-bagi-kesehatan-tubuh/?wp_safelink_data=YjZkNzY3ZDJmOGVkNWQyMWE0NGIwZTU4ODY2ODBjYjkqTWlCNGdtSUYzOGhQTUQ5YXFEL05vTkhUMTUvdWhBUUhtTG54bWFUaGdudlVOWm93cEx0ZVZDSCt5QW1ZQW0vWEdJWUNhMlhmYlRSUjM4RFVyWDZaRGc2Q1g5L0l0L0NTbTcvZWNEaDJrMFZCcDhQc1pXQjNoSHhNMi9TdGNsNktmdElrRWkxQ1JUd1NMdmdwQm56V0Z3PT0=#landing`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.162

### Additional Message

safelink

**Comment by okiehsch** [comment]
Fixed.
