### ISSUE TITLE
etonline.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1749]
### Basic Information

**Test link:** `https://www.etonline.com/media/videos/avengers-endgame-mark-ruffalo-says-he-had-a-dummy-script-to-avoid-spoilers-exclusive`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.163

**Comment by okiehsch** [comment]
Fixed.
