### ISSUE TITLE
durtypass.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#175]
### Basic Information

**Test link:** `https://www.durtypass.com/`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36 OPR/56.0.3051.28 (Edition beta)
**Extension:** Nano Defender 15.0.0.54

**Comment by mapx-** [comment]
fixed
