### ISSUE TITLE
blackgamer.ru

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1755]
### Basic Information

**Test link:** `http://blackgamer.ru/`
**Category:** anti-adblock
**Reported from:** Russia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.164

**Comment by llacb47** [comment]
`blackgamer.ru##+js(abort-on-property-write, adBlockDetected)`

**Comment by jspenguin2017** [comment]
@okiehsch
