### ISSUE TITLE
downdetector.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1757]
### Basic Information

**Test link:** `https://downdetector.pl/status/instagram`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.124

### Additional Message

Why does it block Disqus and all the comments? :/

**Comment by krystian3w** [comment]
@MajkiIT ❗️ ❗️ ❗️ ❗️ ❗️ ❗️ ❗️ ❗️ ❗️ ❗️ ❗️  https://github.com/MajkiIT/polish-ads-filter/issues/14552

**Comment by krystian3w** [comment]
> `Why does it block Disqus and all the comments? :/`

becouse Poland block `AdChoices` by:

`||c.evidon.com$script`

Fix:

`||c.evidon.com$script,badfilter`

And manually accept privacy policy https://github.com/NanoAdblocker/NanoFilters/issues/210

**Comment by jspenguin2017** [comment]
It works fine for me, even if I enable Polish regional filters. 
![image](https://user-images.githubusercontent.com/7283682/64079289-0ceb6600-cca3-11e9-9cf9-91788e7e0ae6.png)

**Comment by krystian3w** [comment]
No work you enabled regional filters? https://github.com/MajkiIT/polish-ads-filter/issues/14552

bad filter still exsist: https://github.com/MajkiIT/polish-ads-filter/blob/75a9a5b1a0eb6e6a83c89bef17dde0ece7a594b6/polish-adblock-filters/adblock.txt#L3303

**Comment by MajkiIT** [comment]
@krystian3w @jspenguin2017 Thanks
https://github.com/MajkiIT/polish-ads-filter/commit/7ffaf0e4a73c300df835d5a01c35bf6c51d20b2b#diff-711027ed0794992ae3b8710d874f3df7

**Comment by jspenguin2017** [comment]
Disqus loads fine for me even with `c.evidon.com` blocked. Maybe caused by different Geo.
