### ISSUE TITLE
hulu.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#176]
### Basic Information

**Test link:** `https://www.hulu.com/watch/202d56f1-920b-4afe-8626-e17e8df69fc4`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.54

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.hulu.com/watch/0f48fc63-ef9e-42b6-bf9d-adb29276c46c`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.64

### Additional Message

Hulu anti adblock thing just before shows isnt blocked

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.hulu.com/watch/5fdf2bc8-d36f-4e1f-ad49-8b897d7692ef`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
**Extension:** Nano Defender 15.0.0.80

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.hulu.com/watch/47ee10d0-567c-4195-a0cf-5cb0ac45fb3e`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.124

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.hulu.com/watch/13cf274c-4e90-4efb-bcae-55b201f04826`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
**Extension:** Nano Defender 15.0.0.147

### Additional Message

Nanodefender doesn't work on hulu like it used to, now it doesnt show the add but counts down the time the add would have taken

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/766e774948be00b0b91cd7c177bd9d44c9b0adea
