### ISSUE TITLE
radioplus.be

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1767]
### Basic Information

**Test link:** `https://radioplus.be/#/stubru/herbeluister`
**Category:** breakage
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.124

**Comment by okiehsch** [comment]
Fixed.
