### ISSUE TITLE
smashboards.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1772]
### Basic Information

**Test link:** `https://smashboards.com/threads/arizona-ultimate-players.466253/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.163

### Additional Message

big red banner that says adblock is on, i have nano blocker on + defender as well

**Comment by mapx-** [comment]
it's already fixed as annoyance: needing the `uBlock filters – Annoyances` list to be enabled

**Comment by jspenguin2017** [comment]
Moved old rule to Nano Filters. Also, ads placeholders fixed in placeholder buster list.
