### ISSUE TITLE
theweathernetwork.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1779]
### Basic Information

**Test link:** `https://www.theweathernetwork.com/ca/weather/ontario/mississauga/L5M0M8/e1097941`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.167

### Additional Message

Webpage is basically blank

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/64293160-492ff800-cf29-11e9-86cc-6c5589e1082c.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.theweathernetwork.com/ca/36-hour-weather-forecast/ontario/toronto`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

Blocks weather details, temperature etc

**Comment by mapx-** [comment]
`||theweathernetwork.com/guid` breaking the page, notified on slack @ryanbr

**Comment by mapx-** [comment]
fixed https://github.com/easylist/easylist/commit/2529f61050e427a1825332caa9ca560f8e8e9755

**Comment by jspenguin2017** [comment]
https://github.com/easylist/easylist/commit/2529f61050e427a1825332caa9ca560f8e8e9755
