### ISSUE TITLE
belfasttelegraph.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1780]
### Basic Information

**Test link:** `https://www.belfasttelegraph.co.uk/news/viral/sharpiegate-donald-trump-memes-hit-twitter-after-map-altered-with-pen-38470049.html`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.167

**Comment by mapx-** [comment]
fixed as annoyance => you have to enable uBo annoyances list
