### ISSUE TITLE
spieleklassiker.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1792]
### Basic Information

**Test link:** `https://www.spieleklassiker.com/Pacman`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.70 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance.

**Comment by okiehsch** [comment]
Added.

**Comment by okiehsch** [comment]
Hm, actually the site also uses hard-adblock that prevents one from playing the game.
Example link: `https://www.spieleklassiker.com/spiel/Lady+Bug+Pacman`
Click "Spiele" to see the anti-adblock message.

I will move the filters to uBO-filters.
