### ISSUE TITLE
gnula.nu

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1797]
### Basic Information

**Test link:** `http://gnula.nu/drama/ver-gisaengchung-parasite-2019-online/`
**Category:** other
**Reported from:** Guatemala
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.124

### Additional Message

Rating not showing up

**Comment by mapx-** [comment]
Where is the rating ?

**Comment by jspenguin2017** [comment]
I don't see it neither. Let's call this one good for now.
