### ISSUE TITLE
publicwww.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#180]
### Basic Information

**Test link:** `https://publicwww.com/examples/ads.html`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.54

### Additional Message

Quite a few images triggers EasyList filters. Recommended fix: `@@||publicwww.com^$image,first-party`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
