### ISSUE TITLE
darmowa-telewizja.online

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1803]
### Basic Information

**Test link:** `http://darmowa-telewizja.online/tvp1.html`
**Category:** anti-adblock
**Reported from:** Ireland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

adblock detected

**Comment by mapx-** [comment]
fixed some popups, anti adb already fixed by regional list

**Comment by jspenguin2017** [comment]
Yep, looks like anti-adblock is handled by Polish regional filters.
