### ISSUE TITLE
textsheet.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#181]
### Basic Information

**Test link:** `https://www.textsheet.com/`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.54

### Additional Message

Breaks survey wall

**Comment by ZaphodBeebblebrox** [comment]
Can you give steps to reproduce?

**Comment by jspenguin2017** [comment]
See https://github.com/NanoMeow/QuickReports/issues/133
I'm not sure how it decides to give you surveys, so you might need to go find more links on Chegg.

**Comment by ZaphodBeebblebrox** [comment]
It took 3 years worth of reloading, but I got another one finally.
