### ISSUE TITLE
release-apk.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1813]
### Basic Information

**Test link:** `https://release-apk.com/index.php?sid=0170b5cce3b678d0c99e83358b4f0844`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 8.1.0; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0
**Extension:** Nano Defender 15.0.0.167

**Comment by mapx-** [comment]
as annoyance, needing uBo annoyances list to be enabled
