### ISSUE TITLE
bestjavporn.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1815]
### Basic Information

**Test link:** `https://bestjavporn.com/video/arm-794-strong-desire-for-beautiful-legs-i-want-to-finish-off-on-your-bare-skinned-legs/`
**Category:** anti-adblock
**Reported from:** China
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by okiehsch** [comment]
Fixed.
