### ISSUE TITLE
zend.phytech.ro

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1818]
### Basic Information

**Test link:** `https://zend.phytech.ro/W89y5`
**Category:** other
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Adblocker 1.0.0.125

### Additional Message

countdown doesn't start

**Comment by mapx-** [comment]
No issue with countdown, I get only anti adb stuff, now fixed
