### ISSUE TITLE
newsaddicted.online

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1820]
### Basic Information

**Test link:** `http://newsaddicted.online/tjJ9YXC1`
**Category:** breakage
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

blocking captcha

**Comment by mapx-** [comment]
fixed
