### ISSUE TITLE
tomsguide.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1822]
### Basic Information

**Test link:** `https://www.tomsguide.com/us/panda-global-ultimate-gamecube-adapter-preview,news-29409.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

**Comment by okiehsch** [comment]
Fixed in annoyances.
