### ISSUE TITLE
leo.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1830]
### Basic Information

**Test link:** `https://www.leo.org/franz%C3%B6sisch-deutsch/`
**Category:** other
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

Ads placeholders

**Comment by krystian3w** [comment]
@mapx-

![obraz](https://user-images.githubusercontent.com/35370833/64896260-71cd9580-d67f-11e9-9b5b-7ad530b7067a.png) |
--- |

**Comment by krystian3w** [comment]
Placeholders and self-promotion can defend:

```
dict.leo.org###adv-text
dict.leo.org##[id^="adv-"]:not(#adv-settings)
```

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance.

**Comment by okiehsch** [comment]
Fixed.
