### ISSUE TITLE
uk.flightaware.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1832]
### Basic Information

**Test link:** `https://uk.flightaware.com/live/airport/VTBS/scheduled?;offset=40;order=filed_departuretime;sort=ASC`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Occasional reminder (can be dismissed) to disable Adblock

**Comment by jspenguin2017** [comment]
Fixed by Adblock Warning Removal List.
