### ISSUE TITLE
trabajosfaciles.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1833]
### Basic Information

**Test link:** `https://www.trabajosfaciles.com/maravillosas-aplicaciones-para-realizar-turismo-en-colombia/`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36 OPR/63.0.3368.88
**Extension:** Nano Defender 15.0.0.168

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.trabajosfaciles.com/ganar-dinero-en-forex-realmente-se-puede/`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36 OPR/63.0.3368.88
**Extension:** Nano Defender 15.0.0.168

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.trabajosfaciles.com/sera-que-busco-un-trabajo-facil/`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36 OPR/63.0.3368.94
**Extension:** Nano Defender 15.0.0.168

### Additional Message

**Comment by llacb47** [comment]
Can't reproduce. There is anti-select.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select

@okiehsch

**Comment by okiehsch** [comment]
Fixed.
