### ISSUE TITLE
mtlurb.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1835]
### Basic Information

**Test link:** `https://mtlurb.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mtlurb.com/topic/15259-stm-edicule-square-cabot-de-la-station-atwater/page/2/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

disables scrolling and shows dialog

**Comment by llacb47** [comment]
Test `mtlurb.com##+js(nostif, purple_box)`

**Comment by jspenguin2017** [comment]
@okiehsch Hard anti-adblock, comes up after a few refreshes.

**Comment by okiehsch** [comment]
Fixed.
