### ISSUE TITLE
leechall.download

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1849]
### Basic Information

**Test link:** `https://leechall.download/go/B9NYOZ506U8CG1L`
**Category:** anti-adblock
**Reported from:** Argentina
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Adblocker 1.0.0.125

### Additional Message

from `https://leechall.com/` (no problem) to `https://leechall.download/go/B9NYOZ506U8CG1L` (anti ad block detected)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://leechall.download/go/K0J7OTELV1XW6ZB`
**Category:** anti-adblock
**Reported from:** Taiwan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.195

### Additional Message

**Comment by llacb47** [comment]
`leechall.download##.adss:style(height:25px!important)`

**Comment by jspenguin2017** [comment]
@llacb47 I don't see the `.adss` element anywhere.

**Comment by llacb47** [comment]
They renamed it. Look at the last inline script.

**Comment by jspenguin2017** [comment]
There is already a rule in uBlock filters that handles that. 
![image](https://user-images.githubusercontent.com/7283682/77704957-fc267880-6f83-11ea-9f92-4d95159e27c9.png)
