### ISSUE TITLE
imageshtorm.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1852]
### Basic Information

**Test link:** `http://imageshtorm.com/img-5d7a692e8b234.html`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3887.7 Safari/537.36 OPR/65.0.3437.0 (Edition developer)
**Extension:** Nano Defender 15.0.0.168

**Comment by mapx-** [comment]
no anti adb, fixed the popups

**Comment by jspenguin2017** [comment]
@mapx- Please let me know when the `nsfw` tag is missing.
