### ISSUE TITLE
nzz.ch

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1857]
### Basic Information

**Test link:** `https://www.nzz.ch/international/pharmakonzern-purdue-beantragt-glaeubigerschutz-auch-soll-es-millionen-ueber-schweizer-bankkonten-versteckt-haben-die-neuesten-entwicklungen-und-hintergruende-zur-opioid-krise-in-den-usa-ld.1504775?utm_source=pocket-newtab`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

**Comment by okiehsch** [comment]
@jspenguin2017 add `@@||nzz.ch^$generichide` to your list.
