### ISSUE TITLE
bing.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1858]
### Basic Information

**Test link:** `https://www.bing.com/search?q=edwards+mira+mesa&PC=U531&cvid=95e26caaa0f14f1ca434ce1b0e16c8cb&FORM=ANAB01&setLang=en`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.0 Safari/537.36 Edg/78.0.276.0
**Extension:** Nano Adblocker 1.0.0.126

### Additional Message

The movie listings are hidden as ads when the extension is enabled; they are not supposed to be.

**Comment by llacb47** [comment]
They are affiliate links.

**Comment by jspenguin2017** [comment]
I don't see any movie listing even in guest mode. Marking as works.

**Comment by jspenguin2017** [comment]
@okiehsch Requires US IP. I'm not sure if those buy ticket links can be considered ads, but it looks like some rules need to be tweaked. 
![image](https://user-images.githubusercontent.com/7283682/65004858-1f78b880-d8bb-11e9-86e5-efd358c327fc.png)

**Comment by mapx-** [comment]
killed in unbreak list @ryanbr

**Comment by jspenguin2017** [comment]
Would that whitelist sponsored search results though?

**Comment by mapx-** [comment]
bing does not target anymore its sponsored results using the normal (compact) "Ad" so that filter (now whitelisted) will  cause only false positives

**Comment by jspenguin2017** [comment]
@mapx- Maybe also `bing.com#@#.b_mhdr`? 
![image](https://user-images.githubusercontent.com/7283682/65280041-bc6e6800-daec-11e9-9dd1-da155f46292d.png)

**Comment by mapx-** [comment]
fixed
