### ISSUE TITLE
typing-speed.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1865]
### Basic Information

**Test link:** `https://typing-speed.net/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

Adblock Detection - asks to disable the adblocker. However, you still have access to everything on the website with enabled adblocker, so it's not really anti-adblock.

**Comment by mapx-** [comment]
fixed as annoyance (use uBo annoyance list)
