### ISSUE TITLE
adweek.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1866]
### Basic Information

**Test link:** `https://www.adweek.com/agencies/sandy-hook-promise-darkly-flips-cheery-back-to-school-ads-on-its-head-in-new-psa/`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.adweek.com/digital/instagram-is-forcing-people-to-log-in-after-viewing-a-set-number-of-photos/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.adweek.com/agencies/nasas-worm-logo-officially-killed-in-1992-will-rise-again-on-falcon-9/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.adweek.com/brand-marketing/travel-brand-beis-dtc-success/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.adweek.com/tv-video/nbcus-ticketing-and-vod-service-fandango-acquires-walmart-owned-vudu/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

The anti-adblock isn't blocked.

**Comment by llacb47** [comment]
`adweek.com##+js(nostif, testAd.offsetHeight)`
