### ISSUE TITLE
wowhead.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#187]
### Basic Information

**Test link:** `https://www.wowhead.com/`
**Category:** breakage
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.55

### Additional Message

The site loads initially and then once fully loaded, blocked by nano defender using ublock origin.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.wowhead.com/`
**Category:** other
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.55

### Additional Message

The website loads for a split second then becomes a completely blank white page whenever nano defender is enabled but when i only use nano adblocker and no defender it loads just fine

**Comment by jspenguin2017** [comment]
Need to remove the broken rule from ND.
