### ISSUE TITLE
hkfree.asianfans.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1875]
### Basic Information

**Test link:** `http://hkfree.asianfans.net/watch-online/lo-and-behold/episode-667`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.21 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.126

### Additional Message

Imported from WebStore support page: 

When adblock is turned on, video redirected to youtube video; when adblock is turned off, play ads videos and the real video

Issue confirmed.

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/7747babc424049975a607c037c2bb62d2e722118
