### ISSUE TITLE
salerno.occhionotizie.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1878]
### Basic Information

**Test link:** `https://salerno.occhionotizie.it/battipaglia-bagnino-morto/?fbclid=IwAR1DFzu4BN79_BjW88P03B7-6RzGgCXYhce7o9wn0x1snUATsZMn-RVKlRA`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.0 Safari/537.36 Edg/78.0.276.2
**Extension:** Nano Defender 15.0.0.168

**Comment by okiehsch** [comment]
Fixed.
