### ISSUE TITLE
fmovies.top

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1892]
### Basic Information

**Test link:** `https://fmovies.top/episodes/euphoria-1x2/?watch-token=VFgarqiion6LMlAK`
**Category:** anti-adblock
**Reported from:** Hong Kong
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

Mirror number 2. I belive the stream source is hqq.tv
Message shown: Owner of this video doesnot allow AdBlock. To watch video disable AdBlock and refresh page.

Streaming is blocked in the meanwhile

**Comment by okiehsch** [comment]
I can't reproduce the anti adblock message, I do see some popops and other crap,
