### ISSUE TITLE
sankakucomplex.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1893]
### Basic Information

**Test link:** `https://www.sankakucomplex.com/search/?q=danmachi`
**Category:** breakage
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.126

**Comment by jspenguin2017** [comment]
@okiehsch
