### ISSUE TITLE
nfl.streamcartel.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1894]
### Basic Information

**Test link:** `http://nfl.streamcartel.org/1.html?ch2`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12371.65.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.93 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

redirects and popups

**Comment by okiehsch** [comment]
I can't reproduce at the link provided.
I fixed popups I observed at other parts of that site.
