### ISSUE TITLE
wowescape.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#19]
### Basic Information

**Test link:** `http://www.wowescape.com/play/magic-tree-fairy-escape/19166`
**Category:** breakage
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
**Extension:** Nano Defender 15.0.0.37

**Comment by jspenguin2017** [comment]
@okiehsch This broke again. Honestly I don't know if it'll worth bothering with this anymore.

**Comment by okiehsch** [comment]
Hm, works on my end are your filters up to date?
![image](https://user-images.githubusercontent.com/16838044/44559689-f9322900-a74b-11e8-9607-d6f74cf86b8b.png)

**Comment by okiehsch** [comment]
I can't reproduce that, the redirection
`||youtube.com/get_video$media,redirect=noopmp4-1s,domain=wowescape.com`
skips that screen basically immediately on my end.

**Comment by jspenguin2017** [comment]
It's loaded from another path for me: 
![image](https://user-images.githubusercontent.com/7283682/44562132-61194d00-a715-11e8-8fe8-57274aef1a1a.png)

**Comment by okiehsch** [comment]
`||wowescape.com/*.mp4$media,redirect=noopmp4-1s,first-party`
works for you?

**Comment by okiehsch** [comment]
Actually I can see the same path in my source and in the logger, so that can't be the reason it does not work for you.
![image](https://user-images.githubusercontent.com/16838044/44562490-2554a680-a75a-11e8-88a9-395e91d92336.png)

**Comment by jspenguin2017** [comment]
That does nuke the video, but nothing happens after.

**Comment by okiehsch** [comment]
Is the only media request on your end the `wowescape.com/*.mp4` one, if you don't block it?

**Comment by okiehsch** [comment]
OK, my bad I can reproduce, the issue was fixed because I still had two non english regional lists enabled, I will add a fix after narrowing it down.

**Comment by okiehsch** [comment]
Fixed. https://github.com/uBlockOrigin/uAssets/commit/9c48c2f3a2df94384aaf215d6d0a6a523846f812

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://www.wowescape.com/play/escape-from-space/19095`
**Category:** breakage
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
**Extension:** Nano Defender 15.0.0.37

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://www.wowescape.com/play/games4king-help-me-to-fly/19226`
**Category:** breakage
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
**Extension:** Nano Defender 15.0.0.37

### Additional Message

**Comment by jspenguin2017** [comment]
Added a reporter rule.

**Comment by llacb47** [comment]
Test these filters:

```
wowescape.com##embed:style(display:block!important)
wowescape.com###adContainer
! override uAssets
||imasdk.googleapis.com$domain=wowescape.com,important
||googlesyndication.com$domain=wowescape.com,important
||wowescape.com/node_modules/videojs-contrib-ads/*$script,important
wowescape.com##[id^="gdsdk_"]
! Ads placeholders
wowescape.com##div:has(>div:has(>.adsbygoogle))
wowescape.com##div.border_radius:has-text(Advertisement)
wowescape.com##.col-sm-4:has-text(Advertisement)
```

Test page: `http://www.wowescape.com/play/games4king-help-me-to-fly/19226`

**Comment by okiehsch** [comment]
>  override uAssets

If those filters are no longer needed to fix the original issue https://github.com/uBlockOrigin/uAssets/issues/3200
I will remove them.
I don't use Flash so I can't properly test the site.

**Comment by llacb47** [comment]
Well, before removing them someone should test the filters.

**Comment by jspenguin2017** [comment]
The rules seems to work, although not sure how long will it last.

**Comment by llacb47** [comment]
Similar game website: `http://games4king.com/games4king-escape-games/g4k-good-habit-boy-rescue-game`

Test rules:
```
! kill ad overlay
games4king.com###wrapped-content:style(display:inherit!important)
games4king.com###ava-game_container:style(display:inherit!important)
! ads placeholders
games4king.com##[id^="leaderboard"]
games4king.com##[class^="ads"]
```

Also should `||cdn.pushcrew.com` be added as annoyance in uAssets?

**Comment by llacb47** [comment]
Another game website: `http://www.funescapegames.com/game/find-the-antiquated-compass`

Test:
```
funescapegames.com###avcms-game-advert
funescapegames.com###avcms-game-container:style(display:inherit!important)
funescapegames.com##div.panel-body:has(.adsbygoogle)
```

**Comment by llacb47** [comment]
Placeholders `https://bestescapegames.com/emerald-castle-escape`

```
bestescapegames.com##[id*="add_"]
bestescapegames.com##[class*="add_"]
bestescapegames.com##div.featured-images:has-text(Advertisement)
bestescapegames.com##.game-center:has-text(Advertisement)
bestescapegames.com##.col-xs-12.col-md-4.right-sidebar01:has(script[src*="ads."])
```

**Comment by llacb47** [comment]
Anti-adblock `http://www.nsrescapegames.com/game/nsr-escape-games/caterpiller-rescue` via `wgplayer.com`, which is an advertisement-serving video player.

```
! anti-adblock fix (add these filters to uAssets or easylist?)
||wgplayer.com^$third-party
||wgplayer.xyz^$third-party
```

Placeholder `http://www.nsrgames.com/`

`nsrgames.com##.mtvn-mpu-ad`

**Comment by llacb47** [comment]
Placeholders: `http://www.dressupone.com/flying-luigi/game`

`www.dressupone.com##[id^="ad-out-"]`

**Comment by llacb47** [comment]
Placeholders: `http://www.mygames4girls.com/-frozen-/`

```
www.mygames4girls.com##.box.stamp:has(ins)
www.mygames4girls.com##div.clearfix.auextend:has-text(Ads)
```

**Comment by jspenguin2017** [comment]
@mapx- Can you have a look?

**Comment by llacb47** [comment]
`games2rule.com` is basically a copy of `wowescape.com`, test the same rules from https://github.com/NanoMeow/QuickReports/issues/19#issuecomment-517969002:

```
games2rule.com##embed:style(display:inherit!important)
games2rule.com###adContainer
games2rule.com##[id^="gdsdk_"]
||imasdk.googleapis.com$domain=games2rule.com,important
||googlesyndication.com$domain=games2rule.com,important
||games2rule.com/node_modules/videojs-contrib-ads/*$script,important
games2rule.com##div:has(>div:has(>.adsbygoogle))
games2rule.com##div.border_radius:has-text(Advertisement)
games2rule.com##.col-sm-4:has-text(Advertisement)
games2rule.com##+js(remove-attr.js, target)
```

**Comment by llacb47** [comment]
Placeholders: `http://www.avmgames.com/avm-games/black-bear-escape-game`

```
avmgames.com##div:has(>ins.adsbygoogle)
avmgames.com###leaderboard_area
avmgames.com##+js(remove-attr.js, target)
```

**Comment by llacb47** [comment]
Placeholders: `http://www.8bgames.com/g2j-gold-coin-bag-escape/`

```
8bgames.com##div.widget-title:has-text(/Ad|Spon/)
8bgames.com##[class^="adds"]:has(script)
8bgames.com##.colorbar
```

**Comment by llacb47** [comment]
Placeholders: `http://www.mousecity.com/` `http://www.mousecity.com/games/hidden-object/tropical-adventure/`


```
mousecity.com##div:has(>script:has-text(slot))
mousecity.com##div:has(>ins.adsbygoogle)
mousecity.com##div[style]:has(>div>script:has-text(slot))
```

**Comment by llacb47** [comment]
Placeholders: `top10newgames.com` `http://top10newgames.com/play.php?games&id=4558&game=8bGames--Little-Monster-Escape`

```
top10newgames.com##.adBlockEnableClass
top10newgames.com##[class^="col-"]:has(>.largesky:has(.adsbyvli))
```

**Comment by llacb47** [comment]
Another games site: https://github.com/NanoMeow/QuickReports/issues/21

**Comment by llacb47** [comment]
Placeholders: `http://www.games2jolly.com/escape-games/top10newgames-escape-from-ancient-tomb-2`

```
games2jolly.com##[id^="leaderboard"]
games2jolly.com##.ads_310_610_sidebar_new
games2jolly.com##.game_play > div:nth-of-type(1)
games2jolly.com##.main_left_home
games2jolly.com###home_right
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by jspenguin2017** [comment]
Going to retriage and split this issue.
