### ISSUE TITLE
watchagathachristiespoirot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1912]
### Basic Information

**Test link:** `https://watchagathachristiespoirot.com/episodes/agatha-christies-poirot-4x2/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3922.0 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by mapx-** [comment]
fixed
