### ISSUE TITLE
forum.benchmark.rs

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1916]
### Basic Information

**Test link:** `https://forum.benchmark.rs/index.php`
**Category:** other
**Reported from:** Serbia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Adblocker 1.0.0.125

### Additional Message

I have imported "My Rules" form uBlock Origin but this version of nanoblock wouldn't apply it.
Can you check it out?

**Comment by jspenguin2017** [comment]
Can't reproduce. Rules are applied properly for me.

**Comment by jspenguin2017** [comment]
Fixed ads placeholders.
