### ISSUE TITLE
marca.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1922]
### Basic Information

**Test link:** `https://www.marca.com/futbol/primera-division/directo/2019/09/25/5d8b9831e2704e719c8b45b2.html`
**Category:** breakage
**Reported from:** Switzerland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.126

### Additional Message

It is blocking the result of the match (top of the page) and the players in game (left of the page)

**Comment by okiehsch** [comment]
Fixed.

**Comment by llacb47** [comment]
Easylist problems...
