### ISSUE TITLE
collegestash.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1925]
### Basic Information

**Test link:** `https://www.collegestash.com/dropdown-es6/`
**Category:** anti-adblock
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.167

**Comment by mapx-** [comment]
fixed
