### ISSUE TITLE
buffstream.to

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1926]
### Basic Information

**Test link:** `http://buffstream.to/watch/nfls`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12371.65.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.93 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

fake play button and fake watch live stream buttons above video

**Comment by llacb47** [comment]
```
buffstreamz.com,buffstream.to##+js(acis, $, modal)
buffstreamz.com,buffstream.to##.btn
```

**Comment by okiehsch** [comment]
Fixed.
