### ISSUE TITLE
smartpeople.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1927]
### Basic Information

**Test link:** `https://www.smartpeople.id/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.126

### Additional Message

```
<!-- adblock-->
<script type='text/javascript'>
//<![CDATA[
// Say Hi to Adblock
function downloadJSAtOnload(){var e=document.createElement("script");e.src="https://cdn.jsdelivr.net/gh/adigunawanxd/smartpeople@master/seosecretidnadblock.js",document.body.appendChild(e)}window.addEventListener?window.addEventListener("load",downloadJSAtOnload,!1):window.attachEvent?window.attachEvent("onload",downloadJSAtOnload):window.onload=downloadJSAtOnload;
//]]>
</script>
```

**Comment by llacb47** [comment]
```
@@||smartpeople.id##+js(acis, downloadJSAtOnload)
||cdn.jsdelivr.net/gh/adigunawanxd/smartpeople@master/seosecretidnadblock.js$script,domain=smartpeople.id
```

The anti-adblock script: https://github.com/adigunawanxd/smartpeople/blob/master/seosecretidnadblock.js

**Comment by okiehsch** [comment]
Fixed.

**Comment by realodix** [comment]
@okiehsch

`smartpeople.id##.post:has(.adsbygoogle)` causes the article content to disappear.

![cats](https://user-images.githubusercontent.com/1314456/68419417-c3505780-01cc-11ea-93c4-11ca484a6e74.jpg)

**Comment by llacb47** [comment]
@mapx-

**Comment by jspenguin2017** [comment]
See: https://github.com/NanoMeow/QuickReports/issues/2241
