### ISSUE TITLE
motherjones.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1928]
### Basic Information

**Test link:** `https://www.motherjones.com/politics/2019/09/trumps-intelligence-chief-offers-a-timely-reminder-trump-is-a-liar/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

empty ad box

**Comment by mapx-** [comment]
`motherjones.com##.htl-ad`
@ryanbr

**Comment by llacb47** [comment]
Also add `motherjones.com###ticker`

**Comment by jspenguin2017** [comment]
I can't reproduce ads placeholders with latest filters. 
![image](https://user-images.githubusercontent.com/7283682/65804493-5498cc80-e13f-11e9-8106-9391b2c4a198.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.motherjones.com/coronavirus-updates/2020/03/small-restaurants-are-furious-about-a-loophole-in-the-stimulus-bill-they-should-be/?utm_source=mj-newsletters&utm_medium=email&utm_campaign=food-for-thought-2020-03-29`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Defender for Firefox 15.0.0.196

### Additional Message

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. 
![image](https://user-images.githubusercontent.com/7283682/78039403-511f1180-732b-11ea-954f-20a5b21389e1.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.motherjones.com/politics/2020/07/stephen-millers-grandmother-died-of-covid-19-her-son-blames-the-trump-administration/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

### Additional Message

Nag banner for ad blocker shows up on the bottom of the page

**Comment by llacb47** [comment]
`motherjones.com##.mj-adblock-widget`

Annoyance

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance, old rule no longer works.

**Comment by okiehsch** [comment]
Fixed.
