### ISSUE TITLE
as.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1933]
### Basic Information

**Test link:** `https://as.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.34 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance. 
```
@@||as.com^$generichide
as.com##.publi
```

**Comment by okiehsch** [comment]
Added, thanks.
