### ISSUE TITLE
ligainsider.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1934]
### Basic Information

**Test link:** `https://www.ligainsider.de/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.93 Safari/537.36 Vivaldi/2.8.1664.40
**Extension:** Nano Defender 15.0.0.168

**Comment by okiehsch** [comment]
Fixed.
