### ISSUE TITLE
hofoot.toclipit.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1940]
### Basic Information

**Test link:** `https://hofoot.toclipit.com/player/html/6JKCbToSSP?popup=yes&autoplay=1`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by okiehsch** [comment]
Fixed.
