### ISSUE TITLE
androidweblog.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1941]
### Basic Information

**Test link:** `https://www.androidweblog.com/zte-blade-a7-vita-root-install-twrp-recovery/`
**Category:** other
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.34 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message

ads space
copyblock

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select

@okiehsch FYI.

**Comment by llacb47** [comment]
Also anti-print.

**Comment by okiehsch** [comment]
The placeholders are caused by `uBO-filters`.

**Comment by okiehsch** [comment]
Fied.
