### ISSUE TITLE
bestforandroid.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1943]
### Basic Information

**Test link:** `https://bestforandroid.com/pixel-4-4xl-leaked/`
**Category:** anti-adblock
**Reported from:** Denmark
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.34 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message

ads space

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholders: `bestforandroid.com##.adv-ads-selfstyle`

**Comment by jspenguin2017** [comment]
First use of `:remove()` in Placeholder Buster, so we don't have to deal with the margin.
