### ISSUE TITLE
pureinfotech.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1948]
### Basic Information

**Test link:** `https://pureinfotech.com/kb4517211-windows-10-build-18362-387-1903/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by mapx-** [comment]
annoyance
