### ISSUE TITLE
rutube.ru

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1949]
### Basic Information

**Test link:** `https://rutube.ru/video/16350f7ca73808bda94b9be5948c9279/?pl_type=user&pl_id=639184`
**Category:** breakage
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

Video does not play with adblocker enabled.

**Comment by llacb47** [comment]
EasyPrivacy breakage

`@@||pladform.ru^*/hls-vod/$domain=rutube.ru`

**Comment by jspenguin2017** [comment]
@okiehsch Breakage.

**Comment by okiehsch** [comment]
Fixed.
