### ISSUE TITLE
depedlps.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#195]
### Basic Information

**Test link:** `https://depedlps.blogspot.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.56

### Additional Message

uBO only

**Comment by jspenguin2017** [comment]
@okiehsch Also popup. 
![image](https://user-images.githubusercontent.com/7283682/46895240-c4318100-ce34-11e8-8e80-0af990966e2e.png)

**Comment by mapx-** [comment]
popup ? meaning anti adb popup ?

**Comment by jspenguin2017** [comment]
I'm getting popup ads: 
![image](https://user-images.githubusercontent.com/7283682/46895507-f4c5ea80-ce35-11e8-999f-da4752877818.png)

**Comment by mapx-** [comment]
How can I reproduce that popup ? clicking what ?

**Comment by jspenguin2017** [comment]
I get the popup when I click anywhere on the background.

**Comment by mapx-** [comment]
`depedlps.*##+js(abort-on-property-read.js, encodeURIComponent)` seems working (get the popup only in chrome)
