### ISSUE TITLE
electriciansforums.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1952]
### Basic Information

**Test link:** `https://www.electriciansforums.net/threads/exploding-socket.59676/`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Comes out with Anti-adblock popup.

**Comment by mapx-** [comment]
fixed
