### ISSUE TITLE
icttipsandtricks.nl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1953]
### Basic Information

**Test link:** `https://www.icttipsandtricks.nl/2017/01/18/ubiquiti-captive-portal-maken-voor-wifi-gasten/`
**Category:** anti-adblock
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.36 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by mapx-** [comment]
fixed
