### ISSUE TITLE
realmadryt.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1957]
### Basic Information

**Test link:** `https://www.realmadryt.pl/news/91550-znamy-sklady`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

it doesn't load comments

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.realmadryt.pl/news/91560-najgorszy-start-realu-madryt-w-historii-ligi-mistrzow`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

The fix by mapx- didn't solve the issue.
Scroll down the page to the end. Under "Komentarze" you should see the comments, but it doesn't show anything. Please fix it.

**Comment by mapx-** [comment]
fixed
