### ISSUE TITLE
mpg.football

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1961]
### Basic Information

**Test link:** `https://mpg.football/championships/live`
**Category:** anti-adblock
**Reported from:** Ireland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by llacb47** [comment]
Requires account. Test account:
```
sewifo@quickemail.top
sewifo@quickemail.top
```

Add `mpg.football##+js(set, ads, true)`
