### ISSUE TITLE
pacogames.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1962]
### Basic Information

**Test link:** `https://www.pacogames.com/driving/police-vs-thief-hot-pursuit`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3929.0 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message

Games do not load while Nano adblocker is active

**Comment by llacb47** [comment]
```
gamearter.com##div[id^="ga_sp_"]
gamearter.com##+js(nano-stb,/SplashScreen|BannerAd/)
gamearter.com##+js(nano-sib,/SplashScreen|BannerAd/)
```

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Can't test, game won't load on my end.

**Comment by llacb47** [comment]
Strange, maybe region locked...

Try loading `https://www.gamearter.com/game/police-vs-thief-hot-pursuit/`

**Comment by okiehsch** [comment]
The game downloads are stuck at 20% on my end. I don't think it is geo dependent.
Probably some quirk with my setup.
I would add your filters but you mention that "there may be better solution as the game freezes for a few seconds", so let's wait and see if somebody can come uo with a better fix.

**Comment by llacb47** [comment]
It freezes on a loading screen, so not too bad. But optimally it wouldn't freeze at all

**Comment by okiehsch** [comment]
Ah so the game itself does not freeze? If that is the case that is not too bad indeed.
I will add your filters.
