### ISSUE TITLE
adn.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1964]
### Basic Information

**Test link:** `https://www.adn.com/arts/film-tv/2019/10/01/review-joaquin-phoenix-is-a-vivid-operatic-joker-but-the-movie-is-way-too-full-of-itself/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

Anti-adblock footer banner on page scroll down

**Comment by okiehsch** [comment]
Fixed.
