### ISSUE TITLE
jbzdy.cc

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1965]
### Basic Information

**Test link:** `https://jbzdy.cc/str/2`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Adblocker 1.0.0.127

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://jbzdy.cc/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

**Comment by okiehsch** [comment]
Fixed.
