### ISSUE TITLE
webmail.freenet.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1966]
### Basic Information

**Test link:** `https://webmail.freenet.de/web/?goTo=email#email|/9302477d38a83ec3b9466fe109f561c80de37303/INBOX/140`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

also show ads

**Comment by okiehsch** [comment]
Needs an account.

**Comment by jspenguin2017** [comment]
Requires account.

**Comment by jspenguin2017** [comment]
@okiehsch Isn't it suppose to redirect you to the login page? So breakage?

**Comment by okiehsch** [comment]
I fixed the breakage, only broken for Chromium users.

**Comment by jspenguin2017** [comment]
Requires account.

**Comment by llacb47** [comment]
Test account:
```
testaccount121212@freenet.de
Testaccount123
```
Login here `https://power.freenet.de/`

**Comment by okiehsch** [comment]
@monzta
`||api.mail.freenet.de/*/mail/ads/` or `webmail.freenet.de##[id^="ext-gridrow"]:has-text(Anzeige)`

**Comment by llacb47** [comment]
Also 
```
webmail.freenet.de##div[id*="-adtag-"]:has(iframe[src*="nativendo"])
webmail.freenet.de##.upsellingAdvertising
```

for placeholders and upselling nag

**Comment by okiehsch** [comment]
@jspenguin2017 
This is fixed on my end after updating `EasyList Germany`
