### ISSUE TITLE
megafile.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1967]
### Basic Information

**Test link:** `https://megafile.io/02o5mlm9ry0y?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9tZWdhZmlsZS5pbyIsImF1ZCI6Imh0dHA6XC9cL21lZ2FmaWxlLmlvIiwiaWF0IjoxNTcwMDg1NDQ1LCJuYmYiOjE1NzAwODU0NDUsImV4cCI6MTg4NTQ0NTU0NSwiZnNpemUiOjM3MzY3MjI0NywiZm5hbWUiOiJVbnRpdGxlZC5Hb29zZS5HYW1lLlVubGVhc2hlZC53d3cuRG93bmxvYWQuaXIucmFyIiwiYnVja2V0IjoiZGxpci1nYW1lIiwicGFzc3dvcmQiOiJ3d3cuZG93bmxvYWQuaXIifQ.l1KVd3GEL70-Aj2UsYNsp1LwVCLuYdDXumB8vBb2Izc`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by okiehsch** [comment]
Fixed.
