### ISSUE TITLE
click-paid.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1968]
### Basic Information

**Test link:** `https://click-paid.com/LObEAx1`
**Category:** ads
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

fake download

**Comment by okiehsch** [comment]
Fixed.
