### ISSUE TITLE
acefile.co

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1972]
### Basic Information

**Test link:** `https://acefile.co/f/12739255/yukisubs-vinland-saga-08-720p-eac3-6659f847-mkv`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

popups after click close button
region locked id

**Comment by llacb47** [comment]
404...  new test link `https://acefile.co/f/4041674/shinhannin-ep1-720p-mkv`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
`acefile.co###btmx` hides nothing at your link on my end.

**Comment by okiehsch** [comment]
Fixed.
