### ISSUE TITLE
git.tc

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#198]
### Basic Information

**Test link:** `http://git.tc/Lh79`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.56

**Comment by ZaphodBeebblebrox** [comment]
@Ryanbr `git.tc##.banner-inner`
