### ISSUE TITLE
keisekaikuy.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1983]
### Basic Information

**Test link:** `https://keisekaikuy.blogspot.com/2019/07/book-cheap-flight-to-tokyo-and-visit.html#?o=1d011834b2b4f400fc64597a69a909726765cf3dfb47202ad05146a0d95eb611dde2484097cbfd0e`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

the adblock is detected 
`https://prnt.sc/pf4axs`

**Comment by llacb47** [comment]
```
@@||keisekaikuy.blogspot.com^$generichide
keisekaikuy.blogspot.com##+js(nano-sib)
```

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
The anti adblock is already fixed on my end, are your filters up to date?
