### ISSUE TITLE
thisvid.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1993]
### Basic Information

**Test link:** `https://thisvid.com/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message

When you click to open a video link in a background tab, the original tab redirects to syndication.exosrv.com and it says the request is blocked by EasyList. I have blocked all popups and the redirects still happen.
It is good that Nano intercepts this and shows a warning but how can I block the redirect completely?

**Comment by mapx-** [comment]
nsfw
