### ISSUE TITLE
enasian.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#20]
### Basic Information

**Test link:** `https://enasian.com/drama/while-you-sleebing/episode-13/52284/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
**Extension:** Nano Defender 15.0.0.37

**Comment by jspenguin2017** [comment]
@mapx- Fix incomplete, need to block `.inside-video-before` otherwise play button not clickable.
