### ISSUE TITLE
mikeadkinsguitar.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#200]
### Basic Information

**Test link:** `http://mikeadkinsguitar.com/apc-ns-1250-battery-wiring-diagram.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.42

### Additional Message

cannot signup to free site

**Comment by jspenguin2017** [comment]
Website gone.
