### ISSUE TITLE
patorjack.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2003]
### Basic Information

**Test link:** `https://patorjack.com/sheila-snow-is-back/`
**Category:** anti-adblock
**Reported from:** Philippines
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

**Comment by okiehsch** [comment]
NSFW and I can't reproduce.

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. Has ads placeholders.

**Comment by okiehsch** [comment]
The anti-adblock issue is fixed in `uAssets` for the site with a generichide filter.
Does
`patorjack.com##.spot`
fix all placeholders?

**Comment by jspenguin2017** [comment]
Maybe also these? 
```
patorjack.com##.adsright
patorjack.com##.refill:has(:scope > .spots)
```

**Comment by okiehsch** [comment]
Added.

**Comment by okiehsch** [comment]
That was quick. ;)
