### ISSUE TITLE
akvideo.stream

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2009]
### Basic Information

**Test link:** `https://akvideo.stream/video/tqhdzslvz1pc`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/eb077e7c1c51fdd7d3c15466e7610750940e9f1a
