### ISSUE TITLE
mangahosted.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2019]
### Basic Information

**Test link:** `https://mangahosted.com/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/987dbe14120698112ac24a151e0aada03de461d9
