### ISSUE TITLE
chemistwarehouse.com.au

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2023]
### Basic Information

**Test link:** `https://www.chemistwarehouse.com.au/buy/84081/Seven-Wonders-Violet-Toning-Conditioner-250ml`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

unable to submit reviews with uBO

**Comment by llacb47** [comment]
`@@||analytics-static.ugc.bazaarvoice.com/prod/static/3/bv-analytics.js$script,domain=chemistwarehouse.com.au`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed in `uBO-unbreak`.
