### ISSUE TITLE
officegamespot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2027]
### Basic Information

**Test link:** `http://www.officegamespot.com/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message

First-party ads reinsertion

```
officegamespot.com##+js(acis, Math.round)
! ads placeholders
officegamespot.com##td:has(>div>script:has-text(cpmstar))
officegamespot.com##td:has(>div[id][align="center"])
```

**Comment by llacb47** [comment]
`news.officegamespot.com^`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
