### ISSUE TITLE
eleventhlevelinteractive.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2028]
### Basic Information

**Test link:** `https://www.eleventhlevelinteractive.com/2019/10/is-affiliate-in-demand.html#?o=d5bd1e687547838d25276d55028b65018969aba267b56906b7a58dd2114026b52d590c4a00e5e580258cb017f4307db3ba68af49cd1035cc5f2314bf4588834d53056dfb77363a3d`
**Category:** breakage
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

blocking get link

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/6428#issuecomment-541327347

`IDN, MYS: ABPindo` issue

**Comment by jspenguin2017** [comment]
Hum... It's unclear whether this website is English or Indonesian. The article is English but part of the UI is Indonesian.

**Comment by jspenguin2017** [comment]
Do you know who is maintaining Indonesian regional filters? @gmarcher ?

**Comment by mapx-** [comment]
@ABPindo

**Comment by llacb47** [comment]
I don't have any issue.

**Comment by jspenguin2017** [comment]
@llacb47 It's a breakage caused by a regional filter. I can reproduce.

**Comment by gmarcher** [comment]
https://github.com/ABPindo/indonesianadblockrules/commit/5625a0a8f19877ccafbb46a19739838d2abdb028
