### ISSUE TITLE
livingstondaily.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2032]
### Basic Information

**Test link:** `https://www.livingstondaily.com/story/news/local/community/green-oak-township/2019/10/11/man-trapped-under-garbage-truck-dies-green-oak-township/3946167002/?fbclid=IwAR3F3WdgR_Un8WmR7D_YclVADK3ArtieYabi3xoh63Ch1T-KfKF8bZjibuAhttps://manjaro.org`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.167

**Comment by mapx-** [comment]
fixed
