### ISSUE TITLE
hollaforums.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2035]
### Basic Information

**Test link:** `https://hollaforums.com/thread/14359173/video-games/holla-forums-i-m-feeling-really-goddamn-nostalgic.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by jspenguin2017** [comment]
@okiehsch `https://www.google.com/search?q=%22i-m-feeling-really-goddamn-nostalgic%22&oq=%22i-m-feeling-really-goddamn-nostalgic%22&aqs=chrome..69i57.677j0j7&sourceid=chrome&ie=UTF-8` Click first result.

**Comment by okiehsch** [comment]
Fixed.
