### ISSUE TITLE
dmntsf.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2038]
### Basic Information

**Test link:** `https://dmntsf.net/anime-x265-ongoing/`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/6016d32caa692301ca19f025a02e882e9ba61bd7
