### ISSUE TITLE
linuxtopia.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#204]
### Basic Information

**Test link:** `https://www.linuxtopia.org/online_books/linux_programming_index.html`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.57

**Comment by okiehsch** [comment]
Fixed.
