### ISSUE TITLE
dl.pcgamestorrents.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2040]
### Basic Information

**Test link:** `http://dl.pcgamestorrents.com/download.php?url=NAZs2f3JVOYsEQ8+d1PxKOOrSi+u174YocLRuqBnOAZxSyCbLjBWeTL/632uVP6qaIPHZECAnZuwS6Na7nLtd0iKfyJcbFiyei/kwIPMC2+f0VZl/Np+xzpaFGrfNocbzCN6LQHNgO0YGUm/CT0kc2futqK6cVJ5nIyeuw/nsGIB38Cd9CAG7uztNV7yUIfLQEymYj5GnrJJRahHgfnV7EjcOlZLB6HpddSXuZxI3i3QMwcYoceYC6/PAGbZ9738wAr8C2bi+EyUfwqH7QOTSJDdgbz5MV+FlIwVk2Wucl3CjUnPbLj1jbRGqle/mkj1KM6QEZ9nkBhIeA6D4kI/+8txCxq6NZGHPX3nG2hw2p9zxNkpEW5ZJtVVxLYYrJ+nZZZkaAtaw3aVbDiSXUFfKdOhBWWrWJVJH0iNsa89S4U7l6Yp2AikhFAf+1FIKRa5wRAQZzOzZ7Lh2cNXOxCH0smfdb4hMFu494FPSUcEFTw57x+JxFQ3vF91NS2ct7vbNOBcqE2OAoX5zBprxRY9rO0MvsEJjB0sl/Q3Zxz08PgO0LdF4WRIll53Z/Tbw3/1TyVP5UQjKuXSd0d+pQgbV2VKNg9KJRyyehfHliHkE4sQSOUl7U/Tz/sWqGJQhuSIcCaOcnIk5LM5RvuzGzuHGDwRXCwLxHjwMVtvFkdjbfO8sN1ENdBQm+/eUEFtjWf7TSXcsTruWf/uXH+EO5iEiNZBk/deznXrNME9B2OwBnhH4KszygmUXprJbNi96Zpwmp8Af/uEE1bciiYCwSMF7Cql17LQJR2Shac4jmPrW7UGj/GZy3APfwLUVr5pSJvLn88EN1HXUjrYUXYM94VqStwwMYNWuErexUZUtQ5RJVQ8OmB/KfwS2iNefBmRuUbFdOGuYhBeXb9qzXSAlCjLWw==`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Adblocker 1.0.0.127

**Comment by okiehsch** [comment]
Fixed.
