### ISSUE TITLE
pt.desserttips.me

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2042]
### Basic Information

**Test link:** `http://pt.desserttips.me/DdsQJkDW`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

fake button

**Comment by okiehsch** [comment]
Fixed.
