### ISSUE TITLE
simpsons.fox-fan.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2043]
### Basic Information

**Test link:** `http://simpsons.fox-fan.tv/series.php?id=1817`
**Category:** anti-adblock
**Reported from:** Russia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

**Comment by okiehsch** [comment]
@@dimisa-RUAdList  
`@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.js$script,domain=fox-fan.tv`
works on my end.

**Comment by dimisa-RUAdList** [comment]
@okiehsch 
This has already been fixed in Adblock Warning Removal List: https://hg.adblockplus.org/antiadblockfilters/rev/dcfaa0aa99ea

**Comment by okiehsch** [comment]
That list is not enabled by default for `uBO-users`. 
I will add it to `uBO-filters`.

**Comment by okiehsch** [comment]
That list is not enabled by default for `uBO-users`.

**Comment by okiehsch** [comment]
Fixed.

**Comment by dimisa-RUAdList** [comment]
@okiehsch 
In ABP/AB the Adblock Warning Removal List is also not enabled by default, however it is automatically activated when it hits the target site. Since there is no automatic activation in uBO, it makes sense to make the Adblock Warning Removal List enabled by default.

**Comment by okiehsch** [comment]
@gorhill what do you think?

**Comment by okiehsch** [comment]
Also I have to saay that I am surprised that AdblockPlus allows filters in that list that remove adblock walls. The site disables the videoplayer if one has an adblocker enabled, so it is more than a mere Adblock warning. It violates their own policy.
https://adblockplus.org/filter-lists-requirements
"Must block only ads
....  it must not work around anti-ad block warnings and messages or technological measures that effectively control access to websites"

**Comment by gorhill** [comment]
> automatically activated when it hits the target site

How does ABP know what is a _target_ site?

**Comment by dimisa-RUAdList** [comment]
@gorhill 
This happens when the awrl has rules for these sites.

**Comment by gorhill** [comment]
There are  generic filters in there, so I don't see how that works. Anyways for now I prefer to not activate by default, I don't have an idea whether it would interfere negatively with uBO's own anti-blocker filters.

**Comment by mapx-** [comment]
However, the anti adb of warning type are already managed by our uBo annoyances list

**Comment by dimisa-RUAdList** [comment]
@gorhill 
I mean not specific domain-bound rules, but any triggered rules, including generic.

**Comment by gorhill** [comment]
> any triggered rules, including generic.

But then... it means the filters are all already loaded in memory and evaluated just like any other filter, and enforced if they are a match... consequently the list is enabled bu default?

**Comment by dimisa-RUAdList** [comment]
Apparently, yes.

**Comment by jspenguin2017** [comment]
It does interfere a little bit, but so far I only saw a couple cases: https://github.com/NanoAdblocker/NanoFilters/blob/2f63d5d36fbda311fd6d1cceddcbdf2e2e50d8c3/NanoFiltersSource/NanoBase.txt#L708
