### ISSUE TITLE
cutadlink.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2044]
### Basic Information

**Test link:** `https://cutadlink.com/fYFp2ksp`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

fake button, overlay ads, popup etc

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/77a46d10f2753c0327d556826eeb63d0decdb9d6
