### ISSUE TITLE
oglobo.globo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2052]
### Basic Information

**Test link:** `https://oglobo.globo.com/economia/previdencia-reforma-cobre-menos-de-20-do-rombo-das-aposentadorias-diz-tcu-24020026`
**Category:** ads
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

add on site

**Comment by mapx-** [comment]
I get only some kind of paywall ?!
`||experience.tinypass.com/xbuilder/experience/load?aid=$script`

**Comment by llacb47** [comment]
I thought tinypass was already blocked by uAssets... or maybe not, because paywalls cannot be added

**Comment by jspenguin2017** [comment]
`t: other`: Fake wall.

**Comment by jspenguin2017** [comment]
Looks like we already have a rule for `tinypass.com`, so I'm adding this for now.
