### ISSUE TITLE
dias-uteis.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2054]
### Basic Information

**Test link:** `https://www.dias-uteis.com/Configura%C3%A7%C3%A3o%20personalizada.htm#a11`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

the site identified that I was using an adblocker

**Comment by okiehsch** [comment]
Fixed.
