### ISSUE TITLE
mtlblog.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2056]
### Basic Information

**Test link:** `https://www.mtlblog.com/news/montreals-first-ever-anglophone-metro-map`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

`https://s.put.re/FbYtfkee.png`

**Comment by okiehsch** [comment]
Fixed.
