### ISSUE TITLE
nfmovies.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2057]
### Basic Information

**Test link:** `https://www.nfmovies.com/`
**Category:** anti-adblock
**Reported from:** Hong Kong
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.nfmovies.com/`
**Category:** anti-adblock
**Reported from:** China
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4166.0 Safari/537.36 Edg/85.0.545.0
**Extension:** Nano Defender Pro 15.0.0.200

### Additional Message

Need close nano ext

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.nfmovies.com/video/?52233-3-26.html`
**Category:** anti-adblock
**Reported from:** Hong Kong
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.200

### Additional Message

Original URL: `chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html`

it need close Anti-adblock.

**Comment by jspenguin2017** [comment]
Some breakage when Chinese regional filters are enabled (some CSS and comment issues). Also has ads timer. However, can't test due to GeoLock, TunnelBear doesn't work.

**Comment by jspenguin2017** [comment]
@okiehsch Some breakage when Chinese regional filters are enabled (some CSS and comment issues). Also has ads timer. Hola works for GeoLock. 

---

Can't reproduce anti-adblock.

**Comment by okiehsch** [comment]
I don't see any obvious CSS issues, for the comments.
````
nfmovies.com#@#+js(aopr, $myui)
@@||nfmovies.com/static/side.jpg$xhr,1p
````
does that fix the issue on your end?

**Comment by jspenguin2017** [comment]
@okiehsch Yes, that fixes both breakage (CSS and comment).

**Comment by okiehsch** [comment]
Fixed.
