### ISSUE TITLE
gfycat.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2061]
### Basic Information

**Test link:** `https://gfycat.com/icyfakecirriped-snow`
**Category:** other
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message

has massive banners asking to create account

**Comment by okiehsch** [comment]
Fixed.
