### ISSUE TITLE
easytools.pro

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2066]
### Basic Information

**Test link:** `https://easytools.pro/safe-domain-checker/oTdVuag`
**Category:** anti-adblock
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

**Comment by mapx-** [comment]
fixed
