### ISSUE TITLE
watchcalifornicationonline.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2067]
### Basic Information

**Test link:** `https://watchcalifornicationonline.com/`
**Category:** anti-adblock
**Reported from:** Malta
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Original URL: `chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html`

can you send me an email status update if its fixed - `<redacted>` or tell me where to go check for status update

**Comment by jspenguin2017** [comment]
See also: https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/44

**Comment by mapx-** [comment]
fixed
