### ISSUE TITLE
lavozdegalicia.es

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2081]
### Basic Information

**Test link:** `https://www.lavozdegalicia.es/noticia/espana/2019/10/19/gobierno-responde-torra-habra-dialogo-margen-ley-exige-nuevo-condene-violencia/00031571490952709271513.htm`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Original URL: `chrome://newtab/`

**Comment by jspenguin2017** [comment]
@mapx- @okiehsch Why is this not hard anti-adblock?

**Comment by okiehsch** [comment]
Fixed in annoyances by mistake I guess. Clearly a hard anti adblock, atleast on my end.

**Comment by mapx-** [comment]
indeed, an error
https://github.com/uBlockOrigin/uAssets/commit/901cf2ad295b6a307dea9cf1aed465c51f2751ed
