### ISSUE TITLE
tlc.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#209]
### Basic Information

**Test link:** `https://www.tlc.com/tv-shows/unexpected/full-episodes/a-family-affair`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:62.0) Gecko/20100101 Firefox/62.0
**Extension:** Nano Defender 15.0.0.57

### Additional Message

it says timeout whenevever i try to click to play.

**Comment by jspenguin2017** [comment]
Requires account.

**Comment by jspenguin2017** [comment]
I'll assume this is resolved until further reports.

**Comment by ZaphodBeebblebrox** [comment]
You might want to mark this issue as geo-lock, I think it works with any U.S. ip
