### ISSUE TITLE
filmix.co

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2091]
### Basic Information

**Test link:** `https://filmix.co/trillery/87695-vozdushnyy-marshal-non-stop-2014.html`
**Category:** anti-adblock
**Reported from:** Ukraine
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.167

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/cf33824059e420c2288307b8139c59333685248a
