### ISSUE TITLE
cmovies.video

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2093]
### Basic Information

**Test link:** `https://www2.cmovies.video/`
**Category:** ads
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

Original URL: `https://www2.cmovies.video/movie/filter/cinema-movies/all/all/all/all/latest/`

**Comment by okiehsch** [comment]
Fixed.
