### ISSUE TITLE
multiup.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2096]
### Basic Information

**Test link:** `https://multiup.org/fr/mirror/bc5d73f6e96806b02ed040ed7c45b888/ACDOCDCRE1902120047..rar`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36 OPR/64.0.3417.61
**Extension:** Nano Defender 15.0.0.168

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://multiup.org/download/0ccdea02344f9e3b9c68207ac53c2c59/ALIGR2020-MW.part1.rar`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36 OPR/64.0.3417.61
**Extension:** Nano Defender 15.0.0.168

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://multiup.org/en/mirror/0e2b8dd1ac5011a04ca7769a4b27be03/ExtraMovies.wiki_FLM19S02E01.mkv`
**Category:** other
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

Original URL: `https://addons.mozilla.org/en-US/firefox/addon/nano-defender-firefox/`

on this site ,file mirrors download doesn't work.when i click download under file server,it doesn't go to target link but instead ads site multinews.me........i found working link via dev tools instead https://i.imgur.com/QwwYDch.gifv...

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://multiup.org/en/mirror/0e2b8dd1ac5011a04ca7769a4b27be03/ExtraMovies.wiki_FLM19S02E01.mkv`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.85 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

**Comment by jspenguin2017** [comment]
@okiehsch Most download buttons don't work. 

---

Has ads placeholders.

**Comment by ghajini** [comment]
Actual issue is you won't get downloads from mirrors when you clicked on them (1fichier,filerio,turbobit,openload etc)......

**Comment by okiehsch** [comment]
> okiehsch dude

````
||multinews.me^$all,badfilter
||multinews.me^$third-party
````
works for this dude

**Comment by ghajini** [comment]
With your solution I get only ads site multinews.me and not a target link, pls test solution before you publish[its a humble request as site is unusable for ubo users)

Proof=
 https://i.imgur.com/HMplozv.gifv

Lastly if you want to know how a real solution is, try adguard 

https://i.imgur.com/L3HJjcT.gifv

**Comment by okiehsch** [comment]
> pls test solution before you publish

I obviously tested before I commited.
Going to 
````
https://multiup.org/en/mirror/0e2b8dd1ac5011a04ca7769a4b27be03/ExtraMovies.wiki_FLM19S02E01.mkv
`````
and clicking the `1fichier` links I get immediately redirected through `multinews.me` to my target location as you can see looking at the timestamps.
![image](https://user-images.githubusercontent.com/16838044/67922377-e36b8f80-fbaa-11e9-8515-980469565e4a.png)

> Lastly if you want to know how a real solution is, try adguard

What's with the attidude are you personally offended if some fix does not work for you?

**Comment by ghajini** [comment]
No attitude bro, 
May I ask have you cleared cookies/data before you go to site and click download on file mirrors because iam stucked at ads site only

**Comment by okiehsch** [comment]
I use incognito mode for testing, so no cookie/data, I only tested the first mirror `1fichier`.
I can test the other ones too. Give me a sec.

**Comment by okiehsch** [comment]
OK, so after testing all of them, except the `usenet` one.
`1fichier.com`, `Filesupload.org`, `Openload.co` and `Turbobit.net` work fine on my end.

I can reproduce your result with `Uptobox.com` and `Filerio.in`.
I end up at 
`https://multinews.me/produit/lentilles-white-out-zombie-halloween-sans-correction`
I agree that adguard's fix works better but I don't see a way to fix this issue without a specialized scriptlet.

I still think that my commit is correct, because the old filter ``||multinews.me^$all` broke the download functionality completely.

**Comment by ghajini** [comment]
Usenet is fake one,forget that. .....
Issue is on all file servers on 1st visit

**Comment by jspenguin2017** [comment]
It still has a redirect on first visit, the real URL is exposed in DOM, so it should be possible to bypass the redirect.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://multiup.org/ddee0948bf683fa1c967ce28923926f2`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

always bring to ads site not to filehosting destination if ublock origin enabled
