### ISSUE TITLE
enrt.eu

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2097]
### Basic Information

**Test link:** `https://enrt.eu/7uUljIH`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

fake button

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e0bee0647e833ed4a1d1db34e8312ebb81b19974
