### ISSUE TITLE
mirchigames.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#21]
### Basic Information

**Test link:** `http://www.mirchigames.com/mirchi-escape-game/find-my-gift`
**Category:** breakage
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
**Extension:** Nano Defender 15.0.0.37

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://www.mirchigames.com/mirchi-escape-game/forest-grandma-escape`
**Category:** breakage
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Adblocker 1.0.0.119

### Additional Message

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://www.mirchigames.com/mirchi-escape-game/dark-castle-escape-3`
**Category:** breakage
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Adblocker 1.0.0.120

### Additional Message

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by llacb47** [comment]
The `Play Game` button doesn't work. (Scroll down and wait for game to load in)
Test link 1: `http://www.mirchigames.com/mirchi-escape-game/dark-castle-escape-3` (The most recent report)
Test link 2: `http://www.mirchigames.com/mirchi-escape-game/find-my-gift` (The first report)

The other reports don't seem to have this issue.

**Comment by jspenguin2017** [comment]
Ah, that's true. Marking as `lesser` as this website uses Flash.

**Comment by llacb47** [comment]
Test:
`wgplayer.com$domain=mirchigames.com`

**Comment by mapx-** [comment]
fixed as suggested
