### ISSUE TITLE
hulkstreams.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2100]
### Basic Information

**Test link:** `http://www.hulkstreams.com/livestreamhd/football/champions-league/galatasaray-vs-real-madrid/20191022/11/`
**Category:** ads
**Reported from:** Colombia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

**Comment by mapx-** [comment]
They are using lots of different servers

Here a part ..
```
alantvsport.com,buffstream.tv,hulkstreams.com,hulkstreamx.com,jackstream.com,olivertv.com,totalsportek.xyz##+js(acis, Math, zfgloaded)
alantvsport.com,buffstream.tv,hulkstreams.com,hulkstreamx.com,jackstream.com,olivertv.com,totalsportek.xyz##+js(aopr, _pop)
alantvsport.com,buffstream.tv,hulkstreams.com,hulkstreamx.com,jackstream.com,olivertv.com,totalsportek.xyz##+js(aopr, open)
alantvsport.com,buffstream.tv,hulkstreams.com,hulkstreamx.com,jackstream.com,olivertv.com,totalsportek.xyz##+js(aopr, decodeURIComponent)
alantvsport.com,buffstream.tv,hulkstreams.com,hulkstreamx.com,jackstream.com,olivertv.com,totalsportek.xyz##+js(aopr, Date.prototype.toUTCString)
```

Maybe we need a new approach if possible:
Filters which can be applied for all the frames for a certain page (start page like `hulkstreams.com` in our case)
