### ISSUE TITLE
mangalist.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2104]
### Basic Information

**Test link:** `https://mangalist.org/url/go/REpFUVZqamZmSTYrb25mUU55VnNUd3g4RURmdXA3M1lkYUtXR3pkSWc3SGMwYnY5aEdySSs1Z2NjTmg2bHFabjlhUTlHT0RpWHgxdnVVRlR3ZEtNb2pHWGJ0NmdhM2xtWVFJMld3clU1OGc9`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

blocking continue link

**Comment by realodix** [comment]
@jspenguin2017 @mapx-

### Enabled uBlock filters
![cats](https://user-images.githubusercontent.com/1314456/67939517-52290700-fc04-11e9-8e78-2865f11e14f0.jpg)

### Disabled uBlock filters
![cats1](https://user-images.githubusercontent.com/1314456/67939546-6240e680-fc04-11e9-9c37-45f22cb7afd5.jpg)

### Possible rule that cause problems
`mangalist.org##+js(acis, $, height)`

**Comment by mapx-** [comment]
fixed
