### ISSUE TITLE
lgbtqnation.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2116]
### Basic Information

**Test link:** `https://www.lgbtqnation.com/2019/10/imitation-alan-turing-vs-real-alan-turing-victim-vs-hero/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Detects adblock

**Comment by mapx-** [comment]
annoyance ("Continue without disabling ..")
