### ISSUE TITLE
winrar.findmysoft.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2122]
### Basic Information

**Test link:** `http://winrar.findmysoft.com/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/77.0.3865.90 Chrome/77.0.3865.90 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

sponsored malware

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
That entire page looks fishy with a capital F; and I for one would simply have blocked it entirely with `||findmysoft.com^$doc`.

But if not:
```
findmysoft.com###as_right
findmysoft.com###col_h1_:has(+ #as_right)
findmysoft.com###col_h3
```

**Comment by jspenguin2017** [comment]
Yea, it's kind of fishy.
