### ISSUE TITLE
tr.beinsports.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2123]
### Basic Information

**Test link:** `http://tr.beinsports.com/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/64.0.3417.73
**Extension:** Nano Defender 15.0.0.168

### Additional Message

"You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page."

**Comment by mapx-** [comment]
annoyance, enable uBo annoyances list
