### ISSUE TITLE
shrink.world

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2125]
### Basic Information

**Test link:** `https://www.shrink.world/xk215W`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

popup + fake button

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/5fd368c4bc4d0b7c3ce1412777ebf08814b6ed1b
