### ISSUE TITLE
safelinkblog.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2128]
### Basic Information

**Test link:** `http://safelinkblog.com/imtM`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Original URL: `https://www.movienear.me/post/Film-Perang-Terbaik-Sepanjang-Masa`

fake button

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://safelinkblog.com/WBOsoI`
**Category:** ads
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Fake Button

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.safelinkblog.com/PKms5t5`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

Fake button

**Comment by jspenguin2017** [comment]
@okiehsch Fake button on default setup.

**Comment by okiehsch** [comment]
Fixed.
