### ISSUE TITLE
open.spotify.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2130]
### Basic Information

**Test link:** `https://open.spotify.com/playlist/37i9dQZEVXcIH4dXS3jiDh`
**Category:** other
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.50 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

Spotify playback crashes when advertisements are scheduled. Requests blocked counter is "15,419 or 89%". I use the 'Discovery Queue' playback function and just let that run for a long time until an advert is forced.

**Comment by mapx-** [comment]
The current filter still working for me
`||akamaized.net/audio/*$media,redirect=noopmp3-0.1s,domain=open.spotify.com`

if there are other audio ad sources it could be tested:
`*$media,redirect=noopmp3-0.1s,domain=open.spotify.com`

**Comment by jspenguin2017** [comment]
Requires account.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://open.spotify.com/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

Hiya, first of all thank you for your hard work on the ad blocker. It is very useful! : ) now on spotify open website the notification comes up saying something went wrong and blocks the service.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://open.spotify.com/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12871.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.95 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

Can't load Spotify web player

**Comment by llacb47** [comment]
@mapx- I badfiltered those filters and spotify still loads fine. Are they needed?

**Comment by mapx-** [comment]
chrome => needed on my end
FF => ok without them

**Comment by llacb47** [comment]
Works fine for me in chrome.
