### ISSUE TITLE
dramaserial.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2144]
### Basic Information

**Test link:** `https://dramaserial.xyz/`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

annoying overlay

**Comment by llacb47** [comment]
for uBo: `dramaserial.xyz##+js(acis, $, popup)`

for all blockers: `||nt1.co/js/jquery.floating_popup.$script`

ping
@gmarcher
@realodix
