### ISSUE TITLE
teknosafe.kertashitam.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2149]
### Basic Information

**Test link:** `https://teknosafe.kertashitam.com/linkteknolink/safelinkscript.php?lnD7tE92Yw4QuXh74=39516`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by okiehsch** [comment]
I can reproduce using Chrome. The probem is that Chrome blocks the bait script with it's own adblocker.
The script is already allowed in `uBO-filters`. This can't be fixed you have to disable Chrome's adblocker for the site.
