### ISSUE TITLE
gota.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#215]
### Basic Information

**Test link:** `https://gota.io/web/`
**Category:** other
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.58

### Additional Message

Adblock detected

**Comment by mapx-** [comment]
fixed as annoyance, list to be enabled
