### ISSUE TITLE
movienear.me

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2150]
### Basic Information

**Test link:** `https://www.movienear.me/post/Film-Fiksi-Terbaik-yang-Harus-Kamu-Tonton`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Original link : `https://safelinkblog.com/PKms5t5`

Fake button + popups

**Comment by okiehsch** [comment]
Fixed.
