### ISSUE TITLE
nakedcapitalism.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2154]
### Basic Information

**Test link:** `https://www.nakedcapitalism.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

Anti-adblock script being proxied as first-party

`https://www.nakedcapitalism.com/proxy.php?remoteURL=https%3A%2F%2Fabd.investingchannel.com%2Fjs%2Fbundle.js` must be blocked

**Comment by okiehsch** [comment]
Fixed in annoyances.
