### ISSUE TITLE
rockpapershotgun.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#216]
### Basic Information

**Test link:** `https://www.rockpapershotgun.com/2018/01/02/biggest-steam-games-2017/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+rockpapershotgun%2Fsteam+%28Rock%2C+Paper%2C+Shotgun%3A+Steam+RSS%29`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
**Extension:** Nano Defender 15.0.0.58

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/47181359-0862cc80-d2e0-11e8-81ae-9ec4c8bd0b04.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.rockpapershotgun.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.81

### Additional Message

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock, but there's a few empty ads placeholders.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.rockpapershotgun.com/2018/10/17/assassins-creed-odyssey-editions-what-each-edition-contains-2/`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.81

### Additional Message
