### ISSUE TITLE
julieseatsandtreats.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2171]
### Basic Information

**Test link:** `https://www.julieseatsandtreats.com/crockpot-buffalo-chicken-dip/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

looks like g00 crap but domain is `eiecaw.com` - not sure if this is IL stuff or not but the logger in firefox is going CRAZY

**Comment by okiehsch** [comment]
Fixed.
