### ISSUE TITLE
mamadu.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2173]
### Basic Information

**Test link:** `https://mamadu.pl/144439,zobacz-co-sie-stanie-gdy-codziennie-zjesz-jeden-jogurt-dziennie`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

adquesto antiadblock

**Comment by krystian3w** [comment]
No longer help @mapx- test this:

https://github.com/MajkiIT/polish-ads-filter/issues/15228#issuecomment-561316416

**Comment by mapx-** [comment]
Does this work ?
`mamadu.pl##+js(nostif, , 1)`

**Comment by krystian3w** [comment]
Yes, kill adquesto and recover article.
