### ISSUE TITLE
itavisen.no

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2175]
### Basic Information

**Test link:** `https://itavisen.no/`
**Category:** anti-adblock
**Reported from:** Norway
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Nano Adblocker is detected. I am using regional filter NOR, DNK, ISL: Dandelion Sprouts nordiske filtre

**Comment by jspenguin2017** [comment]
@DandelionSprout FYI.
