### ISSUE TITLE
usasports.tk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2177]
### Basic Information

**Test link:** `http://www.usasports.tk/2019/10/mlb.html`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

popups

**Comment by okiehsch** [comment]
````
liveonsat.xyz##+js(aopr, Date.prototype.toUTCString)
liveonsat.xyz##+js(aopw, _pop)
liveonsat.xyz##+js(nowebrtc.js)
||loppjod.online^$3p
````
fixes the popups. The player won't play on my end no matter what, so I would need some feedback if those filters are working without issue,

**Comment by mapx-** [comment]
Could be it's about some DRM content (as FF warns me) ?

**Comment by okiehsch** [comment]
If I go directly to the source at `http://www.liveonsat.xyz/mlb1.html` I get quite a few errors regarding the video.
![image](https://user-images.githubusercontent.com/16838044/67932006-5ed93b00-fbc3-11e9-8107-5953ac32a753.png)

**Comment by okiehsch** [comment]
In that case I will add the filters. Should work fine and the OP can cry foul if it doesn't.
