### ISSUE TITLE
cloudncode.blog

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#218]
### Basic Information

**Test link:** `https://cloudncode.blog/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/69.0.3497.81 Chrome/69.0.3497.81 Safari/537.36
**Extension:** Nano Defender 15.0.0.58

### Additional Message

left-over placeholder

**Comment by jspenguin2017** [comment]
`cloudncode.blog##.wpcnt` @ryanbr FYI
