### ISSUE TITLE
animex.club

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2190]
### Basic Information

**Test link:** `https://www.animex.club/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Original URL: `https://www.animex.club/izle/quanzhi-fashi-2nd-season-ihk/9`

**Comment by mapx-** [comment]
fixed => needing turkish ip to test
