### ISSUE TITLE
realhousemoms.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2191]
### Basic Information

**Test link:** `https://realhousemoms.com/buffalo-chicken-dip-crock-pot/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.167

### Additional Message

REAL HOUSEMOMS TV in middle of page is blocked

**Comment by mapx-** [comment]
@ryanbr
