### ISSUE TITLE
minecraft.gamepedia.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2196]
### Basic Information

**Test link:** `https://minecraft.gamepedia.com/Item`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.16 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

undermine adds at the bottom

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Can you point me to the ads, I don't see anything obvious on my end.

**Comment by okiehsch** [comment]
OK, the reason I could not see anything is because this is fixed by filters in `uBO-annoyances` I will move them to `uBO-filters`.
