### ISSUE TITLE
tvtime.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2199]
### Basic Information

**Test link:** `https://www.tvtime.com/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

The login button does not work because of the EasyPrivacy list only with this filter I was able to login `@@||tvtime.com/ga-assets/*`
If you need an account to test you can find one here: `http://bugmenot.com/view/tvtime.com`

**Comment by okiehsch** [comment]
Fixed.
@ryanbr fyi
