### ISSUE TITLE
igds.red

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2206]
### Basic Information

**Test link:** `https://igds.red/episodi/mr-mercedes-1x1/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by okiehsch** [comment]
Fixed.
