### ISSUE TITLE
androgalaxy.in

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2207]
### Basic Information

**Test link:** `https://www.androgalaxy.in/`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 9; ZenFone Max Pro M1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
**Extension:** Nano Defender 15.0.0.168

**Comment by okiehsch** [comment]
Fixed.
