### ISSUE TITLE
aol.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2224]
### Basic Information

**Test link:** `https://www.aol.com/games/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message

Unblocked sponsored content

`The Latest from our Partners`

**Comment by jspenguin2017** [comment]
@okiehsch Seems to work but not sure if it breaks anything: 
```
aol.com###floatingvid-anchor
aol.com##.maas-item
```

**Comment by okiehsch** [comment]
Can't use those they block content, go to `aol.com` to reproduce.

**Comment by okiehsch** [comment]
`aol.com##.Bdtc\(white-gray-medium\)` maybe but that needs to be tested thoroughly before adding it for a high traffic site.

**Comment by llacb47** [comment]
Also at bottom of AOL homepage, seems to be a new addition.

```
aol.com##.module-more-to-explore
! aol.com##.m-cpc works fine but I added the fromourpartners part to be safe
aol.com##div.m-cpc[data-ylk*="fromourpartners"]
```

@okiehsch

**Comment by llacb47** [comment]
can we get this filter added? @mapx-

**Comment by mapx-** [comment]
@ryanbr
