### ISSUE TITLE
fluentu.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2226]
### Basic Information

**Test link:** `https://www.fluentu.com/blog/spanish/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message

Ads reinsertion

`||volstqkwmth.com^`

Also reported at https://github.com/easylist/easylist/issues/4248

**Comment by okiehsch** [comment]
Fixed.
