### ISSUE TITLE
jbzd.cc

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2230]
### Basic Information

**Test link:** `https://jbzd.cc/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
**Extension:** Nano Defender 15.0.0.169

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://jbzd.cc/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.169

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://jbzd.cc/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
**Extension:** Nano Defender 15.0.0.169

### Additional Message

**Comment by krystian3w** [comment]
@olegwukr copy:

```
 @@||jbzd.*^$generichide
 @@||jbzdy.*^$generichide 
```
