### ISSUE TITLE
investmentwatchblog.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2233]
### Basic Information

**Test link:** `https://www.investmentwatchblog.com/realclearinvestigations-spy-vs-spy-euphemism-at-the-fbi/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.169

### Additional Message

Ads getting through & anti-adblock message on firefox

**Comment by okiehsch** [comment]
Fixed.
