### ISSUE TITLE
megadescargas.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2237]
### Basic Information

**Test link:** `https://www.megadescargas.net/`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/64.0.3417.92
**Extension:** Nano Defender 15.0.0.169

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.megadescargas.net/`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/64.0.3417.92
**Extension:** Nano Defender 15.0.0.169

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.megadescargas.net/`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/64.0.3417.92
**Extension:** Nano Defender 15.0.0.170

### Additional Message

**Comment by lain566** [comment]
Fixed. The Op did not correctly provide an example link.
Same issue https://github.com/NanoMeow/QuickReports/issues/1560
