### ISSUE TITLE
tht.fangraphs.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2238]
### Basic Information

**Test link:** `https://tht.fangraphs.com/seven-innings-seven-innings/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.169

### Additional Message

Empty advertisement placeholders (multiple) in middle of article

**Comment by mapx-** [comment]
other relevant test page
`https://blogs.fangraphs.com/chris-davis-and-the-brutal-life-of-a-late-career-slugger/`
