### ISSUE TITLE
foxnews.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2240]
### Basic Information

**Test link:** `https://www.foxnews.com/food-drink/popeyes-chicken-sandwich-woman-scraping-car`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.169

### Additional Message

anti-adblock message with random class names on firefox (sometimes needs multiple page reload to reproduce - likely A/B testing in prod)

screenshot of console: `https://i.imgur.com/IX7WuJs.png`

**Comment by jspenguin2017** [comment]
@mapx- Doesn't seem to work. `/google-funding-choices.js$script,domain=foxnews.com` works for me though.
