### ISSUE TITLE
smartpeople.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2241]
### Basic Information

**Test link:** `https://www.smartpeople.id/2019/10/kartu-pembayaran-e-money-indonesia.html`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.29 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by mapx-** [comment]
right click, select https://github.com/uBlockOrigin/uAssets/commit/03fea2bd9e92d2779645ea0486d078a9b7dcf70a

**Comment by jspenguin2017** [comment]
@okiehsch @mapx- How about changing to `smartpeople.id##div.post:has(:scope > .adsbygoogle)`? Removing the rule would leave ads placeholders on the home page.

**Comment by okiehsch** [comment]
That hides the "TERPOPULER HARI INI/most popular" section.

**Comment by okiehsch** [comment]
Does `smartpeople.id##.date-outer> .date-posts > .post` work for you?

**Comment by jspenguin2017** [comment]
Yep, that works.

**Comment by okiehsch** [comment]
Fixed.
