### ISSUE TITLE
ac-mo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2242]
### Basic Information

**Test link:** `http://ac-mo.com/BISikm`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.169

**Comment by okiehsch** [comment]
Fixed.

**Comment by dumbusernameidk** [comment]
anti-right click

`ac-mo.com##+js(acis, document.oncontextmenu)`

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click.
