### ISSUE TITLE
spankwire.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2243]
### Basic Information

**Test link:** `https://www.spankwire.com/Active-hottie-enjoys-anal-sex/video9691582/`
**Category:** anti-adblock
**Reported from:** Denmark
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

```
www.spankwire.com/dist/lib-detect/dist/index.js
www.spankwire.com/dist/lib-detect/src/index.ts
```

```
export function isABEnabled() {
    const abt = document.createElement('div');
    abt.innerHTML = '&nbsp;';
    abt.className = 'adsbox';
    document.body.appendChild(abt);

    return abt.offsetHeight === 0;
}
```

**Comment by okiehsch** [comment]
Can't reproduce anti adb, fixed broken video playback.

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock neither. Splitting off another issue for ads placeholders.
