### ISSUE TITLE
spankwire.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2246]
### Basic Information

**Test link:** `https://www.spankwire.com/Active-hottie-enjoys-anal-sex/video9691582/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.29 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

nsfw ads placeholders

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholder on the example page: `spankwire.com##.adsbox`

Placeholder on `https://www.spankwire.com/search/Straight/keyword/latex+suit`: `spankwire.com###js-react-search-list iframe[src^="https://ads.trafficjunky."]:upward(3)`
