### ISSUE TITLE
sportnews.to

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2250]
### Basic Information

**Test link:** `http://www.sportnews.to/schedule/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.16 Safari/537.36 Edg/79.0.309.15
**Extension:** Nano Defender 15.0.0.169

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/bcf2fc843e6ec766968995ca3a8f4a31f2b481d8
