### ISSUE TITLE
hofoot.vidcrt.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2254]
### Basic Information

**Test link:** `https://hofoot.vidcrt.net/player/html/ePiLBuCtKJ?popup=yes&autoplay=1`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
**Extension:** Nano Defender 15.0.0.169

### Additional Message

adblock detector still active

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/68535173-4c65ac80-02fb-11ea-9256-a477defa6962.png)
