### ISSUE TITLE
video.vice.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2255]
### Basic Information

**Test link:** `https://video.vice.com/pl/video/bangladeshi-gang-rape/55b7a39ad793cd2d56b40d53`
**Category:** breakage
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.29 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

Blocks cookie screen, breaking video player
See also: https://github.com/PolishFiltersTeam/PolishCookieConsent/issues/33
Fix: `@@||sourcepoint.vice.com^$script,1p`

**Comment by jspenguin2017** [comment]
@okiehsch
