### ISSUE TITLE
laptopmag.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2257]
### Basic Information

**Test link:** `https://www.laptopmag.com/articles/apple-macbook-pro-16-inch-latest-news`
**Category:** anti-adblock
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.29 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

ANTI ADBLOCK

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance.
