### ISSUE TITLE
oms.vidupstream.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2258]
### Basic Information

**Test link:** `https://oms.vidupstream.com/player/html/jvviGOiBBh?popup=yes&autoplay=1`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.169

### Additional Message

Video player (most likely related to cdn.radiantmediatechs.com) refuses to play the video by showing the banner "Ad-blocker software detected. To view this content please disable your ad-blocker.".

**Comment by okiehsch** [comment]
Fixed.
