### ISSUE TITLE
linuxandubuntu.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2259]
### Basic Information

**Test link:** `http://www.linuxandubuntu.com/`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.29 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.128

### Additional Message

blocks icon font

**Comment by jspenguin2017** [comment]
@okiehsch Icon font blocked by a generic rule.

**Comment by okiehsch** [comment]
Fixed.
