### ISSUE TITLE
betanews.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#226]
### Basic Information

**Test link:** `https://betanews.com/2018/10/20/chrome-picture-in-picture/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.64

**Comment by okiehsch** [comment]
Fixed.
