### ISSUE TITLE
debridup.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2261]
### Basic Information

**Test link:** `https://debridup.com/`
**Category:** anti-adblock
**Reported from:** Slovakia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.169

**Comment by ghajini** [comment]
Antiadblock
As long as you try to download something eg `https://1fichier.com/?ptltjgmjpwb2w3hze9wu` and click debrider
Antiadblock shows up
