### ISSUE TITLE
legacy.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2266]
### Basic Information

**Test link:** `https://www.legacy.com/obituaries/newsobserver/browse`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by jspenguin2017** [comment]
@okiehsch Large ads placeholders on the page.

**Comment by DandelionSprout** [comment]
Placeholders:
```
legacy.com##.AffiliateHeader
legacy.com##.FixedStickyAside
legacy.com##.FixedStickyOverlay
legacy.com##.FixedNoOverlay
```
