### ISSUE TITLE
prostream.to

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2269]
### Basic Information

**Test link:** `https://prostream.to/diuhnm0gbg3y.html`
**Category:** ads
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.169

### Additional Message

Original URL: `about:newtab`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0550a82f6b94b78eff9ce4fd32e51986fc858d4b
