### ISSUE TITLE
bitsfree.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2271]
### Basic Information

**Test link:** `https://bitsfree.net/shortlinks.html`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.29 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

ads space

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholder: `bitsfree.net##.mx-auto`
