### ISSUE TITLE
givemereddit.stream

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2272]
### Basic Information

**Test link:** `http://givemereddit.stream/nfl/seattle-seahawks-live-stream`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12499.51.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.92 Safari/537.36
**Extension:** Nano Defender 15.0.0.169

### Additional Message

popup click  play

**Comment by okiehsch** [comment]
Fixed.
