### ISSUE TITLE
yts.lt

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2273]
### Basic Information

**Test link:** `https://yts.lt/movie/children-of-men-2006`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.29 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

vpn ads in the middle

**Comment by jspenguin2017** [comment]
@okiehsch
