### ISSUE TITLE
uploadbank.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2293]
### Basic Information

**Test link:** `http://www.uploadbank.com/iad9sfkrnrib`
**Category:** anti-adblock
**Reported from:** Romania
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.169

### Additional Message

Sometimes it works, sometimes not.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://www.uploadbank.com/myjcjd71lpf0`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Defender 15.0.0.177

### Additional Message

...

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/9b5c12e7decb73c9d512ab8c6777e021b5b68c66
