### ISSUE TITLE
dreamlandresort.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2296]
### Basic Information

**Test link:** `https://www.dreamlandresort.com/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

Anti-right click

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click.
