### ISSUE TITLE
geekglow.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#230]
### Basic Information

**Test link:** `https://www.geekglow.com/`
**Category:** anti-adblock
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
**Extension:** Nano Defender 15.0.0.64

**Comment by jspenguin2017** [comment]
Soft anti-adblock.

**Comment by okiehsch** [comment]
I can't reproduce, looking at the document `generichide` or `(abort-on-property-read.js, anOptions)` will probably work.

**Comment by jspenguin2017** [comment]
That's weird, I can reliably reproduce, also tested regional filters. I'll investigate later.

**Comment by okiehsch** [comment]
The source shows that the site uses "Adblock Notify", but I don't get that message on my end.
The only adblock message I see is 
![image](https://user-images.githubusercontent.com/16838044/47324205-32f5b200-d65f-11e8-8699-02e453cf7d17.png)
at the right side of the page of I scroll down a bit.
All users with and without an adblocker see that pcture.
