### ISSUE TITLE
cartoonbrew.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2319]
### Basic Information

**Test link:** `https://www.cartoonbrew.com/disney/first-act-disney-legend-whoopi-goldberg-tells-disney-stop-hiding-history-152327.html`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

Ad placeholders

`##.cb-ad`

**Comment by DandelionSprout** [comment]
Can confirm the original reporter's claim about `cartoonbrew.com##.cb-ad`. I could not find any other entries of note there.
