### ISSUE TITLE
pcgamer.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#232]
### Basic Information

**Test link:** `https://www.pcgamer.com/cc.html`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
**Extension:** Nano Defender 15.0.0.64

**Comment by jspenguin2017** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/47382545-c78ffc80-d6bf-11e8-9c8d-4bfc5aaf34ff.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.pcgamer.com/best-controller-for-pc-gaming/`
**Category:** breakage
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

Have to disable cosmetic filtering, or images won't show up

**Comment by mapx-** [comment]
first using of `$specifichide` (alias `$shide`) feature

**Comment by gwarser** [comment]
> first using of `$specifichide` (alias `$shide`) feature

And people didn't like this - https://www.reddit.com/r/uBlockOrigin/comments/epgfcw/element_picker_will_not_work_on_pcgamercom/

**Comment by mapx-** [comment]
replaced
