### ISSUE TITLE
eurogamer.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2323]
### Basic Information

**Test link:** `https://www.eurogamer.net/articles/2019-11-19-football-manager-2020-free-agents-bargains-best-cheap-players-transfers-fm20-6112`
**Category:** anti-adblock
**Reported from:** Estonia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.eurogamer.net/search.php?q=a`
**Category:** breakage
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

Original URL: `https://www.eurogamer.net/search.php?q=tamogotchi`

If you search on Eurogamer, the search results won't appear until you disable the adblocker.

**Comment by mapx-** [comment]
fanboy's annoyances list

add
`@@||cdn.cookielaw.org/scripttemplates/$xhr,domain=eurogamer.net`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/842f1ddec4ab249ea0bbd411eadbc601f2012b6a
