### ISSUE TITLE
game-kentang.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2330]
### Basic Information

**Test link:** `https://game-kentang.blogspot.com/2019/10/download-dp-wallpaper-mobile-legends.html#?o=dc277775fe0ba709eafbfa5cffa346f76d1460cf53a0d50fb732c5fc07c47ef2dc1ff3311a157d66`
**Category:** other
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

countdown timer

**Comment by jspenguin2017** [comment]
`t: other`: Timer.
