### ISSUE TITLE
camwhoreshd.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#234]
### Basic Information

**Test link:** `http://www.camwhoreshd.com/videos/269836/manyvids-rae-black-sloppy-blowjob-premium-video-hd-d3d819f168838486/`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.64

**Comment by mapx-** [comment]
no anti adb here, only ads + popups

**Comment by mapx-** [comment]
Does it work for you ?
```
camwhoreshd.com,cwtvembeds.com##+js(window.open-defuser.js)
||camwhoreshd.com^$csp=child-src 'self' *.cwtvembeds.com
camwhoreshd.com,cwtvembeds.com##.hola_top_element
||camwhoreshd.com^$csp=script-src 'self' *
```

**Comment by jspenguin2017** [comment]
Yea, that works.
