### ISSUE TITLE
ouo.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2343]
### Basic Information

**Test link:** `https://ouo.io/BZF1Cv`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.45 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

**Comment by jspenguin2017** [comment]
@okiehsch Has fake button sometimes. 
![image](https://user-images.githubusercontent.com/7283682/69464632-0b7a8880-0d3c-11ea-87c3-9caa9027fc3f.png)

**Comment by okiehsch** [comment]
Fixed.
