### ISSUE TITLE
planetaminecraft.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2355]
### Basic Information

**Test link:** `http://planetaminecraft.com/v/file/136774720266299`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.170

### Additional Message

This site was able to detect anti-Adblock

**Comment by okiehsch** [comment]
Fixed.
