### ISSUE TITLE
strikeout.nu

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2356]
### Basic Information

**Test link:** `https://www.strikeout.nu/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
**Extension:** Nano Defender 15.0.0.170

**Comment by okiehsch** [comment]
Fixed.
