### ISSUE TITLE
moto.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2371]
### Basic Information

**Test link:** `https://www.moto.it/`
**Category:** breakage
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Adblocker 1.0.0.131

### Additional Message

Original URL: `https://github.com/LiCybora/NanoCoreFirefox/releases/`

Greetings, in this site Nano blocks too much, the photos are not displayed, thanks.

**Comment by mapx-** [comment]
Easylist Italy issue
@Khrin
