### ISSUE TITLE
birdurls.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2375]
### Basic Information

**Test link:** `https://birdurls.com/CBtnnhsnl5j`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

popups + fake button + ads

**Comment by mapx-** [comment]
for popups

```
birdurls.com##+js(nowebrtc)
birdurls.com##+js(aopr, decodeURI)
||adscorp.win^$3p
||moonicorn.network^$3p
||url-coin.com^$3p
||9eb10b7a3d04a.com^
```

but ... I see no valid continuation => captcha still redirecting to crap

**Comment by jspenguin2017** [comment]
Yea, not sure what is the expected behavior.

**Comment by ghajini** [comment]
`birdurls.com/xYRmr`
Popup ads and fake buttons
