### ISSUE TITLE
nflbite.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2386]
### Basic Information

**Test link:** `https://nflbite.com/detroit-lions-vs-chicago-bears-live-stream/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12607.34.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.42 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

popup ad overlay

**Comment by okiehsch** [comment]
Fixed.
