### ISSUE TITLE
mail.yahoo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#240]
### Basic Information

**Test link:** `https://mail.yahoo.com/neo/launch?.src=ym&reason=myc#9401`
**Category:** ads
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
**Extension:** Nano Defender 15.0.0.64

### Additional Message

video ads not blocked

**Comment by jspenguin2017** [comment]
Requires account.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mail.yahoo.com/d/folders/1?.src=fp`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
**Extension:** Nano Adblocker 0.0.128.0

### Additional Message

blocking whitelist

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mail.yahoo.com/d/folders/1/messages/ABnvS14COA58XTfc1AbtcGN0TMI?guce_referrer=aHR0cHM6Ly9sb2dpbnByb2R4LmF0dC5uZXQvRklNL3Nwcy9BVFRpZHAvc2FtbDIwL2xvZ2luaW5pdGlhbD9SZXF1ZXN0QmluZGluZz1IVFRQUG9zdCZQYXJ0bmVySWQ9aHR0cHMlM0ElMkYlMkZsb2dpbi55YWhvby5jb20lMkZzYW1sJTJGMi4wJTJGYXR0Ji5sYW5nPWVuLVVTJlRhcmdldD1odHRwcyUzQSUyRiUyRm1haWwueWFob28uY29tJTJGZA&guce_referrer_sig=AQAAAEyf6bu98zSaq7dHOHrFF4t3TfzmjdkFhoLxMt2aOMZnTBc0eZpP-dl2rVXMzXTMjzY1Ov-cQMwhjV4GsQUEQ38lAq3QMgf_9Gq2dLFe6sEbziovNb9JzjSQImPfk1kIP-19hGMwULnTbYyWoMW6TqDxzyR3GCt-l3EzrlgIv0F5`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
**Extension:** Nano Adblocker 0.0.128.0

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mail.yahoo.com/`
**Category:** anti-adblock
**Reported from:** Philippines
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
**Extension:** Nano Defender 15.0.0.196

### Additional Message

Original URL: `https://mail.yahoo.com/d/folders/1`

The Yahoo Mail detects nano adblocker

**Comment by llacb47** [comment]
Can't reproduce.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mail.yahoo.com/d/folders/1`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12871.57.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.81 Safari/537.36
**Extension:** Nano Defender 15.0.0.196

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mail.yahoo.com/d/folders/1`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12871.57.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.81 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mail.yahoo.com/b/folders/1?adblock=1&action=closeOnboarding`
**Category:** anti-adblock
**Reported from:** Tanzania
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mail.yahoo.com/d/folders/1/messages/AGEK6PBfL7PhXqzcpQpE6NaCDEc`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

It gets detected

**Comment by llacb47** [comment]
Still can't reproduce.

**Comment by mapx-** [comment]
someone which can reproduce could test:
`mail.yahoo.com##+js(nostif, dispatchAdBlockDetected)`

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mail.yahoo.com/d/folders/1/messages/21810`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

This hasn't been an issue until about a week ago. On and off again, since around April 28th or so, I am getting "You're using an ad blocker" pop-ups when viewing my Yahoo Mail, which prevents me from doing anything other than agree to whitelist of going to Yahoo Basic Mail. It pops up sporadically and not all the time, but it will happen. As mentioned, this was never an issue the span of time since I began using Nano Adblocker and Nano Defender. It is super recent, and Nano Defender isn't blocking this particular new anti-ad blocker message.

Thank you for your time.
