### ISSUE TITLE
thesimsresource.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2408]
### Basic Information

**Test link:** `https://www.thesimsresource.com/downloads/browse/category/sims2/skipsetitems/1/page/2/cnt/226683/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender 15.0.0.170

### Additional Message

It's not working. It's still telling me to turn off adblock for the site.

**Comment by DandelionSprout** [comment]
Can't seem to reproduce anti-adblock. Placeholders:
```
thesimsresource.com##.sticky_bottom
thesimsresource.com##.crtv-bottom-wrapper
```
