### ISSUE TITLE
flickr.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2410]
### Basic Information

**Test link:** `https://www.flickr.com/photos/viejito/48766959076/in/photostream/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

Ads placeholders in photostream, click right a few photos to get one

**Comment by DandelionSprout** [comment]
I fear that a `##+js` entry could be the only way to fix this one properly, from what I can determine.

**Comment by llacb47** [comment]
Oh yeah, I reported this one lol

**Comment by llacb47** [comment]
Test: `flickr.com##+js(set, appContext.adManager.context.current.adFriendly, false)`

**Comment by llacb47** [comment]
One placeholder on photo page: `flickr.com####.sub-photo-submoola-view` (moola is Flickr codename for ad spots I'm pretty sure)

![image](https://user-images.githubusercontent.com/16567977/79409321-a4b86e80-7f6b-11ea-954b-9dc3e4a95051.png)
