### ISSUE TITLE
link.yoruzora.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2411]
### Basic Information

**Test link:** `https://link.yoruzora.com/2019/11/mengatasi-wifi-laptop-yang-tidak-bisa-konek.html#?o=43d35249e88fbd4faed749a2fb3af58ef14511a5aa0cb7c0cbb0e4e00e550cc6ba19e25b5cd8fcaa`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

**Comment by okiehsch** [comment]
Fixed.
