### ISSUE TITLE
sportsnaut.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2414]
### Basic Information

**Test link:** `https://sportsnaut.com/2019/12/nba-national-television-ratings-down-north-of-20-percent-this-season/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.170

### Additional Message

anti adblock popup message

**Comment by okiehsch** [comment]
Fixed.
