### ISSUE TITLE
merriam-webster.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2416]
### Basic Information

**Test link:** `https://www.merriam-webster.com/thesaurus/obligation`
**Category:** anti-adblock
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

**Comment by okiehsch** [comment]
Fixed.
