### ISSUE TITLE
citethisforme.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#242]
### Basic Information

**Test link:** `http://www.citethisforme.com/`
**Category:** anti-adblock
**Reported from:** Kazakhstan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.64

### Additional Message

Asks to disable adblock or buy premium after some time

**Comment by okiehsch** [comment]
Fixed. https://github.com/uBlockOrigin/uAssets/commit/127b7c6a3b516bfaee5f61a74b9e0b28e959e61a
