### ISSUE TITLE
comingsoon.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2424]
### Basic Information

**Test link:** `https://www.comingsoon.net/tv/news/1112920-the-mandalorian-episode-7-sneak-peek-the-rise-of-skywalker?fbclid=IwAR21_fAajLR35MP0s9Hn1UjYUoErhUgj82LhTXDljlFcI45QCviiv5aU3-Q`
**Category:** anti-adblock
**Reported from:** Estonia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

**Comment by okiehsch** [comment]
It uses admiral and is already fixed in `uBO-annoyances`.

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. Ads placeholder fixed.
