### ISSUE TITLE
anime-loads.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2426]
### Basic Information

**Test link:** `https://www.anime-loads.org/media/cardcaptor-sakura-clear-card-hen`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.170

### Additional Message

affects the site in general. click'n'load for all files is available when registered, but still detects nano adblocker
click'n'load for all episodes is hence disabled.

adblocker v1.0.0.131
defender 15.0.0.170

subscribing to the aak list didn't help too

**Comment by okiehsch** [comment]
Fixed.
