### ISSUE TITLE
glory-link.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2431]
### Basic Information

**Test link:** `http://glory-link.com/pq71Tv`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

**Comment by okiehsch** [comment]
Fixed yesterday. https://github.com/uBlockOrigin/uAssets/issues/6653

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/5f326a2b86ec5dc2276c817275fbfd1b08327ede
