### ISSUE TITLE
baixarsoftware.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2435]
### Basic Information

**Test link:** `https://www.baixarsoftware.com/aida64/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.170

**Comment by okiehsch** [comment]
Fixed.
