### ISSUE TITLE
linkdrop.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2439]
### Basic Information

**Test link:** `http://linkdrop.net/GiPPM`
**Category:** ads
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 9; motorola one power) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
**Extension:** Nano Defender 15.0.0.170

**Comment by okiehsch** [comment]
Fixed.
