### ISSUE TITLE
javlover.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2440]
### Basic Information

**Test link:** `http://javlover.net/doggy-em-hoc-sinh-thpt-phu-ngoc-mong-to/`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 YaBrowser/19.12.0.358 Yowser/2.5 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

**Comment by okiehsch** [comment]
Fixed.
