### ISSUE TITLE
howtogeek.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2446]
### Basic Information

**Test link:** `https://www.howtogeek.com/447107/can-my-iphone-or-ipad-get-a-virus/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

Ad placeholder

**Comment by DandelionSprout** [comment]
Currently no placeholders that I can see.

**Comment by jspenguin2017** [comment]
I see one near the end.

**Comment by jspenguin2017** [comment]
Fixed by https://github.com/NanoAdblockerLab/NanoContrib/pull/26#issuecomment-495962653
