### ISSUE TITLE
downdetector.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2461]
### Basic Information

**Test link:** `https://downdetector.co.uk/status/cloudflare/#indicator-modal`
**Category:** breakage
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
**Extension:** Nano Adblocker 1.0.0.131

**Comment by jspenguin2017** [comment]
https://github.com/NanoAdblocker/NanoFilters/commit/6977c31c814fd7610efb1a174601ee6d232164bd
