### ISSUE TITLE
go.oracle.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2466]
### Basic Information

**Test link:** `https://go.oracle.com/evnunsubpage`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Adblocker 1.0.0.131

### Additional Message

this works
```
@@||en25.com^$script,domain=go.oracle.com
||t.eloqua.com^$badfilter
||t.eloqua.com^$3p
```

**Comment by jspenguin2017** [comment]
@okiehsch Breakage.
