### ISSUE TITLE
winaero.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#247]
### Basic Information

**Test link:** `https://winaero.com/blog/enable-random-mac-address-in-windows-10-for-wi-fi-adapter/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.42

### Additional Message

text link "RECOMMENDED: Click here to fix Windows errors and optimize system performance"

**Comment by jspenguin2017** [comment]
@okiehsch Would you consider to be non-intrusive self-promotion? 
![image](https://user-images.githubusercontent.com/7283682/47595840-886fde80-d93f-11e8-8d67-02abe7496192.png)

**Comment by okiehsch** [comment]
I would, but I will fix
![image](https://user-images.githubusercontent.com/16838044/47596029-cee72c80-d983-11e8-8a7a-56c3273d66ef.png)
which appears at the top of every article.

**Comment by jspenguin2017** [comment]
I'll leave this to you and @ryanbr

**Comment by okiehsch** [comment]
Fixed in annoyance, so if you want to add it to your list.

**Comment by jspenguin2017** [comment]
So it's an ad reinsertion... I'll think about it.

**Comment by DandelionSprout** [comment]
I have a list whose one of two purposes is to deal with highly dubious sponsored PC program links: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/TechnologicalDiversity.txt

If it fits any of you guys' lists (Presumably uAssets and Nano Filters), you are more than welcome to borrow whichever entries you want from it.

**Comment by DandelionSprout** [comment]
Oh, and for the record: The link in https://github.com/NanoMeow/QuickReports/issues/247#issuecomment-433563807 is ***NOT*** self-promotion! That link leads to (Crapware alarm) `https://www.tweakbit.com/land/pc-repair/support?exit=1&startdownload=6&build=aff&clkid=614x6127x20190306140924119ecc5&utm_source=winaero.com&utm_medium=pc-repair-kit&utm_campaign=Winaero`.

**Comment by okiehsch** [comment]
> The link in #247 (comment) is NOT self-promotion! 

It is hidden by the `EasyList` filter 
`winaero.com##.recommended-inline`

**Comment by DandelionSprout** [comment]
Huh. That must be a fairly new addition to EasyList, as the link was still visible with non-custom entries about two months ago.

Now that the mother of all lists have an entry for this, I suppose it's just as well time to close this issue report now.
