### ISSUE TITLE
couponcabin.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2472]
### Basic Information

**Test link:** `https://www.couponcabin.com/distil_r_drop.html?requestId=29714301-3291-4372-96cf-4c7608be9222&httpReferrer=%2Fcoupons%2Ftarget%2F`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.couponcabin.com/coupons/costco/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Defender for Firefox 15.0.0.185

### Additional Message

with uBO enabled, get blocked from viewing deals and redirected to block page `https://www.couponcabin.com/distil_r_drop.html?`

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.couponcabin.com/distil_r_drop.html?requestId=043e6456-a6f5-41e2-9a0e-b4e5b1e99b9f&httpReferrer=%2Fcoupons%2Flulu%2F`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.40
**Extension:** Nano Defender 15.0.0.201

### Additional Message

**Comment by llacb47** [comment]
Anti-adblock: `https://www.couponcabin.com/coupons/staples/`

Distil networks fingerprinting is blocked in Easyprivacy, page won't load without it. Needing whitelist: `@@||couponcabin.com/ga.096759.js`

**Comment by jspenguin2017** [comment]
@okiehsch Breakage. Test link: `https://www.couponcabin.com/coupons/costco/`

**Comment by okiehsch** [comment]
With uBO-disabled I get
![image](https://user-images.githubusercontent.com/16838044/88001002-546b2280-caff-11ea-8de1-594af7a2b662.png)

**Comment by jspenguin2017** [comment]
This works for me: 
```
@@||couponcabin.com^$ghide
@@||couponcabin.com/ga.*.js
```
![image](https://user-images.githubusercontent.com/7283682/88001210-cc642900-cabc-11ea-9e65-6db8015a33a6.png)

**Comment by okiehsch** [comment]
So it is only ant-adblock and no breakage on your end or both?

**Comment by okiehsch** [comment]
Meaning
`@@||couponcabin.com^$ghide`
in `uBO-filters`.
and 
`@@||couponcabin.com/ga.*.js$1p`
in `uBO-unbreak` or both in `uBO-filters`?

**Comment by jspenguin2017** [comment]
`@@||couponcabin.com/ga.*.js$1p` in unbreak, `@@||couponcabin.com^$ghide` in base filter. 
The anti-adblock is hard (comes back on every refresh). 
![image](https://user-images.githubusercontent.com/7283682/88001596-bf940500-cabd-11ea-9b46-d1c442fc9408.png)

**Comment by okiehsch** [comment]
Added, thx.
