### ISSUE TITLE
files.cx

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2474]
### Basic Information

**Test link:** `https://files.cx/id/krqjh7`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

**Comment by llacb47** [comment]
Still get anti-adblock, add `||padsreds.com^$script,domain=files.cx,redirect=noop.txt`


![image](https://user-images.githubusercontent.com/16567977/70763265-84f50d80-1d21-11ea-9198-bc71e80f0466.png)

**Comment by jspenguin2017** [comment]
I can't reproduce.

**Comment by jspenguin2017** [comment]
Can't reproduce. I don't see that overlay coming up.
