### ISSUE TITLE
short.awsubs.co

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2475]
### Basic Information

**Test link:** `http://short.awsubs.co/MdopK`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

blocking continue button

**Comment by gmarcher** [comment]
resolved
https://github.com/ABPindo/indonesianadblockrules/commit/d73322794da57240f719c4b27816e32c5e83bed4
