### ISSUE TITLE
kusonime.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2476]
### Basic Information

**Test link:** `https://kusonime.com/`
**Category:** other
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

anti copy paste and right click

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select, anti-hotkey.
