### ISSUE TITLE
slate.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2482]
### Basic Information

**Test link:** `https://slate.com/news-and-politics/2019/12/second-amendment-gun-sanctuary-movement-constitution.html`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.170

### Additional Message

huge empty ad sections in middle of article

**Comment by llacb47** [comment]
@ryanbr

`slate.com##.ad`

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
AdGuard Base seem to have been two steps ahead of us again, especially with `slate.com##.ad--inArticleBanner`.
