### ISSUE TITLE
mmorpg.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2485]
### Basic Information

**Test link:** `https://www.mmorpg.com/`
**Category:** ads
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Adblocker 1.0.0.131

**Comment by llacb47** [comment]
`mmorpg.com##[onclick^="trackClick"]`

**Comment by jspenguin2017** [comment]
@okiehsch Ads.

**Comment by okiehsch** [comment]
Fixed.
