### ISSUE TITLE
samehadaku.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2486]
### Basic Information

**Test link:** `https://www.samehadaku.tv/`
**Category:** other
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

anti copy paste

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-hotkey, anti-select.
