### ISSUE TITLE
costco.com.mx

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2489]
### Basic Information

**Test link:** `https://www.costco.com.mx/`
**Category:** breakage
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

Original URL: `https://www.costco.com.mx/Salud-y-Belleza/Belleza/Cuidado-para-la-Piel/Crema-Corporal-para-Piel-Seca-Eucerin-1-l/p/544612`

**Comment by okiehsch** [comment]
Fixed.
