### ISSUE TITLE
insidermonkey.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2490]
### Basic Information

**Test link:** `https://www.insidermonkey.com/blog/hedge-fund-and-insider-trading-news-jacob-gottlieb-neil-woodford-praesidium-investment-management-edwards-lifesciences-corp-ew-pacific-premier-bancorp-inc-ppbi-and-more-805524/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.170

### Additional Message

unblocked advertising loading through network `applicationunity.com`

**Comment by okiehsch** [comment]
Fixed.
