### ISSUE TITLE
tr.savefrom.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2492]
### Basic Information

**Test link:** `https://tr.savefrom.net/`
**Category:** ads
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 OPR/65.0.3467.72
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

When you try download a video, popup screen appear + ad in main screen.

**Comment by mapx-** [comment]
maybe `||rek.savefrom.net^`

**Comment by okiehsch** [comment]
I stil get a popup if I try to download a link.
Example link: `youtube.com/watch?v=kKJNGDerams`
Does
````
tr.savefrom.net##+js(window.open-defuser)
||rek.savefrom.net^
tr.savefrom.net##.second-btn-box
````
work for you?
