### ISSUE TITLE
legalinsurrection.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2493]
### Basic Information

**Test link:** `https://legalinsurrection.com/2019/12/if-you-were-as-deceptive-with-the-fbi-as-the-fbi-was-with-the-fisa-court-how-quickly-would-you-be-charged/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.170

### Additional Message

empty ad blocks

fixed with the following 2 filters

`legalinsurrection.com##[id^="div-gpt-ad"]`
`legalinsurrection.com##.sidebarBlock [id^="div-gpt-ad"]:nth-ancestor(2)`

**Comment by okiehsch** [comment]
Fixed.
