### ISSUE TITLE
gamestar.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2494]
### Basic Information

**Test link:** `https://www.gamestar.de/videos/path-of-exile-2-vs-diablo-4-der-grosse-hacknslay-showdown,100026.html`
**Category:** breakage
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

movie player does not load/start.

**Comment by mapx-** [comment]
@ryanbr
