### ISSUE TITLE
stream.golfchannel.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2498]
### Basic Information

**Test link:** `http://stream.golfchannel.com/golf`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.3996.0 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

**Comment by llacb47** [comment]
A flash player in 2019...

```
@@*/crossdomain.xml$object,domain=player.theplatform.com
@@||fwmrm.net/p/nbcu_as3_tve_live/AdManager.swf$object,domain=player.theplatform.com
```
