### ISSUE TITLE
aternos.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#25]
### Basic Information

**Test link:** `https://aternos.org/server/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
**Extension:** Nano Defender 15.0.0.37

### Additional Message

Full page blocker appears. Unable to remove it.

**Comment by jspenguin2017** [comment]
Requires account.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://aternos.org/server/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.39

### Additional Message

It's a free Minecraft server host. you'll need to make an account to experience the issue.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://aternos.org`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 11151.113.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.127 Safari/537.36
**Extension:** Nano Defender 15.0.0.89

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://aternos.org/start/`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.109

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://aternos.org/`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.109

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://aternos.org/server/`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.137

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://aternos.org/server/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.137

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://aternos.org`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Defender 15.0.0.140

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

In html > body there is a div that has a random ID assigned to it that causes the adblock screen to appear. Also in the body element contains a script tag that contains the adblocker code. In the head tag, there is a script tag which has a random variable name that is assigned to the Date.now() function. That variable is used in the adblocker code.

Under head tag:
<script>
(this variable name is always randomize every page refresh)
var LgrKilYBbkQUURNeomxYJPoenhqkZmATXrHrXBGCD = Date.now();
</script>

Under body tag:
<script>
(a lot of these variables has random names, also very evil comment on top of the script)
// disabling this script tag will make the page unusable ;)
(function(){var timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;var ZUinkPzjDwbthBaPdTbJpSfOCqpuqausIzuvy = true;$(window).on('load',function(){if($(window).width() < 300) {return;}var nfsKzYydnpXJVNprpfldxEYgblrkmpzuHtb = Date.now() - LgrKilYBbkQUURNeomxYJPoenhqkZmATXrHrXBGCD;if($('#adUnit').css("display") !== "none" && $('.ad').css("display") !== "none" && typeof pbjsChunk === "function" && typeof __cmp === "function") {ZUinkPzjDwbthBaPdTbJpSfOCqpuqausIzuvy = false;}yJQTomWDCpsUxiIQNwuyIDMRUcb();});function yJQTomWDCpsUxiIQNwuyIDMRUcb() {if(ZUinkPzjDwbthBaPdTbJpSfOCqpuqausIzuvy) {$('.body, .header').hide();$('.ad-replacement').css({ display: 'flex' });$('#zbvVVXMNiagSRuJgejYuRhhOOubkQLRJKxFME').show();setInterval(function(){$('.body, .header').hide();$('#zbvVVXMNiagSRuJgejYuRhhOOubkQLRJKxFME').show();}, 600000);}}$('.bUFHJMTDfAzKgYpOnJcPzCVqBFDWVylVjZHbMcc').click(function(){var btn = $(this);if(btn.hasClass("btn-working")) {return false;}btn.addClass("btn-working");var MlhzPDnAKBkFoMKQxEhILuuVwGNkfrkXcuDQtBnd = 3;$('.yGoiYgiTfSmMHCmGVoybsOXFtcGgxyVrbdmLaY').html(MlhzPDnAKBkFoMKQxEhILuuVwGNkfrkXcuDQtBnd);var SaWyVeXsgdzZjyBJQRLDjDZMYhcnYD = setInterval(function(){MlhzPDnAKBkFoMKQxEhILuuVwGNkfrkXcuDQtBnd--;$('.yGoiYgiTfSmMHCmGVoybsOXFtcGgxyVrbdmLaY').html(MlhzPDnAKBkFoMKQxEhILuuVwGNkfrkXcuDQtBnd);if(MlhzPDnAKBkFoMKQxEhILuuVwGNkfrkXcuDQtBnd === 0) {clearInterval(SaWyVeXsgdzZjyBJQRLDjDZMYhcnYD);btn.removeClass("btn-working");$('.body, .header').show();$('#zbvVVXMNiagSRuJgejYuRhhOOubkQLRJKxFME').hide();$('.yGoiYgiTfSmMHCmGVoybsOXFtcGgxyVrbdmLaY').html("");}}, 1000);});})();var _0x1025=['opacity','hide'];(function(_0x3dee64,_0x57142c){var _0x11367f=function(_0x3c68b9){while(--_0x3c68b9){_0x3dee64['push'](_0x3dee64['shift']());}};_0x11367f(++_0x57142c);}(_0x1025,0x69));var _0x5cb5=function(_0x6f5b5a,_0x2dfb53){_0x6f5b5a=_0x6f5b5a-0x0;var _0x4f71d6=_0x1025[_0x6f5b5a];return _0x4f71d6;};$('#zbvVVXMNiagSRuJgejYuRhhOOubkQLRJKxFME')[_0x5cb5('0x0')]()['css'](_0x5cb5('0x1'),0x1);
</script>

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://aternos.org/server/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Defender 15.0.0.147

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://aternos.org/server/`
**Category:** anti-adblock
**Reported from:** Hungary
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.153

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://aternos.org/en/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.154

### Additional Message

Original URL: `about:newtab`

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://aternos.org/backups/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

**Comment by llacb47** [comment]
Requires account - here are some test credentials:
Username: `dijixatepe`
Password: `dijixatepe@freetmail.net`

Test these filters:
```
aternos.org##+js(abort-current-inline-script.js,Intl)
aternos.org##div[id]:has(div[style]:has(.fa-frown))
aternos.org##aside:has(.ad)
aternos.org##div.ad
aternos.org##.server-bottom-tutorials
```

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
`aternos.org##+js(abort-current-inline-script.js, Intl)`
that breaks the site on my end, I can't scroll anymore.

**Comment by okiehsch** [comment]
Fixed.

**Comment by llacb47** [comment]
Are you sure `aternos.org##+js(abort-current-inline-script.js, Intl)` doesn't work for you? You have to add the cosmetic filter `aternos.org##div[id]:has(div[style]:has(.fa-frown))` to block the hidden adblocker overlay as well. I think it's a better solution because the adtech scripts don't need to be whitelisted.

**Comment by llacb47** [comment]
Some users on reddit have said that the commited fix doesn't work... Maybe the page layout changes on different parts of the site, breaking the filter?

**Comment by jspenguin2017** [comment]
Yea, it broke again. I opened a new issue for it. Note that in this repo, issues that are closed can't be reopened, as the bot software can't handle that yet.
