### ISSUE TITLE
thechive.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2502]
### Basic Information

**Test link:** `https://thechive.com/2019/12/13/weve-all-got-that-one-friend-who-just-cant-do-something-normal-video/?utm_referrer=https%3A%2F%2Fzen.yandex.com`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 YaBrowser/19.12.0.358 Yowser/2.5 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

**Comment by llacb47** [comment]
@mapx-

Don't see any anti-adblock, there is some breakage.

`https://thechive.com/2019/12/15/father-and-daughter-have-a-cute-talk-with-santas-reindeer-video/`
Video broken, fix:
```
@@||acdn.adnxs.com/video/mediation/apn_overlay_integration.js$script,domain=thechive.com
@@||acdn.adnxs.com/video/mediation/VastMediationManager.js$script,domain=thechive.com
@@||acdn.adnxs.com/video/player/vastPlayer/VastPlayer.js$script,domain=thechive.com
```

`https://thechive.com/2019/12/15/someone-is-proving-just-why-toucan-birds-are-absolutely-insane/`
"What's hot" sidebar broken, fix: `@@||petametrics.com^$script,domain=thechive.com`
