### ISSUE TITLE
index.hr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2508]
### Basic Information

**Test link:** `https://www.index.hr/`
**Category:** anti-adblock
**Reported from:** Croatia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 OPR/65.0.3467.72
**Extension:** Nano Defender 15.0.0.170

### Additional Message

You are seeing this message because ad or script blocking software is interfering with this page

**Comment by llacb47** [comment]
@mapx- `generichide` is not needed, maybe change to `index.hr##+js(acis, atob, googlefc)`

**Comment by okiehsch** [comment]
`generichide` is the preferable fix.
See https://github.com/uBlockOrigin/uAssets/commit/f340633dc681d6e0fb696359e06f5498dd5e0c39#commitcomment-20429063

**Comment by jspenguin2017** [comment]
That leaves large ads placeholders in articles. Add `index.hr##.ad-container`

**Comment by okiehsch** [comment]
Fixed.
