### ISSUE TITLE
infotekno.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2509]
### Basic Information

**Test link:** `https://infotekno.net/vga?url=aHR0cHM6Ly9nby5pbmZvdGVrbm8ubmV0L0pySVhjeWkvd2luZG93cy0xMC1saXRlLWVkaXRpb24tMTloMi14NjQtaXNv`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.170

### Additional Message

anti adblock after get link

**Comment by okiehsch** [comment]
Fixed.
