### ISSUE TITLE
plejada.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2514]
### Basic Information

**Test link:** `https://plejada.pl/newsy/rodzina-krolewska-w-zylach-elzbiety-ii-nie-plynie-blekitna-krew-jest-wnuczka/30m9php`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

**Comment by krystian3w** [comment]
IMO year ago:

https://github.com/olegwukr/polish-privacy-filters/blob/6ad49f584adecc7f701a2ab79d3db31b72e885ee/anti-adblock.txt#L137-L139
https://github.com/olegwukr/polish-privacy-filters/blob/6ad49f584adecc7f701a2ab79d3db31b72e885ee/anti-adblock.txt#L280-L281
https://github.com/olegwukr/polish-privacy-filters/blob/6ad49f584adecc7f701a2ab79d3db31b72e885ee/anti-adblock.txt#L320-L321
https://github.com/olegwukr/polish-privacy-filters/blob/6ad49f584adecc7f701a2ab79d3db31b72e885ee/anti-adblock.txt#L331

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. Ads placeholders fixed.
