### ISSUE TITLE
owllink.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2524]
### Basic Information

**Test link:** `https://owllink.net/XUEfzb`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.3999.0 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

**Comment by TestPolygon** [comment]
> `||i.ibb.co$image`

Remove the rule or fix this.

It is the same thing like `||i.imgur.com$image` rule. 
You have broken a lot of sites that uses this image hosting for image embedding.
