### ISSUE TITLE
gratis.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2526]
### Basic Information

**Test link:** `https://www.gratis.com/`
**Category:** other
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.170

### Additional Message

url isn't opening when adblock program is working

**Comment by okiehsch** [comment]
Fixed.
