### ISSUE TITLE
kimkazandi.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2528]
### Basic Information

**Test link:** `https://www.kimkazandi.com/`
**Category:** other
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 OPR/65.0.3467.78
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

Anti select/anti copy paste, site auto-refresh every minute and ads placeholders.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select.
