### ISSUE TITLE
tucson.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#253]
### Basic Information

**Test link:** `https://tucson.com/news/local/border-agent-to-pay-k-after-starting-sawmill-fire-during/article_77b07742-c343-11e8-a6c7-9b739a2ac90b.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
**Extension:** Nano Defender 15.0.0.64

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/47595681-b9034880-d93e-11e8-989c-9712c476b378.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://tucson.com/opinion/local/ren-e-schafer-horton-stop-donating-to-the-catholic-church/article_435e9ee5-37fa-5392-bf93-f049b698d387.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Defender 15.0.0.146

### Additional Message

**Comment by jspenguin2017** [comment]
@okiehsch Broke. 
![image](https://user-images.githubusercontent.com/7283682/57896954-7b99d600-7810-11e9-870d-9b8c55d4c45f.png)

**Comment by okiehsch** [comment]
Fixed.
