### ISSUE TITLE
forum.nlmod.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2545]
### Basic Information

**Test link:** `https://forum.nlmod.net/`
**Category:** anti-adblock
**Reported from:** Ireland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.170

**Comment by okiehsch** [comment]
Fixed in annoyances.
