### ISSUE TITLE
football-lineups.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2548]
### Basic Information

**Test link:** `https://www.football-lineups.com/tourn/FA_Premier_League_2019-2020/`
**Category:** anti-adblock
**Reported from:** Pakistan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

Original URL: `https://www.football-lineups.com/`

As soon as you open any link from the site it takes you to this page: `https://www.football-lineups.com/start.php`

**Comment by okiehsch** [comment]
Fixed.
