### ISSUE TITLE
mispuani.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2553]
### Basic Information

**Test link:** `https://www.mispuani.xyz/reduce-asthma-and-breathe-free/?u=U2FsdGVkX18ZG3OSJUXzkVa5N9NMKriazoq8vgehhBiG2%2FueARhx%2BXKZqi6sz7ru3JIdZyiezZBAd%2BfKmXfWobypzMf0SHu79j43AhH0KO%2FeHryk3kZT7MC1mv5qSwT5rMpLzmBXQECi1ipGfch5G%2B13RjAQCIPRys2eb8ZtBw4xapAEzeB0PpQmkJQBZqUnZyUguL9HeMmazs%2FKxEdtRc94W%2BkF%2FFOMH2gxg86%2BgZSA0g3HRC67ESL4HwW90TG5lQFaxTl8hXIxXXSHLu5a%2BXzulgS1ViRlXEDzZBhqZS%2B7foDh637TI47Ay4U9ahFL0t7ewFE8%2FA9RFvbXK0bJpcAWMs6NTuSAgJ2Ao8znsUJinvPT4MBp4Eo89kl%2FI3DYadXPcHHTAdsuRgRutNFY%2FpDtmQ9yq66bx7trVF%2F%2FltM%3D`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

poopups after solving captcha

**Comment by okiehsch** [comment]
Fixed.
