### ISSUE TITLE
rysafe.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2557]
### Basic Information

**Test link:** `https://rysafe.blogspot.com/2018/11/why-you-need-travel-insurance.html?url=IyNvJTVEa1FKJTFGJTQwciU1RHpkJTE4TWZmaWclMUVnJTdEcU5OYSUxOSU3QiUwNSU3RiUxQSUxQkQlNUMlMTklMTVMQSUxN0ZNWEclMDdFR0slMDZNRE9HR08lMDZNJTVFQVpMJTA3JTA3JTEyJTVCWCU1QyU1QyU0MCMj`
**Category:** breakage
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

blocking generate link

**Comment by okiehsch** [comment]
Fixed.
