### ISSUE TITLE
simpsonsua.com.ua

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#256]
### Basic Information

**Test link:** `https://simpsonsua.com.ua/sezon-7/210-7-sezon-21-seriia.html`
**Category:** anti-adblock
**Reported from:** Ukraine
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
**Extension:** Nano Defender 15.0.0.65

**Comment by mapx-** [comment]
```
simpsonsua.com.ua##+js(set-constant.js, canRunAds, true)
@@||simpsonsua.com.ua/adv$image,first-party
@@||simpsonsua.com.ua/test-ad.php$xmlhttprequest,first-party
simpsonsua.com.ua##.adsbyyottos
```

`@@||simpsonsua.com.ua^$csp,first-party`

The last exception for a csp filter from russian adguard list

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/47965422-74457480-e004-11e8-8b20-906ffb8dfbb6.png)
![image](https://user-images.githubusercontent.com/7283682/47965429-832c2700-e004-11e8-999e-88ad4a727c76.png)

**Comment by okiehsch** [comment]
Fixed.
