### ISSUE TITLE
blogmelong.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2561]
### Basic Information

**Test link:** `http://blogmelong.com/benefits-of-drinking-water-for-a-healthy-body/?wp_safelink_data=MDkzZjY1ZTA4MGEyOTVmODA3NmIxYzU3MjJhNDZhYTIqZ21yWVlPTzNDSDBkM2RySzZJRkQzNStxRlJhRGx5Ylc1QVNYeEhjeWxMRT0=#landing`
**Category:** breakage
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

blocking visit link

**Comment by okiehsch** [comment]
Fixed.
