### ISSUE TITLE
fmoviesto.to

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2569]
### Basic Information

**Test link:** `https://fmoviesto.to/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

Original URL: `https://www.winningpokernetwork.com/online-poker-promotions/new-at/`

**Comment by okiehsch** [comment]
Fixed.
