### ISSUE TITLE
hitbits.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2570]
### Basic Information

**Test link:** `https://hitbits.io/faucet`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

**Comment by llacb47** [comment]
Requires account, test creds
```
Username: raleh96964
Password: raleh96964@qmailshop.com
```

No anti-adblock on that page for me, but on the offerwalls page some of the offers have annoying countdowns and anti-adblock.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://hitbits.io/home`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

**Comment by jspenguin2017** [comment]
@okiehsch 3 issues. 

Anti-adblock on `https://hitbits.io/offerwalls/adscendmedia`
![image](https://user-images.githubusercontent.com/7283682/71539022-d7722480-28f2-11ea-9d07-5fefacb31ed1.png)

Popup on `https://www.shortdat.link/ROFggd`

Anti-adblock after clicking visit link on `https://hitbits.io/offerwalls/shortlinks/8`
![image](https://user-images.githubusercontent.com/7283682/71539028-f2dd2f80-28f2-11ea-9c76-16bb3bc6219c.png)

**Comment by jspenguin2017** [comment]
Also has ads placeholders, but those are minor and may not be worth fixing.

**Comment by okiehsch** [comment]
I can't reproduce the third issue.
![image](https://user-images.githubusercontent.com/16838044/71539148-72d9b880-2938-11ea-9998-11a313d9a644.png)

**Comment by jspenguin2017** [comment]
@okiehsch Anti-adblock *after clicking* "Visit Link".

**Comment by okiehsch** [comment]
Fixed.
