### ISSUE TITLE
toledoblade.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2572]
### Basic Information

**Test link:** `https://www.toledoblade.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

The page opens then pops up a window with the following request: "It looks like you currently have an ad blocker installed.
Ad blockers function by blocking page elements that appear to be related to advertising. Often this has unexpected negative effects on other functionality within the website.
Please disable your ad blocker or whitelist toledoblade.com."

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.toledoblade.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.170

### Additional Message

Detects that you are using an adblocker and displays an overlay.

**Comment by llacb47** [comment]
`||doorbrazil.com^`

**Comment by okiehsch** [comment]
Fixed.
