### ISSUE TITLE
cyberstumble.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2573]
### Basic Information

**Test link:** `https://www.cyberstumble.com/mobile-legends-for-pc/`
**Category:** anti-adblock
**Reported from:** Argentina
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

I can't overpass anti-adblock killer with nano defender

**Comment by llacb47** [comment]
`cyberstumble.com##+js(aopw, ai_adb)`

**Comment by okiehsch** [comment]
Fixed.
