### ISSUE TITLE
asia-mag.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2575]
### Basic Information

**Test link:** `https://asia-mag.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

**Comment by okiehsch** [comment]
Fixed.
