### ISSUE TITLE
gamerspad.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2577]
### Basic Information

**Test link:** `http://www.gamerspad.net/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

This site lags the browser because it loads hundreds of ads in the background in hidden iframes, it should be blocked as badware along with the culpable domains.

Another site that does this: `http://www.comparetvs.net/`
```
||comparetvs.net^
||gamerspad.net^
||find-me-now.com^
||marketingenhanced.net^
```

ad serving domains - a generic filter can be made:
```
://xml.*/redirect?feed=*&auth=*&subid=*&url=
||mob.palmparadise.info^
||adk.mybestclick.net^
||mob.bluevibes.online^
```

**Comment by llacb47** [comment]
bump
