### ISSUE TITLE
dnserrorassist.att.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2578]
### Basic Information

**Test link:** `http://dnserrorassist.att.net/search/?q=hotels&t=9`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

**Comment by llacb47** [comment]
`dnserrorassist.att.net##.b-links`

**Comment by jspenguin2017** [comment]
@okiehsch This one should be handled by EasyList?

**Comment by okiehsch** [comment]
Yes.

**Comment by jspenguin2017** [comment]
@ryanbr

**Comment by llacb47** [comment]
Only took 9 months

`https://forums.lanik.us/viewtopic.php?f=62&t=45110`
https://github.com/easylist/easylist/commit/282f5e6e5c0a964eb76474cafa8880a09fa7ef64

**Comment by jspenguin2017** [comment]
https://github.com/easylist/easylist/commit/282f5e6e5c0a964eb76474cafa8880a09fa7ef64
