### ISSUE TITLE
wilmaa.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#258]
### Basic Information

**Test link:** `https://www.wilmaa.com/watch`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.66

**Comment by jspenguin2017** [comment]
I'm not sure what is the expected behavior of this website, but it seems fine: 
![image](https://user-images.githubusercontent.com/7283682/47965462-f2a21680-e004-11e8-93b3-b74e958e661d.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.wilmaa.com/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

### Additional Message

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.wilmaa.com/watch`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.113

### Additional Message

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.wilmaa.com/watch`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.113

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.wilmaa.com/watch`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.125

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.wilmaa.com/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.128

### Additional Message

**Comment by jspenguin2017** [comment]
Maybe requires account, otherwise cannot reproduce.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.wilmaa.com/watch`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.154

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.wilmaa.com/watch`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.154

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.wilmaa.com/watch`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.155

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.wilmaa.com/watch`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.160

### Additional Message

**Comment by mapx-** [comment]
fixed
