### ISSUE TITLE
channelmyanmar.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2582]
### Basic Information

**Test link:** `https://channelmyanmar.org/tvshows/the-witcher-2019-season-1/`
**Category:** ads
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

**Comment by okiehsch** [comment]
Fixed.

**Comment by justsharing** [comment]
missing web content 
**url:** https://channelmyanmar.org/tvshows/*
![error](https://user-images.githubusercontent.com/47627998/81328995-d54f7c00-90c3-11ea-8a4c-d712cfef06f4.png)

**Comment by mapx-** [comment]
fixed
