### ISSUE TITLE
dictionary.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2584]
### Basic Information

**Test link:** `https://www.dictionary.com/browse/hello?s=t`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.16 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

ads spaces

```
https://www.dictionary.com/
https://www.dictionary.com/browse/hello?s=t
```

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
```
dictionary.com##aside[id^="dcom-serp-"]
```
