### ISSUE TITLE
streameast.live

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2585]
### Basic Information

**Test link:** `http://www.streameast.live/cfb-football/memphis-tigers-penn-state-nittany-lions/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12607.58.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

ads overlay over video

**Comment by llacb47** [comment]
`||cadspmz.com^`

**Comment by jspenguin2017** [comment]
@okiehsch Popup.

**Comment by okiehsch** [comment]
Fixed,
