### ISSUE TITLE
lumiafirmware.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2587]
### Basic Information

**Test link:** `https://www.lumiafirmware.com/nope`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.170

**Comment by llacb47** [comment]
```
lumiafirmware.com##+js(aeld, DOMContentLoaded, Adblocker)
! or
lumiafirmware.com##+js(aopr, document.getElementById)
```

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Site is broken on my end. I can't solve the captcha even if I disable uBO.

**Comment by jspenguin2017** [comment]
Yea, the site isn't working very well right now, sometimes it works after a few refreshes. I'll consider it to be broken, let's wait a few days before testing this again.

**Comment by jspenguin2017** [comment]
@okiehsch Looks like the website is up again. Captcha can be solved properly in guest mode.
