### ISSUE TITLE
orlygift.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#259]
### Basic Information

**Test link:** `https://www.orlygift.com/`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; rv:63.0) Gecko/20100101 Firefox/63.0
**Extension:** Nano Defender 15.0.0.40

**Comment by jspenguin2017** [comment]
Soft anti-adblock. Click "win a key now", press "back" button. 
![image](https://user-images.githubusercontent.com/7283682/47965485-2da44a00-e005-11e8-8ac3-26fe34eba9b0.png)
