### ISSUE TITLE
best-series.me

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2593]
### Basic Information

**Test link:** `https://best-series.me/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 7.0; VS987) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
**Extension:** Nano Adblocker 1.0.0.130

### Additional Message

Original URL: `https://techcola.com/`

**Comment by llacb47** [comment]
Redirects/popups
`||vdains.info^$3p`
Also debugger trap (out of scope for this repo)

**Comment by jspenguin2017** [comment]
@okiehsch Popunder.

**Comment by okiehsch** [comment]
Fixed.
