### ISSUE TITLE
komiku.co

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2594]
### Basic Information

**Test link:** `https://komiku.co/manga/the-legendary-moonlight-sculptor/`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

ads on first click

**Comment by okiehsch** [comment]
Can't access the site.
![image](https://user-images.githubusercontent.com/16838044/71569176-879b8500-2acd-11ea-8635-e2815e07ad75.png)

**Comment by jspenguin2017** [comment]
I can't access neither.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://komiku.co/`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

popups, etc
