### ISSUE TITLE
blog.infolanjutan.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2595]
### Basic Information

**Test link:** `https://blog.infolanjutan.xyz/2019/12/the-definitive-guide-to-cryptosuite.html#?o=6db078c8672cd8d2d613a2d0cbf86d7405f3ef586e5f8c21375090834ff954b561211da51236b783fdb5232f7391db20174d9af7415ea780b80cb2903b878b1ee05294c13ee3d4b1`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

**Comment by okiehsch** [comment]
Fixed.
