### ISSUE TITLE
rbc.ru

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#260]
### Basic Information

**Test link:** `https://www.rbc.ru/`
**Category:** anti-adblock
**Reported from:** Russia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
**Extension:** Nano Defender 15.0.0.64

**Comment by ZaphodBeebblebrox** [comment]
Fixed in russian filters.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.rbc.ru/rbcfreenews/5bd826899a7947a097b0a87d`
**Category:** anti-adblock
**Reported from:** Kazakhstan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.66

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.rbc.ru/`
**Category:** anti-adblock
**Reported from:** Russia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
**Extension:** Nano Defender 15.0.0.66

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.rbc.ru/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.66

### Additional Message

**Comment by jspenguin2017** [comment]
@okiehsch Tried Russian regional filter, doesn't seem to work. 
![image](https://user-images.githubusercontent.com/7283682/47965528-c33fd980-e005-11e8-8f11-f5e8daa8db60.png)

**Comment by okiehsch** [comment]
`rbc.ru##+js(abort-on-property-read.js, RA.eventManager)`
but that breaks search.

**Comment by okiehsch** [comment]
> Tried Russian regional filter

Adguard will not fix the issue, https://github.com/AdguardTeam/AdguardFilters/issues/24402

**Comment by okiehsch** [comment]
I know, I don't understand that quote either, maybe something got lost in translation.
I think a `setTimeout` filter will work without breaking search, I am looking for one.

**Comment by okiehsch** [comment]
`rbc.ru##+js(setTimeout-defuser.js, t=null, 300)`
works for me.

**Comment by okiehsch** [comment]
Fixed.

**Comment by okiehsch** [comment]
> It's not a paywall, it doesn't appear if the page is whitelisted.

**off-topic**
@jspenguin2017 just as a follow up, adguard seems to define a paywall in a slightly different way, if an anti-adblock message gives the user the choice to pay instead of seeing ads, they consider it a paywall and will not circumvent it.
https://github.com/AdguardTeam/AdguardFilters/issues/24208

**Comment by jspenguin2017** [comment]
@okiehsch That is just ridiculous. Since the paywall doesn't show without AdGuard, can we say AdGuard is illegally placing paywalls on other people's websites?

**Comment by okiehsch** [comment]
They do it for legal reasons, there was a big case this year in germany and if you read the court decision, you can certainly make the argument that if an adblocker is in a competitive relationship with publishers and therefore falls under [competition law](https://en.wikipedia.org/wiki/Competition_law#Modern_competition_law), it is illegal to circumvent anti-adblock messages by the publisher.

Why adguard concludes that there is a difference between an anti-adblock message that gives the user no choice and a message that gives the choice of paying is beyond me.

**Comment by okiehsch** [comment]
They are a company and as such are in a competitive relationship with publishers.

**Comment by okiehsch** [comment]
The court does not actually say it is illegal to circumvent anti-adblock messages by the publisher, because ABP does not circumvent anti-adblock messages in the first-place but if you read the context, they certainly are open to the possibilitiy that circumventing **could** be an unfair hindrance of the publishers product,
