### ISSUE TITLE
wizardsubs.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2602]
### Basic Information

**Test link:** `https://wizardsubs.com/2019/12/14/ultraman-tiga-episode-01-49-hdtv-subtitle-indonesia/`
**Category:** other
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

anti right click anti selection etc

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/commit/9564396c78c07f7efbaca39265eac7adea2a57bb Fixed in annoyances

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select.
