### ISSUE TITLE
coswitmedia.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2603]
### Basic Information

**Test link:** `http://coswitmedia.com/tv10/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.16 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

`PropellerAds` `Recommended` at bottom. Empty ad divs also left over

**Comment by llacb47** [comment]
No ads on default filters. Popup when clicking on player fixed with scriptlet.
```
coswitmedia.com##+js(acis, parseInt)
coswitmedia.com##[id^="custom_html"]:not(:has(script[src*="chatango"]))
```

**Comment by jspenguin2017** [comment]
I see ads on default. Also has a lot of ads placeholders. 
![image](https://user-images.githubusercontent.com/7283682/71608069-902aa480-2b3b-11ea-9842-7b7cb53b6fe1.png)

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
