### ISSUE TITLE
europixhd.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2604]
### Basic Information

**Test link:** `https://europixhd.io/mov/the-golden-compass-online-free-hd-with-subtitles-europix`
**Category:** anti-adblock
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

**Comment by llacb47** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/71608266-2e6b3a00-2b3d-11ea-8f04-537b64ae1c7a.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://europixhd.io/tvs/westworld-online/westworld-season-3-hd-with-subtitles-europix#vidbox`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

Anti-adblock pops up when you try to choose server 1 (netu.tv).

**Comment by llacb47** [comment]
Can confirm something is happening. When I click on server 1 the tab autocloses.

**Comment by mapx-** [comment]
Did you use the last filters ?
https://github.com/uBlockOrigin/uAssets/commit/fae87c042802d89417c0741ee713473be5689e28

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/fae87c042802d89417c0741ee713473be5689e28
