### ISSUE TITLE
rbxnow.gg

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2608]
### Basic Information

**Test link:** `https://rbxnow.gg/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362
**Extension:** Nano Adblocker 0.0.128.0

### Additional Message

OK SO I DID EVRYTHING THAT I NEED TO DO BUT IT DOSENT WORK IT SAYS IT TO 8% TO 16%.

**Comment by okiehsch** [comment]
Fixed.
