### ISSUE TITLE
indishare.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2609]
### Basic Information

**Test link:** `https://www.indishare.org/u0kob846gnog`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.133

### Additional Message

Countdown hidden and unblocked popup (click anywhere on countdown page during countdown)

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/4176d4126f31c0d73399cd443d4f2ada1f68b213
