### ISSUE TITLE
wowtoken.info

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2618]
### Basic Information

**Test link:** `https://wowtoken.info/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.16 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.133

### Additional Message

ads space, block trigger anti-adblock

**Comment by jspenguin2017** [comment]
Ads placeholder, but very difficult to remove.

**Comment by jspenguin2017** [comment]
Current solution can't be published to extension store, fix available in debug builds of ND.

**Comment by jspenguin2017** [comment]
Fixed in Pro version.
