### ISSUE TITLE
nowagoal.stream

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2619]
### Basic Information

**Test link:** `http://nowagoal.stream/ch2.html`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.133

### Additional Message

hidden ads iframes from wstream 

fixed with `wstream.*##+js(acis, String.fromCharCode, buzz)`

**Comment by llacb47** [comment]
Also `wstream.*##+js(nostif, createElement, 15000)` 
15 seconds through the stream it loads a 3rd-party ad/popup url

**Comment by jspenguin2017** [comment]
@okiehsch Popup.

**Comment by okiehsch** [comment]
Fixed.
