### ISSUE TITLE
mdpr.jp

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2622]
### Basic Information

**Test link:** `https://mdpr.jp/music/detail/1925426`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.133

### Additional Message

anti-drag, anti right-click on photos

`mdpr.jp##+js(ra, oncontextmenu|onmousedown|onselectstart)`

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select.
