### ISSUE TITLE
linkedin.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2629]
### Basic Information

**Test link:** `https://www.linkedin.com/`
**Category:** breakage
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Adblocker 1.0.0.134

### Additional Message

Original URL: `https://www.linkedin.com/feed/`

CSS and JS seem to be blocked.

**Comment by jspenguin2017** [comment]
Works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.linkedin.com/feed/`
**Category:** breakage
**Reported from:** Latvia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
**Extension:** Nano Adblocker 1.0.0.134

### Additional Message

CORS issues

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.linkedin.com/company/hello/about`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

`linkedin.com##.org-container__ad-module`
