### ISSUE TITLE
theherald-news.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2635]
### Basic Information

**Test link:** `https://www.theherald-news.com/2019/04/08/no-longer-a-youtube-star/a9gfitm/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.176

**Comment by mapx-** [comment]
annoyance => ublock filters annoyance list to be enabled

**Comment by llacb47** [comment]
`||honorablehall.com^`
