### ISSUE TITLE
shortbitsfree.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2639]
### Basic Information

**Test link:** `https://shortbitsfree.net/cw0RWX`
**Category:** ads
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.176

### Additional Message

Fake captcha and continue button

**Comment by llacb47** [comment]
Ad domains, popups, and mining:

```
||adser.io^$3p
||hostcontent.live^$3p
||coinzillatag.com^$3p
shortbitsfree.net##+js(window.open-defuser)
||shortbitsfree.net/coinimp-cache/*
```

Maybe: `/coinimp-cache/*` It might be worth using as a generic: see `https://www.google.com/search?q=inurl%3A%22coinimp-cache%22` and the fact that `coinimp` is the name of a javascript miner: `https://www.coinimp.com/`

Fake captcha (maybe worth generic):
```
shortbitsfree.net##[href^="https://www.onclickmega.com/"]
! or
shortbitsfree.net##[href*="/jump/next.php"]
```

Anti-adblock: 

`shortbitsfree.net##+js(aopr, app_vars.force_disable_adblock)`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
`t: other`: Cryptojacking.
