### ISSUE TITLE
mercurynews.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#264]
### Basic Information

**Test link:** `https://www.mercurynews.com/2018/10/28/person-struck-by-caltrain-in-belmont/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3594.0 Safari/537.36
**Extension:** Nano Defender 15.0.0.66

**Comment by jspenguin2017** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/47965546-e4082f00-e005-11e8-837e-92fe5cab5540.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.mercurynews.com/2019/03/19/slow-traffic-lights-growth-surge-hamper-el-camino-real-roadshow/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.109

### Additional Message

**Comment by jspenguin2017** [comment]
Hum... I was able to reproduce anti-adblock once after navigating ~6 articles. May need further investigation.
