### ISSUE TITLE
topshort.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2641]
### Basic Information

**Test link:** `https://topshort.net/adskipper.php`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.4050.0 Iron Safari/537.36
**Extension:** Nano Defender 15.0.0.176

**Comment by jspenguin2017** [comment]
@okiehsch Ads and anti-adblock: `https://url.topadnetworks.net/MHmU`

**Comment by jspenguin2017** [comment]
Anti-adblock caused by broken rule in ND, added whitelist.

**Comment by jspenguin2017** [comment]
Splitting ads to another issue.
