### ISSUE TITLE
businessemailetiquette.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#265]
### Basic Information

**Test link:** `https://www.businessemailetiquette.com/`
**Category:** other
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.66

### Additional Message

anti-select and anti-copy

**Comment by jspenguin2017** [comment]
Annoyance.
