### ISSUE TITLE
dictionary.reverso.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2652]
### Basic Information

**Test link:** `https://dictionary.reverso.net/english-definition/hit%20the%20nail%20on%20the%20head`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.16 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
AdGuard Base is already removing the placeholders with `reverso.net##.locdrcas`.
