### ISSUE TITLE
speedtest.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2655]
### Basic Information

**Test link:** `https://www.speedtest.net/`
**Category:** breakage
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

Sometimes the speed test itself is broken (blocked), other times the speed test works just fine. Disabling Nano Adblocker makes it work 100% of the time.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.speedtest.net/`
**Category:** breakage
**Reported from:** Czechia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Adblocker 1.0.0.134

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.speedtest.net/`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Adblocker 1.0.0.134

### Additional Message

**Comment by jspenguin2017** [comment]
Works fine with latest filters.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.speedtest.net/#`
**Category:** breakage
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

Can't Start speedtesting
