### ISSUE TITLE
doramaindo.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2663]
### Basic Information

**Test link:** `https://doramaindo.id/`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.176

### Additional Message

annoying overlay

**Comment by llacb47** [comment]
`doramaindo.id##.adsmodal`

**Comment by jspenguin2017** [comment]
@okiehsch Overlay ads.

**Comment by jspenguin2017** [comment]
Also has some ads placeholders.

**Comment by okiehsch** [comment]
The overlay ad is blocked by the regional list on my end.

**Comment by jspenguin2017** [comment]
My bad, forgot to test regional filters. Both ads and ads placeholders are fixed by Indonesian regional filters. 
![image](https://user-images.githubusercontent.com/7283682/71935425-f9c23880-3163-11ea-856c-8abb2326411d.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://doramaindo.id/`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message
