### ISSUE TITLE
libgen.lc

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2665]
### Basic Information

**Test link:** `http://libgen.lc/ads.php?md5=f6898acfa0d5077ed3f616da7906917b`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

`libgen.*##+js(acis, $, appendMessage)`

**Comment by okiehsch** [comment]
Fixed in annoyances.
