### ISSUE TITLE
knack.be

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2667]
### Basic Information

**Test link:** `https://www.knack.be/nieuws/belgie/hilde-crevits-ik-was-zeer-ongelukkig-tussen-kerst-en-nieuw/article-news-1549889.html`
**Category:** anti-adblock
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Adblocker 1.0.0.134

**Comment by okiehsch** [comment]
Fixed.
