### ISSUE TITLE
bitcofaucet.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2668]
### Basic Information

**Test link:** `https://bitcofaucet.com/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.176

**Comment by okiehsch** [comment]
Fixed.
