### ISSUE TITLE
distractify.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2670]
### Basic Information

**Test link:** `https://www.distractify.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.177

### Additional Message

anti-adblock footer message

**Comment by llacb47** [comment]
`distractify.com##+js(acis, atob, googlefc)`

**Comment by okiehsch** [comment]
Why was the suggested filter marked as outdated?
Works on my end.

**Comment by llacb47** [comment]
Didn't work in Nano for me, issue just on my side I guess.

**Comment by okiehsch** [comment]
I added it @jspenguin2017 does it work for you?

**Comment by jspenguin2017** [comment]
Fix works for me.
