### ISSUE TITLE
folhabv.com.br

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2679]
### Basic Information

**Test link:** `https://folhabv.com.br/formulario/DESATIVE-SEU-AD-BLOCK/25`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.16 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

**Comment by jspenguin2017** [comment]
@okiehsch Redirect from homepage (`https://folhabv.com.br/`) after a few seconds. Portuguese regional filters do not help.

**Comment by okiehsch** [comment]
Fixed.
