### ISSUE TITLE
fox-url.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#268]
### Basic Information

**Test link:** `http://fox-url.com/R4b31I`
**Category:** other
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/70.0.3538.77 Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.66

### Additional Message

Timer

**Comment by jspenguin2017** [comment]
@okiehsch Timer skippable: 
```
fox-url.com##+js(nano-setInterval-booster.js)
```

**Comment by okiehsch** [comment]
Fixed.
