### ISSUE TITLE
bricksrus.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2680]
### Basic Information

**Test link:** `https://www.bricksrus.com/donorsite/trinityumc`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

anti right click

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click.
