### ISSUE TITLE
botanical-online.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2681]
### Basic Information

**Test link:** `https://www.botanical-online.com/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

Anti right click anti select

**Comment by llacb47** [comment]
I didn't think of using CSP, clever.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select.
