### ISSUE TITLE
photopea.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2684]
### Basic Information

**Test link:** `https://www.photopea.com/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
**Extension:** Nano Defender 15.0.0.177

### Additional Message

Keeps asking to show ads periodically.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.photopea.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

antiadblock through window.confirm dialog every 10 seconds or so

fix: `photopea.com##+js(nostif, "t#% &20")` or `photopea.com##+js(set, confirm, noopFunc)`

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/commit/6a36458b91831f14c6d8a9d498d42ca1ed660129

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/6a36458b91831f14c6d8a9d498d42ca1ed660129
