### ISSUE TITLE
ur-files.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2687]
### Basic Information

**Test link:** `https://ur-files.com/xyd0yo2cqrgl/IDM.6.36.Build.1.FULL-CahBorneo.Com.rar.html`
**Category:** ads
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.176

### Additional Message

fake download

**Comment by okiehsch** [comment]
Fixed.
