### ISSUE TITLE
botanical-online.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2688]
### Basic Information

**Test link:** `https://www.botanical-online.com/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.42 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

ads space

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholders:
```
botanical-online.com##.anes
botanical-online.com##.row:nth-of-type(2):has(.anes)
```
