### ISSUE TITLE
reactiongaming.us

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2689]
### Basic Information

**Test link:** `https://reactiongaming.us/community/threads/quick-start-guide-how-to-set-up-an-eldewrito-dedicated-server.1244/`
**Category:** anti-adblock
**Reported from:** Russia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.177

**Comment by okiehsch** [comment]
Fixed.
