### ISSUE TITLE
movieshdstreaming.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2692]
### Basic Information

**Test link:** `https://www.movieshdstreaming.com/movies/richard-jewell-2019/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12607.58.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.176

### Additional Message

fake watch and download buttons and other ads

**Comment by okiehsch** [comment]
Fixed.
