### ISSUE TITLE
animeshd.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2693]
### Basic Information

**Test link:** `https://animeshd.org/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36 Edg/79.0.309.60
**Extension:** Nano Defender 15.0.0.177

**Comment by okiehsch** [comment]
Fixed.
