### ISSUE TITLE
tipssehatcantik.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2710]
### Basic Information

**Test link:** `https://www.tipssehatcantik.com/jadwal-dan-lokasi-tes-ujian-skd-cpns-kab-malang-2019`
**Category:** other
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Extension:** Nano Defender 15.0.0.176

### Additional Message

anti right click

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select, anti-right-click.
