### ISSUE TITLE
theregister.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2716]
### Basic Information

**Test link:** `https://www.theregister.co.uk/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.177

### Additional Message

Original URL: `https://www.theregister.co.uk/?__cf_chl_jschl_tk__=b9ceec99b4e7bc8404a74bce155cc348ff821bf6-1578703870-0-AVzFU7R89ubA5JgxjVkeyN9UzD10tHJTR1A_Nv2_Z0M3f5GZzCA78r4xqab02mzhWdzQO-yicb3kVgi9zPVtJladdzYSbHAzT8Jm3-hGpgzUg8a221Go63j81Ef8nSiAutzjDxXy1WhDlVbuaj9U4Ekkc0gm_yUJh0viOggbPduqJm0Mjo5SWd-Sz85CtlbD2S15_3Yaq7F7yl5MTbQkflMrfHONG04WI53QkTepDCL6M1Ug5Mac8hIOcw9nuLdFZLc6Mm303QJros9Ucnnn5rI`

detects adblocker

**Comment by jspenguin2017** [comment]
@okiehsch FYI.
