### ISSUE TITLE
ntv.com.tr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2717]
### Basic Information

**Test link:** `https://www.ntv.com.tr/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 6.0.1; ASUS_Z00LD) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

**Comment by okiehsch** [comment]
Fixed.
