### ISSUE TITLE
mangaku.in

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2720]
### Basic Information

**Test link:** `https://mangaku.in/one-piece-chapter-967-v2/`
**Category:** ads
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Extension:** Nano Defender 15.0.0.176

### Additional Message

popups
anti right click
anti select
banner ads

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click.
