### ISSUE TITLE
mangakyo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2723]
### Basic Information

**Test link:** `https://www.mangakyo.com/`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Extension:** Nano Defender 15.0.0.176

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/b970e178d7005e87025c1d1f1eda7d0b01aacb51
