### ISSUE TITLE
globaldjmix.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2735]
### Basic Information

**Test link:** `https://globaldjmix.com/livedjsets/transmission-2016-the-lost-oracle-live-from-o2-arena-prague-full-set-download-mp3-29-october-2016`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:71.0) Gecko/20100101 Firefox/71.0
**Extension:** Nano Defender 15.0.0.170

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/dac5a43550eac5ce442b7fd2ec275cfcc1fea543
