### ISSUE TITLE
kompasiana.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2737]
### Basic Information

**Test link:** `https://www.kompasiana.com/`
**Category:** ads
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Extension:** Nano Defender 15.0.0.176

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.kompasiana.com/`
**Category:** ads
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.kompasiana.com/`
**Category:** ads
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 5.1.1; A37f) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

Ads reinjection

**Comment by mapx-** [comment]
fixed
