### ISSUE TITLE
nekopoi.care

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2739]
### Basic Information

**Test link:** `https://nekopoi.care/boku-to-joi-no-shinsatsu-nisshi-episode-1-subtitle-indonesia/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Extension:** Nano Defender 15.0.0.176

### Additional Message

can't streaming

**Comment by jspenguin2017** [comment]
Works fine with Indonesian regional filters.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://nekopoi.care/tayu-tayu-episode-3-subtitle-indonesia/`
**Category:** ads
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Defender 15.0.0.198

### Additional Message

**Comment by jspenguin2017** [comment]
@gmarcher @okiehsch Banner ads. 
![image](https://user-images.githubusercontent.com/7283682/82610350-6ec66580-9b7b-11ea-92ab-a3b71d19217e.png)
