### ISSUE TITLE
alantvstream.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#275]
### Basic Information

**Test link:** `http://www.alantvstream.com/live-stream/racing/moto-gp/malaysian-grand-prix-02-11-2018.html`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.66

**Comment by jspenguin2017** [comment]
@okiehsch Has popup.

**Comment by okiehsch** [comment]
Fixed.
