### ISSUE TITLE
reuters.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2751]
### Basic Information

**Test link:** `https://www.reuters.com/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Adblocker 1.0.0.134

### Additional Message

giant cookie consent thingy covering the screen

**Comment by mapx-** [comment]
`reuters.com###_evidon-barrier-wrapper`

@ryanbr

**Comment by yourduskquibbles** [comment]
@mapx- I just noticed this while trying to recreate the consent overlay but `uBlock filters - Privacy` seems to be blocking the markets data at the top of the `reuters.com` homepage 

`@@||googletagmanager.com/gtm.js$script,domain=reuters.com` seems to fix the issue but is this too aggressive of unblocking on a high traffic site?

screenshot from stock browser/no extensions is below to show what is blocked
![reuters](https://user-images.githubusercontent.com/22258847/72369812-e3b9f800-36ce-11ea-80cd-ef5cf7a117c9.png)

**Comment by mapx-** [comment]
No, it's ok

**Comment by ryanbr** [comment]
@mapx- we have `easylist_cookie_general_hide.txt:###_evidon-barrier-wrapper` already?

**Comment by mapx-** [comment]
@ryanbr right, missed it
