### ISSUE TITLE
oceantech.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2760]
### Basic Information

**Test link:** `http://oceantech.xyz/Vt4Wm5DH`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

fake download
`http://jasarekber.net/ccbhyALp`

**Comment by okiehsch** [comment]
Fixed.
