### ISSUE TITLE
startv.com.tr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2766]
### Basic Information

**Test link:** `https://www.startv.com.tr/dizi/babil/oyuncular`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
**Extension:** Nano Adblocker 1.0.0.134

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance.

**Comment by okiehsch** [comment]
````
You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page.
````
I will fix that in the main list, nothing is "interfering" with the page, all works fine.

**Comment by okiehsch** [comment]
Fixed.
