### ISSUE TITLE
includehelp.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2767]
### Basic Information

**Test link:** `https://www.includehelp.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance.

**Comment by okiehsch** [comment]
Fixed.
