### ISSUE TITLE
haipedia.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2768]
### Basic Information

**Test link:** `https://www.haipedia.com/post/Senjata-Paling-Mematikan-di-PUBG-Mobile`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

fake button popups anti adblock

`https://www.shrinkads.com/d5UXgE`

**Comment by okiehsch** [comment]
Fixed.
