### ISSUE TITLE
otodom.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2771]
### Basic Information

**Test link:** `https://www.otodom.pl/wynajem/mieszkanie/`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

Photos are not loading.

**Comment by okiehsch** [comment]
Fixed.
