### ISSUE TITLE
enjoydressup.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2777]
### Basic Information

**Test link:** `https://www.enjoydressup.com/play/retro-arcade-days?ref=notset`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
**Extension:** Nano Defender 15.0.0.177

### Additional Message

Adblocker detected. It seems to be the game's original creator, Idea Studios, baking anti-adblock into their games.

**Comment by okiehsch** [comment]
Fixed.
