### ISSUE TITLE
watchseriesunblocked.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2778]
### Basic Information

**Test link:** `http://www1.watchseriesunblocked.org/tag/mindhunter.html`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

popups fake notifs

**Comment by okiehsch** [comment]
Fixed.
