### ISSUE TITLE
buffstreamz.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2779]
### Basic Information

**Test link:** `http://buffstreamz.com/watch/nfl`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12739.37.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.58 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

`NFL Streams` schedule buttons on right click is popup with fake watch link

**Comment by okiehsch** [comment]
Fixed.
