### ISSUE TITLE
kimcartoon.to

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#278]
### Basic Information

**Test link:** `http://kimcartoon.to/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.66

### Additional Message

The website still detects that an adblock is still installed, but does not prevent any functionality.

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/47965649-c4bdd180-e006-11e8-967c-cb15c3145d3a.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://kimcartoon.to/`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 9; Redmi Note 4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.112 Mobile Safari/537.36
**Extension:** Nano Defender 15.0.0.139

### Additional Message

Website detects adblock. But fully functional. Happens only when 1st time visiting site.
https://imgur.com/a/G5PjKsW

**Comment by jspenguin2017** [comment]
@okiehsch Soft anti-adblock. `kimcartoon.to###adbWarnContainer`

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://kimcartoon.to/`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.139

### Additional Message

https://ibb.co/bNjZ7SR

**Comment by okiehsch** [comment]
Already fixed. https://github.com/uBlockOrigin/uAssets/commit/7d7c6df4c1b308c9225326b5a68e35c9698c8158

**Comment by jspenguin2017** [comment]
Ah, the block screen comes up every 180 minutes, so it's not soft.
