### ISSUE TITLE
technopat.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2783]
### Basic Information

**Test link:** `https://www.technopat.net/`
**Category:** ads
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.technopat.net/sosyal/konu/yeni-windows-10-sueruemue-manganese-olarak-anilabilir.889861/`
**Category:** ads
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36 Edg/81.0.416.53
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

**Comment by mapx-** [comment]
`technopat.net##.pageskin`
@Alex-302
