### ISSUE TITLE
hedgeaccordingly.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2787]
### Basic Information

**Test link:** `https://hedgeaccordingly.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
**Extension:** Nano Defender 15.0.0.177

### Additional Message

anti adblock banner at bottom

**Comment by llacb47** [comment]
`hedgeaccordingly.com##+js(aopw, ABD)`

**Comment by okiehsch** [comment]
Fixed in annoyances.
