### ISSUE TITLE
richmond.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2788]
### Basic Information

**Test link:** `https://www.richmond.com/news/local/photos-scenes-from-the-gun-rights-rally-at-capitol-square/collection_9dba409a-4f0d-57ee-93eb-5da72a50ebbe.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
**Extension:** Nano Defender 15.0.0.177

### Additional Message

anti-adblock modal

**Comment by yourduskquibbles** [comment]
These filters seem to work for me... 

`richmond.com##.fc-ab-root`
`richmond.com##body[style*="overflow: hidden;"]:style(overflow-x: hidden !important; overflow-y: scroll !important;)` 


This modal probably impact all `BH media` domains, I don't have time to fully test, but list of domains are below

### `BH Media Group, Inc.` - `https://www.bhmginc.com/markets/`
`dailyprogress.com`
`dothaneagle.com`
`fredericksburg.com`
`godanriver.com`
`greensboro.com`
`heraldcourier.com`
`hickoryrecord.com`
`journalnow.com`
`kearneyhub.com`
`martinsvillebulletin.com`
`mcdowellnews.com`
`morganton.com`
`newsadvance.com`
`nonpareilonline.com`
`nptelegraph.com`
`oanow.com`
`omaha.com`
`pressofatlanticcity.com`
`richmond.com`
`roanoke.com`
`scnow.com`
`starexponent.com`
`starherald.com`
`statesville.com`
`theeagle.com`
`theindependent.com`
`tulsaworld.com`
`wacotrib.com`
`yorknewstimes.com`

Domain string
`dailyprogress.com,dothaneagle.com,fredericksburg.com,godanriver.com,greensboro.com,heraldcourier.com,hickoryrecord.com,journalnow.com,kearneyhub.com,martinsvillebulletin.com,mcdowellnews.com,morganton.com,newsadvance.com,nonpareilonline.com,nptelegraph.com,oanow.com,omaha.com,pressofatlanticcity.com,richmond.com,roanoke.com,scnow.com,starexponent.com,starherald.com,statesville.com,theeagle.com,theindependent.com,tulsaworld.com,wacotrib.com,yorknewstimes.com`

**Comment by llacb47** [comment]
can we try to find a scriplet solution (non-cosmetic)?

**Comment by yourduskquibbles** [comment]
> 
> 
> can we try to find a scriplet solution (non-cosmetic)?

Yes of course, I'm just useless when it comes to creating those 😶
