### ISSUE TITLE
filmesonlinex.co

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2795]
### Basic Information

**Test link:** `https://www.filmesonlinex.co/chernobyl-dublado/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

choosing any episode results in being loaded crap 3p scripts and popup

**Comment by okiehsch** [comment]
Fixed.
