### ISSUE TITLE
macdrop.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2801]
### Basic Information

**Test link:** `http://macdrop.net/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

**Comment by mapx-** [comment]
popups, no anti adb on my side
