### ISSUE TITLE
citpekalongan.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2816]
### Basic Information

**Test link:** `https://www.citpekalongan.com/2020/01/23-24-desember-2020-part-650-gratis.html`
**Category:** other
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

anti right click anti select

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select, anti-hotkey.

**Comment by JobcenterTycoon** [comment]
anti select again
