### ISSUE TITLE
uploadbank.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2826]
### Basic Information

**Test link:** `http://www.uploadbank.com/wtyvh20vxvxl`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://www.uploadbank.com/nplo36616wj1`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0
**Extension:** Nano Defender for Firefox 15.0.0.205

### Additional Message

Welcome to UploadBank.
It looks like you are using an adblocker.

But without ads revenue, we can't provide free downloads.

I have disabled my adblocker. Let me in!

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/4321ff85adefc55425103a2853284549c68e0be4

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/4321ff85adefc55425103a2853284549c68e0be4
