### ISSUE TITLE
snopes.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2829]
### Basic Information

**Test link:** `https://www.snopes.com/news/2020/01/23/trump-rollbacks-obama-school-lunch/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

**Comment by jspenguin2017** [comment]
@okiehsch Does this go into the main filter?

**Comment by okiehsch** [comment]
Yes, @mapx- I decided to fix all google contributor adblock messages in `uBO-filters`. 
See https://github.com/NanoMeow/QuickReports/issues/2766#issuecomment-575838759 
They seem to imply to me that an adblocker is breaking some site functionality which is simply not true.
They are not asking their users to disable adblocking to support the site.

**Comment by okiehsch** [comment]
Also the "interfering" message is caused by 
`||fundingchoicesmessages.google.com^$3p`
in `uBO-filters`, so it makes sense to fix it inthe same list.
If you allow `fundingchoicesmessages.google.com`
