### ISSUE TITLE
euw.op.gg

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#283]
### Basic Information

**Test link:** `http://euw.op.gg/summoner/userName=eyesreye`
**Category:** ads
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.67

### Additional Message

Ads are not getting blocked.

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/47966367-c4c1cf80-e00e-11e8-80af-50924ad3e2b2.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://euw.op.gg/ranking/champions/name=nocturne`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
**Extension:** Nano Adblocker 1.0.0.125

### Additional Message

Happens on all OP.gg sections it is blocking to much cant select champions

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed,
