### ISSUE TITLE
glassdoor.ca

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2833]
### Basic Information

**Test link:** `https://www.glassdoor.ca/Reviews/Employee-Review-HELLO-RVW3648641.htm`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

ads placeholder

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by llacb47** [comment]
`glassdoor.*##[id*="-AdSlot-"]`
