### ISSUE TITLE
sharetvr.my.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2837]
### Basic Information

**Test link:** `https://sharetvr.my.id/dl.php?id=NnRjS2NWWmN3WksxVDdEUkY5MjFROGdqN1YxUjNNcVJGSFZ1VEhtanRCWVRUaS9IQzQ5Yk1YMmRHL2Z6eUc0RjNDdzZKelZFYnVxbmFZNXlLTmlkcGhRM2ZHS2E2YVlWRjNvR2p1dHpOT0IrRHJRNmQ3clBRRlBDNkFYUmh0NG0=&type=2`
**Category:** other
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

boostr timer

**Comment by llacb47** [comment]
`sharetvr.my.id##+js(nano-sib)`

**Comment by jspenguin2017** [comment]
@okiehsch Timer can be boosted.

**Comment by okiehsch** [comment]
Fixed.
