### ISSUE TITLE
givekey.ru

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2844]
### Basic Information

**Test link:** `https://givekey.ru/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.44
**Extension:** Nano Adblocker 1.0.0.135

**Comment by okiehsch** [comment]
@dimisa-RUAdList
`@@||givekey.ru^$generichide`

**Comment by dimisa-RUAdList** [comment]
https://hg.adblockplus.org/ruadlist/rev/5800fd1f2d0e
