### ISSUE TITLE
cbc.ca

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2853]
### Basic Information

**Test link:** `https://www.cbc.ca/radio/thenextchapter/bob-joseph-believes-indigenous-reconciliation-can-be-realized-sooner-rather-than-later-1.5438015`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

**Comment by jspenguin2017** [comment]
Ads placeholders.
