### ISSUE TITLE
shrink.world

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2857]
### Basic Information

**Test link:** `https://www.shrink.world/post/game-simulasi-balap-terbaik#b4B2tH`
**Category:** ads
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

```
http://www.shrink.world/b4B2tH
http://www.shrink.world/pZf07maE
```

fake button after solving captcha

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/fbfef20a243a6579ba92e093929c626766202038
