### ISSUE TITLE
beatsandsamples.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#286]
### Basic Information

**Test link:** `http://beatsandsamples.com/adblock-banned.html`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.69

**Comment by okiehsch** [comment]
Fixed.
