### ISSUE TITLE
play.aetv.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2862]
### Basic Information

**Test link:** `https://play.aetv.com/shows/beyond-scared-straight/season-1/episode-1`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

Video won't play

**Comment by mapx-** [comment]
working fine FF / chrome, uBo default settings
