### ISSUE TITLE
lexigram.gr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2868]
### Basic Information

**Test link:** `https://www.lexigram.gr/lex/latin/it/testo#Hist0`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

**Comment by atassos** [comment]
This change in the filters breaks for me the functionality of the website.
console log:
TypeError: cannot declare global binding `ajaxCheckUserBehaviour': property must be configurable or both writable and enumerable
ReferenceError: jsInitEnv is not defined

**Comment by mapx-** [comment]
Test these filters
```
lexigram.gr#@#+js(set, ajaxCheckUserBehaviour, trueFunc)
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=lexigram.gr
@@||lexigram.gr/lex/resources/advertisement.js$script,1p
```

**Comment by atassos** [comment]
mapx- Thanks. The filter you suggested: lexigram.gr#@#+js(set, ajaxCheckUserBehaviour, trueFunc)
works, Contrary to the existing one: 
! https://github.com/NanoMeow/QuickReports/issues/2868
lexigram.gr##+js(set, ajaxCheckUserBehaviour, trueFunc)

I suggest that this is updated on ublock as it breaks the functionality for all ublock visitors of the site.

**Comment by mapx-** [comment]
already fixed in uBO list, see above the commit
