### ISSUE TITLE
hausbau-forum.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2877]
### Basic Information

**Test link:** `https://www.hausbau-forum.de/threads/pax-236-in-raumhoehe-236.21867/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
**Extension:** Nano Defender Pro 15.0.0.181

**Comment by okiehsch** [comment]
Fixed.
