### ISSUE TITLE
adnan-tech.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2878]
### Basic Information

**Test link:** `http://adnan-tech.com/tutorial/add-thumbnail-to-video-php-ffmpeg`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Edg/79.0.309.71
**Extension:** Nano Defender 15.0.0.180

**Comment by okiehsch** [comment]
Fixed +no right click copy annoyance.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select.
