### ISSUE TITLE
warps.club

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2889]
### Basic Information

**Test link:** `https://warps.club/forum/`
**Category:** anti-adblock
**Reported from:** Thailand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Edg/79.0.309.71
**Extension:** Nano Defender Pro 15.0.0.180

**Comment by mapx-** [comment]
nsfw
