### ISSUE TITLE
texviewer.herokuapp.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2890]
### Basic Information

**Test link:** `https://texviewer.herokuapp.com/?state=%7B%22ids%22:%5B%2211pCn19Jp0p7xa0uXba9_FpsF54_Y1GVw%22%5D,%22action%22:%22open%22,%22userId%22:%22112093714551120561786%22%7D`
**Category:** anti-adblock
**Reported from:** New Zealand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

Pop-up saying "Please disable the adblock for free use" when I try to "View as PDF"

**Comment by jspenguin2017** [comment]
@okiehsch @mapx- A rule that covers the entire public suffix, are you sure about that?

**Comment by llacb47** [comment]
Definitely a mistake.

**Comment by okiehsch** [comment]
Updated.
