### ISSUE TITLE
cammelhub.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2895]
### Basic Information

**Test link:** `https://cammelhub.com/male/user/twinkzz101`
**Category:** anti-adblock
**Reported from:** Costa Rica
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

**Comment by okiehsch** [comment]
The link is not NSFW but the domain is. I am not sure if you label it NSFW in such a case.

**Comment by okiehsch** [comment]
Fixed.
