### ISSUE TITLE
ghacks.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2916]
### Basic Information

**Test link:** `https://www.ghacks.net/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender for Firefox 15.0.0.182

### Additional Message

You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.ghacks.net/`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender for Firefox 15.0.0.182

### Additional Message

**Comment by krystian3w** [comment]
Race condition with `##+js(nostif, removeChild, 100)`

?

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/73603583-d65f9300-4541-11ea-8bd1-7c473071fc88.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.ghacks.net/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.131 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

**Comment by krystian3w** [comment]
Possible detect CPU with pur JavaScript only?

**Comment by jspenguin2017** [comment]
@krystian3w I don't understand what you mean. Elaborate?

**Comment by krystian3w** [comment]
In Poland popular is use old CPU (10-20 years old: 2000-2010 year production).

**Comment by jspenguin2017** [comment]
It is certainly possible that CPU can change race condition results, but for this issue, I think the likely reason is people are using outdated filters.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.ghacks.net/2020/07/30/opera-software-publishes-opera-70-for-the-desktop/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

placeholders

**Comment by jspenguin2017** [comment]
https://github.com/NanoAdblockerLab/NanoContrib/pull/133
