### ISSUE TITLE
chat.babel.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#292]
### Basic Information

**Test link:** `https://chat.babel.com/Content/_AdBlock/AdBlockDetected.html`
**Category:** anti-adblock
**Reported from:** Algeria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.69

### Additional Message

Adblock detected still.

**Comment by ZaphodBeebblebrox** [comment]
People keep reporting the adblockdetected pages.

**Comment by jspenguin2017** [comment]
Requires account.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://chat.babel.com/Chat`
**Category:** anti-adblock
**Reported from:** Algeria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
**Extension:** Nano Defender 15.0.0.157

### Additional Message

https://chat.babel.com/Content/_AdBlock/AdBlockDetected.html

**Comment by llacb47** [comment]
Bait: `https://chat.babel.com/Scripts/Lib/adsbygoogle.js`
`@@||chat.babel.com/Scripts/Lib/adsbygoogle.js$script,first-party`

**Comment by llacb47** [comment]
Also anti-adblock on root domain: `https://www.babel.com/search.aspx`

![Anti-adblock](https://user-images.githubusercontent.com/16567977/62405457-5729dc00-b56b-11e9-902b-960805acacaa.png)

**Comment by jspenguin2017** [comment]
Need test account to verify. 

@okiehsch Annoyance on `https://www.babel.com/search.aspx` (no account required).

**Comment by okiehsch** [comment]
Fixed.

**Comment by llacb47** [comment]
You do not need an account, go to `https://chat.babel.com/`, click the blue `Join` button, and fill out the fields with some random information.

**Comment by okiehsch** [comment]
Fixed.
