### ISSUE TITLE
sfgate.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2921]
### Basic Information

**Test link:** `https://www.sfgate.com/bayarea/article/mask-N95-coronavirus-Bay-Area-San-Francisco-15020642.php`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

site recognizes ad block

**Comment by llacb47** [comment]
Admiral annoyance, `||prepareplanes.com^`
