### ISSUE TITLE
bleacherreport.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2922]
### Basic Information

**Test link:** `https://bleacherreport.com/houston-texans`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

Started blocking page containers for tweets on 1/31/2020.
```
##li.twitterEmbed.atom:nth-of-type(1) > .twitterEmbed__container > .tw-align-center.twitter-tweet
```

**Comment by okiehsch** [comment]
Fixed.
