### ISSUE TITLE
sfgate.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2932]
### Basic Information

**Test link:** `https://www.sfgate.com/bayarea/article/mask-N95-coronavirus-Bay-Area-San-Francisco-15020642.php`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.78 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

ads placeholders

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
AdGuard Base is already blocking all placeholders there that I can find.
