### ISSUE TITLE
isikuota.co.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2944]
### Basic Information

**Test link:** `https://isikuota.co.id/bug-host-axis-hitz/`
**Category:** other
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.181

### Additional Message

anti right click, select

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select.
