### ISSUE TITLE
flashplayer.fullstacks.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#295]
### Basic Information

**Test link:** `http://flashplayer.fullstacks.net/?kind=Drive_Game&state=%7B%22ids%22:%5B%2218B8kl7-bXvBI-AEaPi52UFvockkql3XC%22%5D,%22action%22:%22open%22,%22userId%22:%22100469386829937453553%22%7D`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 10452.99.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.203 Safari/537.36
**Extension:** Nano Defender 15.0.0.69

**Comment by jspenguin2017** [comment]
@okiehsch
`flashplayer.fullstacks.net##+js(set-constant.js, gadb, false)`
