### ISSUE TITLE
allindiaroundup.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2952]
### Basic Information

**Test link:** `https://allindiaroundup.com/india/here-are-some-interesting-things-about-jai-anmol-ambani-the-elder-son-of-anil-ambani/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.181

**Comment by okiehsch** [comment]
Fixed.
