### ISSUE TITLE
jazzradio.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#296]
### Basic Information

**Test link:** `https://www.jazzradio.com/about-blockers`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.69

### Additional Message

Anti adblock not working on this website I cannot disable "Please disable your Ad Blocker for this website" banner

**Comment by jspenguin2017** [comment]
Related to https://github.com/NanoMeow/QuickReports/issues/290
