### ISSUE TITLE
tecknity.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2960]
### Basic Information

**Test link:** `https://tecknity.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.181

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
