### ISSUE TITLE
mediasetplay.mediaset.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2961]
### Basic Information

**Test link:** `https://www.mediasetplay.mediaset.it/diretta/canale5_cC5`
**Category:** other
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.181

### Additional Message

Please
Page (player video) not found

**Comment by okiehsch** [comment]
Fixed.
