### ISSUE TITLE
geekdrop.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2962]
### Basic Information

**Test link:** `https://geekdrop.com/`
**Category:** anti-adblock
**Reported from:** Finland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
**Extension:** Nano Defender for Firefox 15.0.0.182

### Additional Message

Original URL: `https://geekdrop.com/content/logitechg-discord-exe-process-eating-cpu-what-how-stop-it`

**Comment by okiehsch** [comment]
Fixed.
