### ISSUE TITLE
haramainsoftware.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2965]
### Basic Information

**Test link:** `https://www.haramainsoftware.com/antivirus/smadav-2020-pro/`
**Category:** ads
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.181

### Additional Message

and anti select

**Comment by mapx-** [comment]
no anti select on my end, only popups
