### ISSUE TITLE
livescience.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2972]
### Basic Information

**Test link:** `https://www.livescience.com/tweezers-nose-triassic-reptile.html`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.181

**Comment by mapx-** [comment]
annoyance
