### ISSUE TITLE
arenabg.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2988]
### Basic Information

**Test link:** `https://arenabg.com/come-to-daddy-2019-1080p-web-dl-dd5-1-h264-fgt-865687/`
**Category:** ads
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72
**Extension:** Nano Adblocker 1.0.0.135

**Comment by okiehsch** [comment]
Fixed.
