### ISSUE TITLE
olarila.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2989]
### Basic Information

**Test link:** `https://www.olarila.com/`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
**Extension:** Nano Adblocker 1.0.0.134

### Additional Message

Original URL: `https://www.olarila.com/topic/6818-olarila-catalina-for-intel-and-amd-pcs/`

**Comment by okiehsch** [comment]
Fixed.
