### ISSUE TITLE
gamepciso.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#2990]
### Basic Information

**Test link:** `https://gamepciso.com/order-of-the-gatekeepers-download-free/`
**Category:** breakage
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.181

**Comment by mapx-** [comment]
popups .. but breakage where ?

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://gamepciso.com/rocketron-download-free/`
**Category:** breakage
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.181

### Additional Message

download button broken

**Comment by jspenguin2017** [comment]
@okiehsch Download button is not working properly.

**Comment by okiehsch** [comment]
Fixed.
