### ISSUE TITLE
acmilan.com.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#300]
### Basic Information

**Test link:** `http://www.acmilan.com.pl`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
**Extension:** Nano Defender 15.0.0.71

**Comment by mapx-** [comment]
@MajkiIT

`acmilan.com.pl##+js(set-constant.js, showAds, true)`

**Comment by MajkiIT** [comment]
@mapx- Thanks
https://github.com/MajkiIT/polish-ads-filter/commit/d63b74eedd300a2ef12b34aa020b17ef0de9e07d
