### ISSUE TITLE
forumcoin.win

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3007]
### Basic Information

**Test link:** `https://forumcoin.win/waves/`
**Category:** anti-adblock
**Reported from:** Russia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.181

### Additional Message

Original URL: `https://forumcoin.win/waves/block.php`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/3328a802fee332af3ed19cc731830f88bc3f496c
