### ISSUE TITLE
botayit.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3010]
### Basic Information

**Test link:** `https://botayit.com/download-techsmith-camtasia-2019/`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.181

**Comment by okiehsch** [comment]
Fixed.
