### ISSUE TITLE
letsupload.co

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3019]
### Basic Information

**Test link:** `https://letsupload.co/1uc9n?pt=T1V0NFNIWlFkbmhWUmpSSWEyWjNka1JEYTAxdVFUMDlPb2sxWS9Na3lsSkozdTZQd2hsaDNrcz0%3D`
**Category:** breakage
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 Edg/80.0.361.48
**Extension:** Nano Defender 15.0.0.185

**Comment by mapx-** [comment]
only ads, not broken
