### ISSUE TITLE
pinsec.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3021]
### Basic Information

**Test link:** `https://pinsec.xyz/kqP`
**Category:** anti-adblock
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.185

**Comment by okiehsch** [comment]
Fixed.
