### ISSUE TITLE
journaldev.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3022]
### Basic Information

**Test link:** `https://www.journaldev.com/25101/python-not-equal-operator`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 Edg/80.0.361.50
**Extension:** Nano Defender Pro 15.0.0.181

### Additional Message

Anti-adblock pops up on all pages, the URL is just a specific example. I have Nano adblocker and Nano defender installed. I am using Microsft Edge (new chromium based version). Thanks for this.

**Comment by okiehsch** [comment]
Fixed.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.journaldev.com/23610/python-string-equals`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.185

### Additional Message
