### ISSUE TITLE
mixmods.com.br

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3026]
### Basic Information

**Test link:** `https://www.mixmods.com.br/2014/02/Livraria-CLEO.html`
**Category:** anti-adblock
**Reported from:** Morocco
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.185

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/2f95db27c9f50b5fe3dd4b88194e470069fd89ce

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-hotkey, anti-select.
