### ISSUE TITLE
wickedspot.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3030]
### Basic Information

**Test link:** `http://wickedspot.org/sherman-maus-blew-velvet/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.185

**Comment by mapx-** [comment]
**NSFW**
