### ISSUE TITLE
creditcardgenerator.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3038]
### Basic Information

**Test link:** `https://creditcardgenerator.com/visa-credit-card-generator/`
**Category:** anti-adblock
**Reported from:** Europe (Opera Mini Proxy)
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.95
**Extension:** Nano Adblocker 1.0.0.135

**Comment by okiehsch** [comment]
Fixed.
