### ISSUE TITLE
hu.motorsport.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3039]
### Basic Information

**Test link:** `https://hu.motorsport.com/`
**Category:** anti-adblock
**Reported from:** Hungary
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
**Extension:** Nano Defender for Firefox 15.0.0.185

### Additional Message

Original URL: `https://hu.motorsport.com/f1/news/a-ferrari-nagyon-odafigyel-arra-amit-vettel-es-leclerc-mond-de-2021-nehez-lesz/4683861/`

**Comment by okiehsch** [comment]
Fixed.
