### ISSUE TITLE
convert-case.softbaba.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3041]
### Basic Information

**Test link:** `https://convert-case.softbaba.com/js-uppercase-to-lowercase/21825-javascript-test-for-uppercase`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Defender for Firefox 15.0.0.185

### Additional Message

This site is just using the open source "IAB Adblock detector" (`https://github.com/InteractiveAdvertisingBureau/AdBlockDetection/blob/master/adblockDetector.js`).  I would have expected it to be blocked easily.  "adblockDetector.js" script is whitelisted by Fanboy’s Enhanced Tracking List.

**Comment by okiehsch** [comment]
Fixed.
