### ISSUE TITLE
download.cnet.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3042]
### Basic Information

**Test link:** `https://download.cnet.com/games/windows/`
**Category:** other
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; rv:73.0) Gecko/20100101 Firefox/73.0
**Extension:** Nano Defender for Firefox 15.0.0.185

### Additional Message

Original URL: `https://download.cnet.com/`

webpage does not work properly,the drop down menu from the page header won't showed up.and the 'load more' button isn't working as well...

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ccbe727237c999dd4f858912b933ff8e12092718

**Comment by Yuki2718** [comment]
It seems whitelisting is not mandatory. These rules works:
`||tags.tiqcdn.com/utag/cbsi/cnetglobalsite/prod/utag.js$script,redirect=noop.js,domain=www.cnet.com
`
`||tags.tiqcdn.com/utag/cbsi/downloadcomsite/prod/utag.js$script,redirect=noop.js,domain=download.cnet.com`
