### ISSUE TITLE
mlsbd.site

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3046]
### Basic Information

**Test link:** `https://mlsbd.site/hacked-2020-hindi-pre-dvdrip-480p-720p-x264-400mb-1-2gb-download-watch-online/`
**Category:** ads
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.185

**Comment by okiehsch** [comment]
Fixed.
