### ISSUE TITLE
meutimao.com.br

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3048]
### Basic Information

**Test link:** `https://www.meutimao.com.br/`
**Category:** anti-adblock
**Reported from:** New Zealand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.185

### Additional Message

Big soccer club website from Brazil, detecting adblock

**Comment by okiehsch** [comment]
Fixed.
