### ISSUE TITLE
rbxoffers.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3050]
### Basic Information

**Test link:** `https://rbxoffers.com/home`
**Category:** breakage
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 Edg/80.0.361.50
**Extension:** Nano Defender Pro 15.0.0.185

### Additional Message

The offers on this site are not longer viewed.

**Comment by okiehsch** [comment]
Fixed anti adb. Needs an account to test for breakage.
