### ISSUE TITLE
unifi.com.my

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3053]
### Basic Information

**Test link:** `https://unifi.com.my/personal/home/fibre-broadband`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.17 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.135

### Additional Message

"buy now" button doesn't work.

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
