### ISSUE TITLE
viptools.es

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3061]
### Basic Information

**Test link:** `https://viptools.es/`
**Category:** anti-adblock
**Reported from:** Peru
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
**Extension:** Nano Defender Pro 15.0.0.186

### Additional Message

Are you using adblocker?
Please disable or remove adblocker and Refresh the page.

**Comment by okiehsch** [comment]
Fixed.
