### ISSUE TITLE
shortearn.eu

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3062]
### Basic Information

**Test link:** `http://shortearn.eu/SjgxX`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.185

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/7a02490052109a1b4bb742e704378cfeaece2879
