### ISSUE TITLE
techtobo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3064]
### Basic Information

**Test link:** `https://www.techtobo.com/`
**Category:** anti-adblock
**Reported from:** Czechia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.185

### Additional Message

Nanoblock is still being detected. :(

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ef9fe3044fd72fcdb07a9f849d4e9a8464c874d0
