### ISSUE TITLE
tek.no

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3065]
### Basic Information

**Test link:** `https://www.tek.no/test/i/wPLW21/hp-spectre-x360-13`
**Category:** other
**Reported from:** Norway
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0
**Extension:** Nano Adblocker 1.0.0.134

### Additional Message

Blank page

**Comment by lassekongo83** [comment]
@DandelionSprout: Get rid of `tek.no##.b`

`tek.no##div:has-text(/^annonse$/)` works to get rid of the placeholder ad text.

**Comment by DandelionSprout** [comment]
I received word of this last night in https://github.com/DandelionSprout/adfilt/issues/62, and I believe I fixed it pretty soon afterwards.

**Comment by lassekongo83** [comment]
Well, I guess I can be slow at times. :+1:

**Comment by jspenguin2017** [comment]
https://github.com/DandelionSprout/adfilt/commit/0df190d98451855b1f0d09f7fa116f7babcdd5eb
