### ISSUE TITLE
phimgi.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3067]
### Basic Information

**Test link:** `https://phimgi.tv/xem-phim/thi-tran-riverdale-phan-2-riverdale-season-2-tap-8-server-1/`
**Category:** anti-adblock
**Reported from:** Taiwan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.185

**Comment by okiehsch** [comment]
Fixed.
