### ISSUE TITLE
encurta.eu

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3071]
### Basic Information

**Test link:** `https://encurta.eu/rkBt9rW6?__cf_chl_captcha_tk__=bbaaf9418c1994dec3cdc73ec37ff5215743e926-1581964964-0-AdXFJGBEoOKrWkfqn-AvICTk39Ftxo-e52XWYgiqXiGx5b4reFTVFJEW36SKCi3J2ow4wFV0iccWuFDlD86i2Q12pCrBy6q8U0iN29bA8zJmsodOuhSKSYpJE5UxQwXlAs0YdmZ7SD8o4h6oyM0fil7EpC9QKg44H8_qZM14oHobDcjIKGcG56XOBjO9PJ4xWESwDZN_BP-LzJpRaqlsqLmuraexHSWkU8wvXQHWC3okmlX6T2iqaNYfxlmaLUH8gf_YM7Ps2y96bA1tQ6KxnJVdDesrFY0Zj36OF9kNAsl3Ru_9y66bY0o9c4PrPE1v3Qy-EavpJU6DpbLhFyg3QQm81KhHRMcIjYMvQ9FpzJ0JQauuxra77T0y06v5ODGkDQ`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 5.1.1; A37f) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
**Extension:** Nano Defender 15.0.0.187

### Additional Message

`https://encurta.eu/rkBt9rW6`

Fake button

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ab0b4591ac1a6b6d7502c04d606956f542a5ea68
