### ISSUE TITLE
selfhacked.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3083]
### Basic Information

**Test link:** `https://selfhacked.com/blog/galantamine-12-proven-health-benefits-galantamine-backed-science/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
**Extension:** Nano Defender for Firefox 15.0.0.185

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

Hi! 

I have firefox 73.0.1 (64-bit), uBlock Origin 1.24.5rc2, And nano defender 15.0.0.185.   I enabled the advanced setting URL, I see 3 custom NANO filters in the list and I also have The Adblock warning removal list.   All lists updated.

I also cleared the cookies for this site, closed/reopened firefox, etc.

Thanks!

**Comment by okiehsch** [comment]
Fixed.
