### ISSUE TITLE
infolokerserang.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3092]
### Basic Information

**Test link:** `https://www.infolokerserang.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
**Extension:** Nano Defender for Firefox 15.0.0.185

**Comment by okiehsch** [comment]
Fixed.
