### ISSUE TITLE
katmoviehd.nl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3096]
### Basic Information

**Test link:** `https://katmoviehd.nl/`
**Category:** ads
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
**Extension:** Nano Defender 15.0.0.187

**Comment by okiehsch** [comment]
Fixed.
