### ISSUE TITLE
tii.ai

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3097]
### Basic Information

**Test link:** `https://tii.ai/XO8In`
**Category:** ads
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.95
**Extension:** Nano Adblocker 1.0.0.135

**Comment by ghajini** [comment]
`https://tii.ai/DXM0`

Popup ads

**Comment by lain566** [comment]
Fixed.
