### ISSUE TITLE
cruisin.me

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3098]
### Basic Information

**Test link:** `https://www.cruisin.me/cruise-port-tracker`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
**Extension:** Nano Defender 15.0.0.187

### Additional Message

Original URL: `https://www.cruisin.me/cruise-port-tracker/united-states/miami-florida/`

**Comment by okiehsch** [comment]
Fixed.
