### ISSUE TITLE
palimas.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3099]
### Basic Information

**Test link:** `https://palimas.tv/video?id=25652&v=9eXF5b6xYDq5-Ella-Hughes-Case-No.-5144158`
**Category:** anti-adblock
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.187

**Comment by okiehsch** [comment]
NSFW. Fixed.
