### ISSUE TITLE
playpuls.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#31]
### Basic Information

**Test link:** `http://playpuls.pl/seriale/lombard-zycie-pod-zastaw`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.39

### Additional Message

anti-adblock detected

**Comment by jspenguin2017** [comment]
Fixed by Polish regional filters.

**Comment by jspenguin2017** [comment]
@okiehsch @MajkiIT Broke. 
![image](https://user-images.githubusercontent.com/7283682/44633448-b8ebca00-a948-11e8-8512-7fb9c5f1a3d9.png)

**Comment by okiehsch** [comment]
@MajkiIT
````
playpuls.pl##+js(setInterval-defuser.js, muted, 8000)
playpuls.pl##+js(setTimeout-defuser.js, Math.round, 5000)
````

**Comment by MajkiIT** [comment]
@jspenguin2017 @okiehsch Thanks
