### ISSUE TITLE
cfouca.fr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#310]
### Basic Information

**Test link:** `https://www.cfouca.fr/la-chine-donne-un-ultimatum-a-la-france-de-mettre-fin-au-pacte-colonial-en-afrique/?utm_sq=fwvgzj54ca&utm_source=Facebook&utm_medium=partners&utm_campaign=Pens%C3%A9eLibre`
**Category:** ads
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.71

**Comment by okiehsch** [comment]
I don't see any ads with the regional list enabed, I do get an anti-adblock message, which I can click away.
