### ISSUE TITLE
limontorrents.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3100]
### Basic Information

**Test link:** `https://www.limontorrents.com/naruto-shippuden/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Defender 15.0.0.187

**Comment by okiehsch** [comment]
Fixed.
