### ISSUE TITLE
maachanime.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3102]
### Basic Information

**Test link:** `http://maachanime.com/`
**Category:** other
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
**Extension:** Nano Defender 15.0.0.187

### Additional Message

anti right click

**Comment by okiehsch** [comment]
Fixed + anti adb.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select, anti-right-click.
