### ISSUE TITLE
ruinmyweek.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3104]
### Basic Information

**Test link:** `https://ruinmyweek.com/tweets/wendys-roasts-burger-king/?utm_content=buffer494a3&utm_medium=facebook&utm_source=tfln&utm_campaign=ooo&fbclid=IwAR3mNPBch7_8WF_M87-NwRjjsOaUG5okL1Vrtm3nENduOQuIEAGNdQuK_L4`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
**Extension:** Nano Defender Pro 15.0.0.186

### Additional Message

Anti-adblocker popup.

**Comment by okiehsch** [comment]
Fixed.
