### ISSUE TITLE
fairytail-tube.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#311]
### Basic Information

**Test link:** `http://fairytail-tube.org/folge/263-u5tZ1Ax`
**Category:** other
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.71

### Additional Message

After installation of NanoDefender with uBlock Origin, the videos can not be loaded anymore on fairytail-tube.org.
Before the installation, an ad was loaded and shown before the video starts, now nothing happens after clicking the start button.

**Comment by okiehsch** [comment]
I can fix the pre-roll ads, I can't reproduce the video not starting.
