### ISSUE TITLE
imghot.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3110]
### Basic Information

**Test link:** `http://imghot.net/hyfjgfj`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
**Extension:** Nano Defender 15.0.0.187

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a12ca255505cedff5e354c2a9d6019c8882913ee
