### ISSUE TITLE
dvdgayonline.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3111]
### Basic Information

**Test link:** `https://dvdgayonline.com/`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 9; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0
**Extension:** Nano Defender for Firefox 15.0.0.185

### Additional Message

Original URL: `https://dvdgayonline.com/movies/collin-oneals-world-of-men-lebanon/`

**Comment by okiehsch** [comment]
NSFW. Fixed.
