### ISSUE TITLE
vidlii.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3117]
### Basic Information

**Test link:** `https://www.vidlii.com/`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

Cloudflare Apps - Anti-adblock

**Comment by jspenguin2017** [comment]
Will be fixed in the next version of ND.
