### ISSUE TITLE
download.htdrive.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3120]
### Basic Information

**Test link:** `https://download.htdrive.com/f34a8d7b61994bd8`
**Category:** anti-adblock
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
**Extension:** Nano Adblocker 1.0.0.134

### Additional Message

webdesign broken
adblock detection

**Comment by llacb47** [comment]
`@@||download.htdrive.com/*/js/advertisement.js$script,1p`

**Comment by okiehsch** [comment]
Fixed.
