### ISSUE TITLE
thekat.nl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3125]
### Basic Information

**Test link:** `https://thekat.nl/`
**Category:** breakage
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender for Firefox 15.0.0.185

**Comment by mapx-** [comment]
fixed
