### ISSUE TITLE
watchmovie.movie

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3127]
### Basic Information

**Test link:** `https://watchmovie.movie/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

cannot focus inside of search box when nano enabled

**Comment by okiehsch** [comment]
Fixed.
