### ISSUE TITLE
wtk.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3132]
### Basic Information

**Test link:** `https://wtk.pl/news/54965-rzecznik-policji-o-19-latku-ktory-zabil-rowerzyste-ukrywal-sie-wiele-godzin-w-takim-miejscu-ktorego-nie-mozna-bylo-ustalic`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36 Edg/80.0.361.57
**Extension:** Nano Defender Pro 15.0.0.187

### Additional Message

Nano Adblocker has been detected

**Comment by okiehsch** [comment]
Anti adblock is fixed in the regional list.
Videos are broken.

**Comment by okiehsch** [comment]
Fixed.
