### ISSUE TITLE
jestrudo.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3135]
### Basic Information

**Test link:** `https://www.jestrudo.pl/jak-robic-jasne-zdjecia/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36 Edg/80.0.361.57
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

Original URL: `https://www.jestrudo.pl/?z`

With ad-block enabled redirecting to `https://www.jestrudo.pl/?z`

**Comment by okiehsch** [comment]
Fixed.
