### ISSUE TITLE
worldometers.info

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3136]
### Basic Information

**Test link:** `https://www.worldometers.info/world-population/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

`worldometers.info##.container > div:has(:scope > .adsbygoogle)`

**Comment by jspenguin2017** [comment]
Also on home page: `https://www.worldometers.info/`
