### ISSUE TITLE
ap-siken.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3147]
### Basic Information

**Test link:** `https://www.ap-siken.com/apkakomon.php`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Defender 15.0.0.190

### Additional Message

Aftter push the buttun "正解を表示する”, explations of the problems("解説") are hidden due to Adblocker.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.ap-siken.com/apkakomon.php`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Defender 15.0.0.190

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.ap-siken.com/apkakomon.php`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

The answer is not displayed when I press the button

**Comment by jspenguin2017** [comment]
@okiehsch Hard anti-adblock, dims the answer. Also has ads placeholders. 
![image](https://user-images.githubusercontent.com/7283682/88682180-9e2fac00-d0af-11ea-9bba-81fad6d80fb9.png)

**Comment by okiehsch** [comment]
Where do I have to click to reproduce?

**Comment by jspenguin2017** [comment]
Click `出題開始 START`, then click `正解を表示する`.

**Comment by okiehsch** [comment]
Fixed.
