### ISSUE TITLE
tvsinpagar.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#315]
### Basic Information

**Test link:** `http://www.tvsinpagar.com/descargar/serie/chicago-fire/temporada-5/capitulo-14/#`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.72

**Comment by ZaphodBeebblebrox** [comment]
I only got a malicious redirect, no anti-adblock. uBlockOrigin/uAssets@e0f67d1  uBlockOrigin/uAssets@979d1bc
