### ISSUE TITLE
gubukbisnis.me

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3166]
### Basic Information

**Test link:** `https://www.gubukbisnis.me/post/hal-yang-perlu-anda-ketahui-sebelum-memulai-bisnis#y0nhHW`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Defender 15.0.0.190

### Additional Message

and cant scroll and fake button on countdown

**Comment by okiehsch** [comment]
I don't see a fake button.
