### ISSUE TITLE
melissagraham.site

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3173]
### Basic Information

**Test link:** `https://melissagraham.site/xI9iGDk`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Defender 15.0.0.190

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/eb229ec49548e96d5fedd02a53e8756cb73102c6

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/eb229ec49548e96d5fedd02a53e8756cb73102c6
