### ISSUE TITLE
money.cnn.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3179]
### Basic Information

**Test link:** `https://money.cnn.com/2013/11/13/technology/enterprise/microsoft-stack-ranking/index.html`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
**Extension:** Nano Defender for Firefox 15.0.0.190

### Additional Message

Ads/promotion links on right sidebar

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholder on top: `money.cnn.com##.breadcrumb`
Sponsored external textlink ads for credit cards: `money.cnn.com##section.column:has(:scope > #moneySponsors)`

**Comment by jspenguin2017** [comment]
Please open a PR to Nano Contrib.

**Comment by jspenguin2017** [comment]
OK, so this is not just placeholders? 

@okiehsch FYI.

**Comment by okiehsch** [comment]
The `money.cnn.com` subdomain is not in use anymore as far as I can see. The example link is a 7 years old article.

**Comment by jspenguin2017** [comment]
`.breadcrumb` does not look like a placeholder, it is empty in guest mode as well.
