### ISSUE TITLE
mangaid.click

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3181]
### Basic Information

**Test link:** `https://mangaid.click/manga/battle-through-the-heavens/282/1`
**Category:** other
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Defender 15.0.0.190

### Additional Message

anti right click anti select

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click.
