### ISSUE TITLE
librospreuniversitariospdf.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3187]
### Basic Information

**Test link:** `https://librospreuniversitariospdf.blogspot.com/`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
**Extension:** Nano Defender Pro 15.0.0.190

### Additional Message

Message "Detectamos tu Adblock", "por favor desactiva tu adblock".

**Comment by okiehsch** [comment]
Fixed + ads + right click disabled.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click.
