### ISSUE TITLE
mythethao.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3188]
### Basic Information

**Test link:** `http://mythethao.net/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

**Comment by mapx-** [comment]
```
mythethao.net##.banner_bar
mythethao.net##.banner_top
mythethao.net##.banner
*.gif$domain=mythethao.net,image
```

**Comment by jspenguin2017** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Non English?

**Comment by mapx-** [comment]
reported here:
https://www.facebook.com/abpvn.org

**Comment by mapx-** [comment]
VN list, FB reporting: https://www.facebook.com/abpvn.org/

**Comment by hoang-rio** [comment]
Updated in *ABPVN* with commit https://github.com/abpvn/abpvn/commit/895fda06a5c80b751d54f2508f6b215cc04271a2
