### ISSUE TITLE
techminto.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3196]
### Basic Information

**Test link:** `https://techminto.com/perfect-credit-card-for-students-reviews/`
**Category:** anti-adblock
**Reported from:** Peru
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
**Extension:** Nano Defender Pro 15.0.0.190

### Additional Message

"Adblock detected"

**Comment by okiehsch** [comment]
Fixed.
