### ISSUE TITLE
motherjones.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#32]
### Basic Information

**Test link:** `https://www.motherjones.com/food/2018/08/farmworkers-are-dying-from-extreme-heat/?utm_source=mj-newsletters&utm_medium=email&utm_campaign=food-for-thought-2018-08-26`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
**Extension:** Nano Defender 15.0.0.37

**Comment by jspenguin2017** [comment]
@okiehsch FYI. Annoyance.
