### ISSUE TITLE
verified-extensions.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3205]
### Basic Information

**Test link:** `https://verified-extensions.com/access.html?an=at&t=e2ae73fae1718285364b7f848af1ac00&k=15162033&l=br`
**Category:** ads
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Defender 15.0.0.190

**Comment by llacb47** [comment]
badware list?

**Comment by jspenguin2017** [comment]
Looks pretty sketchy, more likely than not it's malware. @okiehsch What do you think?

**Comment by okiehsch** [comment]
https://malwaretips.com/blogs/remove-verified-extensions-com/

**Comment by jspenguin2017** [comment]
`t: other`: Badware.
