### ISSUE TITLE
zone-annuaire.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3206]
### Basic Information

**Test link:** `https://www.zone-annuaire.com/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

popups

**Comment by okiehsch** [comment]
Fixed.
