### ISSUE TITLE
whathifi.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3208]
### Basic Information

**Test link:** `https://www.whathifi.com/reviews/samsung-qe65q70r-review`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

**Comment by llacb47** [comment]
Scriptlet fix: `whathifi.com##+js(aopr, _sp_._networkListenerData)` 

Network fix: ||ttauri.whathifi.com^

Also works:

```
||futurecdn.net^*/header.js$script,3p
||whathifi.com^*space-gb.js$script,redirect=noop.js
||whathifi.com^*space-gb.js$xhr,redirect=noop.txt
```

**Comment by mapx-** [comment]
I cannot reproduce, is it annoyance ?

does this work ?
`whathifi.com##+js(aopr, _sp_.mms.startMsg)`

**Comment by llacb47** [comment]
Yes, it's already blocked by the annoyance list 🤦‍♂️

![image](https://user-images.githubusercontent.com/16567977/75928731-04840b80-5e3d-11ea-9a44-aeb218f3c15e.png)
