### ISSUE TITLE
shmoop.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3210]
### Basic Information

**Test link:** `https://www.shmoop.com/study-guides/poetry/chimney-sweeper-experience/summary#stanza-1-summary`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36 Edg/80.0.361.62
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

prevents subheaders from opening

**Comment by jspenguin2017** [comment]
Has some ads placeholders, but can't reproduce breakage. The website behaves the same in guest mode.

**Comment by DandelionSprout** [comment]
I can't find any placeholders, but I did find a visible tracking iframe: `||dn5bj2dqerm21.cloudfront.net^`
