### ISSUE TITLE
mixdrop.to

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3213]
### Basic Information

**Test link:** `https://mixdrop.to/f/aucdoiw70flu`
**Category:** anti-adblock
**Reported from:** Philippines
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Defender 15.0.0.190

### Additional Message

Original URL: `https://pinoymovieshub.me/movies/ani-the-harvest/`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/176aea91bccc9823dd8779f9a314571d88f8586c
