### ISSUE TITLE
underconsideration.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3216]
### Basic Information

**Test link:** `https://www.underconsideration.com/brandnew/`
**Category:** anti-adblock
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
**Extension:** Nano Defender for Firefox 15.0.0.190

### Additional Message

adblock detection

**Comment by okiehsch** [comment]
Fixed in annoyances,

**Comment by jspenguin2017** [comment]
Test link: `https://www.underconsideration.com/brandnew/archives/new_logo_and_identity_for_pleo_by_koto.php`
