### ISSUE TITLE
vier.be

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3218]
### Basic Information

**Test link:** `https://www.vier.be/de-mol/bruno1`
**Category:** breakage
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

Cannot play video with Nano Adblocker and Nano Defender active.

**Comment by okiehsch** [comment]
Fixed.
