### ISSUE TITLE
newsmax.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3219]
### Basic Information

**Test link:** `https://www.newsmax.com/newsfront/lisa-page-peter-strzok-trump/2020/03/02/id/956515/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
**Extension:** Nano Defender for Firefox 15.0.0.190

### Additional Message

please disable adblock message at top

**Comment by okiehsch** [comment]
Fixed in `uBO-filters`.
"Please disable your Ad Blocker to view this site properly."
The site displays just fine, they just want to scare users into disabling their blockers.
So I will fix it in a default list and not in annoyances.
