### ISSUE TITLE
javdoe.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3220]
### Basic Information

**Test link:** `https://javdoe.tv/movie/s1no-1style-ssni-409-yua-mikami-secret-agent-investigator-woman-aphrodisiaphics-immortal-limit-torture-special.html`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

"Please turn off adblockers in order to continue watching JavDoe.TV"

**Comment by okiehsch** [comment]
Fixed.
