### ISSUE TITLE
semuanyabola.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3226]
### Basic Information

**Test link:** `https://www.semuanyabola.com/jersi-liverpool-kain-lap/?fbclid=IwAR2AntNrkUVo8CT3wg1Ooyl3e_BRvUKI711DMZv8p6kyt_54uniySsevoRU`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.191

**Comment by okiehsch** [comment]
Fixed.
