### ISSUE TITLE
ockles.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3227]
### Basic Information

**Test link:** `https://ockles.com/0Fo5Qnb7DgzXkVYL`
**Category:** ads
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.191

**Comment by llacb47** [comment]
No ads, timer can be boosted.
