### ISSUE TITLE
carbonite.co.za

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3233]
### Basic Information

**Test link:** `https://carbonite.co.za/index.php?forums/in-game-currency-items.33/`
**Category:** anti-adblock
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

**Comment by okiehsch** [comment]
Fixed.
