### ISSUE TITLE
nekopoi.web.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3236]
### Basic Information

**Test link:** `https://www.nekopoi.web.id/2020/02/ishuzoku-reviewers-episode-7-subtitle-indonesia.html`
**Category:** other
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.191

### Additional Message

anti right click anti hotkey

**Comment by jspenguin2017** [comment]
`t: other`: Anti-copy, anti-select.
