### ISSUE TITLE
miranpeterman.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3238]
### Basic Information

**Test link:** `https://www.miranpeterman.com/delavnice/kako-pozdraviti-rane-preteklosti/`
**Category:** breakage
**Reported from:** Slovenia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

Original URL: `https://myblog.miranpeterman.com/testna-stran-2/`

Extension is blocking Subscribe Form. Please fix this.
regards
Mike

**Comment by jspenguin2017** [comment]
https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/48

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/7cbae9c91dbc9d5dcf44404854f2f4cf46427cde
