### ISSUE TITLE
uplinkto.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3242]
### Basic Information

**Test link:** `https://uplinkto.net/view/175MZ7BAc8`
**Category:** ads
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.191

**Comment by okiehsch** [comment]
Fixed.
