### ISSUE TITLE
interestingengineering.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3246]
### Basic Information

**Test link:** `https://interestingengineering.com/square-tire-british-airways-plane-baffles-experts`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.191

### Additional Message

forcing users to turn off adblock

**Comment by okiehsch** [comment]
Fixed in anooyances.
`||spellsalsa.com^$important` for `NanoBase.txt`.
