### ISSUE TITLE
oxy.cloud

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3250]
### Basic Information

**Test link:** `https://oxy.cloud/d/pyH`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.43 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

Original URL: `chrome://newtab/`

banner ads at final destination page.

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by llacb47** [comment]
Generic for easylist: `##[href^="http://advertisesimple.info/"]`
