### ISSUE TITLE
news.mydrivers.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3252]
### Basic Information

**Test link:** `https://news.mydrivers.com/1/672/672211.htm`
**Category:** ads
**Reported from:** Hong Kong
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.43 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

ad spase

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholders:
```
news.mydrivers.com##.baidu_left
news.mydrivers.com##.baidu_right:style(float: left !important)
news.mydrivers.com##.adsbygoogle:upward(1)
```
