### ISSUE TITLE
gplinks.co

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3254]
### Basic Information

**Test link:** `https://gplinks.co/Hljx57fv`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/82.0.4078.2 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/1cad13ebfd01b81417bef9a947f23bf9be904d6f
