### ISSUE TITLE
tvp.info

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3258]
### Basic Information

**Test link:** `https://www.tvp.info/47037696/jak-rozprzestrzenia-sie-koronawirus-wideo`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.191

**Comment by okiehsch** [comment]
Fixed.
