### ISSUE TITLE
wiadomosci.onet.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3272]
### Basic Information

**Test link:** `https://wiadomosci.onet.pl/kraj/koronawirus-w-polsce-specjalne-oredzie-prezydenta-andrzej-duda-ws-koronawirusa/w9x24cy`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
**Extension:** Nano Adblocker 1.0.0.140

**Comment by okiehsch** [comment]
Fixed.
