### ISSUE TITLE
abandonmail.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3279]
### Basic Information

**Test link:** `https://www.abandonmail.com/adblock`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.193

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e384b3fd496b7806616a31d20d40e63ab7644f6d
