### ISSUE TITLE
savealoonie.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3282]
### Basic Information

**Test link:** `https://www.savealoonie.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 10; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0
**Extension:** Nano Defender for Firefox 15.0.0.194

### Additional Message

Any specific deal, coupon, freebie, etc. on this site that you click will force you to disable your adblocker in order to view it

**Comment by okiehsch** [comment]
Fixed.
