### ISSUE TITLE
kurazone.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#329]
### Basic Information

**Test link:** `https://www.kurazone.net/2018/11/cara-membuat-caption-source-image-pada-gambar-postingan-blog.html`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
**Extension:** Nano Defender 15.0.0.73

**Comment by jspenguin2017** [comment]
Also anti-select.
