### ISSUE TITLE
checkwhocalled.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3297]
### Basic Information

**Test link:** `https://checkwhocalled.com/phone-number/1-888-409-1410`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

ads space

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
```
checkwhocalled.com###top_left
checkwhocalled.com###top_right:style(max-width: none !important; padding-bottom: 5px !important)
```
