### ISSUE TITLE
sklep.pl.canalplus.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3298]
### Basic Information

**Test link:** `https://sklep.pl.canalplus.com/prepaid-mix`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

Website won't load tv channel lists on gray box:

> Podana oferta nie zawiera w sobie kanałów. Skontaktuj się z pomocą techniczną.

After one or two minutes above text sholud by changed to images of list channels tv.

For my helps:

`@@||cloudfront.net/frosmo.easy.js$script,domain=sklep.pl.canalplus.com`

**Comment by mapx-** [comment]
@ryanbr

**Comment by jspenguin2017** [comment]
Unsure what the issue is, the website behaves the same with or without the exception rule.

**Comment by ryanbr** [comment]
I can't reproduce this

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/16521

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/15756

**Comment by krystian3w** [comment]
Maybe geolocked and need Poland VPN.

**Comment by hawkeye116477** [comment]
I think that they are checking if visitor is from Poland or not and they are showing channels logos only for people with Polish IP.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://sklep.pl.canalplus.com/prepaid-mix/formularze-skrocone/sklep-platforma-canal-oferta-na-karte?pm_source=pl_canalplus&pm_medium=subpage_telewizja-na-karte&pm_content=button&pm_campaign=20012020&pm_term=kup-tnk`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

empty section:

![](https://user-images.githubusercontent.com/19818572/84779975-55330500-afe5-11ea-85f4-6f8cde9cc97d.png)

He says there are no channels, even though there are.
The problem is caused by **EasyPrivacy** and can be solved with the rule:

`@@/frosmo.easy.js$domain=sklep.pl.canalplus.com`

**Comment by jspenguin2017** [comment]
For https://github.com/NanoMeow/QuickReports/issues/3298#issuecomment-644922630 : 
I see the same thing in guest mode.

**Comment by jspenguin2017** [comment]
For https://github.com/NanoMeow/QuickReports/issues/3298#issuecomment-644922630 : 
Can't reproduce. I see the same thing in guest mode.

**Comment by krystian3w** [comment]
Use Polish VPN and disable https://github.com/MajkiIT/polish-ads-filter/commit/8ca418e07e9762f916a71059c90d67758c8be4b0 (with bad filter), the best move that fix into `EasyPrivacy` instead small Polish regional list.
