### ISSUE TITLE
smsiak.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3299]
### Basic Information

**Test link:** `https://www.smsiak.pl/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

`@@||smsiak.pl/js/advertisement.js`

**Comment by krystian3w** [comment]
Similar fraud / scam as https://github.com/NanoMeow/QuickReports/issues/3300#issuecomment-598789909

**Comment by jspenguin2017** [comment]
@okiehsch 

---

`t: other`: Badware.

**Comment by okiehsch** [comment]
Fixed.
