### ISSUE TITLE
bleepingcomputer.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3309]
### Basic Information

**Test link:** `https://www.bleepingcomputer.com/forums/t/715194/windows-10-cumulative-update-kb4551762/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

BC AdBot (Login to Remove)

**Comment by jspenguin2017** [comment]
Ads placeholder.

**Comment by DandelionSprout** [comment]
AdGuard Base was apparently blocking it successfully already with `bleepingcomputer.com###ips_Posts > .post_block:has(div.apb)`, which it seems I was too late to find out. 😅

**Comment by jspenguin2017** [comment]
That rule is a lot cleaner, I updated Placeholder Buster.
