### ISSUE TITLE
dxmaps.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3310]
### Basic Information

**Test link:** `https://www.dxmaps.com/spots/mapg.php?Lan=E`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Defender for Firefox 15.0.0.194

### Additional Message

Big adblock warning on the left ("I am sorry to notice that advertising seems to be blocked by your browser"). However, it might be very difficult or even impossible to block it (I have already tried to do so), since it is somehow directly attatched/connected to the map which should of course stay there. I don't know whether this issue can be solved, but I wanted to submit it to you anyway, of course. Maybe you can do something about it.

**Comment by okiehsch** [comment]
Fixed.
