### ISSUE TITLE
jav.guru

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3311]
### Basic Information

**Test link:** `https://jav.guru/88725/stars-208-i-love-my-teacher-and-i-hate-her-too-and-i-had-the-dqn-bad-boys-fuck-her-brains-out-yuna-ogura/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Defender for Firefox 15.0.0.194

### Additional Message

The option " Stream EP" detects

**Comment by okiehsch** [comment]
Fixed.
