### ISSUE TITLE
calgaryherald.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3315]
### Basic Information

**Test link:** `https://calgaryherald.com/news/local-news/live-at-430-p-m-province-to-provide-update-on-covid-19-response/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

big spaces

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholders:
```
calgaryherald.com##.ad__section-border
calgaryherald.com##section:has(:scope > .widget-flyercity)
```

**Comment by llacb47** [comment]
Also works: `calgaryherald.com##.ad`
