### ISSUE TITLE
medicalnewstoday.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3318]
### Basic Information

**Test link:** `https://www.medicalnewstoday.com/articles/coronavirus-myths-explored`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

banner on top

**Comment by jspenguin2017** [comment]
Can't reproduce ads, but has ads placeholders.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/b1b8142034da7941ae305dd61200f384dc3840f1
https://github.com/uBlockOrigin/uAssets/commit/933ee7cb6580c3573f9aa3046a886d267df447ae

Fixed.
