### ISSUE TITLE
grantorrent.cc

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3325]
### Basic Information

**Test link:** `https://grantorrent.cc/`
**Category:** ads
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

Original URL: `https://windows-reparatur.de/repair/Wie_Sie_Probleme_beheben_mit_Windows/`

al entrar en `https://grantorrent.cc/` me redirige a una pagina con esta url `https://windows-reparatur.de/repair/Wie_Sie_Probleme_beheben_mit_Windows/` 

gracias

**Comment by okiehsch** [comment]
Fixed.
