### ISSUE TITLE
en.akinator.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3326]
### Basic Information

**Test link:** `https://en.akinator.com/theme-selection`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Defender for Firefox 15.0.0.194

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://en.akinator.com/game`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Adblocker 1.0.0.151

### Additional Message

Prevents the game from starting entirely. Sometimes it loads the page but the game its self gets stuck on loading, sometimes the page loads as blank.

**Comment by llacb47** [comment]
Their server is buggy and returns `500 Internal Server Error` a lot. 

Test page: `https://en.akinator.com/theme-selection`

If you can get the page to load, needs CNAME whitelist:
`@@||en.akinator.com.cdn.ezoic.net^$script,font,css,domain=en.akinator.com`

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/88000732-a7bb8180-cabb-11ea-9ef3-2deeac1b1261.png)

**Comment by llacb47** [comment]
In firefox, needs CNAME whitelist...

**Comment by jspenguin2017** [comment]
@LiCybora

**Comment by llacb47** [comment]
The fix needs to go in the unbreak list @okiehsch

**Comment by okiehsch** [comment]
I can't reproduce and I rather not allow all first-party scripts, they have quite a few "bad" ones.

**Comment by llacb47** [comment]
@okiehsch `https://streamable.com/5h0t48`

Fonts and scripts are getting blocked, I can't play the game.

**Comment by okiehsch** [comment]
Added, thx.
