### ISSUE TITLE
cyberciti.biz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3329]
### Basic Information

**Test link:** `https://www.cyberciti.biz/faq/centos-8-set-up-openvpn-server-in-5-minutes/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

ads space

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholders:
```
cyberciti.biz##.adsbygoogle:upward(1)
cyberciti.biz##h2:has-text(/^ADVERTISEMENTS$/)
```

**Comment by llacb47** [comment]
IMO better:
```
cyberciti.biz##center:has(.adsbygoogle)
cyberciti.biz##.widget:has(.adsbygoogle)
```
