### ISSUE TITLE
videogamesblogger.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3330]
### Basic Information

**Test link:** `https://www.videogamesblogger.com/2020/03/17/borderlands-3-reveals-guns-love-and-tentacles-dlc-first-12-minutes.htm`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

Original URL: `https://www.videogamesblogger.com/`

yavli
also on
`https://faithit.com/i-still-believe-number-1-box-office/` at bottom
`https://madworldnews.com/chelsea-trump-obama-virus/`
`https://sonsoflibertymedia.com/uk-source-claims-dvla-worker-registers-army-vehicles-for-commercial-roads-ongoing-in-face-of-manufactured-coronavirus-crisis/`

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.videogamesblogger.com/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

yavli

**Comment by mapx-** [comment]
It was fixed today

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/6c0ec7a0ef4b9e4108654de5cf4e596ae0181a44#diff-728d382ab45d1e85df51bb432db0ce90
