### ISSUE TITLE
miniurl.pw

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3332]
### Basic Information

**Test link:** `https://miniurl.pw/volcan`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Adblocker 1.0.0.140

**Comment by okiehsch** [comment]
Fixed.
