### ISSUE TITLE
nsfwmega.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3334]
### Basic Information

**Test link:** `https://nsfwmega.com/forum/48-riot/`
**Category:** anti-adblock
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Defender for Firefox 15.0.0.194

**Comment by okiehsch** [comment]
Needs an account.
