### ISSUE TITLE
worldgreynews.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3335]
### Basic Information

**Test link:** `https://www.worldgreynews.com/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

bad inline script

```
||ofgogoatan.com^$3p
worldgreynews.com##+js(aopr, String.fromCharCode)
```

**Comment by okiehsch** [comment]
Fixed.
