### ISSUE TITLE
nulljungle.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3341]
### Basic Information

**Test link:** `https://nulljungle.com/php-scripts/ips-community-suite-full-nulled/`
**Category:** anti-adblock
**Reported from:** Hong Kong
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Defender 15.0.0.194

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back
