### ISSUE TITLE
fastssh.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3344]
### Basic Information

**Test link:** `https://www.fastssh.com/page/ssh-account-creator/server/14/SSH-Server-Indonesia-2/`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.136 Safari/537.36
**Extension:** Nano Defender 15.0.0.194

### Additional Message

this site tell  me to deactivate adblock

**Comment by okiehsch** [comment]
Fixed.
