### ISSUE TITLE
watchonlyfoolsandhorses.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3347]
### Basic Information

**Test link:** `http://watchonlyfoolsandhorses.com/seasons/specials/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

blockadblock  page comes up.

**Comment by okiehsch** [comment]
Fixed.
