### ISSUE TITLE
okcaller.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3348]
### Basic Information

**Test link:** `https://www.okcaller.com/usercomments.php`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.194

**Comment by jspenguin2017** [comment]
Also space on details page: `https://www.okcaller.com/detail.php?number=800000000`
