### ISSUE TITLE
latestnumber.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3349]
### Basic Information

**Test link:** `http://latestnumber.com/?number=8000000000`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.194

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
```
latestnumber.com##.h90
latestnumber.com##.hidden-xs
```
