### ISSUE TITLE
shindanmaker.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3350]
### Basic Information

**Test link:** `https://shindanmaker.com/c/list?mode=hot`
**Category:** ads
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.69 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

blanc space

**Comment by jspenguin2017** [comment]
Ads placeholders.
