### ISSUE TITLE
helis.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3355]
### Basic Information

**Test link:** `https://www.helis.com/database/cn/48745/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

`helis.com##+js(aopw, adBlockDetected)` in ublock filters breaks the comment form on this page.

`Uncaught ReferenceError: quickr is not defined` when submit

**Comment by okiehsch** [comment]
Fixed.
