### ISSUE TITLE
mt-milcom.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3360]
### Basic Information

**Test link:** `https://mt-milcom.blogspot.com/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

Anti-select, anti-keyboard shortcuts, anti-context menu

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select.
