### ISSUE TITLE
frkmusic.cc

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3361]
### Basic Information

**Test link:** `https://www.frkmusic.cc/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.194

**Comment by okiehsch** [comment]
Fixed.
