### ISSUE TITLE
thecourier.com.au

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3362]
### Basic Information

**Test link:** `https://www.thecourier.com.au/story/6690211/school-holidays-extended-for-covid-19-preparations/`
**Category:** breakage
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

Article doesn't fully load with adblocker enabled

**Comment by okiehsch** [comment]
Fixd.

**Comment by llacb47** [comment]
Instead of whitelisting scripts, how about this:

```
examiner.com.au,theadvocate.com.au,thecourier.com.au##.subscriber-hider:style(display:inherit!important)
examiner.com.au,theadvocate.com.au,thecourier.com.au##.subscribe-truncate:before:style(background:none!important)
examiner.com.au,theadvocate.com.au,thecourier.com.au##.subscribe-truncate:style(order:0!important;max-height:inherit!important)
```

**Comment by llacb47** [comment]
@okiehsch ?

**Comment by okiehsch** [comment]
Done.
