### ISSUE TITLE
boundingintocomics.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3375]
### Basic Information

**Test link:** `https://boundingintocomics.com/2020/03/21/michael-shannon-talks-supergirl-and-if-he-would-reprise-his-role-as-general-zod/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.69 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

`boundingintocomics.com##.widget_custom_html:has([id^="zergnet-widget-"])`

**Comment by jspenguin2017** [comment]
Ads placeholders.
