### ISSUE TITLE
nypost.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3385]
### Basic Information

**Test link:** `https://nypost.com/2020/03/19/sales-of-fish-tank-additive-skyrocket-after-studies-say-it-could-treat-coronavirus/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

blank spaces

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
Placeholders:
```
nypost.com##.widget_nypost_dfp_ad_widget
nypost.com##.widget_text.module:has(a[href*="?utm_source=nypost"])
nypost.com##.ob-widget-items-container:not(:has(a[href*="nypost.com"])):not(:has(a[href*="traffic.outbrain.com"]))
```
