### ISSUE TITLE
fuwaostnime.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3388]
### Basic Information

**Test link:** `https://fuwaostnime.com/manami-numakura-minna-de-best-album/`
**Category:** anti-adblock
**Reported from:** Philippines
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Defender Pro 15.0.0.194

**Comment by okiehsch** [comment]
Fixed.
