### ISSUE TITLE
amd.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#339]
### Basic Information

**Test link:** `http://www.amd.com/report`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
**Extension:** Nano Defender 15.0.0.72

### Additional Message

Redirecting to page doesn't work.

**Comment by okiehsch** [comment]
Fixed.
