### ISSUE TITLE
moodesu.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3392]
### Basic Information

**Test link:** `https://moodesu.com/series/eizouken-ni-wa-te-wo-dasu-na-sub-indo/`
**Category:** other
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.195

### Additional Message

anti copy paste

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click.
