### ISSUE TITLE
corriere.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3393]
### Basic Information

**Test link:** `https://www.corriere.it/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Raspbian Chromium/78.0.3904.108 Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.195

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.corriere.it/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.69 Safari/537.36
**Extension:** Nano Defender 15.0.0.195

### Additional Message

www.corriere.it##.is--active.bck-adblock
+
manually removing html class has--adblock after loading

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.corriere.it/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.69 Safari/537.36
**Extension:** Nano Defender 15.0.0.195

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.corriere.it/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.195

### Additional Message

Anti Adblock detects Ublock Origin

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.corriere.it/`
**Category:** anti-adblock
**Reported from:** Unknown
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.195

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.corriere.it/index.shtml`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Defender Pro 15.0.0.194

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.corriere.it/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.195

### Additional Message

No action detected

**Comment by llacb47** [comment]
![image](https://user-images.githubusercontent.com/16567977/77582278-8653db80-6eb5-11ea-8985-23da2c85a72c.png)


Not fixed in regional lists

`||corriereobjects.it/rcs_anti-adblocker/*`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/af7d939a5077b3746d3628275df36e9273582b24
https://github.com/uBlockOrigin/uAssets/commit/03dd9eb389ba3bfa984e88e6f2ce62594f2bbe8b

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.corriere.it/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.195

### Additional Message

Anti Ad-block popup
