### ISSUE TITLE
dramacute.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3398]
### Basic Information

**Test link:** `https://dramacute.org/nonton-find-me-in-your-memory-2020-subtitle-indonesia/`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.195

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select, anti-right-click.

**Comment by JobcenterTycoon** [comment]
`dramacute.xyz` anti select and anti right click
