### ISSUE TITLE
steamplay.me

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3399]
### Basic Information

**Test link:** `https://steamplay.me/y0jt038zd90b`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 12871.48.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.72 Safari/537.36
**Extension:** Nano Defender 15.0.0.195

### Additional Message

huge blank adspace above the captcha that loads video

**Comment by okiehsch** [comment]
Fixed.
