### ISSUE TITLE
bostoncommons.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3401]
### Basic Information

**Test link:** `https://bostoncommons.net/`
**Category:** anti-adblock
**Reported from:** Europe (Opera Mini Proxy)
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36 OPR/67.0.3575.97
**Extension:** Nano Adblocker 1.0.0.141

**Comment by okiehsch** [comment]
Fixed.
