### ISSUE TITLE
tomshardware.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3402]
### Basic Information

**Test link:** `https://www.tomshardware.com/cc.html`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender for Firefox 15.0.0.194

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.tomshardware.com/cc.html`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender for Firefox 15.0.0.196

### Additional Message

**Comment by DandelionSprout** [comment]
My perception is that `https://www.tomshardware.com/cc.html` is for the warning page itself. I can't seem to reproduce the warning on any other pages.

**Comment by angelsl** [comment]
Seems to be back again.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.tomshardware.com/cc.html`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
**Extension:** Nano Defender for Firefox 15.0.0.199

### Additional Message

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock, ads placeholders fixed.
