### ISSUE TITLE
jemerik.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3404]
### Basic Information

**Test link:** `https://www.jemerik.com/2020/03/cara-mencopot-kaca-film.html`
**Category:** breakage
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.195

### Additional Message

`https://www.jemerik.com/2020/03/cara-mencopot-kaca-film.html?safe=252e605701fd268a89915952e995a307b516aa5c3935e6b8e609dff4697c8935977c33c3a564c7aeb0c44752fbbd66c5487392e89575d047761068b095690a82b926dda979a256e4422fb5bbdfd491db955a564886aa0deedbca92f8c1887cd3b8b1cc2e9e6cbd5eb728e9fba3100f9210eb9c76ab94a7e971e79536c7e2f8f16f97283f1210d28b42da1ebc2ff434aa17e31ba66e1ad92c`

badrule blocking generate link

**Comment by okiehsch** [comment]
Fixed.
