### ISSUE TITLE
marketbeat.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3409]
### Basic Information

**Test link:** `https://www.marketbeat.com/stocks/NYSEARCA/SPY/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
**Extension:** Nano Defender for Firefox 15.0.0.194

### Additional Message

Ad below page header

`The Top Three 5G Stocks to Buy Right Now (Ad)`
`FREE Report: This new tech will be more impactful than the steam engine, electricity and the internet. Click here to get the names of 3 stocks that are URGENT buys.`

**Comment by llacb47** [comment]
`marketbeat.com##[id*="pnlAd"]` also at midpage and footer

Also modal on page load:
![image](https://user-images.githubusercontent.com/16567977/77711386-36edd800-6fa7-11ea-8bc4-c6b703c97030.png)
and modal on mouseout:
![image](https://user-images.githubusercontent.com/16567977/77712343-df9d3700-6fa9-11ea-8687-c9be4c651e60.png)
```
||marketbeat.com/Scripts/lowerrightad.js
||marketbeat.com/scripts/modal/*
marketbeat.com##+js(aeld, mouseleave, NativeDisplayAdID)
```

**Comment by yourduskquibbles** [comment]
Added some cosmetic filters to cleanup - should be fixed now

**Comment by jspenguin2017** [comment]
Why is this annoyance? It says ad on the modal.

**Comment by yourduskquibbles** [comment]
Updated the filter list location
