### ISSUE TITLE
ethikuma.link

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#341]
### Basic Information

**Test link:** `https://ethikuma.link/?ip=adf97e85e958651139b54f732751500e&pbk3=c0cfcc3402a361d622aa167e51de612a6625352544890409074&r=%2Foc%2Fhan&co=1&rf=1&zoneid=1856430&xref=Ym1vdmllcy5jbG91ZA&fs=0&cf=0&sw=2560&sh=1440&sah=1400&wx=-7&wy=-7&ww=2575&wh=1415&cw=2543&wiw=2560&wih=1327&wfc=5&pl=https%3A%2F%2Fbmovies.cloud%2Ffilm%2Frobozuna-season-1-26726%2Fwatching.html%3Fep%3D3875171v2&drf=&np=0&pt=0&nb=1&ng=1&ix=0&nw=1`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
**Extension:** Nano Defender 15.0.0.72

**Comment by okiehsch** [comment]
Fixed. I would suggest to change the title to "bmovies.cloud".

**Comment by jspenguin2017** [comment]
The title and opening post should be machine-friendly. In case we want to build a parser for some reason, we won't have to deal with the inconsistency. 

Manual search will look into comments as well, so it shouldn't be a problem.
