### ISSUE TITLE
poring.world

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3410]
### Basic Information

**Test link:** `https://poring.world/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.195

### Additional Message

i cant acess this site, something is blocking it

**Comment by jspenguin2017** [comment]
Has some ads placeholders but the website works fine for me.

**Comment by llacb47** [comment]
`poring.world##div.jss187:has(ins.adsbygoogle)`
