### ISSUE TITLE
marketwatch.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3417]
### Basic Information

**Test link:** `https://www.marketwatch.com/story/president-trump-criticizes-gm-in-series-of-tweets-over-speed-of-ventilator-production-2020-03-27?mod=autos`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.141

### Additional Message

Sponsored "compare bank accounts" under article

`marketwatch.com##.sa-captivate-box`

**Comment by yourduskquibbles** [comment]
@ryanbr This can be fixed in EasyList? Filters below.

`marketwatch.com##.sa-captivate-box`
`||myfinance.com^$domain=marketwatch.com`
`||smartasset.com^$domain=marketwatch.com`
