### ISSUE TITLE
get-url.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3418]
### Basic Information

**Test link:** `http://get-url.com/download.php?url=NAZs2f3JVOYsEQ8+d1PxKJVSJ0AxhJ6fqihJW5R3wf6DXWea7JPZUy0aPuhaCmGi6pxBEG19wvo1VlZY8F4mgmOaVmq1SaDHD/3O00yd1QqDdQP3063tkTC5Guik7wLTEQmIvoxZ981pP2u1LJCZs/WI4jEW0NTZOwoiWM0m3kfvCtzNhmGFeV9Ls/ua2DP/PBnERVV8HMj1GooT4bxgnB33yiRgLuDuTHvVCyf5SWIHeQil0aPP/Tkixs1Lp1iH3ncGtospVyuYk9VUostwWrJW7H0mePhE0IAs7sUBJ7NoM4o2x1GID2B12ijpdbrHl6ZpXOaKp1yFGeunj0+L4oWMQWQh1tVG1+T8031uElC8EVVNzfDDSp3UzNv8vophvdTIJw3tEw/54fjf4zb1hkrd88wpnyW/NYmKES8zJh83eqx7X7oYVbeNHOg4ISLS`
**Category:** anti-adblock
**Reported from:** Uruguay
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.141

**Comment by llacb47** [comment]
`get-url.com##+js(aopw, phabdba)`

The timer can be boosted on lookalike site `bluemediafiles.com`: 
```
bluemediafiles.com##+js(nano-stb, , 990)
bluemediafiles.com##.item:has(svg)
```
Test URL: click any of the download links at `https://igg-games.com/oneiros-free-download.html`

**Comment by okiehsch** [comment]
Fixed.
