### ISSUE TITLE
auslogics.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3419]
### Basic Information

**Test link:** `https://www.auslogics.com/en/articles/fix-ntoskrnl-exe-bsod/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.196

**Comment by okiehsch** [comment]
Fixed in annoyances.
