### ISSUE TITLE
onbatch.my.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3428]
### Basic Information

**Test link:** `https://www.onbatch.my.id/`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.196

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/73789b24ecd14b98c17678a68853f4e89a07257a
