### ISSUE TITLE
stealive.club

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#343]
### Basic Information

**Test link:** `https://www.stealive.club/download2.php`
**Category:** ads
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
**Extension:** Nano Defender 15.0.0.74

**Comment by jspenguin2017** [comment]
@ryanbr FYI. 
```
stealive.club##.linktl_flashad_reset.linktl_flashad_wrap
```

**Comment by jspenguin2017** [comment]
@okiehsch @ryanbr FYI. 
```
stealive.club##.linktl_flashad_reset.linktl_flashad_wrap
```

**Comment by jspenguin2017** [comment]
@okiehsch
Full screen overlay with timer, but only show up once. Not sure if you want to fix this in uAssets...

**Comment by okiehsch** [comment]
Fixed, closing the overlay results in a popup, so it should be fixed in `uBO-filters`.
