### ISSUE TITLE
nhungvithuoc.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3436]
### Basic Information

**Test link:** `https://nhungvithuoc.xyz/link/fc93cf2?v=e5bc74`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.196

### Additional Message

It requires that you disable adblock to proceed to the download page. Originally from `https://yifyhdtorrent.net/movie/4551-trancers-ii-1991`

**Comment by okiehsch** [comment]
Fixed.
