### ISSUE TITLE
dood.watch

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3437]
### Basic Information

**Test link:** `https://dood.watch/d/aqk4vrexlnuc`
**Category:** ads
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 7.1.2; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0
**Extension:** Nano Defender for Firefox 15.0.0.196

### Additional Message

Popup ads

**Comment by okiehsch** [comment]
Fixed.
