### ISSUE TITLE
sledujserialy.to

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#344]
### Basic Information

**Test link:** `https://sledujserialy.to/episode/friends-s04e03#2629`
**Category:** anti-adblock
**Reported from:** Czechia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
**Extension:** Nano Defender 15.0.0.74

### Additional Message

every site with a TV show drops you the "Turn off AdBlock for page to work correctly", eg `https://sledujserialy.to/episode/friends-s04e03#2629`
I tried to install just NanoDefender, that lets you to videos but displays a lot of ads and various pop-ups, which is of course not ideal.

if you can fix it, i would be eternally glad.

Wishing you a nice day
Jakub

**Comment by jspenguin2017** [comment]
Maybe requires account, otherwise cannot reproduce.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://sledujserialy.to/episode/osklivka-betty-s04e20`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.64 Safari/537.36
**Extension:** Nano Defender 15.0.0.87

### Additional Message

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Added, thanks.
