### ISSUE TITLE
promotecode.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3445]
### Basic Information

**Test link:** `http://promotecode.xyz/travel/92e683`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.141

**Comment by llacb47** [comment]
```
promotecode.xyz##+js(aeld, DOMContentLoaded, blocked)
promotecode.xyz##+js(nano-sib, countdown)
```

**Comment by okiehsch** [comment]
Fixed.
