### ISSUE TITLE
notiziemusica.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3446]
### Basic Information

**Test link:** `https://notiziemusica.it/che-cose-la-musica-in-8d/news/?refresh_ce`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Defender for Firefox 15.0.0.196

**Comment by okiehsch** [comment]
Fixed.
