### ISSUE TITLE
loudersound.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3447]
### Basic Information

**Test link:** `https://www.loudersound.com/news/the-hu-release-new-version-of-yuve-yuve-yu-with-english-vocal-from-danny-case`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.196

**Comment by okiehsch** [comment]
Fixed in annoyances.
