### ISSUE TITLE
downdetector.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3448]
### Basic Information

**Test link:** `https://downdetector.pl/status/facebook-messenger/`
**Category:** other
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Adblocker 1.0.0.141

### Additional Message

breakage Disqus comments by `EasyPrivacy` - badfilter:

`||ziffdavis.com^$3p`

and `EasyList` generic network filter:

`/adscript.`

```
@@||downdetector.com/*/javascript/adscript.js$script
@@/sitenotice/*.js$script,domain=allestoringen.be|allestoringen.nl|allestörungen.at|allestörungen.ch|allestörungen.de|downdetector.ae|downdetector.ca|downdetector.c|downdetector.co.nz|downdetector.co.uk|downdetector.co.za|downdetector.com.ar|downdetector.com.au|downdetector.com.br|downdetector.com.co|downdetector.com|downdetector.cz|downdetector.dk|downdetector.ec|downdetector.es|downdetector.fi|downdetector.fr|downdetector.gr|downdetector.hk|downdetector.hr|downdetector.hu|downdetector.id|downdetector.ie|downdetector.in|downdetector.it|downdetector.jp|downdetector.mx|downdetector.my|downdetector.no|downdetector.pe|downdetector.pk|downdetector.pl|downdetector.pt|downdetector.ro|downdetector.ru|downdetector.se|downdetector.sg|downdetector.sk|downdetector.web.tr
```

---

Reproduce:

Need European `IP`/`Proxy`/`VPN`.

---

related language pages, may also broken...:

```
domain=allestoringen.be|allestoringen.nl|allestörungen.at|allestörungen.ch|allestörungen.de|downdetector.ae|downdetector.ca|downdetector.c|downdetector.co.nz|downdetector.co.uk|downdetector.co.za|downdetector.com.ar|downdetector.com.au|downdetector.com.br|downdetector.com.co|downdetector.com|downdetector.cz|downdetector.dk|downdetector.ec|downdetector.es|downdetector.fi|downdetector.fr|downdetector.gr|downdetector.hk|downdetector.hr|downdetector.hu|downdetector.id|downdetector.ie|downdetector.in|downdetector.it|downdetector.jp|downdetector.mx|downdetector.my|downdetector.no|downdetector.pe|downdetector.pk|downdetector.pl|downdetector.pt|downdetector.ro|downdetector.ru|downdetector.se|downdetector.sg|downdetector.sk|downdetector.web.tr
```

**Comment by jspenguin2017** [comment]
@okiehsch Breakage on default setup.

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
@okiehsch This seems to affect all 44 domains. Also are you sure you want to pin the `468f75ae9c61daf` hash?

**Comment by okiehsch** [comment]
> Also are you sure you want to pin the 468f75ae9c61daf hash?

What do you mean?

**Comment by jspenguin2017** [comment]
I mean in your commit the filter matches `468f75ae9c61daf`, unsure if that's intended.

**Comment by okiehsch** [comment]
I still don' understand what is `468f75ae9c61daf`?
I certainly did not intentionally match "it",
I have updated my commit.

**Comment by jspenguin2017** [comment]
I meant this: 
![image](https://user-images.githubusercontent.com/7283682/78846220-4ff38180-79c8-11ea-8996-81be9ba49a3f.png)

**Comment by okiehsch** [comment]
Oh boy, sorry for my brain fart. No that was not intentional and thanks for the heads up.
