### ISSUE TITLE
thelayoff.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3456]
### Basic Information

**Test link:** `https://www.thelayoff.com/u-s-bancorp`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.196

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/9589b504d5b78336943ea395671096c028a21a53
