### ISSUE TITLE
photorecon.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3469]
### Basic Information

**Test link:** `http://photorecon.net/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.141

### Additional Message

anti hotkey, anti select

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/649cf21ed8b85285128d43a547a9028ebc63c4eb

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select.
