### ISSUE TITLE
thesukan.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3471]
### Basic Information

**Test link:** `https://thesukan.net/`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Defender for Firefox 15.0.0.196

**Comment by okiehsch** [comment]
Fixed.
