### ISSUE TITLE
full-anime.fr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3472]
### Basic Information

**Test link:** `https://www.full-anime.fr/fullmetal-alchemist-film-1-vostfr/`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36
**Extension:** Nano Defender 15.0.0.196

**Comment by okiehsch** [comment]
Fixed in annoyances.
