### ISSUE TITLE
vz.lt

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3477]
### Basic Information

**Test link:** `https://www.vz.lt/verslo-aplinka/2020/04/03/europoje-koronaviruso-pandemijos-auku-skaicius-virsijo-40000`
**Category:** anti-adblock
**Reported from:** Republic of Lithuania
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.196

### Additional Message

Still showing screen for detected ad-blocker. This is lithuanian news business news site.

**Comment by okiehsch** [comment]
Fixed.
