### ISSUE TITLE
tenforums.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3479]
### Basic Information

**Test link:** `https://www.tenforums.com/general-support/153554-recycle-bin-content-search-results.html`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.141

### Additional Message

`tenforums.com##.chill`

**Comment by llacb47** [comment]
Placeholder.
![image](https://user-images.githubusercontent.com/16567977/78413904-91121d00-75e7-11ea-8468-807b13d02eb8.png)

**Comment by krystian3w** [comment]
`###posts > .media400`

`https://www.sevenforums.com/installation-setup/415754-update-your-win-7-installation-media.html`

**Comment by jspenguin2017** [comment]
@krystian3w Can't reproduce.

**Comment by llacb47** [comment]
@jspenguin2017 it's a placeholder.
![image](https://user-images.githubusercontent.com/16567977/78504102-e14cc480-7738-11ea-8562-22ce99feaea6.png)

**Comment by jspenguin2017** [comment]
Fixed.
