### ISSUE TITLE
daytonflash.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3480]
### Basic Information

**Test link:** `http://daytonflash.com/trumps-poll-numbers-rising-despite-intense-criticism-of-coronavirus-handling/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.141

### Additional Message

Anti-select, anti-hotkey, anti-view source

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select, anti-right-click.
