### ISSUE TITLE
techrepublic.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3481]
### Basic Information

**Test link:** `https://www.techrepublic.com/article/transgender-employees-in-tech-why-this-progressive-industry-has-more-work-to-do-to-achieve-true-gender-inclusivity/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.141

### Additional Message

bunch of download buttons for sponsored content

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.techrepublic.com/article/how-to-use-snapshots-in-virtualbox/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.196

### Additional Message

`techrepublic.com##.content > div:has(:scope > .sharethrough-article)`

**Comment by jspenguin2017** [comment]
Unsure if those recommended content should be considered to be ads. Closing for now.
