### ISSUE TITLE
paginadanoticia.com.br

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3494]
### Basic Information

**Test link:** `https://paginadanoticia.com.br/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Defender 15.0.0.196

### Additional Message

Original URL: `https://paginadanoticia.com.br/noticia/2180/jovem-assassinado-a-tiros-em-santo-estevao.html?fbclid=IwAR1ZWZyCv-eccGsCbonz9Tq73wi4UOdbkVxcoziAFffwPT5C_vD2aDL0DMA`

**Comment by okiehsch** [comment]
Fixed.
