### ISSUE TITLE
prepostseo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3502]
### Basic Information

**Test link:** `https://www.prepostseo.com/es/reverse-image-search`
**Category:** anti-adblock
**Reported from:** Argentina
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.141

**Comment by okiehsch** [comment]
Fixed.
