### ISSUE TITLE
sevenforums.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3503]
### Basic Information

**Test link:** `https://www.sevenforums.com/installation-setup/415754-update-your-win-7-installation-media.html`
**Category:** other
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
**Extension:** Nano Adblocker 1.0.0.141

### Additional Message

> https://github.com/NanoMeow/QuickReports/issues/3479#issuecomment-609434141

**Comment by jspenguin2017** [comment]
https://github.com/NanoAdblockerLab/NanoContrib/commit/b8646ee14eed4fbd2d6657070139001b332e300b
