### ISSUE TITLE
m.uber.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3505]
### Basic Information

**Test link:** `https://m.uber.com/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.196

### Additional Message

page does not open

**Comment by mapx-** [comment]
needing
`@@||cdn-net.com/cc.js$script,domain=uber.com`
just to log in

**Comment by mapx-** [comment]
@ryanbr
