### ISSUE TITLE
tr.link

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3510]
### Basic Information

**Test link:** `https://tr.link/1X9j4`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Defender 15.0.0.196

**Comment by okiehsch** [comment]
Already fixed earlier today.
https://github.com/uBlockOrigin/uAssets/commit/607a30c9ee8bb90122354842528e09461e5b2402
