### ISSUE TITLE
javmec.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3511]
### Basic Information

**Test link:** `https://www.javmec.com/movie/10mu-100418-01.html`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Defender Pro 15.0.0.196

### Additional Message

Video player stops after few seconds INFO:  "Please turn off adblockers in order to continue watching by JAVMEC"

**Comment by okiehsch** [comment]
Fixed.
