### ISSUE TITLE
realclearpolitics.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3514]
### Basic Information

**Test link:** `https://www.realclearpolitics.com/articles/2020/04/06/an_advantaged_disease_indeed_142867.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.realclearpolitics.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.realclearpolitics.com/epolls/other/president_trump_job_approval-6179.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

It only seems to find the adblocker on secondary pages rather than the home page.

**Comment by DandelionSprout** [comment]
Placeholder at `https://www.realclearpolitics.com/articles/2020/04/15/how_china_delayed_warnings_to_public_during_6_key_days_in_january_142952.html`: `realclearpolitics.com##.init.widget_slot:not(.loaded)`
