### ISSUE TITLE
awsubs.co

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3516]
### Basic Information

**Test link:** `https://awsubs.co/psycho-pass-3-first-inspector-episode-1-subtitle-indonesia/`
**Category:** ads
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

**Comment by okiehsch** [comment]
The visible ads are already blocked by the regional list.
