### ISSUE TITLE
busyfinance.site

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3519]
### Basic Information

**Test link:** `https://www.busyfinance.site/2020/04/modern-financial-advising-for-beginners.html?safe=d66cc53a3e1397c5488a05c572ae5b0f2c612a9c9697b355a7c8bbe05e73df39fdbc252dcf5530f8e32b1d884ddaea4ba1adb55eba0811ed33f1333d19d5820516b7fa4a06c9c90ecd386a719555bd7b5adbc03610d2de75f74a66593462f67af55f165c8a090584`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

**Comment by llacb47** [comment]
Test also: `http://www.behealth-id.xyz/2020/03/tips-for-healthy-living-and-weight-loss.html?kareeI=d66cc53a3e1397c5488a05c572ae5b0f2c612a9c9697b355a7c8bbe05e73df39fdbc252dcf5530f8e32b1d884ddaea4ba1adb55eba0811ed33f1333d19d5820516b7fa4a06c9c90ecd386a719555bd7b5adbc03610d2de75f74a66593462f67af55f165c8a090584`


```
! anti-adblock
busyfinance.site,behealth-id.xyz##+js(nostif, offsetLeft)
! debugger trap
busyfinance.site,behealth-id.xyz##+js(set, config.pauseInspect, false)
! popup on continue button
behealth-id.xyz##+js(set, config_baru.showPOPUP, false)
! boost timer
behealth-id.xyz##+js(nano-sib)
```

**Comment by okiehsch** [comment]
Fixed.

**Comment by okiehsch** [comment]
@llacb47 would you be interested in gaining write access to `uAssets`?

**Comment by llacb47** [comment]
Maybe, but you guys already do a pretty good job at listening to what I have to offer, so I'm not sure if it's needed.

**Comment by okiehsch** [comment]
> Maybe .....  I'm not sure if it's needed.

It's up to you, you clearly know the syntax and your proposed filters work well, so it would make it easier if you don't have to post suggestions and could commit yourself in my opinion.
