### ISSUE TITLE
ani.gamer.com.tw

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#352]
### Basic Information

**Test link:** `https://ani.gamer.com.tw/animeVideo.php?sn=10917`
**Category:** anti-adblock
**Reported from:** Taiwan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
**Extension:** Nano Defender 15.0.0.75

**Comment by ZaphodBeebblebrox** [comment]
Annoyance, fixed in regional lists.

**Comment by jspenguin2017** [comment]
Fixed in Chinese regional filter.

**Comment by jspenguin2017** [comment]
Legacy rule to remove? https://github.com/uBlockOrigin/uAssets/issues/245
![image](https://user-images.githubusercontent.com/7283682/48982459-17d3f300-f0a0-11e8-9390-f822e0aa12ef.png)

**Comment by jspenguin2017** [comment]
Preroll ads fixed in Nano Defender. https://github.com/jspenguin2017/uBlockProtector/pull/1045
