### ISSUE TITLE
thejobsmovie.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3527]
### Basic Information

**Test link:** `https://www.thejobsmovie.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Defender for Firefox 15.0.0.197

**Comment by llacb47** [comment]
`thejobsmovie.com##+js(nostif, adsBlocked)`

**Comment by okiehsch** [comment]
Fixed.
