### ISSUE TITLE
titsbox.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#353]
### Basic Information

**Test link:** `https://titsbox.com/`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
**Extension:** Nano Defender 15.0.0.75

### Additional Message

Cannot play any video.

**Comment by jspenguin2017** [comment]
@okiehsch Video not clickable.

**Comment by okiehsch** [comment]
Fixed.
