### ISSUE TITLE
poisekai.site

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3532]
### Basic Information

**Test link:** `https://www.poisekai.site/2020/04/12.html`
**Category:** other
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

anti copy paste

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-hotkey.
