### ISSUE TITLE
snowbeartranslation.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3533]
### Basic Information

**Test link:** `https://snowbeartranslation.com/`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

adblock detected

**Comment by okiehsch** [comment]
Fixed + anti-select/right-click.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select.

**Comment by JobcenterTycoon** [comment]
F12 is disabled too
