### ISSUE TITLE
signup.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3534]
### Basic Information

**Test link:** `https://signup.com/Dashboard#/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.141

**Comment by jspenguin2017** [comment]
Ads placeholders. Also in reservation page. Requires account.
