### ISSUE TITLE
web-capture.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3547]
### Basic Information

**Test link:** `https://web-capture.net/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

**Comment by krystian3w** [comment]
Annoyance (no block fuctions on site) - should copied to `Nano Defender Integration` / `Nano Base`.

**Comment by krystian3w** [comment]
```
! https://github.com/uBlockOrigin/uAssets/issues/6892
! https://github.com/uBlockOrigin/uAssets/issues/6893
snapito.com,web-capture.net##+js(acis, document.getElementById, test-block)
web-capture.net###stw_ad
```

**Comment by jspenguin2017** [comment]
Can't reproduce issue with `snapito.com`.
