### ISSUE TITLE
aibouanime.site

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3551]
### Basic Information

**Test link:** `https://www.aibouanime.site/`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

**Comment by jspenguin2017** [comment]
See: https://github.com/NanoMeow/QuickReports/issues/3551
