### ISSUE TITLE
download.pixelexperience.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3557]
### Basic Information

**Test link:** `https://download.pixelexperience.org/changelog/tissot/PixelExperience_tissot-10.0-20200407-1119-OFFICIAL.zip`
**Category:** breakage
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

**Comment by llacb47** [comment]
Broken if `https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js` is blocked

`@@||cdnjs.cloudflare.com/ajax/libs/cookieconsent2/*/cookieconsent.$domain=download.pixelexperience.org`

**Comment by jspenguin2017** [comment]
Can't reproduce breakage on default settings.
