### ISSUE TITLE
besttechinfo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#356]
### Basic Information

**Test link:** `https://besttechinfo.com/unlock-iphone/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
**Extension:** Nano Defender 15.0.0.75

**Comment by okiehsch** [comment]
Fixed.
