### ISSUE TITLE
marketplace.visualstudio.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3560]
### Basic Information

**Test link:** `https://marketplace.visualstudio.com/items?itemName=adguard.adblock`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

logo blocked by mistake

**Comment by llacb47** [comment]
https://github.com/easylist/easylist/commit/eee3ad71cc55b23b76b35b229557833e70c6cf0e
