### ISSUE TITLE
therealdeal.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3561]
### Basic Information

**Test link:** `https://therealdeal.com/2020/04/12/urbanites-are-fleeing-to-rural-communities-out-west/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

Original URL: `https://therealdeal.com/`

"Anti-flicker snippet" causes page to be invisible for four seconds - annoyance
`https://support.google.com/optimize/answer/7100284?hl=en`

```
<style>.async-hide { opacity: 0 !important}</style>
<script>if(navigator.onLine){(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};(a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;})(window,document.documentElement,'async-hide','dataLayer',4000,{'GTM-K694XL6':true});}</script>
```

nostif and acis don't work because the script is loaded too early

fix: `therealdeal.com##.async-hide:style(opacity:1!important)`

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://therealdeal.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

click on video at midpage

**Comment by okiehsch** [comment]
Fixed both reports. One in annoyances.
