### ISSUE TITLE
suzylu.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3567]
### Basic Information

**Test link:** `https://www.suzylu.co.uk/anime-reactions/naruto-shippuden/1`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 Edg/80.0.361.111
**Extension:** Nano Defender Pro 15.0.0.197

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.suzylu.co.uk/anime-reactions/sword-art-online-2/16`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

anti-contextmenu on player

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click.
