### ISSUE TITLE
loudersound.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3572]
### Basic Information

**Test link:** `https://www.loudersound.com/news/nektar-make-live-from-the-wildey-theatre-concert-available-to-fans`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

newsletter signup box broken

**Comment by jspenguin2017** [comment]
https://github.com/easylist/easylist/commit/5d64d3990dc4a2857c2229442568a559f4ab2c29
