### ISSUE TITLE
creativebloq.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3573]
### Basic Information

**Test link:** `https://www.creativebloq.com/infographic/diagram-reveals-design-limitations-41619830`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

newsletter signup box broken

**Comment by jspenguin2017** [comment]
https://github.com/easylist/easylist/commit/66bc3c3ba87590ccdb5cedb06a83fbdddb6c24cc
