### ISSUE TITLE
aldiblogger.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3574]
### Basic Information

**Test link:** `http://aldiblogger.com/oP9ZvgfZ`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 5.1.1; A37f) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

Fake button

**Comment by okiehsch** [comment]
Fixed + popup.
