### ISSUE TITLE
videosection.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3577]
### Basic Information

**Test link:** `https://videosection.com/video/51660948`
**Category:** ads
**Reported from:** South Korea
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
**Extension:** Nano Defender for Firefox 15.0.0.197

### Additional Message

Original URL: `moz-extension://8447c35a-4bf2-49e0-9da4-f872fe63e496/document-blocked.html?details=%7B%22url%22%3A%22https%3A%2F%2Fsyndication.exosrv.com%2Fsplash.php%3Fcat%3D%26idzone%3D3622433%26type%3D8%26p%3Dhttps%253A%252F%252Fvideosection.com%252Fvideo%252F121074942%253Futm_source%253Dhdporn%2526utm_medium%253Dclick%2526utm_campaign%253Dhdporn%26sub%3D%26block%3D1%26el%3D%26tags%3D%26scr_info%3DaW5saW5lfHBvcE1hZ2ljfDEuMC4w%22%2C%22hn%22%3A%22syndication.exosrv.com%22%2C%22dn%22%3A%22exosrv.com%22%2C%22fs%22%3A%22%7C%7Csyndication.exosrv.com%5E%24document%22%7D`

popup

**Comment by okiehsch** [comment]
Fixed. NSFW.
