### ISSUE TITLE
mitelcel.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3580]
### Basic Information

**Test link:** `https://www.mitelcel.com/mitelcel/login`
**Category:** breakage
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
**Extension:** Nano Defender for Firefox 15.0.0.197

### Additional Message

doesnt show user&password fields

**Comment by okiehsch** [comment]
Fixed.
