### ISSUE TITLE
riie.jp

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3589]
### Basic Information

**Test link:** `https://riie.jp/episode/bokutachi-wa-benkyou-ga-dekinai-ova-episode-002/`
**Category:** other
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

anti select

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select.
