### ISSUE TITLE
uhuseries.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3591]
### Basic Information

**Test link:** `https://uhuseries.com/young-blood-ep1/`
**Category:** breakage
**Reported from:** Thailand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

**Comment by okiehsch** [comment]
Nothing is broken except the sanity of whoever thinks that packing a site to the brim witht blinking ads is a good idea.
Fixed popups and the aforementioned ads.
