### ISSUE TITLE
dropgalaxy.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3606]
### Basic Information

**Test link:** `https://dropgalaxy.com/720-munirka-building-demolition-removal-of-debris-to-take-at-least-a-week-say-civic-officials.html`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; arm_64; Android 9; CPH1823) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 YaBrowser/19.12.2.142.00 (beta) Mobile Safari/537.36
**Extension:** Nano Defender Pro 15.0.0.197

### Additional Message

`https://dropgalaxy.in/3w80q0zbz8uj`

**Comment by okiehsch** [comment]
Fixed.
