### ISSUE TITLE
box-series.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3607]
### Basic Information

**Test link:** `https://box-series.com/play/774gtN9W1P/`
**Category:** ads
**Reported from:** Thailand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

**Comment by llacb47** [comment]
This website is horribly coded and loads all three player options at once. Also, it seems that the preroll complete events do not fire properly and I still have to click a skip button 5+ times.

```
*$media,domain=stream.box-series.com,redirect=noopmp3-0.1s
stream.box-series.com##.overlay
||4x4x2.xyz^$3p
```

**Comment by okiehsch** [comment]
Fixed.
