### ISSUE TITLE
coolsoft.altervista.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3612]
### Basic Information

**Test link:** `https://coolsoft.altervista.org/en/virtualmidisynth`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.14 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

placeholders

**Comment by DandelionSprout** [comment]
Placeholder:
```
! https://coolsoft.altervista.org/en/virtualmidisynth
coolsoft.altervista.org###content-right-floatbox
```
