### ISSUE TITLE
totalcar.hu

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3617]
### Basic Information

**Test link:** `https://totalcar.hu/tv/2020/04/16/opel_vetra_totalcar_teszt_tv_2002/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://totalcar.hu/tesztek/2020/04/22/suzuki_swift_12_mild_hybrid/?fbclid=IwAR1ITG04VchamARV8qVreAwv4fTUUdWbjS4cPCpENH37a3Cbg066qb9JzVE`
**Category:** anti-adblock
**Reported from:** Hungary
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://totalcar.hu/magazin/kozelet/2020/05/04/a_suv_bun_nem/`
**Category:** anti-adblock
**Reported from:** Hungary
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
**Extension:** Nano Defender 15.0.0.201

### Additional Message

**Comment by llacb47** [comment]
`totalcar.hu##+js(acis, fetch, adsbygoogle)`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/46b6f9e2238363129ed024a5f9bf8418574ebaf7

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/46b6f9e2238363129ed024a5f9bf8418574ebaf7
