### ISSUE TITLE
runmods.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3620]
### Basic Information

**Test link:** `https://www.runmods.com/`
**Category:** ads
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a237cc7c5c90b7864e121aa61b625daa4a2d6995

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select.
