### ISSUE TITLE
gal-dem.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3621]
### Basic Information

**Test link:** `https://gal-dem.com/that-is-a-lot-of-shin-ramyun-killing-eve-and-the-safety-of-returning-to-cooking-traditional-food/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

Big pop-up and darkened screen

**Comment by okiehsch** [comment]
Fixed.
