### ISSUE TITLE
adslink.pw

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3626]
### Basic Information

**Test link:** `https://www.adslink.pw/IOGrz`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

**Comment by Yuki2718** [comment]
They must have added new anti-adb:

![adslink](https://user-images.githubusercontent.com/58900598/90241792-b735ac80-de66-11ea-9642-ae85b547e18e.png)

`adslink.pw##+js(aopw, ai_adb)`
works on my Firefox 79 + uBO 1.29 (default)
