### ISSUE TITLE
extremereportbot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3629]
### Basic Information

**Test link:** `https://extremereportbot.com/report/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

type anything in the box and submit

**Comment by okiehsch** [comment]
Fixed. Sticky.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://extremereportbot.com/report/`
**Category:** anti-adblock
**Reported from:** Russia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Defender 15.0.0.198

### Additional Message

**Comment by jspenguin2017** [comment]
Doesn't look too sticky, that was over a month.
