### ISSUE TITLE
radio.securenetsystems.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3635]
### Basic Information

**Test link:** `https://radio.securenetsystems.net/cirrusencore/index.cfm?stationCallSign=WSPC&retry=true&playSessionID=2C2A6720-BF65-3E75-365198EFAA51827F`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
**Extension:** Nano Defender for Firefox 15.0.0.197

### Additional Message

started detecting ad-blocker

**Comment by mapx-** [comment]
link to test: `https://streamdb3web.securenetsystems.net/cirrusencore/index.cfm`

fix => https://github.com/uBlockOrigin/uAssets/commit/f7df38fc465f64be53eb8c5ad73922ba752434c5

**Comment by jspenguin2017** [comment]
Test link: `https://streamdb3web.securenetsystems.net/cirrusencore/index.cfm`

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/f7df38fc465f64be53eb8c5ad73922ba752434c5
