### ISSUE TITLE
kino.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3636]
### Basic Information

**Test link:** `https://www.kino.de/film/10-dinge-die-ich-an-dir-hasse-1998/quiz/bist-du-ein-fan-von-teenie-filmen-wie-viele-filme-hast-du-gesehen-234/?utm_campaign=i-bc398w&utm_medium=fan_organic&utm_source=facebook`
**Category:** breakage
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

Quiz is blocked on this side (also on all other quiz sites from this page)

**Comment by mapx-** [comment]
@ryanbr
