### ISSUE TITLE
day-hoc.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3641]
### Basic Information

**Test link:** `https://day-hoc.org/giao-duc-tich-cuc-giao-duc-dua-tren-diem-manh/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

cursor is still default one over text due to `.unselectable`

placeholder ad in sidebar

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0e5c3c6ff1aec39aaf3800f082e6975bd242053a

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select.
