### ISSUE TITLE
music.paolitravelling.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3642]
### Basic Information

**Test link:** `https://music.paolitravelling.xyz/?p=28040`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

**Comment by okiehsch** [comment]
Fixed.
