### ISSUE TITLE
krunker.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3644]
### Basic Information

**Test link:** `https://krunker.io/social.html?p=market`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

not load

**Comment by okiehsch** [comment]
Site will load now. Needs an account to test properly.
