### ISSUE TITLE
day-hoc.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3645]
### Basic Information

**Test link:** `https://day-hoc.org/giao-duc-tich-cuc-giao-duc-dua-tren-diem-manh/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.24 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

ads space, split from https://github.com/NanoMeow/QuickReports/issues/3641

**Comment by DandelionSprout** [comment]
Seems to have been fixed by `##.td-a-rec` in AdGuard Base.
