### ISSUE TITLE
olimpiadas.uol.com.br

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3647]
### Basic Information

**Test link:** `https://olimpiadas.uol.com.br/noticias/redacao/2016/08/21/com-muito-esporte-na-areia-rio-2016-e-a-1-olimpiada-de-verao-no-inverno.htm`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0
**Extension:** Nano Defender for Firefox 15.0.0.197

**Comment by okiehsch** [comment]
The site appears to be broken, I get the anti adblock message with uBO disabled, the video is broken and some drop down menus don't function either.
