### ISSUE TITLE
streamz.vg

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3655]
### Basic Information

**Test link:** `https://streamz.vg/xcd2e5fa99af5dc0a1de780c8e02c5790`
**Category:** anti-adblock
**Reported from:** Austria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

The site still detects the uBlock origin plugin

(btw, great work you guys are doing, thanks!)

**Comment by llacb47** [comment]
Working link: `https://streamz.cc/fMWswemRyZ256Z2hhVFRU`

anti-adblock and popups

**Comment by mapx-** [comment]
I get no popups, only anti adb in firefox
`streamz.*##+js(nostif, nextFunction, 2000)`

**Comment by ghajini** [comment]
Firefox android
Clear cookies/data and more important change IP

@mapx- @uBlock-user
there is Preroll video ad showing antiadblock shown(issue.streamz.cc/issue.mp4)
Here NSFW

`https://streamz.vg/x2537ca750d6a01a88945bc1ad84faa04`

**Comment by ghajini** [comment]
It doesn't fixed. ...they locked previous URL I posted

Anyway new URL =
`https://streamz.vg/x8e1b0d5ec04942de659a421d706678e5`

**Comment by mapx-** [comment]
already removed (the video), so we'd need the source for these videos
if you have such source just send it here `axis.trivia@gmail.com`

**Comment by uBlock-user** [comment]
@mapx- Homepage itself is a great source

**Comment by ghajini** [comment]
Email sent

**Comment by mapx-** [comment]
got it, thx

**Comment by llacb47** [comment]
@mapx- email is still visible in edit history fyi

**Comment by jspenguin2017** [comment]
@llacb47 Removed.

**Comment by jspenguin2017** [comment]
@llacb47 Removed. Thanks.

**Comment by jspenguin2017** [comment]
Also it seems to work fine for me: 
![image](https://user-images.githubusercontent.com/7283682/80283725-1fedf300-86d7-11ea-84c9-bd166db76ad2.png)

**Comment by llacb47** [comment]
You can find links for this site here: `https://movie4ever.xyz/`

**Comment by jspenguin2017** [comment]
@llacb47 I'm not sure what you're trying to say, can you elaborate? (What is the issue, reproduction steps, etc.)

**Comment by llacb47** [comment]
If there is another anti-adblock issue with this site and the provided links are inadequate, this site's download links include `streamz.vg` links that can be used for testing in the future. Just trying to look ahead
