### ISSUE TITLE
animeindo.fun

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3657]
### Basic Information

**Test link:** `https://animeindo.fun/enen-no-shouboutai-episode-15-subtitle-indonesia/`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

player still contain ads when clicked

**Comment by llacb47** [comment]
no ads for me.

debugger trap.

**Comment by gmarcher** [comment]
no problem here

**Comment by jspenguin2017** [comment]
@okiehsch Sometimes there is a popup when first clicking the player.
