### ISSUE TITLE
opensubtitles.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3663]
### Basic Information

**Test link:** `https://www.opensubtitles.org/en/search/subs`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

placeholder

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.opensubtitles.org/en/login`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 YaBrowser/20.6.0.905 Yowser/2.5 Yptp/1.23 Safari/537.36
**Extension:** Nano Defender 15.0.0.200

### Additional Message

Not working, and site goes blank after the pop up display

**Comment by mapx-** [comment]
fixed anti adb stuff, no blank page on my side
