### ISSUE TITLE
adsrt.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3664]
### Basic Information

**Test link:** `https://adsrt.org/knNIj4`
**Category:** ads
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 10; motorola one power) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

Black video ad banner covering half of the screen

**Comment by krystian3w** [comment]
https://agrd.io/report?

**Comment by krystian3w** [comment]
floating player:

`###vastWrapper:has(#content_video)`

so half on only `motorola one power`
