### ISSUE TITLE
ariva.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3666]
### Basic Information

**Test link:** `https://www.ariva.de/news/dramatische-oelpreis-auswirkungen-deshalb-muessen-infineon-8360384`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.24 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

```
ariva.de##.werb_textlink
ariva.de###iqd_mainAd
```

**Comment by jspenguin2017** [comment]
@okiehsch Ads showing due to `@@||ariva.de^$ghide` in uBlock filters.
