### ISSUE TITLE
comtechies.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#367]
### Basic Information

**Test link:** `https://comtechies.com/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/70.0.3538.77 Chrome/70.0.3538.77 Safari/537.36
**Extension:** Nano Defender 15.0.0.75

**Comment by jspenguin2017** [comment]
@okiehsch Intrusive self-promotion popup and banner ads on the side.

**Comment by okiehsch** [comment]
Fixed.
