### ISSUE TITLE
kissanime.nz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3670]
### Basic Information

**Test link:** `https://kissanime.nz/Anime/kaguya-sama-love-is-war-2nd-season.15762/Episode-003?id=162418&s=hserver`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

**Comment by okiehsch** [comment]
Fixed.
