### ISSUE TITLE
pentruea.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3671]
### Basic Information

**Test link:** `https://pentruea.com/multi-spun-ca-este-cel-mai-bun-tort-din-lume-eu-sunt-de-acord/`
**Category:** anti-adblock
**Reported from:** Czechia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
**Extension:** Nano Defender for Firefox 15.0.0.197

**Comment by mapx-** [comment]
right click, copy https://github.com/uBlockOrigin/uAssets/commit/2475000f9aab477a96f6bf5d769ad3178369a03b

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-hotkey.
