### ISSUE TITLE
europixhd.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3677]
### Basic Information

**Test link:** `https://europixhd.io/watch-online-movie/extraction-2020-online-free-hd-with-subtitles-europix?__cf_chl_jschl_tk__=dccf965971053bdfd70f61d52ec63ca9dcc8bef9-1588001227-0-AYgyCk60BnwcWbqoOkoaXIqrHtvyCPkeGT5_jnNbfN3DaO8qZ_zssfPj4mPs_nB0QStqE0kx7Zexw1WhNOPPPwZHqc55JF8wkCbftfBcU_VYVSsXsLojF0vOsDg7zOFoq33AW9yd60cxm4Tx1XJUCb3_yEJgWA0SVF4Q3ceHpIUD2QB7NECARpEoV9ZWrTjzZcuLbVC7Tos4idubT7M74jCPITCR3eDRqlk4Oqdq-RzthO9XDFZGZdF5Fc5OvImkoJ5EavcPleVtSIz8HGZqBnledOPHhy3sDLErn2jZxhbJqcnv8kJrwAABYI7yRfwGJZzEeY0qk0CFwpyrAx5bCRGj4Q8NtMLv8eUeSe2T2NqmXVP014JQhYuPyifWHu9sKw`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

breakage: search bar cannot be clicked due to `zfgloaded` inline script (i think)

**Comment by okiehsch** [comment]
Fixed.
