### ISSUE TITLE
gilakerja.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3679]
### Basic Information

**Test link:** `https://gilakerja.com/inilah-rahasia-cara-lolos-tes-wawancara-kerja/`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

`https://gilakerja.com/inilah-rahasia-cara-lolos-tes-wawancara-kerja/?link=aHR0cHM6Ly93d3cxNC56aXBweXNoYXJlLmNvbS92L3Jkd3VnaU5SL2ZpbGUuaHRtbA==`

continue link didn't appear

**Comment by mapx-** [comment]
for the link maybe needing another test case

**Comment by jspenguin2017** [comment]
If the fix is not complete, we will eventually receive another report. Closing for now.
