### ISSUE TITLE
getmakerlog.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3684]
### Basic Information

**Test link:** `https://getmakerlog.com/discussions/bhimtebhaisaab-do-you-guys-use-google-analytics-on`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

breakage due to filter `-google-analytics-` in EasyPrivacy.

Cannot reply to thread. Also, cannot navigate away from thread and back to it due to xhr being blocked. (Test by clicking on "Top" in the discussions bar and then click the back button)

Test account:

```
<redacted>
```

Suggested filter: `@@||api.getmakerlog.com/discussions/*$~third-party`

**Comment by jspenguin2017** [comment]
See: https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/54

**Comment by llacb47** [comment]
I made that test account so an easylist member could reproduce the issue easily. It's a throwaway. 

I originally saw the issue reported here: `https://twitter.com/matteing/status/1254147003489095681`

**Comment by jspenguin2017** [comment]
There's also some ads on the right.

**Comment by jspenguin2017** [comment]
@llacb47 Feel free to post the account here or on Slack. All test accounts sent through Quick Issue Reporter will be redacted as per Privacy Policy.

**Comment by jspenguin2017** [comment]
Also, the "Top" button works for me.

**Comment by llacb47** [comment]
Ads: `||intravert.co^$3p`

**Comment by llacb47** [comment]
The account:

Username: `test12345a`
Password: `comeho4619@oriwijn.com`

**Comment by llacb47** [comment]
Video of breakage: `https://streamable.com/flnf6h`

**Comment by llacb47** [comment]
Fixed.
