### ISSUE TITLE
iir.ai

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3690]
### Basic Information

**Test link:** `https://iir.ai/SPl1LA`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

popup on click continue button, popup on click countdown

**Comment by okiehsch** [comment]
Fixed.

**Comment by llacb47** [comment]
Also here: `https://tii.ai/Imzcpn9`
