### ISSUE TITLE
iamcarolinecalloway.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3696]
### Basic Information

**Test link:** `https://www.iamcarolinecalloway.com/#`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

Anti-select, anti-right click, anti-view source

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select, anti-hotkey.

**Comment by llacb47** [comment]
`.unselectable` has style `cursor: default`: annoying
