### ISSUE TITLE
dramaserial.best

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3700]
### Basic Information

**Test link:** `https://dramaserial.best/tv/my-engineer-2020/`
**Category:** ads
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

pre roll ads

**Comment by okiehsch** [comment]
Fixed.

**Comment by llacb47** [comment]
![image](https://user-images.githubusercontent.com/16567977/80554400-02e94680-899b-11ea-9bd4-f3fc13007e1d.png)
there is a popup when you start this sota player.

**Comment by okiehsch** [comment]
Have you enabled the regional indonesian list?
