### ISSUE TITLE
vulture.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3714]
### Basic Information

**Test link:** `https://www.vulture.com/2020/04/harrison-ford-plane-investigation.html`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

click on hyperlink not to vulture.com, it goes to `go.redirectingat.com`

**Comment by THEtomaso** [comment]
@mapx-:

> `vulture.com##+js(aopr, Object.keys)`

This rule breaks embedded images and videos!

**Comment by llacb47** [comment]
> @mapx-:
> 
> > `vulture.com##+js(aopr, Object.keys)`
> 
> This rule breaks embedded images and videos!

Example:

```
https://www.vulture.com/2019/12/every-movie-of-the-2010s-ranked-sort-of.html
https://www.vulture.com/2020/04/homeland-deaths-series-finale.html
```

A rule like that is like grasping at straws, clearly we need a better solution. The problem is the responsible code is in an inline script and loaded through requirejs.

**Comment by llacb47** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Can you give me an example of a redirection after removing the filter?

**Comment by okiehsch** [comment]
At the example link you posted
`https://www.vulture.com/2019/12/every-movie-of-the-2010s-ranked-sort-of.html`
there is a clickable link to `nymag.com` but I do not get redirected after removing `vulture.com##+js(aopr, Object.keys)`

**Comment by okiehsch** [comment]
I found one at `https://www.vulture.com/2020/04/harrison-ford-plane-investigation.html`.
The first clickable link to `gothamist.com`.
`vulture.com##+js(aeld, /^(?:click|mousedown)$/, latest!==)`
works form.
