### ISSUE TITLE
avdelphi.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3715]
### Basic Information

**Test link:** `https://www.avdelphi.com/flight.html?callsign=N96GU&recache=1588279931`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

anti context menu

**Comment by llacb47** [comment]
If you press F12 you get redirected to `https://www.avdelphi.com/privacy.html`.
If you open devtools using browser menu there is a debugger trap.

@mapx- sorry, I didn't notice when reporting.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-hotkey.

**Comment by llacb47** [comment]
Not resolved yet.

**Comment by llacb47** [comment]
```
avdelphi.com##+js(set, f12lock, false)
avdelphi.com##+js(nosiif, debugger)
```

**Comment by jspenguin2017** [comment]
Hum... This site assigned the F12 key to another function instead of simply blocking it. I'm not sure if that would be anti-hotkey.

**Comment by llacb47** [comment]
It redirects it to another page. Seems pretty evil to me.
