### ISSUE TITLE
usgamer.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#372]
### Basic Information

**Test link:** `https://www.usgamer.net/articles/19-11-2018-assassins-creed-odyssey-guide/best-abilities-unlock-guide`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
**Extension:** Nano Defender 15.0.0.75

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/48985020-98a2e700-f0c0-11e8-938e-1ececf0894a4.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.usgamer.net/articles/beloved-youtuber-shirley-curry-skyrim-grandma-will-be-an-npc-in-the-elder-scrolls-6`
**Category:** anti-adblock
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.115

### Additional Message

**Comment by jspenguin2017** [comment]
Ads placeholders fixed. Can't reproduce anti-adblock.
