### ISSUE TITLE
ploudos.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3721]
### Basic Information

**Test link:** `https://ploudos.com/server/`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

You have to login to see the detection.
The detection works by the following code in an inline script tag.
The code of the detection script: `https://pastebin.com/LNevG7gh`

**Comment by llacb47** [comment]
Test account: 
```
raroho1740@oriwijn.com
raroho1740@oriwijn.com
```

**Comment by llacb47** [comment]
```
||ad.plus^$3p
@@||ploudos.com^$ghide
```
