### ISSUE TITLE
komorkomania.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#373]
### Basic Information

**Test link:** `https://komorkomania.pl/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
**Extension:** Nano Defender 15.0.0.75

**Comment by mapx-** [comment]
fixed in regional list

**Comment by jspenguin2017** [comment]
Fixed in Polish regional filters.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://komorkomania.pl/32795,android-system-webview-co-to-jest`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
**Extension:** Nano Defender 15.0.0.201

### Additional Message

scroll down "Nie ma wolności mediów bez oglądalności reklam
Masz włączone blokowanie reklam, co uniemożliwia odtworzenie filmu. Wyłącz blokowanie (np. Adblock lub inne), aby zobaczyć film.
(kod błędu:<13>)"

**Comment by jspenguin2017** [comment]
@okiehsch Anti-adblock, regional filters no longer work. 
![image](https://user-images.githubusercontent.com/7283682/87612926-203fce00-c6c9-11ea-82b4-07f09a87ded4.png)

**Comment by okiehsch** [comment]
Fixed.
