### ISSUE TITLE
forum.wordreference.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3730]
### Basic Information

**Test link:** `https://forum.wordreference.com/threads/pensar-de-forma.3694775/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

blank bar

**Comment by mapx-** [comment]
`forum.wordreference.com##[id$="_mid"]`
@ryanbr
