### ISSUE TITLE
khatrimaza.kim

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3738]
### Basic Information

**Test link:** `https://khatrimaza.kim/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 7.1.2; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0
**Extension:** Nano Defender for Firefox 15.0.0.197

**Comment by ghajini** [comment]
`khatrimaza.kim##+js(aeld, , 0x)`
`||binalbamp.com^`

**Comment by jspenguin2017** [comment]
I can't reproduce, there's no popup for me.

**Comment by ghajini** [comment]
> ### User Environment
> **Browser:** Mozilla/5.0 (Android 7.1.2; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0

Because you haven't tested on said platform

**Comment by ghajini** [comment]
Popup ads over here also ,mirrors of khatrimaza
`khatrimaza.icu`
`www.okhatrimaza.tel`

**Comment by mapx-** [comment]
@ghajini I get no popup

**Comment by ghajini** [comment]
I get popups opera browser /firefox desktop/firefox android on these sites
```
khatrimaza.icu
www.okhatrimaza.tel
khatrimaza.Kim

**Comment by mapx-** [comment]
finally I get popups on `khatrimaza.icu`

filter `khatrimaza.icu##+js(acis, puShown , /doOpen|popundr/)`

**Comment by mapx-** [comment]
`binalbamp` script is empty on my side

**Comment by ghajini** [comment]
> `binalbamp` script is empty on my side

`https://binalbamp.com/rxcXf1mXzuUEOhE4/15374`
Filters to summarize
```
khatrimaza.*##+js(aeld, , 0x)
||binalbamp.com^
||dostophog.com^
khatrimaza.icu##+js(acis, puShown , /doOpen|popundr/)
okhatrimaza.*##+js(acis, Object.defineProperty, XMLHttpRequest)
||ilkmawgod.site^
