### ISSUE TITLE
wg-gesucht.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3742]
### Basic Information

**Test link:** `https://www.wg-gesucht.de/1-zimmer-wohnungen-in-Berlin-gesucht.7954603.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

First reported at `https://forums.lanik.us/viewtopic.php?f=62&t=44637`

google funding choices anti-adblock `You are seeing this message because ad or script blocking software is interfering with this page.`

also anti-adblock script: `https://www.wg-gesucht.de/js/lib/dab.lib.tjb1585596165.js`

**Comment by llacb47** [comment]
Lol, never mind. https://github.com/uBlockOrigin/uAssets/commit/52978392b8a35695f76531eb506179fc22040960

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/52978392b8a35695f76531eb506179fc22040960
