### ISSUE TITLE
music.apple.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3744]
### Basic Information

**Test link:** `https://music.apple.com/us/album/ready-lets-go/1496585255?i=1496585320`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

anti-select

```
music.apple.com##*:style(-webkit-user-select:auto!important;-moz-user-select:auto!important;-ms-user-select:auto!important;user-select:auto!important;-webkit-user-drag:auto!important)
music.apple.com##body:style(cursor:auto!important)
```

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select, anti-right-click.
