### ISSUE TITLE
watchfriendsonline.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3751]
### Basic Information

**Test link:** `https://watchfriendsonline.net/watch-free/friends-8x1/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

**Comment by llacb47** [comment]
@mapx-

1. New popads inline script spamming `undefined`
2. 3p popads script `https://d3g5ovfngjw9bw.cloudfront.net/uikit.min.js`
3. 3p script `https://zidiplay.com/asset/sostress.js?_=1588521879517` (not doing anything?)

Lots of 3p junk and xhrs.

**Comment by ghajini** [comment]
@llacb47, 
watchfriendsonline.net##+js(acis, atob, decodeURIComponent)
works

No need to add redirect rule
