### ISSUE TITLE
sciencealert.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3757]
### Basic Information

**Test link:** `https://www.sciencealert.com/we-re-passing-through-the-trail-of-halley-s-comet-and-it-s-about-to-light-up-the-sky`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

placeholder

**Comment by DandelionSprout** [comment]
Placeholders: `sciencealert.com##div[class^=priad][id]:upward(1)`
