### ISSUE TITLE
eroasmr.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3759]
### Basic Information

**Test link:** `https://eroasmr.com/video/whispered-countdown-to-come/`
**Category:** ads
**Reported from:** Ukraine
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 OPR/68.0.3618.63
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

"You can skip ad in 5 s" in some videos.

**Comment by okiehsch** [comment]
Fixed.
