### ISSUE TITLE
kobieta.interia.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3762]
### Basic Information

**Test link:** `https://kobieta.interia.pl/zdrowie/news-bole-brzucha-pomagamy-rozpoznac-ich-przyczyne,nId,4465217#iwa_source=worthsee`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.24 Safari/537.36 Edg/83.0.478.18
**Extension:** Nano Adblocker 1.0.0.142

**Comment by krystian3w** [comment]
Not shall pass for empty form when reported is breakage?

**Comment by krystian3w** [comment]
```
https://kobieta.interia.pl/zdrowie/news-bole-brzucha-pomagamy-rozpoznac-ich-przyczyne,nId,4465217,nPack,2
```

on 2-nd page of article I found anti-adblock in embeded player:

![obraz](https://user-images.githubusercontent.com/35370833/81121555-4c074080-8f2f-11ea-91c2-5747c2121f1c.png)

```
https://get.x-link.pl/f84a9613-6a39-52b1-862f-19e10ceb8c26,f20619f7-9e42-7221-80b4-030fc73b67b0,embed.html
```

Link `get.x-link.pl` may not stable.
