### ISSUE TITLE
wallpaperaccess.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3763]
### Basic Information

**Test link:** `https://wallpaperaccess.com/super-hi-res-2560x1440`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

`https://forums.lanik.us/viewtopic.php?f=64&t=44641`

```
wallpaperaccess.com#@#.ads1
wallpaperaccess.com##+js(nano-sib)
```

**Comment by okiehsch** [comment]
Fixed.
