### ISSUE TITLE
gaybeeg.info

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3765]
### Basic Information

**Test link:** `https://gaybeeg.info/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

`https://forums.lanik.us/viewtopic.php?f=62&p=154476#p154476`

New popads script

**Comment by okiehsch** [comment]
Fixed.
