### ISSUE TITLE
gaystream.pw

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3766]
### Basic Information

**Test link:** `https://gaystream.pw/video/4308/seeking-the-ultimate-top-eddy-ceetee-jacob-peterson.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

ads link identified but ads redirection not blocked

**Comment by okiehsch** [comment]
Fixed.
