### ISSUE TITLE
phoneworld.com.pk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#378]
### Basic Information

**Test link:** `https://www.phoneworld.com.pk/samsung-galaxy-s10-lite-to-feature-infinity-0-display/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
**Extension:** Nano Defender 15.0.0.78

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/49044440-fef43c00-f18a-11e8-81b2-1b332e07390f.png)
