### ISSUE TITLE
mexa.sh

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3784]
### Basic Information

**Test link:** `https://mexa.sh/t6olsya4ggx9/200505-Voice-RJ286273-MP3-Only.rar.html`
**Category:** other
**Reported from:** Thailand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

- Found code block that make use of `atob` to inject ads and anti-adblock, but it's fail, however, it's flushing requests to `undefined` infinitely instead and reduce browser performance.
- Test add script inject `##+js(acis, atob)` and it's stopped.

**Comment by okiehsch** [comment]
Fixed.
