### ISSUE TITLE
skidrowcodex.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3786]
### Basic Information

**Test link:** `https://www.skidrowcodex.net/x-plane-11-global-scenery-codex/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

popads

**Comment by llacb47** [comment]
New popads script.
