### ISSUE TITLE
tw-calc.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3801]
### Basic Information

**Test link:** `https://tw-calc.net/about-script`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

https://github.com/bogachenko/fuckfuckadblock/issues/52

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/commit/20381bcae969db7e93eb20df6c30ab4767efd055#r39054340

**Comment by jspenguin2017** [comment]
@okiehsch @mapx- The fix is bad, it breaks item preview.
