### ISSUE TITLE
downloadsource.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3807]
### Basic Information

**Test link:** `https://www.downloadsource.net/`
**Category:** other
**Reported from:** Hungary
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

no works: `downloadsource.*##.date:not(dt):style(display: block !important;)` from `uBO unbreak`

maybe this is better: 

```
downloadsource.*##:root body #content .date:not(dt):style(display: block !important;)
```

**Comment by jspenguin2017** [comment]
I don't see any obvious breakage on this website. 
![image](https://user-images.githubusercontent.com/7283682/81488648-c46c4b00-9228-11ea-9225-320d320ad929.png)

**Comment by krystian3w** [comment]
Breakage - hidden dates with Nano, uBo recover date:

![obraz](https://user-images.githubusercontent.com/35370833/81496438-f37dcd80-92b7-11ea-915c-b792ea4858fa.png) |
--- |

**Comment by jspenguin2017** [comment]
@okiehsch
