### ISSUE TITLE
earth.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3810]
### Basic Information

**Test link:** `https://www.earth.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edg/81.0.416.72
**Extension:** Nano Defender Pro 15.0.0.197

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

**Comment by llacb47** [comment]
shouldn't this go in annoyances? 
![image](https://user-images.githubusercontent.com/16567977/81482970-b9a1be00-9208-11ea-9593-303f9ee068ee.png)

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/81483587-90505480-923f-11ea-9ece-cbe6b809c4e8.png)

**Comment by krystian3w** [comment]
`US` user recommend move into filters-2020? Maybe pop-up no have ❌.

**Comment by llacb47** [comment]
🤦‍♂️

**Comment by jspenguin2017** [comment]
@krystian3w @llacb47 I don't understand what you two are trying to say. I don't see any other issues with this website.
