### ISSUE TITLE
tw-calc.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3816]
### Basic Information

**Test link:** `https://tw-calc.net/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.44 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

Ads placeholders: 
```
https://tw-calc.net/
https://tw-calc.net/calculators/battle
etc...
```

**Comment by DandelionSprout** [comment]
Most of the glaring ones were fixed in a recent uBlock Filters update. However, `tw-calc.net##.rectangle.container` still remains.
