### ISSUE TITLE
searchenginejournal.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3822]
### Basic Information

**Test link:** `https://www.searchenginejournal.com/a-b-multivariate-testing-seo/366184/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

**Comment by llacb47** [comment]
```
searchenginejournal.com###summitad-wrap
searchenginejournal.com##.ss_slot
searchenginejournal.com###spcat_ifr
searchenginejournal.com##.sej-bann-section
searchenginejournal.com##.avert-text
```

**Comment by jspenguin2017** [comment]
(Pinged on Slack)
