### ISSUE TITLE
tutorialspark.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3824]
### Basic Information

**Test link:** `http://tutorialspark.com/html5/TutorialsPark_HTML5_Begins_Demo.php`
**Category:** ads
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

`Ad` hard coded in styles (aka placeholder):

```
tutorialspark.com###mainblock:style(top: 0 !important; bottom: 1px !important;)
```

![image](https://user-images.githubusercontent.com/7283682/81578914-b9b8cf80-9368-11ea-9971-3191a264f294.png) |
--- |
`#adsense_editor` on top |

similar: https://github.com/uBlockOrigin/uAssets/issues/1658

**Comment by llacb47** [comment]
Fixed in AdGuard Base:
```
tutorialspark.com###mainblock:style(top: 0 !important; bottom: 1px !important;)
tutorialspark.com###toprect
```

**Comment by krystian3w** [comment]
Only `"lang": "az",` may enabled AG Base in uBO: https://github.com/DandelionSprout/uBlock/blob/patch-1/assets/assets.json#L82

**Comment by jspenguin2017** [comment]
@krystian3w 

I don't see that in the official repo: https://github.com/gorhill/uBlock/blob/eba9f82dcc40b17d10be7516525d54933456170a/assets/assets.json#L77

Also `lang` controls which locale will have the filter automatically enabled, it does not stop the user from manually enabling it.

**Comment by krystian3w** [comment]
So close and add label "need AdGuard base".

EOT.

**Comment by jspenguin2017** [comment]
For now, I don't want the placeholder buster list to rely on AdGuard base.
