### ISSUE TITLE
tikview.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3827]
### Basic Information

**Test link:** `https://tikview.com/therock/tiktok-music/6822270078566910726`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

also unblocked push ads domain `cdnster.com`

**Comment by okiehsch** [comment]
Fixed.
