### ISSUE TITLE
everydayporn.co

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3828]
### Basic Information

**Test link:** `https://www.everydayporn.co/videos/155066/leo-stuke-xleox-homemade-3/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4138.0 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

**Comment by okiehsch** [comment]
Fixed.
