### ISSUE TITLE
oturl.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#383]
### Basic Information

**Test link:** `http://oturl.com/lPMQ5p9`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
**Extension:** Nano Defender 15.0.0.78

**Comment by okiehsch** [comment]
Fixed.
