### ISSUE TITLE
settlersonlinemaps.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3836]
### Basic Information

**Test link:** `http://settlersonlinemaps.com/exguide.php?LangCode=11`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message

Hi,
I use this page a lot and the notice that comes up saying that I have an adblocker running is really annoying. I have no idea how I can even whitelist the page. I've tried previously but have not stopped the notice from popping up. So could you look into Nano Defender sorting it please?  Thank You in advance.
\<redacted>

**Comment by jspenguin2017** [comment]
https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/-/issues/55
