### ISSUE TITLE
bcvc.live

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3844]
### Basic Information

**Test link:** `https://bcvc.live/sT3wGTJ`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/81.0.4044.122 Chrome/81.0.4044.122 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

**Comment by llacb47** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. Destination (another link shortener): `https://shorten.sh/s6vRaHs`

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. Destination: `https://shorten.sh/s6vRaHs`

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://bcvc.live/mfdplCw`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 OPR/68.0.3618.125
**Extension:** Nano Defender 15.0.0.198

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://bcvc.live/LnulbNo`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 OPR/68.0.3618.125
**Extension:** Nano Defender 15.0.0.198

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://bcvc.live/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
**Extension:** Nano Defender 15.0.0.198

### Additional Message

Original URL: `https://bcvc.live/2ySjcHf`

adblocker warning.
