### ISSUE TITLE
homeworklib.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3851]
### Basic Information

**Test link:** `https://www.homeworklib.com/questions/1379929/2s3s-12-dibromo-12-diphenylethane-were-formed-in`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

ads, placeholders, etc. on the right side

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/82134002-a87c2280-97af-11ea-9878-5334b8872351.png)

**Comment by jspenguin2017** [comment]
(Pinged on Slack)

**Comment by ryanbr** [comment]
Not an easy fix, open to suggestions that don't involve nth elements

**Comment by jspenguin2017** [comment]
`homeworklib.com##.title:has-text(/^Ads$/):upward(1)`

**Comment by jspenguin2017** [comment]
Not sure if that can be added to EasyList though... 

@okiehsch
