### ISSUE TITLE
eska.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3852]
### Basic Information

**Test link:** `https://www.eska.pl/news/zoom-jak-zainstalowac-i-korzystac-instrukcja-krok-po-kroku-aa-rqWi-rwh1-Aqqt.html`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

**Comment by krystian3w** [comment]
In player:

![wyszukiwarka](https://user-images.githubusercontent.com/35370833/82446046-3012ab80-9aa6-11ea-8853-40f446765723.JPG)

**Comment by mapx-** [comment]
`@@||eska.pl^$ghide`
