### ISSUE TITLE
css-tricks.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3856]
### Basic Information

**Test link:** `https://css-tricks.com/notion-powered-websites/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.56 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

Test: 
```
https://css-tricks.com/notion-powered-websites/
https://css-tricks.com/nerds-guide-color-web/
```

Rules: 
```
css-tricks.com##.end-of-article-ads
css-tricks.com###all-ads
````

**Comment by llacb47** [comment]
`css-tricks.com##.fem-ad` also works

**Comment by jspenguin2017** [comment]
Would this also be considered ads? 
![image](https://user-images.githubusercontent.com/7283682/82134056-728b6e00-97b0-11ea-8a45-2035b21cabf4.png)

**Comment by jspenguin2017** [comment]
(Pinged on Slack)
