### ISSUE TITLE
inoreader.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#386]
### Basic Information

**Test link:** `https://www.inoreader.com/feed/http%3A%2F%2Fwww.estense.com%2F%3Ffeed%3Drss2`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
**Extension:** Nano Defender 15.0.0.78

### Additional Message

Adblock Detected!
Ads do help us to keep Inoreader running, so please support us by whitelisting our site in your Adblocking software. Apart from your browser adblocker, you may have to whitelist us in your VPN/Security software's adblockers as well. Once done, just refresh this web page. You can also upgrade to our Starter plan to remove all ads.
Upgrade for an ad-free experience

**Comment by mapx-** [comment]
it was fixed in ublock filters days ago
