### ISSUE TITLE
brainly.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3861]
### Basic Information

**Test link:** `https://brainly.pl/zadanie/16013100`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 OPR/68.0.3618.104
**Extension:** Nano Defender 15.0.0.197

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://brainly.pl/zadanie/9340006`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Defender 15.0.0.198

### Additional Message

**Comment by krystian3w** [comment]
🍝 JS glitch?

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/pull/7459

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/01087f723e832144486ec3ed116757984d168f02
