### ISSUE TITLE
ilgeniodellostreaming.tw

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3864]
### Basic Information

**Test link:** `https://ilgeniodellostreaming.tw/episodi/i-simpson-9x1/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

for every video in this website an anti-adblock appears :(
thank you very much for your work :)

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/49c7f0a43456afe2b489860b2bcb2175d9898d89

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/49c7f0a43456afe2b489860b2bcb2175d9898d89
