### ISSUE TITLE
androidpit.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3867]
### Basic Information

**Test link:** `https://www.androidpit.com/google-pixel-4a-price-release-date-specs-features`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

```
androidpit.com##.gptSlot:upward(.article-sidebar__tile)
androidpit.com###snhb-halfpage_right-0:upward(1)
androidpit.com###snhb-sticky_mobile-0
androidpit.com###div-header
```

**Comment by jspenguin2017** [comment]
Another test link: `https://www.androidpit.com/`
