### ISSUE TITLE
coingecko.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3874]
### Basic Information

**Test link:** `https://www.coingecko.com/en/coins/bitcoin`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

sponsored exchanges

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/82134299-b469e380-97b3-11ea-945d-45aaa84fb747.png)

**Comment by jspenguin2017** [comment]
(Pinged on Slack)
