### ISSUE TITLE
addthis.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3875]
### Basic Information

**Test link:** `https://www.addthis.com/academy/customizing-the-addthis-toolbox/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.56 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

```
addthis.com##.addthis_horizontal_follow_toolbox:upward(1)
```

**Comment by jspenguin2017** [comment]
Widget blocked by uBlock privacy filter.
