### ISSUE TITLE
imagebam.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#388]
### Basic Information

**Test link:** `http://www.imagebam.com/gallery/pyaup2nyt8a3il7szcn7iczftw52dkk3`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
**Extension:** Nano Defender 15.0.0.79

### Additional Message

Says adblock detected!

**Comment by jspenguin2017** [comment]
Works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://www.imagebam.com/sys/upload/done/`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.101

### Additional Message

Adblock Plus breaks the upload functionality. Please disable it.

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://www.imagebam.com/sys/upload/done/`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

Adblock Plus breaks the upload functionality. Please disable it.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://www.imagebam.com/sys/upload/done/`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

Adblock Plus breaks the upload functionality. Please disable it.

**Comment by mapx-** [comment]
Even disabling uBo I get same message / behaviour.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://www.imagebam.com/sys/upload/done/`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.106

### Additional Message

Adblock Plus breaks the upload functionality. Please disable it.

**Comment by jspenguin2017** [comment]
I just realized the filter rule was in ND Integration.
