### ISSUE TITLE
mangatoon.mobi

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3883]
### Basic Information

**Test link:** `https://mangatoon.mobi/id/watch/2330/24176`
**Category:** other
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Defender 15.0.0.198

### Additional Message

anti right click

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select.
