### ISSUE TITLE
tv.avclub.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3891]
### Basic Information

**Test link:** `https://tv.avclub.com/janelle-monae-explains-how-homecoming-parallels-our-cur-1843486921`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

No video playback

**Comment by llacb47** [comment]
`@@||avclub.com/x-kinja-static/assets/new-client/adManager.$script,1p`

more general `@@||avclub.com^*/adManager.$script,1p`

**Comment by jspenguin2017** [comment]
(Pinged on Slack)

**Comment by llacb47** [comment]
https://github.com/easylist/easylist/commit/cf61a20319d62c2d333464dee366db994f690366
