### ISSUE TITLE
devblogs.microsoft.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3892]
### Basic Information

**Test link:** `https://devblogs.microsoft.com/`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.145

### Additional Message

style broken for the cookie banner thing

**Comment by llacb47** [comment]
Caused by `||s-microsoft.com/mscc/` in Easyprivacy

**Comment by okiehsch** [comment]
Fixed.
