### ISSUE TITLE
marketscreener.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3895]
### Basic Information

**Test link:** `https://www.marketscreener.com/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.145

### Additional Message

placeholders

**Comment by DandelionSprout** [comment]
Partially fixed in AdGuard Base through:
```
marketscreener.com##div[style="width: 100%;"] > #zppMiddle2
marketscreener.com##.hPubRight2
```

I'll add `marketscreener.com##.myFooter` to Nano Placeholder Buster in a PR I plan to make later today.

**Comment by llacb47** [comment]
Adguard base is not a default filterlist :) So they need to be fixed, do you agree?

**Comment by DandelionSprout** [comment]
I'm a big fan of AdGuard Base, and am honestly wishing it was a default list. 😅

**Comment by llacb47** [comment]
`marketscreener.com##[id^="zpp"]`

Interestingly there are no placeholders in Firefox
