### ISSUE TITLE
echodnia.eu

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3897]
### Basic Information

**Test link:** `https://echodnia.eu/radomskie/`
**Category:** ads
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363
**Extension:** Nano Adblocker 0.0.128.0

### Additional Message

red "gratka"

**Comment by mapx-** [comment]
to be reported to the polish lists
`echodnia.eu##.promoContainer`

**Comment by jspenguin2017** [comment]
@mapx- Do you know who to ping?

**Comment by mapx-** [comment]
@MajkiIT @olegwukr

**Comment by MajkiIT** [comment]
@mapx- Thanks
