### ISSUE TITLE
start.me

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3898]
### Basic Information

**Test link:** `https://start.me/start/int/startpage`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

At bottom - annoyance:

![image](https://user-images.githubusercontent.com/7283682/82463149-b2d14180-9a79-11ea-8b7b-38fc7828c64c.png)

**Comment by krystian3w** [comment]
By Gargul/Kulfon: `start.me##+js(nostif, adBanner)` https://github.com/MajkiIT/polish-ads-filter/issues/16390

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance.

**Comment by okiehsch** [comment]
Fixed.
