### ISSUE TITLE
mentalfloss.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3900]
### Basic Information

**Test link:** `https://www.mentalfloss.com/amazingfactgenerator`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.145

### Additional Message

ad placeholder - click the button a few times

**Comment by krystian3w** [comment]
![Przechwytywanie](https://user-images.githubusercontent.com/35370833/82558427-e097b280-9b6d-11ea-9e4a-390063e1fc6f.JPG)

**Comment by krystian3w** [comment]
IMO need scriptlet, because "Skip ad" need click and "more facts please!" is disabled.

Or liked for EasyList - "no worth".

**Comment by jspenguin2017** [comment]
Hum, might need a new script snippet.

**Comment by krystian3w** [comment]
Maybe now no needed new, I tested AdGuard scriptlet.

`AdamWr` invented:

 `mentalfloss.com#%#//scriptlet("set-constant", "countClicks", "0")`

They AdGuard probably added additional a version with `remove-class` as a fallback, because they will probably quickly detect fake zero clicks.

**Comment by jspenguin2017** [comment]
Yea, that works. 

@okiehsch `mentalfloss.com##+js(set-constant, countClicks, 0)`
