### ISSUE TITLE
socialblade.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3905]
### Basic Information

**Test link:** `https://socialblade.com/youtube/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.145

### Additional Message

placeholders

**Comment by llacb47** [comment]
```
socialblade.com##[id^="cdm-zone-"]:upward(div[style*="height:"][style*="background:"])
socialblade.com##[style="clear: both;"]+div[style*="#333"]:style(margin-top:10px)
socialblade.com###bottomAd
```

**Comment by jspenguin2017** [comment]
Hum, this is a bit tricky, hiding `#bottomAd` triggers anti-adblock. Also there is another placeholder near the end. 
![image](https://user-images.githubusercontent.com/7283682/82611139-0aa4a100-9b7d-11ea-853c-9cb0d4f039d2.png)

**Comment by llacb47** [comment]
The anti-adblock is just annoyance, the cosmetic filters hide everywhere it appears, so it's a non-issue.
Footer: `socialblade.com###footer-section-wrap+div`

**Comment by jspenguin2017** [comment]
Another test link: `https://socialblade.com/youtube/`
