### ISSUE TITLE
kultura.onet.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3907]
### Basic Information

**Test link:** `https://kultura.onet.pl/muzyka/gatunki/pop/perfumy-lindsay-lohan/34xh1zf`
**Category:** ads
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
**Extension:** Nano Adblocker 1.0.0.142

### Additional Message

`###onet-ad-right:upward(aside)`

**Comment by krystian3w** [comment]
maybe also: `###extraAdsBlock` or `##.asideAds`

**Comment by jspenguin2017** [comment]
Another test link: `https://www.onet.pl/?utm_source=detal_viasg_kobieta&utm_medium=synergy&utm_campaign=allonet_detal_popularne&srcc=ucs&pid=b36ec2fc-5d5b-4118-a6fb-d07ba7cda1d8&sid=63eeb4cc-4788-4ae3-a160-ddd0a01f6209&utm_v=2`

**Comment by krystian3w** [comment]
I have a little breakge:

```
zapytaj.onet.pl#@##onet-ad-right:upward(aside)
```

hide left sidebar on:

`https://zapytaj.onet.pl/Category/007,003/2,28963674,Czy_strona_Ocean_of_Games_jest_bezpieczna_.html`

**Comment by jspenguin2017** [comment]
Another test link: `https://zapytaj.onet.pl/Category/007,003/2,28963674,Czy_strona_Ocean_of_Games_jest_bezpieczna_.html`
