### ISSUE TITLE
shotly.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3909]
### Basic Information

**Test link:** `https://shotly.io/Qnei9`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.145

### Additional Message

fake buttons

**Comment by jspenguin2017** [comment]
@okiehsch Fake buttons. 
![image](https://user-images.githubusercontent.com/7283682/82610571-e1cfdc00-9b7b-11ea-9323-3f936d5caebc.png)

**Comment by okiehsch** [comment]
Fixed.
