### ISSUE TITLE
diffchecker.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3914]
### Basic Information

**Test link:** `https://www.diffchecker.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.145

### Additional Message

`If you want to help keep us running, please whitelist Diffchecker in your ad blocker.`

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance. 
![image](https://user-images.githubusercontent.com/7283682/82713964-02fefe00-9c4a-11ea-9df1-61445b58c19b.png)

**Comment by okiehsch** [comment]
Fixed.
