### ISSUE TITLE
dizibox.pw

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3922]
### Basic Information

**Test link:** `https://www.dizibox.pw/dave-1-sezon-4-bolum-izle/`
**Category:** breakage
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.145

### Additional Message

blocked the actual video content

**Comment by krystian3w** [comment]
`dizibox.pw#@#.reklam2`, ad need better filter.

**Comment by jspenguin2017** [comment]
No breakage with Turkish regional filters enabled, but has ads. 

@okiehsch FYI.

**Comment by okiehsch** [comment]
`dizibox.pw###pageskin`
@Alex-302

**Comment by Alex-302** [comment]
> dizibox.pw###pageskin

Done. It was in wrong filter.
