### ISSUE TITLE
serialy.bombuj.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3933]
### Basic Information

**Test link:** `http://serialy.bombuj.tv/serial/ncis-los-angeles-2x10`
**Category:** anti-adblock
**Reported from:** Czechia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.13 Safari/537.36
**Extension:** Nano Defender 15.0.0.198

**Comment by okiehsch** [comment]
Caused in part by a filter in the regional list.
Fixed.
@addisr fyi
