### ISSUE TITLE
apply.cfnc.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3935]
### Basic Information

**Test link:** `https://apply.cfnc.org/application/NCCU/NCCUDistanceLearningApp/NCCUDistanceLearningApp`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edg/81.0.416.77
**Extension:** Nano Adblocker 1.0.0.147

### Additional Message

Breaks the site, prevents you from saving application

**Comment by okiehsch** [comment]
Needs an account.
