### ISSUE TITLE
dms.privacy-port.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3938]
### Basic Information

**Test link:** `https://dms.privacy-port.de/system/companies`
**Category:** breakage
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Defender 15.0.0.198

### Additional Message

The site keeps showing the loading animation indefinitely, screenshots:
`https://i.imgur.com/SheraUn.png`
`https://i.imgur.com/VIMivMO.png`

**Comment by okiehsch** [comment]
Needs an account.
