### ISSUE TITLE
lalawin.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3942]
### Basic Information

**Test link:** `https://lalawin.com/`
**Category:** anti-adblock
**Reported from:** South Korea
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.147

### Additional Message

Original URL: `chrome-extension://gabbbocakeomblphkmmnoamkioajlkfo/dashboard.html#1p-filters.html`

Website includes adblock detection script and blocks only certain parts of pages cannot be bypassed.
More examples:
`jimnong.tistory.com`
`ilsangt.tistory.com`

**Comment by mapx-** [comment]
anti adb already fixed by `KOR: YousList`

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select, anti-copy.
