### ISSUE TITLE
happymoney.co.kr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3943]
### Basic Information

**Test link:** `http://happymoney.co.kr/`
**Category:** breakage
**Reported from:** South Korea
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.147

### Additional Message

Websites Presents nothing while attempting to access website. Have to disable adblocker first and then turn back on in order to proceed. There is no problem after disabling and re-enabling adblocker.

Custom filter list

```
www.happymoney.co.kr##.rightOne
www.happymoney.co.kr##.slideBx
www.happymoney.co.kr##.js-btnopen.marT10.btn_1.btn40
www.happymoney.co.kr###sepay_1
www.happymoney.co.kr##.btnSecurity
www.happymoney.co.kr##.myotpWarning
```

**Comment by jspenguin2017** [comment]
@okiehsch Breakage, happens on default setup + regional filters. 
![image](https://user-images.githubusercontent.com/7283682/82853907-30ef7700-9ec4-11ea-89e8-a54dee28d297.png)

**Comment by okiehsch** [comment]
Fixed.
