### ISSUE TITLE
geeksforgeeks.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3951]
### Basic Information

**Test link:** `https://www.geeksforgeeks.org/why-prims-and-kruskals-mst-algorithm-fails-for-directed-graph/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Defender 15.0.0.199

### Additional Message

Extra `<br>`s around ads.

**Comment by DandelionSprout** [comment]
Placeholder: `geeksforgeeks.org##div[style="min-height:280px"]`
