### ISSUE TITLE
adaranth.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3954]
### Basic Information

**Test link:** `https://adaranth.com/afu.php?zoneid=1407888&var=1407888&rid=wfxzsvAkbQDjdtH2xjZy_Q%3D%3D`
**Category:** other
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.147

### Additional Message

Malicious redirects not blocked

**Comment by mapx-** [comment]
https://malwaretips.com/blogs/remove-adaranth-com/

**Comment by jspenguin2017** [comment]
`t: other`: Badware. 

---

@okiehsch Maybe add the domain to the badware filter?

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a8bed37a515c53b345b8b04a2c91e600248dd03f#diff-d8c958abb503fa31dd3ad7deb48bdef0
