### ISSUE TITLE
nsspot.herokuapp.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3957]
### Basic Information

**Test link:** `https://nsspot.herokuapp.com/mobidiet/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
**Extension:** Nano Defender 15.0.0.199

### Additional Message

detects adblock. upload a mobi file then hit "Convert, Reduce File Size"
a popup comes up

thank you

**Comment by okiehsch** [comment]
Fixed.
