### ISSUE TITLE
bbs.wenxuecity.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3968]
### Basic Information

**Test link:** `https://bbs.wenxuecity.com/bbs/financenews/12356.html`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Defender 15.0.0.199

**Comment by visualage** [comment]
need to block script `https://www.wenxuecity.com/script/wxc_ab_help.js`. The following static filter rule works fine:
`||/script/wxc_ab_help.js^$script,domain=wenxuecity.com`

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. 
![image](https://user-images.githubusercontent.com/7283682/83331458-c6d42a80-a253-11ea-8c31-ececc7ec6aa2.png)

**Comment by visualage** [comment]
It is back now. They removed the `<script>` tag with `src`. Instead, embed the whole script in HTML.
<img width="698" alt="Screen Shot 2020-06-01 at 6 14 38 PM" src="https://user-images.githubusercontent.com/1828207/83469156-c2fefe80-a433-11ea-9f7a-8e34d4530d3b.png">
<img width="654" alt="Screen Shot 2020-06-01 at 6 15 01 PM" src="https://user-images.githubusercontent.com/1828207/83469177-d316de00-a433-11ea-9836-24db3d312929.png">

**Comment by visualage** [comment]
The detection is done by see if `adsbygoogle` is defined.
<img width="486" alt="Screen Shot 2020-06-01 at 6 18 26 PM" src="https://user-images.githubusercontent.com/1828207/83469342-4c163580-a434-11ea-813d-466223793ff5.png">

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock with Chinese regional filters enabled.

**Comment by jspenguin2017** [comment]
Placeholder fixed.
