### ISSUE TITLE
thegearhunt.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3969]
### Basic Information

**Test link:** `https://thegearhunt.com/best-outside-thermometers-reviewed/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
**Extension:** Nano Defender 15.0.0.199

### Additional Message

anti text select / anti right-click

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-copy, anti-hotkey, anti-select.
