### ISSUE TITLE
gentside.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#397]
### Basic Information

**Test link:** `https://www.gentside.com/galaxy-s10/galaxy-s10-date-de-sortie-prix-et-fiche-technique-du-smartphone-de-samsung_art84938.html`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
**Extension:** Nano Defender 15.0.0.80

### Additional Message

pop-up anti adblock

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/49468200-78121580-f7c1-11e8-8e41-4e9b1dda67d5.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.gentside.com/idris-elba/idris-elba-en-james-bond-sa-rencontre-tres-genante-avec-daniel-craig-aux-golden-globes-2019_art89265.html`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.85

### Additional Message

**Comment by jspenguin2017** [comment]
Still works for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.gentside.com/telechargement/torrent-gratuit-top-10-des-meilleurs-sites-pour-telecharger_art83654.html`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36 OPR/66.0.3515.36
**Extension:** Nano Defender 15.0.0.180

### Additional Message

Detect Ublock origin
