### ISSUE TITLE
nfl.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3970]
### Basic Information

**Test link:** `https://www.nfl.com/videos/bills-roster-reset-will-diggs-elevate-buffalo-to-a-division-title`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

Video not playing with Adblock on

**Comment by okiehsch** [comment]
Fixed.
