### ISSUE TITLE
spectrum.ieee.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3974]
### Basic Information

**Test link:** `https://spectrum.ieee.org/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.30 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

placeholder

**Comment by DandelionSprout** [comment]
Placeholder: `spectrum.ieee.org##.masthead-wrap`
