### ISSUE TITLE
wowescape.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3975]
### Basic Information

**Test link:** `http://www.wowescape.com/play/magic-tree-fairy-escape/19166`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.30 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

Placeholders, also on home page.

**Comment by DandelionSprout** [comment]
Placeholders:
```
! http://www.wowescape.com/play/magic-tree-fairy-escape/19166
wowescape.com##.googleAd_one
wowescape.com##.bordernew:upward(1)
```
