### ISSUE TITLE
funescapegames.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3977]
### Basic Information

**Test link:** `http://www.funescapegames.com/game/speculation-forest`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.30 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

Small placeholder, also on home page.

**Comment by DandelionSprout** [comment]
```
! https://www.funescapegames.com/game/speculation-forest
www.funescapegames.com##.header-extra
! https://www.funescapegames.com/
www.funescapegames.com##div[id^="funescapegames"]:upward(2)
www.funescapegames.com##.adsbygoogle:upward(1)
```
