### ISSUE TITLE
bestescapegames.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3978]
### Basic Information

**Test link:** `https://bestescapegames.com/emerald-castle-escape`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.30 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

Placeholders, also on home page.

**Comment by DandelionSprout** [comment]
```
! https://bestescapegames.com/emerald-castle-escape
bestescapegames.com##.boxed > .col-xs-12.col-md-9
bestescapegames.com###madd_hidden
bestescapegames.com##.right-sidebar01
! https://bestescapegames.com/
bestescapegames.com##div[class^="add_div"]:upward(2)
bestescapegames.com##.home_add_newgames
bestescapegames.com##.redc_m:has-text(/^Advertisement/):upward(2)
```

**Comment by jspenguin2017** [comment]
Please open a PR. Thank you for your contribution.

**Comment by jspenguin2017** [comment]
Another test link: `https://bestescapegames.com/`
