### ISSUE TITLE
dressupone.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3980]
### Basic Information

**Test link:** `http://www.dressupone.com/flying-luigi/game`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.30 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

Placeholders, also on home page.

**Comment by DandelionSprout** [comment]
Placeholders:
```
! http://www.dressupone.com/flying-luigi/game
dressupone.com###ad-out-container
dressupone.com###ad-out-container-right
! http://www.dressupone.com/
dressupone.com###ad-box:upward(1)
```
