### ISSUE TITLE
mirchigames.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3983]
### Basic Information

**Test link:** `http://www.mirchigames.com/mirchi-escape-game/find-my-gift`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.30 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

Placeholders, also on home page.

**Comment by DandelionSprout** [comment]
```
! http://www.mirchigames.com/mirchi-escape-game/find-my-gift
mirchigames.com##.optionbox
mirchigames.com##.bottom_wrapper
! http://www.mirchigames.com/
mirchigames.com##.content_side.home_one
```

**Comment by jspenguin2017** [comment]
Another test link: `http://www.mirchigames.com/`
