### ISSUE TITLE
dressupwho.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3985]
### Basic Information

**Test link:** `https://www.dressupwho.com/games/princess-steampunk/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.30 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

Placeholders.

**Comment by DandelionSprout** [comment]
```
! https://www.dressupwho.com/games/princess-steampunk/
dressupwho.com###leaderboard\ index
dressupwho.com##.game_area_ad
dressupwho.com###game_info_ad
```

I couldn't find any obvious placeholders on the front page.

The frontpage game list contains "doctor" "games", therefore the site should be treated as NSFW.
