### ISSUE TITLE
freebinchecker.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3987]
### Basic Information

**Test link:** `https://www.freebinchecker.com/`
**Category:** anti-adblock
**Reported from:** Ukraine
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 OPR/68.0.3618.104
**Extension:** Nano Adblocker 1.0.0.148

**Comment by okiehsch** [comment]
Fixed.
