### ISSUE TITLE
canberratimes.com.au

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#3992]
### Basic Information

**Test link:** `https://www.canberratimes.com.au/story/6775644/porter-declines-to-apologise-for-robo-debt/?cs=14231`
**Category:** breakage
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
**Extension:** Nano Defender 15.0.0.199

### Additional Message

Content not loading

**Comment by mapx-** [comment]
@ryanbr
