### ISSUE TITLE
overclockers.ru

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#40]
### Basic Information

**Test link:** `https://overclockers.ru`
**Category:** anti-adblock
**Reported from:** Russia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.40

**Comment by okiehsch** [comment]
After adding that fix the anti-adblock is solved but all kind of site functionality is broken, including search and login.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/5c5fe3dcaac16dabe93ff4728e566b653081dbc9

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://overclockers.ru/?utm_source=feed_the_cat`
**Category:** anti-adblock
**Reported from:** Kazakhstan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.41

### Additional Message

Detects after some time

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/347cb111a07201c83b85b2de42701a18f3750ca3

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://overclockers.ru/`
**Category:** anti-adblock
**Reported from:** Russia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
**Extension:** Nano Defender 15.0.0.47

### Additional Message

Does not work.
A few seconds after the opening of the site, there appears a message with the request to turn off the adblock.

**Comment by llacb47** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
Looks like this isn't sticky anymore.
