### ISSUE TITLE
ubeat.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4018]
### Basic Information

**Test link:** `https://ubeat.tv/v/ubeat-crew-con-pol-gise-los-extraterrestres-viajan-al-universo-paralelo`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
**Extension:** Nano Defender 15.0.0.199

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

When you open a video it detects Nano Adblocker ignoring Nano Defender. This does not happen in the home page, only in the videos.
I also have installed "Pop up blocker for Chrome", but if I pause it the page will still detect Nano Adblocker.
Thank you for your work.

**Comment by okiehsch** [comment]
Fixed.
