### ISSUE TITLE
zeit.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#402]
### Basic Information

**Test link:** `https://www.zeit.de/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
**Extension:** Nano Defender 15.0.0.80

### Additional Message

Bitte deaktivieren Sie Ihren Adblocker.
Sie unterstützen damit die Arbeit unserer Redaktion. Wir finanzieren ZEIT ONLINE zu einem Großteil durch Werbung.

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/49809329-d38d5780-fd1b-11e8-8d38-ad195b437e9b.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.zeit.de/2019/14/urheberrechtsreform-europaparlament-youtube-uploadfilter-internet`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.112

### Additional Message

Site remark: Please deactivate Adblocker appeared

**Comment by jspenguin2017** [comment]
@okiehsch Comes up every time, tried Germany regional filters. 
![image](https://user-images.githubusercontent.com/7283682/55125614-e744aa00-50cf-11e9-8916-1dafbdaef7a7.png)

**Comment by okiehsch** [comment]
When you say comes up every time, do you mean that if you dismiss the message by clicking
"Mit Adblocker weitersurfen" the message still appears on your end?

**Comment by jspenguin2017** [comment]
Yea, It still comes up after refresh. I tried both buttons.

**Comment by okiehsch** [comment]
I can't reproduce that but I will add the `uBO-filters`.

**Comment by okiehsch** [comment]
Fixed.
