### ISSUE TITLE
nightfallnews.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4027]
### Basic Information

**Test link:** `https://nightfallnews.com/category/world/UK-Hong-Kong-US-Protests-Travel-Your-Thursday-Briefing`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

anti adblock even with nano defender preventing viewing the full slideshow

**Comment by okiehsch** [comment]
Fixed.
