### ISSUE TITLE
boston.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4028]
### Basic Information

**Test link:** `https://www.boston.com/news/local-news/2020/06/04/did-i-miss-anything-a-man-emerges-from-a-75-day-silent-retreat-in-vermont`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
**Extension:** Nano Defender for Firefox 15.0.0.199

### Additional Message

Right click the picture of the esteemed gentleman sitting barefoot at the top of the reported page sitting on patio and try to `view image` (raw jpg) results in uBO blocking the image with message of

> uBlock Origin has prevented the following page from loading:

`https://c.o0bc.com/wp-content/uploads/2020/06/1b3a0d6a-77c5-4f97-8d01-6e2d14f10280-850x478$large.jpg`

> Because of the following filter

`||o0bc.com^$domain=~boston.com|~bostonglobe.com`

> Found in: uBlock filters – Unbreak

**Comment by okiehsch** [comment]
Fixed.
