### ISSUE TITLE
isitdownrightnow.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4032]
### Basic Information

**Test link:** `https://www.isitdownrightnow.com/netflix.com.html`
**Category:** ads
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.38 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

placeholders

**Comment by DandelionSprout** [comment]
Placeholders:
```
isitdownrightnow.com###commentstop
isitdownrightnow.com##.ad336:upward(1)
```

**Comment by jspenguin2017** [comment]
Can someone send a PR?

**Comment by DandelionSprout** [comment]
I suppose I can. It just surprised me a bit initially, because usually you've been the one who've taken care of NanoMeow reports, plus I had a minor foot injury yesterday that distracted me from making a PR.

Give me 15min.

**Comment by jspenguin2017** [comment]
I'm quite busy these days and the amount of backlogged reports is quickly getting out of hand... Thanks for the PR, I'll review it tonight. 

Take care of yourself first though, there's no rush in fixing placeholders. And I hope you'll recover soon.
