### ISSUE TITLE
portableapps.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4037]
### Basic Information

**Test link:** `https://portableapps.com/platform/features`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

anti-adblock back in left column:

> Please Help Support Us
> 
> Please consider white-listing us or making a donation so we can keep bringing you awesome apps. If you recently donated, thank you!

`portableapps.com##+js(nostif, (), 3000)` = no works now.

**Comment by krystian3w** [comment]
`portableapps.com##+js(nostif, (), 2500)`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/4a805727b48378df58242377640fea1d9859cd1b
