### ISSUE TITLE
freegogpcgames.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#404]
### Basic Information

**Test link:** `http://freegogpcgames.com/`
**Category:** other
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
**Extension:** Nano Defender 15.0.0.80

### Additional Message

Invisible overlay when mouse clicking on the website makes the browser opening redirect link to a malicious download link, not blocked by the extension. I don't know how to fix it other than trusting my kaspersky to block the malicious link on its own. (it works)
.
Kaspersky detailed report:
```
05.12.2018 07.41.36;Dangerous URL blocked;http://dc08i221b0n8a.cloudfront.net/?nbicd=689996;http://dc08i221b0n8a.cloudfront.net/?nbicd=689996;URL;URL listed in database of malicious URLs;Google Chrome;12/05/2018 07:41:36
```

**Comment by jspenguin2017** [comment]
Can't reproduce, no popup for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://freegogpcgames.com/1063/factorio/`
**Category:** ads
**Reported from:** Portugal
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
**Extension:** Nano Defender 15.0.0.197

### Additional Message
