### ISSUE TITLE
jkanime.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4040]
### Basic Information

**Test link:** `https://jkanime.net/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

fake push notif ads, popups (maybe), crap 3p xhrs

reported on reddit: `https://www.reddit.com/r/uBlockOrigin/comments/gxe9o4/help_with_ublock/ft0tl02/`

**Comment by okiehsch** [comment]
Fixed.

**Comment by llacb47** [comment]
Are you sure this fixes the fake push notif ads?

**Comment by okiehsch** [comment]
It works on my end.
