### ISSUE TITLE
games.dailymail.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4042]
### Basic Information

**Test link:** `https://games.dailymail.co.uk/games/word-wipe`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

anti-adblock, also placeholders

**Comment by okiehsch** [comment]
Fixed.

**Comment by llacb47** [comment]
Placeholders: `games.dailymail.co.uk##div[data-element-description$=" ad"]`
