### ISSUE TITLE
comandotorrents.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4045]
### Basic Information

**Test link:** `https://comandotorrents.org/it-a-coisa-torrent-2017-dual-audio-5-1-dublado-bluray-720p-1080p-download-dublado-dual-audio/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36 Edg/83.0.478.45
**Extension:** Nano Defender 15.0.0.199

### Additional Message

this famous torrent website (`https://comandotorrents.org`) added an anti-adblock filter and it's blocking ubo/nano defender now

**Comment by okiehsch** [comment]
Fixed.
