### ISSUE TITLE
manga.adonisfansub.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4046]
### Basic Information

**Test link:** `https://manga.adonisfansub.com/manga/kimetsu-no-yaiba/bolum-58/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.148

**Comment by okiehsch** [comment]
Fixed.
