### ISSUE TITLE
mysanantonio.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#406]
### Basic Information

**Test link:** `https://www.mysanantonio.com/opinion/article/Digital-media-bubble-is-bursting-That-s-hurting-13439600.php`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
**Extension:** Nano Defender 15.0.0.80

### Additional Message

IL / g00 is loading even in Firefox which it has never done before.

**Comment by mapx-** [comment]
working for me:
`mysanantonio.com##+js(abort-on-property-read.js, I10C)`

(I get g00 only using a US IP)

**Comment by jspenguin2017** [comment]
Leftover ads banner placeholder.

**Comment by DandelionSprout** [comment]
Placeholder: `mysanantonio.com##.zoneInlineD`
