### ISSUE TITLE
wiadomosci.onet.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4070]
### Basic Information

**Test link:** `https://wiadomosci.onet.pl/kraj/koronawirus-w-polsce-rekord-zarazen-ekspert-komentuje/8bhywym`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
**Extension:** Nano Defender for Firefox 15.0.0.199

**Comment by krystian3w** [comment]
No reporduce, race condition or something?

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/84599593-6e468500-ae30-11ea-9f47-12aabab87b46.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://wiadomosci.onet.pl/szczecin/konkurs-na-polskie-imie-dla-planetoidy/d3h8cn4`
**Category:** ads
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

`##.extraListTop.extraList`

**Comment by jspenguin2017** [comment]
For https://github.com/NanoMeow/QuickReports/issues/4070#issuecomment-649593928 : 
Ads placeholders, but the provided rule does not work.

**Comment by krystian3w** [comment]
Should works:

![obraz](https://user-images.githubusercontent.com/35370833/86516147-7fc2f180-be1e-11ea-84eb-58474052f632.png) |
--- |


---
hidde whitebox bettwen:

![obraz](https://user-images.githubusercontent.com/35370833/86516177-b436ad80-be1e-11ea-9073-6da707635cd9.png) |
--- |

**Comment by jspenguin2017** [comment]
@krystian3w That rule did not work for me, the ads placeholders are still shown.

**Comment by krystian3w** [comment]
Yo try move:
 
![obraz](https://user-images.githubusercontent.com/35370833/86516362-2bb90c80-be20-11ea-8439-3e662953a056.png)

Even higher than the filter with APB syntax allows?

**Comment by jspenguin2017** [comment]
@krystian3w 
I don't understand what you are trying to say. Try to move what? 
The placeholder buster filter accepts any syntax that works with Nano.

**Comment by krystian3w** [comment]
so try:
```
wiadomosci.onet.pl##.extraListTop.extraList
#if !env_mobile
wiadomosci.onet.pl##.pageContent .extraList:style(margin-top: -315px !important;)
#endif
```

![obraz](https://user-images.githubusercontent.com/35370833/86516427-bd287e80-be20-11ea-9329-52ca3b9fe5b7.png) |
--- |

This reset whitebox in right column.

**Comment by krystian3w** [comment]
The gap after the bold paragraph need not be corrected.

**Comment by jspenguin2017** [comment]
Ah, I see. Yes, that works. Thanks.
