### ISSUE TITLE
linfoweb.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4072]
### Basic Information

**Test link:** `https://linfoweb.com/toplistes/top-6-les-vagues-les-plus-hautes-du-monde/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

https://github.com/abp-filters/abp-filters-anti-cv/issues/394

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/b127e0f4a52b2af7c00bad0aafd46e1157af28a9
