### ISSUE TITLE
aviationweek.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4076]
### Basic Information

**Test link:** `https://aviationweek.com/defense-space/missile-defense-weapons/us-air-force-investigates-hypersonic-test-mishap`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

page hidden for three seconds
add: `aviationweek.com##.content-body-wrapper:style(opacity:1!important)`

**Comment by ryanbr** [comment]
blocked tracker

https://github.com/easylist/easylist/commit/95e5abbe6e0afb64fd8aadba9d728b4d2c8cfa55

**Comment by jspenguin2017** [comment]
`t: other`: Animation annoyance. 

---

@okiehsch @mapx- Should this be fixed in uBlock annoyance filter?

**Comment by mapx-** [comment]
added

**Comment by krystian3w** [comment]
AdGuard shuld repair in `AdGuard Base` instad of `AdGuard Annoyance`.
