### ISSUE TITLE
lenovo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4078]
### Basic Information

**Test link:** `https://www.lenovo.com/sg/en/sgedu/laptops/c/laptops#type=TYPE_ATTR1`
**Category:** other
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

Images don't load. JS image loader on non-stop loading. It is a legit site (Lenovo official website). Thank you!

**Comment by mapx-** [comment]
I cannot reproduce OP issue, however are missing some elements on page (bottom, left side, chat etc)

needing
```
@@||api.useinsider.com^$domain=lenovo.com
@@||image.useinsider.com/lenovosg/$image,domain=lenovo.com
@@||tags.tiqcdn.com/utag/lenovo/$script,domain=lenovo.com
@@||inside-graph.com^$domain=lenovo.com
@@||confirmit.com/api/$domain=lenovo.com
```

@ryanbr

**Comment by ryanbr** [comment]
can the submitter test each of these whitelists

**Comment by krystian3w** [comment]
I do not think so..., Issue is very annoymus and maybe no possible to found for newbie with installed Nano Defender / Nano Adblocker.

**Comment by jspenguin2017** [comment]
The reports are anonymous by design. Just fix what you can reproduce, if the fix is not good, we will likely receive another report soon.

**Comment by jspenguin2017** [comment]
The reports are anonymous by design. Just fix what you can reproduce, if the fix is not complete, the reporter or someone else using the same website will likely submit another report.
