### ISSUE TITLE
bestofcomicbooks.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4079]
### Basic Information

**Test link:** `https://bestofcomicbooks.com/most-handsome-men-in-the-world/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

3p crap push notifs ads

**Comment by okiehsch** [comment]
Fixed.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7f0ea83a9916da0399b3709d2cc5986c35286098
