### ISSUE TITLE
dizibox.pw

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#408]
### Basic Information

**Test link:** `https://www.dizibox.pw/the-affair-4-sezon-2-bolum-izle/`
**Category:** ads
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
**Extension:** Nano Defender 15.0.0.80

### Additional Message

the video add cannot be blocked

**Comment by okiehsch** [comment]
Fixed.
