### ISSUE TITLE
tr.link

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4083]
### Basic Information

**Test link:** `https://tr.link/krJCtq`
**Category:** ads
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 OPR/68.0.3618.125
**Extension:** Nano Adblocker 1.0.0.149

**Comment by okiehsch** [comment]
Fixed.
