### ISSUE TITLE
serietvonline.fun

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4088]
### Basic Information

**Test link:** `https://serietvonline.fun/streaming/macgyver/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Raspbian Chromium/78.0.3904.108 Chrome/78.0.3904.108 Safari/537.36
**Extension:** Nano Defender 15.0.0.200

**Comment by okiehsch** [comment]
Fixed.
