### ISSUE TITLE
tikitoks.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4092]
### Basic Information

**Test link:** `https://tikitoks.com/sounds/original-sound-stephenpy01/6746655777680820994`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

**Comment by okiehsch** [comment]
Fixed.
