### ISSUE TITLE
facciabuco.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4102]
### Basic Information

**Test link:** `https://www.facciabuco.com/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
**Extension:** Nano Defender Pro 15.0.0.199

**Comment by okiehsch** [comment]
Fixed.
