### ISSUE TITLE
macwelt.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#411]
### Basic Information

**Test link:** `https://www.macwelt.de/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
**Extension:** Nano Defender 15.0.0.80

**Comment by mapx-** [comment]
```
@@||macwelt.de/js/advert.js$script,first-party
macwelt.de##+js(set-constant.js, atob, noopFunc)
```
anti adb + ads, could you test the filters ?
