### ISSUE TITLE
ustreamix.to

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4111]
### Basic Information

**Test link:** `https://ustreamix.to/index.html`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender for Firefox 15.0.0.200

### Additional Message

 The function of this site becomes corrupted due to AdBlock, turn off AdBlock or exclude it in the AdBlock settings

**Comment by krystian3w** [comment]
Sticky
