### ISSUE TITLE
led.korail.pe.kr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4115]
### Basic Information

**Test link:** `https://led.korail.pe.kr/KORAIL.php`
**Category:** breakage
**Reported from:** South Korea
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

blocking entire contents

**Comment by mapx-** [comment]
`led.korail.pe.kr#@#.adsbygoogle`

@yous

**Comment by yous** [comment]
Seems like it comes from other filters other than YousList. YousList has `ins.adsbygoogle` variants only, and the site has `div` with `.adsbygoogle`.

**Comment by mapx-** [comment]
I know - but you could fix it in your list.

**Comment by mapx-** [comment]
@ryanbr
