### ISSUE TITLE
electronics.howstuffworks.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4124]
### Basic Information

**Test link:** `https://electronics.howstuffworks.com/lcd-projectors1.htm`
**Category:** ads
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.45 Safari/537.36
**Extension:** Nano Defender 15.0.0.200

### Additional Message

placeholders

**Comment by DandelionSprout** [comment]
```
! https://electronics.howstuffworks.com/lcd-projectors1.htm
howstuffworks.com##.recirc-panel
howstuffworks.com##div[data-track-gtm="Recirculate Widget"]
```
