### ISSUE TITLE
urlcash.me

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#413]
### Basic Information

**Test link:** `http://urlcash.me/Da1dfd`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
**Extension:** Nano Defender 15.0.0.80

**Comment by jspenguin2017** [comment]
The URL may have expired. 

@okiehsch Popup?
