### ISSUE TITLE
loktrk.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4130]
### Basic Information

**Test link:** `http://loktrk.com/help/removeAB.php`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36 Edg/83.0.478.45
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

This isn't really a bug but I don't know how else to bring this to your attention. It appears this site is used to force visitors to their clients websites to disable their adblocker. It's really quite clever in an annoying type way since there doesn't seem a way around it. Maybe you guys can figure it out. If you go to `www.babupc.com`, this webpage appears to force you remove your adblock but even if I disable your plugin (which I don't want to) it still refuses to let me through.

**Comment by jspenguin2017** [comment]
@okiehsch Hard anti-adblock.

**Comment by okiehsch** [comment]
> go to www.babupc.com, this webpage appears to force you remove your adblock but even if I disable your plugin


Same on my end.

**Comment by llacb47** [comment]
`Mixed Content: The page at 'https://babupc.com/' was loaded over HTTPS, but requested an insecure script 'http://www.loktrk.com/gLoader.php?GID=56435&go=&sid='. This request has been blocked; the content must be served over HTTPS.`

LOL, when you use super old anti-adblock code that doesn't support HTTPS. 

The code here, in case it goes offline: `https://pastebin.com/nZfPdQbM`

```
||loktrk.com^$3p
babupc.com##+js(set, awm, true)
```

**Comment by jspenguin2017** [comment]
Hum... Putting this on hold for now.

**Comment by mapx-** [comment]
> This Account has been suspended.

**Comment by jspenguin2017** [comment]
@mapx- Where did you see that message?

**Comment by mapx-** [comment]
> @mapx- Where did you see that message?

not anymore, fixed
