### ISSUE TITLE
valor.globo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4132]
### Basic Information

**Test link:** `https://valor.globo.com/empresas/noticia/2020/06/16/cinemark-e-cinepolis-vao-a-justica-para-reduzir-gastos.ghtml`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

copy and paste hijacking - adds stuff

**Comment by jspenguin2017** [comment]
`t: other`: Anti-copy.
