### ISSUE TITLE
virginradio.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4137]
### Basic Information

**Test link:** `https://www.virginradio.it/sezioni/1219/virgin-radio-rock-classic?refresh_ce`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
**Extension:** Nano Adblocker 1.0.0.148

### Additional Message

Doesn't play the radio when the blocker is on.

**Comment by okiehsch** [comment]
Fixed.
