### ISSUE TITLE
stackify.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4138]
### Basic Information

**Test link:** `https://stackify.com/7-essential-best-practices-to-follow-when-adopting-a-devops-model/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

banner ads in the middle of the article

**Comment by jspenguin2017** [comment]
(Pinged on Slack)
