### ISSUE TITLE
softwaresde.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4140]
### Basic Information

**Test link:** `https://softwaresde.com/windows/download-5bf05812bc1f718ef29e52678be1d797-1667.html/showlink-3071`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.200

### Additional Message

Pop-up with content as below:
AdBlock :-(
We have detected that you are using AdBlock Plus or some other adblocking software. We need money to operate the site, and almost all of that comes from our online advertising.

We would appreciate it very much if you whitelist our website in your AdBlocker.

Thank you

**Comment by okiehsch** [comment]
Fixed.
