### ISSUE TITLE
video.repubblica.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4141]
### Basic Information

**Test link:** `https://video.repubblica.it/cronaca/batterio-killer-in-reparto-pediatrico-a-verona-salvini-mangia-le-ciliegie-mentre-zaia-parla-dell-inchiesta/362339/362893?ref=RHPPTP-BS-I257387636-C12-P1-S4.3-T1`
**Category:** anti-adblock
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

Impossibile to reproduce videos with active adblocker.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://video.repubblica.it/motori/a-bordo-della-ferrari-con-leclerc-in-soggettiva-per-le-vie-di-maranello/362561/363115?ref=RHPPTP-BS-I253430426-C12-P12-S1.3-T1`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.200

### Additional Message

Videos on repubblica.it don't load unless adblockers are removed.
No errors. The container doesn't load.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://video.repubblica.it/politica/salvini-e-i-contestatori-di-mondragone-puzzo-ci-credo-stai-tu-due-ore-in-mezzo-a-quella-gentaglia/363304/363861?ref=RHPPTP-BH-I260642867-C12-P4-S2.4-F4`
**Category:** breakage
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

video is blocked

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://video.repubblica.it/cronaca/vicenza-poliziotto-prende-per-il-collo-ragazzo-nero-il-battibecco-prima-del-fermo/365445/365997?ref=RHPPTP-BH-I264447193-C12-P2-S4.4-T2`
**Category:** breakage
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
**Extension:** Nano Defender Pro 15.0.0.201

### Additional Message

There should be a video in this page but it's not shown

**Comment by mapx-** [comment]
`@@||scripts.kataweb.it/wt/wt.js$script,domain=video.repubblica.it`

@khrin
