### ISSUE TITLE
malasngeblog.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4146]
### Basic Information

**Test link:** `https://www.malasngeblog.com/2019/07/cara-buat-akun-gmail-tanpa-no-hp.html`
**Category:** other
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
**Extension:** Nano Defender 15.0.0.200

### Additional Message

anti right click

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select.
