### ISSUE TITLE
games.chicagotribune.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4150]
### Basic Information

**Test link:** `https://games.chicagotribune.com/games/best-free-themed-puzzles`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:77.0) Gecko/20100101 Firefox/77.0
**Extension:** Nano Defender for Firefox 15.0.0.200

**Comment by llacb47** [comment]
Site is clone of https://github.com/NanoMeow/QuickReports/issues/4042
