### ISSUE TITLE
gaming-style.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4152]
### Basic Information

**Test link:** `https://www.gaming-style.com/RushTeam/index.php?page=Game`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
**Extension:** Nano Defender 15.0.0.200

### Additional Message

Detects nano wıth adblocker+defender

**Comment by okiehsch** [comment]
Fixed.
