### ISSUE TITLE
clinixplayer.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4156]
### Basic Information

**Test link:** `https://clinixplayer.com/links/watch-download/`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.200

**Comment by okiehsch** [comment]
Fixed.
