### ISSUE TITLE
news-on-tour.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4158]
### Basic Information

**Test link:** `https://www.news-on-tour.de/anti-adblocker/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

Sie haben einen ADBLOCKER aktiv! Darum können Sie den Beitrag nicht lesen…

**Comment by okiehsch** [comment]
Fixed.
