### ISSUE TITLE
abola.pt

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4161]
### Basic Information

**Test link:** `https://www.abola.pt/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
**Extension:** Nano Defender for Firefox 15.0.0.200

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/hckbn5/cant_get_rid_of_this/fvk47al/

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/85232986-a9146400-b3c0-11ea-886b-c061c22bcefa.png)

**Comment by jspenguin2017** [comment]
@gwarser Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/85232986-a9146400-b3c0-11ea-886b-c061c22bcefa.png)

**Comment by jspenguin2017** [comment]
@gwarser @okiehsch Actually, there's a soft anti-adblock: `abola.pt###abola-default-ad`
![image](https://user-images.githubusercontent.com/7283682/85233158-99494f80-b3c1-11ea-9ddb-31253695c877.png)

**Comment by okiehsch** [comment]
Fixed.
