### ISSUE TITLE
ytdown.cc

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4165]
### Basic Information

**Test link:** `https://ytdown.cc/`
**Category:** other
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
**Extension:** Nano Defender for Firefox 15.0.0.200

### Additional Message

breakage , can't insert youtube url into online downloader

**Comment by okiehsch** [comment]
Fixed.
