### ISSUE TITLE
keepv.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4166]
### Basic Information

**Test link:** `https://keepv.id/`
**Category:** ads
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
**Extension:** Nano Defender for Firefox 15.0.0.200

### Additional Message

popups on clicking go button (insert video url then clicking go)

**Comment by okiehsch** [comment]
Fixed.
