### ISSUE TITLE
savethevideo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4167]
### Basic Information

**Test link:** `https://www.savethevideo.com/download?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DQeOOpkb0Tyo`
**Category:** ads
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
**Extension:** Nano Defender for Firefox 15.0.0.200

### Additional Message

popups on clicking download
first go to `www.savethevideo.com`
try to insert any youtube video and click download ,popup ads appear

**Comment by okiehsch** [comment]
Fixed.
