### ISSUE TITLE
arponag.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4169]
### Basic Information

**Test link:** `https://arponag.xyz/Trigon`
**Category:** anti-adblock
**Reported from:** Chile
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

no funciona en esa pagina

**Comment by okiehsch** [comment]
Fixed.
