### ISSUE TITLE
kentonline.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4172]
### Basic Information

**Test link:** `https://www.kentonline.co.uk/whitstable/news/experts-stunned-by-weather-phenomenon-over-kent-228963/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.200

**Comment by llacb47** [comment]
`http://voldffgkdsllkjthlkjt.b-cdn.net/`

![image](https://user-images.githubusercontent.com/16567977/85239738-324c8a80-b403-11ea-8f01-71b6097f22f2.png)

😂
