### ISSUE TITLE
userupload.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4175]
### Basic Information

**Test link:** `https://userupload.net/35s5lso4j04j`
**Category:** breakage
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
**Extension:** Nano Defender for Firefox 15.0.0.200

### Additional Message

blocking countdown
cannot download

**Comment by mapx-** [comment]
fixed
