### ISSUE TITLE
codeproject.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4177]
### Basic Information

**Test link:** `https://www.codeproject.com/Articles/494/ObjectLookup-Utility`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

placeholders

**Comment by DandelionSprout** [comment]
```
! https://www.codeproject.com/Articles/494/ObjectLookup-Utility
codeproject.com##.bottom-promo
codeproject.com###ctl00_RightSideBar
! https://www.codeproject.com/
codeproject.com##.align-center.padded-top
```

**Comment by jspenguin2017** [comment]
Another test link: `https://www.codeproject.com/`
