### ISSUE TITLE
fulltip.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4178]
### Basic Information

**Test link:** `https://fulltip.net/install-checkra1n-on-a-pc-without-a-hackintosh.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

**Comment by okiehsch** [comment]
Fixed.
