### ISSUE TITLE
lagom.nl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4183]
### Basic Information

**Test link:** `http://www.lagom.nl/lcd-test/`
**Category:** other
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36 Edg/83.0.478.54
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

Blank; ruins entire webpage

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `http://www.lagom.nl/lcd-test/conclusion.php`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

`lagom.nl##.ad`

**Comment by jspenguin2017** [comment]
Can't reproduce breakage, ads placeholders fixed.
