### ISSUE TITLE
vidbem.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4184]
### Basic Information

**Test link:** `https://www.vidbem.com/embed-qyxga8vz2hh8.html`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

https://github.com/abp-filters/abp-filters-anti-cv/issues/397

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/9ae7394380228ea48dad2def4943d8e053fbd635

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/9ae7394380228ea48dad2def4943d8e053fbd635
