### ISSUE TITLE
tpaste.in

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4187]
### Basic Information

**Test link:** `https://tpaste.in/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4166.0 Safari/537.36 Edg/85.0.545.0
**Extension:** Nano Defender 15.0.0.200

### Additional Message

Original URL: `https://tpaste.in/premium-accounts/express-vpn-free-windows-license-keys/`

**Comment by okiehsch** [comment]
Fixed,
