### ISSUE TITLE
edailybuzz.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4196]
### Basic Information

**Test link:** `https://edailybuzz.com/2020/04/09/where-is-tony-britts-now-tony-britts-wiki-death-wife-net-worth-fitness-instructor-funeral/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

Tons of blocking done here script wise. Left clicks, right click, developer mode and mobile as well.

**Comment by llacb47** [comment]
Firefox needs only:
```
edailybuzz.com##^script[id^="wccp"]
edailybuzz.com##^style:has-text(/user-select|selection/)
edailybuzz.com##+js(aopr, anOptions)
```

Chrome needs:
```
edailybuzz.com##+js(acis, jQuery, wccp)
edailybuzz.com##+js(acis, document.oncontextmenu)
edailybuzz.com##+js(acis, document.ondragstart)
edailybuzz.com##+js(aopr, anOptions)
edailybuzz.com##*:style(user-select:auto!important;cursor:auto!important)
edailybuzz.com##*::selection:style(background-color:#338FFF!important)
```

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-copy, anti-select.

**Comment by krystian3w** [comment]
`opportunitydesk.org##*::selection:style(background-color: #3399FF !important)`
`edailybuzz.com##*::selection:style(background-color:#338FFF!important)`

maybe the best use same hex number in the feature?

**Comment by jspenguin2017** [comment]
It probably should be `initial` instead of a hex value actually.

**Comment by jspenguin2017** [comment]
`edailybuzz.com` needs UserCSS actually... https://github.com/NanoMeow/QuickReports/issues/4267

**Comment by jspenguin2017** [comment]
@krystian3w Yea, they probably should be the browser default hex value. Although I'm not sure why `initial` doesn't work and an explicit hex value needs to be given. I don't think that's a problem but feel free to open an issue in the uAssets repository. 

---

`edailybuzz.com` needs UserCSS actually... https://github.com/NanoMeow/QuickReports/issues/4267

**Comment by jspenguin2017** [comment]
@krystian3w Yea, they probably should be the browser default hex value. Although I'm not sure why `initial` doesn't work and an explicit hex value needs to be given. I don't know what's the correct hex value, but feel free to open an issue in the uAssets repository. 

---

`edailybuzz.com` needs UserCSS actually... https://github.com/NanoMeow/QuickReports/issues/4267
