### ISSUE TITLE
wunderground.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4203]
### Basic Information

**Test link:** `https://www.wunderground.com/wundermap?lat=35.15&lon=-90.21&radar=1`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

The radar is blank (no map, only white screen) and the side controls are missing.

**Comment by mapx-** [comment]
`||wunderground.com/bundle-next/scripts.$badfilter` => EL guys notified on slack
