### ISSUE TITLE
sourceforge.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4212]
### Basic Information

**Test link:** `https://sourceforge.net/projects/skim-app/files/latest/download`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

"Get a Free VoIP Quote" ads

**Comment by jspenguin2017** [comment]
(Pinged on Slack)

**Comment by jspenguin2017** [comment]
https://github.com/easylist/easylist/commit/bba54edfd88278e2fd20adda2dc8bdfe68939b79
