### ISSUE TITLE
dove.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4213]
### Basic Information

**Test link:** `https://www.dove.com/us/en/men-care.html#`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

Cannot open website menus with adblock active

**Comment by llacb47** [comment]
Easyprivacy rule `/config/analytics.js` causing breakage, 

add `@@||dove.com/etc/ui/dovemencare/clientlibs/core/core/config/analytics.js$script,~third-party`
