### ISSUE TITLE
uploadraja.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4216]
### Basic Information

**Test link:** `https://uploadraja.com/s7qq5d96pnpd`
**Category:** ads
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
**Extension:** Nano Defender for Firefox 15.0.0.200

### Additional Message

popups
fixable with `uploadraja.com##+js(acis, adcashMacros)`

**Comment by ghajini** [comment]
`uploadraja.com/fqyolwra51pv`

Popup ads
