### ISSUE TITLE
androidhive.info

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4238]
### Basic Information

**Test link:** `https://www.androidhive.info/2014/07/3-ways-to-manage-android-sd-card-and-phone-memory/`
**Category:** anti-adblock
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

if you enable addblock it just removes all the information if adblock is disabled all the info comes in but with ads ofcours

**Comment by mapx-** [comment]
`androidhive.info#@#.tag-sponsored`

@ryanbr
