### ISSUE TITLE
ilgeniodellostreaming.gs

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4239]
### Basic Information

**Test link:** `https://ilgeniodellostreaming.gs/film/john-wick-r7/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

**Comment by okiehsch** [comment]
Fixed + ads + right click disabled.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click.
