### ISSUE TITLE
tattle.life

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4243]
### Basic Information

**Test link:** `https://tattle.life/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 10; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0
**Extension:** Nano Defender for Firefox 15.0.0.200

### Additional Message

Original URL: `https://tattle.life/threads/jack-monroe-38-will-she-call-her-next-cat-sue-purrkins.7210/page-2`

Anti-adblock blocks the whole site.

**Comment by okiehsch** [comment]
Fixed.
