### ISSUE TITLE
anywho.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4247]
### Basic Information

**Test link:** `https://www.anywho.com/reverse-phone-lookup`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

placeholders

**Comment by DandelionSprout** [comment]
I seem to be unable to connect to it tonight. Chrome on my PC claims "Connection timed out".
