### ISSUE TITLE
mypornsnap.top

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4249]
### Basic Information

**Test link:** `https://mypornsnap.top/photos/16/pinterest-getty/9f054d70088d5b89ca4ae1d6396d8637-to-bring-mania-jpg`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.149

### Additional Message

popunders and crap 3p

nsfw site but most of the page is not nsfw

**Comment by okiehsch** [comment]
Fixed.
