### ISSUE TITLE
hubblespacetelescope.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4253]
### Basic Information

**Test link:** `http://hubblespacetelescope.blogspot.com/2017/06/fire-tv-stick.html?m=1`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
**Extension:** Nano Defender for Firefox 15.0.0.200

**Comment by Yuki2718** [comment]
The page is intentionally made to be broken if EL is enabled. The blog author made many hostile remarks against ad-blocker in other pages of the blog. IDK if we should make a whitelist for such a page.
