### ISSUE TITLE
mtlblog.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4263]
### Basic Information

**Test link:** `https://www.mtlblog.com/news/canada/qc/montreal/montreal-weather-is-looking-like-another-heatwave-this-week`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.150

### Additional Message

Placeholders

**Comment by DandelionSprout** [comment]
Already fixed in AdGuard Base through `mtlblog.com##.ad`.
