### ISSUE TITLE
tajemnice-swiata.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#427]
### Basic Information

**Test link:** `https://www.tajemnice-swiata.pl/432-hz-zakazany-stroj-w-muzyce/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.113 Safari/537.36 Vivaldi/2.1.1337.51
**Extension:** Nano Defender 15.0.0.80

**Comment by okiehsch** [comment]
I am not sure if the new polish anti-adblock list will handle such issues from now on.

@olegwukr fyi `tajemnice-swiata.pl##+js(fuckadblock.js-3.2.0)` fixes the issue on my end.

**Comment by krystian3w** [comment]
fan sister site: `odkrywamyzakryte.com##+js(fuckadblock.js-3.2.0)`

Also help `generichide` and this: `##+js(abort-on-property-write.js, adBlockDetected)`

**Comment by jspenguin2017** [comment]
https://github.com/NanoMeow/QuickReports/issues/1630

Don't dig up old issues.
