### ISSUE TITLE
moeimg.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4271]
### Basic Information

**Test link:** `http://moeimg.net/`
**Category:** ads
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.85 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.150

### Additional Message

small placeholders in side bar. thanks.

**Comment by DandelionSprout** [comment]
Reported to AdGuard Japanese through https://github.com/AdguardTeam/AdguardFilters/issues/58879.
