### ISSUE TITLE
spiele-umsonst.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4280]
### Basic Information

**Test link:** `https://www.spiele-umsonst.de/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.150

**Comment by okiehsch** [comment]
Fixed Google Contributor anti-adblock message.

**Comment by llacb47** [comment]
There's also an ad for World of tanks, is it fixed in regional filters?

**Comment by jspenguin2017** [comment]
That is fixed in the German regional filters.

**Comment by jspenguin2017** [comment]
Yes, that is fixed in the German regional filters.
