### ISSUE TITLE
revivelink.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4281]
### Basic Information

**Test link:** `http://revivelink.com/GNIE7R`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.150

### Additional Message

unblocked 3p crap

**Comment by okiehsch** [comment]
Already fixed. https://github.com/uBlockOrigin/uAssets/commit/66efc81d90b70ea0d9d3d016bc37a7d8e51e2efb

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/66efc81d90b70ea0d9d3d016bc37a7d8e51e2efb
