### ISSUE TITLE
usereserva.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4290]
### Basic Information

**Test link:** `https://www.usereserva.com/c/adulto/reserva/reserva-colecoes-mascaras`
**Category:** breakage
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.150

**Comment by okiehsch** [comment]
Fixed.
