### ISSUE TITLE
motortrend.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4291]
### Basic Information

**Test link:** `https://www.motortrend.com/news/dodge-future-fca-psa/?wc_mid=4035%3A19489&wc_rid=4035%3A354850&_wcsid=6188DBADE230C909087BDB2EF9577EEFFDA323D399DB8329&fbclid=IwAR1y5FC-TjA4HhIo8TTIKZuHPsHYo_WqVFViK7dIWIUl_1nvWBb3NDccH1E`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

### Additional Message

Reports a generic full-page error that hides the article, only if adblocker is turned on.

**Comment by okiehsch** [comment]
Not sure if the breakage by the site is deliberate to block adblock users.
I will fix it in `uBO-filters`.

**Comment by llacb47** [comment]
![image](https://user-images.githubusercontent.com/16567977/87216255-02aae700-c30c-11ea-8ef0-5e859e3deb9a.png)

I hope this is accidental... Imagine if they were to push some buggy code that would normally be inconsequential but because of this choice, nobody would have access to the site.
