### ISSUE TITLE
dl-protect.top

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4301]
### Basic Information

**Test link:** `https://www.dl-protect.top/liens/`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Edg/83.0.478.61
**Extension:** Nano Adblocker 1.0.0.150

**Comment by okiehsch** [comment]
Fixed.
