### ISSUE TITLE
uplod.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4304]
### Basic Information

**Test link:** `https://uplod.net/15tlq50znp1c4kpt`
**Category:** anti-adblock
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
**Extension:** Nano Defender 15.0.0.201

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select, anti-hotkey.
