### ISSUE TITLE
highschooldxd-gamecards.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4311]
### Basic Information

**Test link:** `https://highschooldxd-gamecards.blogspot.com/`
**Category:** anti-adblock
**Reported from:** El Salvador
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

**Comment by okiehsch** [comment]
Fixed.
