### ISSUE TITLE
biguz.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4313]
### Basic Information

**Test link:** `https://biguz.net/video/?id=10534090&name=rough-sex-with-young-blonde-kenzie-reeves`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.151

### Additional Message

NSFW NSFW NSFW

Prerolls not blocked

Maybe also unblocked on these websites (haven't check): `https://biguzplayer.com/`

**Comment by mapx-** [comment]
it seems working 
`||biguz.net/*.php$xhr,1p`

@ryanbr

**Comment by jspenguin2017** [comment]
(Pinged on Slack)
