### ISSUE TITLE
dutafilm.red

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4314]
### Basic Information

**Test link:** `https://dutafilm.red/film/nonton-suki-demo-nai-kuseni-2016-otvtoq`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

### Additional Message

cannot play the movies, appears text "Hayoloh!"

**Comment by mapx-** [comment]
only popups, no breakage
