### ISSUE TITLE
akvideo.stream

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4320]
### Basic Information

**Test link:** `https://akvideo.stream/api/vcmod/fastredirect/streaming.php?id=251491`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
**Extension:** Nano Defender 15.0.0.201

### Additional Message

cannot solve captcha

**Comment by okiehsch** [comment]
I can solve the captcha, the video player is hidden.
Fixed.
