### ISSUE TITLE
javsub.co

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4337]
### Basic Information

**Test link:** `https://javsub.co/adn-031-evil-visitors-from-the-past-jav-english/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

**Comment by okiehsch** [comment]
Fixed + popups.
