### ISSUE TITLE
bimmertoday.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4338]
### Basic Information

**Test link:** `https://www.bimmertoday.de/2020/07/17/asa-kompressor-bmw-tuning-ikone-verkauft-nur-noch-3-tage/`
**Category:** breakage
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 10; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0
**Extension:** Nano Adblocker 1.0.0.151

**Comment by mapx-** [comment]
broken by `fanboy's annoyances` list
needing `bimmertoday.de#@#.push-container:not(body):not(html)`

**Comment by mapx-** [comment]
@ryanbr
