### ISSUE TITLE
w.animesanka.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4341]
### Basic Information

**Test link:** `https://w.animesanka.com/`
**Category:** breakage
**Reported from:** Algeria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
**Extension:** Nano Adblocker 1.0.0.151

### Additional Message

Original URL: `https://w.animesanka.com/2019/09/hunter-x-hunter-2011-1080p.html`

**Comment by okiehsch** [comment]
I can't read arabic, so no clue if there is any breakage or not.
I fixed popups and right-click annoyance.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-hotkey.
