### ISSUE TITLE
watchseries.movie

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4344]
### Basic Information

**Test link:** `https://www6.watchseries.movie/series/star-trek-the-next-generation-season-5-yor-episode-15`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4205.0 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

popup ads

**Comment by okiehsch** [comment]
Fixed. https://github.com/uBlockOrigin/uAssets/commit/d0ea7c04528ff70654da38ce3f415c6659aea494

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/d0ea7c04528ff70654da38ce3f415c6659aea494
