### ISSUE TITLE
f.tabtter.jp

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4350]
### Basic Information

**Test link:** `https://f.tabtter.jp/app/client.cgi`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.3
**Extension:** Nano Defender Pro 15.0.0.201

**Comment by llacb47** [comment]
![image](https://user-images.githubusercontent.com/16567977/87891700-d7f61800-ca08-11ea-998a-93a3be8c2735.png)

Google translated:
![image](https://user-images.githubusercontent.com/16567977/87891707-e0e6e980-ca08-11ea-80b7-f7086cffd7a5.png)

Needs account to test (login with twitter). Comes back every refresh. This works:
`||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect=noopjs,domain=f.tabtter.jp`
