### ISSUE TITLE
dl.helow.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4351]
### Basic Information

**Test link:** `https://dl.helow.id/bitcoin-drops/`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

### Additional Message

`https://onsafelink.com/m/2PxUoHl7`

**Comment by jspenguin2017** [comment]
@okiehsch Fake buttons on `https://onsafelink.com/m/2PxUoHl7` and the second page (`https://dl.ocanoke.com/make-money-from-the-internet/2PxUoHl7`).

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
@okiehsch There are still fake buttons on `https://onsafelink.com/m/2PxUoHl7`: 
![image](https://user-images.githubusercontent.com/7283682/88249981-54843300-cc63-11ea-8e6c-1677c9a57331.png)

**Comment by okiehsch** [comment]
That link redirects me to `https://dl.helow.id/how-to-create-an-account-on-unidax/`

**Comment by okiehsch** [comment]
I get an ati adblock message but no fake button.
![image](https://user-images.githubusercontent.com/16838044/88250210-2cb6be80-cca7-11ea-8e79-33fd152aba9a.png)

**Comment by okiehsch** [comment]
If you post a filter fixing the fake button on your end I will add it.

**Comment by jspenguin2017** [comment]
@okiehsch This works for me: 
```
dl.helow.id##a[href="https://www.ocanoke.com/"]
dl.helow.id##a[href="#"]
```

**Comment by okiehsch** [comment]
Added, thx.
