### ISSUE TITLE
ilgeniodellostreaming.gy

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4355]
### Basic Information

**Test link:** `https://ilgeniodellostreaming.gy/episodi/greys-anatomy-14x1/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 OPR/69.0.3686.77
**Extension:** Nano Adblocker 1.0.0.152

**Comment by okiehsch** [comment]
Fixed.
