### ISSUE TITLE
androidpolice.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4357]
### Basic Information

**Test link:** `https://www.androidpolice.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

soft anti-adblock / fallback ads

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance.

**Comment by okiehsch** [comment]
Fixed.
