### ISSUE TITLE
scriptinghelpers.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4360]
### Basic Information

**Test link:** `https://scriptinghelpers.org/blog/scripting-helpers-forum-data-breach`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://scriptinghelpers.org/questions/109550/why-wont-my-currency-shop-button-give-the-money`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

ANTI-ADBLOCK

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance.

**Comment by okiehsch** [comment]
Fixed.
