### ISSUE TITLE
wall.alphacoders.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4361]
### Basic Information

**Test link:** `https://wall.alphacoders.com/search.php?search=black`
**Category:** ads
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

**Comment by llacb47** [comment]
Placeholders

`wall.alphacoders.com##[class*="ads-"]`
