### ISSUE TITLE
tucao.one

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4362]
### Basic Information

**Test link:** `https://www.tucao.one/`
**Category:** ads
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

baner ads

**Comment by jspenguin2017** [comment]
@okiehsch NSFW banners, do you know who to ping for this?

**Comment by llacb47** [comment]
@cjx82630

**Comment by okiehsch** [comment]
`EasyList China` has filters for that site but I don't think they have a github repo.

**Comment by jspenguin2017** [comment]
(Asked on Slack)

**Comment by cjx82630** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
`https://hg.adblockplus.org/easylistchina/rev/2751e8b7637c`
