### ISSUE TITLE
vladan.fr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4368]
### Basic Information

**Test link:** `https://www.vladan.fr/flash-dell-perc-h310-with-it-firmware/#:~:text=The%20thing%20is%20that%20the%20Dell%20Perc%20H310,6Gbs%20throughput.%20The%20firmware%20used%20is%20Dell%27s%20firmware.`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.40
**Extension:** Nano Defender Pro 15.0.0.201

### Additional Message

black screen with notification to disable ad-block

**Comment by okiehsch** [comment]
Fixed.
