### ISSUE TITLE
xxxfiles.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4371]
### Basic Information

**Test link:** `https://www.xxxfiles.com/videos/162219/4aeddd6c8a71feb34f59238a884a4c54/?sid=12320`
**Category:** ads
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
**Extension:** Nano Adblocker 1.0.0.151

**Comment by okiehsch** [comment]
Fixed. NSFW.
