### ISSUE TITLE
turkcehentai.club

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4373]
### Basic Information

**Test link:** `https://www.turkcehentai.club/`
**Category:** anti-adblock
**Reported from:** Cyprus
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 OPR/69.0.3686.77 (Edition Campaign 34)
**Extension:** Nano Defender 15.0.0.201

**Comment by okiehsch** [comment]
Fixed.
