### ISSUE TITLE
loadsamusicsarchives.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4375]
### Basic Information

**Test link:** `http://loadsamusicsarchives.blogspot.com/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4208.0 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

popup ads

**Comment by llacb47** [comment]
`||weatherforecastmap.com^$3p`

**Comment by okiehsch** [comment]
Fixed.
