### ISSUE TITLE
taxifarefinder.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4376]
### Basic Information

**Test link:** `https://www.taxifarefinder.com/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4209.3 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

Site does not function properly when nano adblocker is active

**Comment by mapx-** [comment]
@ryanbr `ezodn`  stuff

**Comment by ryanbr** [comment]
Should this not work? https://github.com/easylist/easylist/commit/bbc34c49940 @mapx-

**Comment by mapx-** [comment]
try going to (firefox for example)
`https://www.taxifarefinder.com/newsroom/2020/06/11/is-it-safe-to-take-a-taxi-now/`

`dayton` is not enough

![image](https://user-images.githubusercontent.com/10303732/88479006-aae7bf00-cf4c-11ea-81cc-eb11bf46f896.png)
