### ISSUE TITLE
bukadrive.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4379]
### Basic Information

**Test link:** `https://bukadrive.com/file/4397584507`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

**Comment by llacb47** [comment]
`bukadrive.com##+js(set, fabActive, false)`
