### ISSUE TITLE
watchtvseries.one

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4381]
### Basic Information

**Test link:** `https://watchtvseries.one/black-monday-season-2-episode-10/`
**Category:** ads
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
**Extension:** Nano Defender 15.0.0.201

### Additional Message

Original URL: `about:newtab`

popup ads

**Comment by okiehsch** [comment]
Fixed.
