### ISSUE TITLE
horriblesubs.info

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4383]
### Basic Information

**Test link:** `https://horriblesubs.info/shows/digimon-adventure-2020/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.44
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

Is there a filter to block bs like this?

```
! 7/25/2020 https://horriblesubs.info
horriblesubs.info/images/b/covid19.png
```

(aside adding to my own rules)

**Comment by jspenguin2017** [comment]
The bottle shows in guest mode as well, so it's not anti-adblock. 

Placeholders fixed.
