### ISSUE TITLE
parispi.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4384]
### Basic Information

**Test link:** `https://www.parispi.net/news/local_news/article_26dd6912-cdda-11ea-a796-9b1a44abe960.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

### Additional Message

Ads are being blocked by your browser.
Please disable your ad blocker, whitelist our site, or purchase a subscription

**Comment by llacb47** [comment]
This issue is on all town news sites. This works:

```
@@||townnews.com^*/tncms/*/ads/*/tnt.ads.advertisements.$script
```
