### ISSUE TITLE
ibtimes.sg

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4394]
### Basic Information

**Test link:** `https://www.ibtimes.sg/healthy-young-adults-also-take-weeks-recover-covid-19-cdc-reveals-49047`
**Category:** other
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Adblocker 1.0.0.151

### Additional Message

video follows you as you scroll

**Comment by llacb47** [comment]
`ibtimes.sg##+js(aopr, dfpSlots.cmd.push)`

**Comment by jspenguin2017** [comment]
Floating video players are out of scope. Ads placeholder fixed.
