### ISSUE TITLE
simply-hentai.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4397]
### Basic Information

**Test link:** `https://www.simply-hentai.com/neon-genesis-evangelion/karma-evangelion/page/10392072`
**Category:** anti-adblock
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

**Comment by okiehsch** [comment]
`simply-hentai.com##+js(aeld, , [native code])`
breaks the ability to browse through the comic by clicking previous or next.
I don't see any anti adblock message after removing that filter on my end.
