### ISSUE TITLE
themeplatinum.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#440]
### Basic Information

**Test link:** `https://themeplatinum.blogspot.com/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
**Extension:** Nano Defender 15.0.0.81

**Comment by okiehsch** [comment]
Fixed.
