### ISSUE TITLE
news.sky.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4401]
### Basic Information

**Test link:** `https://news.sky.com/story/one-billion-tonnes-of-plastic-waste-to-be-dumped-by-2040-predicts-study-12034933`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

```
news.sky.com##[data-format="leaderboard"]
```

**Comment by DandelionSprout** [comment]
Seems to already be fixed in AdGuard Base through `news.sky.com##div[data-ad-format="leaderboard"]`.
