### ISSUE TITLE
cidade.iol.pt

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4405]
### Basic Information

**Test link:** `https://cidade.iol.pt/`
**Category:** anti-adblock
**Reported from:** Portugal
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.44
**Extension:** Nano Defender 15.0.0.201

### Additional Message

Footer message whilst blocking ads

**Comment by okiehsch** [comment]
Fixed.
