### ISSUE TITLE
javjunkies.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4406]
### Basic Information

**Test link:** `http://www.javjunkies.com/main/2020/07-24-11/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
**Extension:** Nano Adblocker 1.0.0.151

### Additional Message

Images not loading. Tested on private mode on Microsoft Edge. Images load correctly but not not when Nanoblocker is active.

**Comment by mapx-** [comment]
@ryanbr
