### ISSUE TITLE
scrapbox.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4415]
### Basic Information

**Test link:** `https://scrapbox.io/shokai/AD1_A`
**Category:** breakage
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

**Comment by Yuki2718** [comment]
I put the below comment in a wrong issue (deleted), it was for this issue:
> The page is intentionally made to be broken if EL is enabled. The blog author made many hostile remarks against ad-blocker in other pages of the blog. IDK if we should make a whitelist for such a page.
