### ISSUE TITLE
hotexamples.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4418]
### Basic Information

**Test link:** `https://hotexamples.com/examples/helloworld/SayHello/world/php-sayhello-world-method-examples.html`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

**Comment by DandelionSprout** [comment]
I could only find `hotexamples.com##.page-side-banner`, which had no visible impact on the page after being hidden.

**Comment by jspenguin2017** [comment]
Also: `https://hotexamples.com/examples/-/-/prepareFilename/php-preparefilename-function-examples.html`
