### ISSUE TITLE
siteapps.caa.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4420]
### Basic Information

**Test link:** `https://siteapps.caa.co.uk/g-info/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

form doesn't submit

`@@||siteapps.caa.co.uk/scripts/plugins/analytics/ga.min.js`

**Comment by okiehsch** [comment]
Fixed in `EasyPrivacy`.
