### ISSUE TITLE
doujindesu.info

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4428]
### Basic Information

**Test link:** `https://doujindesu.info/`
**Category:** other
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

### Additional Message

anti right click

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select.
