### ISSUE TITLE
miniwebtool.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#443]
### Basic Information

**Test link:** `https://www.miniwebtool.com/mac-address-generator/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.81

### Additional Message

Asking to disable adblock

**Comment by jspenguin2017** [comment]
@okiehsch Hard anti-adblock, overlay comes up every time you click generate. 
![image](https://user-images.githubusercontent.com/7283682/50047869-7a0a8d00-007b-11e9-894e-dd3b412fb5b7.png)
