### ISSUE TITLE
humanbenchmark.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4430]
### Basic Information

**Test link:** `https://humanbenchmark.com/tests/aim`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

### Additional Message

doesnt block the ad block check

**Comment by llacb47** [comment]
I see two issues.

Admiral "continue without disabling" anti-adblock.
![image](https://user-images.githubusercontent.com/16567977/89105193-0272a880-d3ed-11ea-9c6d-7bd8c16e690a.png)

Fix: 
```
humanbenchmark.com##+js(aopr, admiral)
||stalesummer.com^
```

Crappy error handling breaks ajax navigation between pages (click on dashboard).

![image](https://user-images.githubusercontent.com/16567977/89105121-72346380-d3ec-11ea-8c5b-322a3a12ad2d.png)

Fix: `humanbenchmark.com##+js(set, pubg.unload, noopFunc)`

**Comment by jspenguin2017** [comment]
@okiehsch Page breaks when clicking on "Dashboard". 

---

Anti-adblock and ads placeholders fixed.
