### ISSUE TITLE
tokvid.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4431]
### Basic Information

**Test link:** `https://tokvid.com/iamtiagz/video/6854288404570606854`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

Inline script tries to open popups to `https://topblockchainsolutions.nl/jump/next.php?r=3177135&padbl=1`

**Comment by okiehsch** [comment]
Fixed.
