### ISSUE TITLE
mesquitaonline.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4445]
### Basic Information

**Test link:** `https://mesquitaonline.com/2020/08/03/n-s-penha-promove-alteracao-nas-linhas-de-onibus-para-o-meier-e-centro-do-rio/?_unique_id=5f28bc82cbe04`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 9; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0
**Extension:** Nano Defender 15.0.0.201

**Comment by mapx-** [comment]
anti right click, select => https://github.com/uBlockOrigin/uAssets/commit/369805b0ce20e1ef62d916aece957557b96e9551

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/369805b0ce20e1ef62d916aece957557b96e9551

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click, anti-select.
