### ISSUE TITLE
files.im

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4451]
### Basic Information

**Test link:** `https://files.im/v6hhga6nr4b8`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 OPR/70.0.3728.71
**Extension:** Nano Defender 15.0.0.201

### Additional Message

popups

**Comment by llacb47** [comment]
```
||ufow9xfashbm.com^
||catastrophetray.com^
||preparedjuxtapose.com^
||ngegas.files.im^
! really only need this one
files.im##+js(aopr, Object.freeze)
```
