### ISSUE TITLE
mangaku.pro

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4453]
### Basic Information

**Test link:** `https://mangaku.pro/boku-no-hero-academia-chapter-hq-279/`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 OPR/70.0.3728.71
**Extension:** Nano Defender 15.0.0.201

### Additional Message

popups

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click.
