### ISSUE TITLE
sfchronicle.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4462]
### Basic Information

**Test link:** `https://www.sfchronicle.com/#`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

Blocking SF Chronicle website photos that start towards the middle of the page and the blocking continues to the bottom of the page (some initial headline photos at the top of the page still display).

Please fix. Thank you.

**Comment by mapx-** [comment]
@ryanbr
