### ISSUE TITLE
bcrlivestream.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4463]
### Basic Information

**Test link:** `https://bcrlivestream.com/w4lvh-5/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

Redirects to adware

**Comment by okiehsch** [comment]
Fixed.
