### ISSUE TITLE
solarmovie.ink

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4471]
### Basic Information

**Test link:** `https://www.solarmovie.ink/movie/filter/series`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

https://github.com/easylist/easylist/issues/5922

Also:

`https://veranime.top/` - https://github.com/easylist/easylist/issues/5920

`https://verhentai.top/` - https://github.com/easylist/easylist/issues/5921

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d206893c2a3fc1c7855431c033c1cfd29c1f2119
