### ISSUE TITLE
nsat.collegeboard.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4478]
### Basic Information

**Test link:** `https://nsat.collegeboard.org/satweb/registration/viewAuthenticateStudentAction.action;jsessionid=U0nPtpTUiZQnbmgJugA3ku1AEO-kFPkJvSZC-nEDV2jVaWiTw8BZ!955639552!1463872810`
**Category:** breakage
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.52
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

Some functions didn't apear with adblocker on

**Comment by llacb47** [comment]
Needs account (which I have), I can reproduce.

uBo on:
![image](https://user-images.githubusercontent.com/16567977/89926909-89850500-dbd3-11ea-8a9a-12918e66f4a1.png)
![image](https://user-images.githubusercontent.com/16567977/89926774-52165880-dbd3-11ea-9a9b-a88670fe05f9.png)


uBo off:
![image](https://user-images.githubusercontent.com/16567977/89926435-e7fdb380-dbd2-11ea-80c4-c208f9bd7796.png)

Fix: 

`@@||assets.adobedtm.com^*/mbox-contents-$script,domain=nsat.collegeboard.org`
