### ISSUE TITLE
hothardware.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4479]
### Basic Information

**Test link:** `https://hothardware.com/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

placeholder

**Comment by DandelionSprout** [comment]
Submitted to EasyList through https://github.com/easylist/easylist/issues/5968.

**Comment by jspenguin2017** [comment]
I doubt EasyList would fix it.

**Comment by DandelionSprout** [comment]
I've had a fairly good run with having EasyList fix placeholders in the past 2 weeks, although they seem to be somewhat slow at doing so: https://github.com/easylist/easylist/issues?q=is%3Aissue+author%3ADandelionSprout+created%3A%3E2020-08-01
