### ISSUE TITLE
chicago.cbslocal.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4483]
### Basic Information

**Test link:** `https://chicago.cbslocal.com/live/cbsn-chicago/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.59 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

### Additional Message

Live video doesn't load until you refresh page with ublock disabled.

After first successful load after disabling ublock on the page the live video will now loads with ublock enabled again and page refreshed

Default uBO filters + nano defender default filters

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/88aec4ccfb31fa9f352e1ff5a430593688f82204
