### ISSUE TITLE
jnovels.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4484]
### Basic Information

**Test link:** `https://jnovels.com/a-sunset-with-izaya-orihara-epub/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

https://github.com/brave/adblock-lists/issues/436

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/df85848439525a277a030b82cd0b6afb21cb9c5f

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/df85848439525a277a030b82cd0b6afb21cb9c5f
