### ISSUE TITLE
speedtest.appzend.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4485]
### Basic Information

**Test link:** `http://speedtest.appzend.net/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 13099.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.110 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

### Additional Message

Detects the adblocker

**Comment by okiehsch** [comment]
Fixed.
