### ISSUE TITLE
cpuid.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4489]
### Basic Information

**Test link:** `https://www.cpuid.com/downloads/hwmonitor/hwmonitor_1.41.zip`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance.

**Comment by okiehsch** [comment]
Fixed.
