### ISSUE TITLE
xendrive.ru

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4492]
### Basic Information

**Test link:** `https://xendrive.ru/6L7XQEO/part-1-id-scans-and-templates-evileaks-suzip#dl`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4210.0 Safari/537.36 Edg/86.0.594.1
**Extension:** Nano Defender Pro 15.0.0.201

**Comment by okiehsch** [comment]
Fixed.
