### ISSUE TITLE
overtakefans.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4494]
### Basic Information

**Test link:** `https://overtakefans.com/f1-live-stream/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36 Edg/84.0.522.59
**Extension:** Nano Defender Pro 15.0.0.201

**Comment by okiehsch** [comment]
Fixed.
