### ISSUE TITLE
overlordfree.web.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#450]
### Basic Information

**Test link:** `https://overlordfree.web.id/rezero-arc-4-chapter-75-bahasa-indonesia/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 6.0.1; Mobile; rv:63.0) Gecko/63.0 Firefox/63.0
**Extension:** Nano Defender 15.0.0.81

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
