### ISSUE TITLE
pimylifeup.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4505]
### Basic Information

**Test link:** `https://pimylifeup.com/raspberry-pi-remote-desktop/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

Ad's still get through even if I enable all the lists.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7766

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/48d66cb23daf1bc306960079a3f84476d9ee41f9
https://github.com/uBlockOrigin/uAssets/commit/d31345744c87405b45c67dd9ce7fccf3643dfbc6
