### ISSUE TITLE
detail.chiebukuro.yahoo.co.jp

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4506]
### Basic Information

**Test link:** `https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q10197674080`
**Category:** breakage
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

**Comment by Yuki2718** [comment]
Will be fixed in AG JPN: https://github.com/AdguardTeam/AdguardFilters/pull/61550

**Comment by jspenguin2017** [comment]
I don't see any issues with this website. 
![image](https://user-images.githubusercontent.com/7283682/90326428-6a74d300-df45-11ea-903f-2f2d4d952d26.png)

**Comment by Yuki2718** [comment]
This is quite a conditional issue, anyway fixed in EL now.
