### ISSUE TITLE
anitoki.web.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4509]
### Basic Information

**Test link:** `https://anitoki.web.id/`
**Category:** other
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
**Extension:** Nano Defender Pro 15.0.0.201

### Additional Message

Anti-drag

**Comment by okiehsch** [comment]
Fixed + ad-redirect if one clicks the download links.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://anitoki.web.id/`
**Category:** other
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
**Extension:** Nano Defender Pro 15.0.0.204

### Additional Message

Thanks for the previous issue.
but when on the home page, the drag still doesn't work.

Indonesian filter already has this "anitoki.web.id##+js(acis, auto_safelink)" and work.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select. 

---

Splitting https://github.com/NanoMeow/QuickReports/issues/4509#issuecomment-674437593 to another issue.
