### ISSUE TITLE
programme-tv.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4514]
### Basic Information

**Test link:** `https://www.programme-tv.net/news/tv/258978-alain-marshall-pousse-un-gros-coup-de-gueule-contre-le-gouvernement-dans-les-grandes-gueules-plein-le-dos-des-contradictions-video/`
**Category:** breakage
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

### Additional Message

I can't play video

**Comment by mapx-** [comment]
all fine here using the default setup
