### ISSUE TITLE
fxempire.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4518]
### Basic Information

**Test link:** `https://www.fxempire.com/news/article/china-blue-chip-index-hits-5-year-high-australian-shares-tumble-as-borders-close-659419`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.69 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

`||engine.fxempire.com^`

**Comment by jspenguin2017** [comment]
(Pinged on Slack)

**Comment by jspenguin2017** [comment]
https://github.com/easylist/easylist/commit/be015ad389b08737b671fd8c657e2417129154dd
