### ISSUE TITLE
tecnotutoshd.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4519]
### Basic Information

**Test link:** `https://www.tecnotutoshd.net/2020/08/`
**Category:** anti-adblock
**Reported from:** Chile
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

detec

**Comment by okiehsch** [comment]
Fixed.
