### ISSUE TITLE
anitoki.web.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4520]
### Basic Information

**Test link:** `https://anitoki.web.id/`
**Category:** other
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.69 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

Anti-select
`anitoki.web.id##+js(acis, auto_safelink)`

**Comment by jspenguin2017** [comment]
@okiehsch Anti-select annoyance on home page, recent fix does not work.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select.

**Comment by okiehsch** [comment]
The suggested fix does work for you?
Looking at the source it does not make much sense and the anti select is disabled by the existing filters.
I don't understand why it does not work on the homepage.

**Comment by jspenguin2017** [comment]
Ops, copied the wrong rule, it should be `anitoki.web.id##+js(aeld, mousedown)`

**Comment by okiehsch** [comment]
Fixed in uBO-filters.
