### ISSUE TITLE
darkbydm.now.sh

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4524]
### Basic Information

**Test link:** `https://darkbydm.now.sh/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

hover to any thumbnail and shows loading... and download is not possible
disable nano adblocker and download is enabled

**Comment by mapx-** [comment]
@ryanbr
