### ISSUE TITLE
mirrorace.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4527]
### Basic Information

**Test link:** `https://mirrorace.org/m/1xfnc?__cf_chl_jschl_tk__=1e58838a5120295423e13620c54a9a2617247b2e-1597647248-0-AT5MUQQnuBJJsAhU4zsaW3yd5Mh4EmWjDZ4WQ_rilejexjil9U2ozVY2xtZZmkB8d8PJJ2VL1H73NxW2M4NERhpodb9gMcOH2KzbL2l7YfJFUJs_Ke_co3WxS4LYjicDdkOHfLEPU1HGRuaHo8dvPfRWYCppfJ_0q11umdJMnEGZGuGl1sQycSIhhVzSnLzCjk-gkWvav1LaIL1YLvyxPa_9mebGtYJJjQJE21pfS-5FjdOEJdxenrtH7rHfwKOtW0qYGpj-awPHiSyaqc-V_Ra6dsTMr4l02KGXbLd2RM0xIz69U5XY_tddeMTBwUndtO0lattaxKA-7bVcvHEfM08`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 OPR/70.0.3728.106
**Extension:** Nano Defender 15.0.0.201

### Additional Message

vpn ads

**Comment by okiehsch** [comment]
Fixed.
