### ISSUE TITLE
hypebeast.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4529]
### Basic Information

**Test link:** `https://hypebeast.com/tags/bait`
**Category:** anti-adblock
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
**Extension:** Nano Defender 15.0.0.201

### Additional Message

Pop-up that request a whitelisting does not go away

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commits/master

**Comment by llacb47** [comment]
@okiehsch i think you meant https://github.com/uBlockOrigin/uAssets/commit/45b7a79d82c41b4e81875d6426bdf33fd6b77518 :)

**Comment by okiehsch** [comment]
Yes https://github.com/uBlockOrigin/uAssets/commits/master is rather vague 😁

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/45b7a79d82c41b4e81875d6426bdf33fd6b77518
