### ISSUE TITLE
pozirk.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4533]
### Basic Information

**Test link:** `https://www.pozirk.com/all-in-one-solitaire-game/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36 Edg/84.0.522.59
**Extension:** Nano Defender 15.0.0.204

### Additional Message

Nano Adblocker + Defender are detected by the site, which then do not deliver any content

**Comment by okiehsch** [comment]
Fixed.
