### ISSUE TITLE
officedepot.co.cr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4540]
### Basic Information

**Test link:** `https://www.officedepot.co.cr/officedepotCR/en/Gamers/c/04-04-0-0?siteName=Office+Depot+Costa+Rica`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

lazy loading broken

https://github.com/AdguardTeam/AdguardFilters/issues/61868

**Comment by okiehsch** [comment]
Fixed.
