### ISSUE TITLE
randomlists.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4545]
### Basic Information

**Test link:** `https://www.randomlists.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance.

**Comment by okiehsch** [comment]
Fixed.
