### ISSUE TITLE
viafree.se

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#456]
### Basic Information

**Test link:** `https://www.viafree.se/program/film/sag-aldrig-aldrig/20580/984184`
**Category:** anti-adblock
**Reported from:** Denmark
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.81

### Additional Message

It doesnt work after I installed everything on the said website. `https://jspenguin2017.github.io/uBlockProtector/#known-issues`

**Comment by jspenguin2017** [comment]
See also: https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/35

**Comment by jspenguin2017** [comment]
Requires account.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.viafree.se/program/influencers-x-viafree/pakostat/sasong-2/avsnitt-1`
**Category:** anti-adblock
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.93

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.viafree.se/program/reality/paradise-hotel/sasong-10/avsnitt-12`
**Category:** anti-adblock
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.112

### Additional Message

**Comment by jspenguin2017** [comment]
https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/41

@okiehsch FYI.

**Comment by jspenguin2017** [comment]
https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/41

**Comment by jspenguin2017** [comment]
Fixed by Swedish regional filters. 
![image](https://user-images.githubusercontent.com/7283682/55602718-33bd6480-5724-11e9-85f0-541d08c10fdd.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.viafree.se/program/reality/paradise-hotel/sasong-10/avsnitt-16`
**Category:** anti-adblock
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.120

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.viafree.se/program/reality/paradise-hotel/sasong-10/avsnitt-17`
**Category:** anti-adblock
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.124

### Additional Message

Can't get past the built in anti-adblock in the video player. Also seems like their system changes regularly because sometimes my ad-blocker works and sometimes it doesn't. It worked yesterday but doesn't today.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.viafree.se/program/reality/paradise-hotel/sasong-10/avsnitt-16`
**Category:** anti-adblock
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.125

### Additional Message

Thanks for the great work you do.
The site worked last week without it discovering my adblock but now it detects that I have an AdBlock activated :/ .

Again thanks.

**Comment by jspenguin2017** [comment]
@okiehsch @lassekongo83 Looks like this isn't working anymore.

**Comment by lassekongo83** [comment]
Defusing one of the connectivity check timeouts `r, 0` seems to get rid of the preroll ads, but the video does not continue after midroll. If `raven.min.js` is blocked, and the `error` listener defused, then I can sometimes continue after midrolls after an over 200 sec long loading screen. (Assuming no `redirect` filter is used on the media.) And that's where I got stuck. The solution I have is just not good enough yet.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.viafree.se/program/samhalle/efterlyst/sasong-53/994636`
**Category:** anti-adblock
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.125

### Additional Message

adblock gets detected

**Comment by okiehsch** [comment]
> These videos should not require a login. (But will probably still be geo-locked.) 

They are not geolocked on my end, but I also can only get rid of the pre-roll ads without breaking the player.

**Comment by lassekongo83** [comment]
@okiehsch 
Do these work for you?
```
||fwmrm.net^*/admanager.js$domain=viafree.se,important
||cdn.ravenjs.com^$script,domain=viafree.se
viafree.se##+js(setTimeout-defuser.js, r, 0)
viafree.se##+js(addEventListener-defuser.js, error, (t,n))
```

**Comment by DandelionSprout** [comment]
Testing those 4 entries with `https://www.viafree.no/programmer/sport/hvit-tornado-rosenborgs-europaeventyr`, it seems to work well enough on my end.

**Comment by DandelionSprout** [comment]
@theel0ja FYI for the sake of Finnish Adblock List: 

```
||fwmrm.net^*/admanager.js$domain=viafree.fi,important
viafree.fi##+js(setTimeout-defuser.js, r, 0)
viafree.fi##+js(addEventListener-defuser.js, error, (t,n))
||cdn.ravenjs.com^$script,domain=viafree.fi
```

(The first three should go into the uBO extras list.)

**Comment by DandelionSprout** [comment]
But now that I think about it... why don't we just simply add wildcard-domain versions of those entries to uAssets anyway? Something like:

```
||fwmrm.net^*/admanager.js$domain=viafree.*,important
||cdn.ravenjs.com^$script,domain=viafree.*
viafree.*##+js(setTimeout-defuser.js, r, 0)
viafree.*##+js(addEventListener-defuser.js, error, (t,n))
```

**Comment by okiehsch** [comment]
The filters work at
`https://www.viafree.se/program/reality/bilprovningen/sasong-2`
and also at
`https://www.viafree.se/program/reality/paradise-hotel/sasong-10/avsnitt-16`
which needs an account, so this seems to be fixed 👍

**Comment by okiehsch** [comment]
@DandelionSprout 
`||example.com^domain=example1.*`
will not work you can't replace the public suffix part with a wildcard, that only works with cosmetic filters.

**Comment by DandelionSprout** [comment]
Ah, okay.

**Comment by lassekongo83** [comment]
Fixed here now as well https://github.com/lassekongo83/Frellwits-filter-lists/commit/7b52a8055aeaf51b11363de10291c0fcb0f287dc#diff-2d391aac410440671d706405901ce5deR1560

**Comment by theel0ja** [comment]
> @theel0ja FYI for the sake of _Adblock List for Finland_:

Make a PR.

**Comment by DandelionSprout** [comment]
>Make a PR.

Duly done. 🙂
