### ISSUE TITLE
rightwingtribune.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4566]
### Basic Information

**Test link:** `https://rightwingtribune.com/2020/08/22/chicago-blm-militant-asking/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

`rightwingtribune.com##.z-ad-lockerdome-inline`

placeholders

**Comment by llacb47** [comment]
```
rightwingtribune.com##.z-ad-lockerdome-inline
rightwingtribune.com##.powerinbox
```
