### ISSUE TITLE
moviesjoy.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4571]
### Basic Information

**Test link:** `https://www1.moviesjoy.net/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
**Extension:** Nano Defender 15.0.0.205

### Additional Message

Redirects when clicking on search bar

**Comment by okiehsch** [comment]
Fixed.
