### ISSUE TITLE
korehakituk.nekonikoban.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4576]
### Basic Information

**Test link:** `http://korehakituk.nekonikoban.org/`
**Category:** ads
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

Hi, 

There is a small ad banner near the top, please take a look. 

Thanks.

**Comment by jspenguin2017** [comment]
I don't see any ads, but there seems to be a small placeholder.
