### ISSUE TITLE
elheraldo.hn

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4577]
### Basic Information

**Test link:** `https://www.elheraldo.hn/sucesos/1403234-466/enfrentamiento-narcoavioneta-droga-gracias-dios-aseguran-sucesos-honduras`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.152

### Additional Message

copy paste hijacking

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-copy.
