### ISSUE TITLE
welingelichtekringen.nl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4578]
### Basic Information

**Test link:** `https://www.welingelichtekringen.nl/`
**Category:** anti-adblock
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
**Extension:** Nano Defender for Firefox 15.0.0.205

### Additional Message

Banner at the lower side of the pages ....

**Comment by okiehsch** [comment]
Fixed.
