### ISSUE TITLE
mynet.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4584]
### Basic Information

**Test link:** `https://www.mynet.com/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
**Extension:** Nano Defender 15.0.0.205

### Additional Message

Original URL: `https://www.mynet.com/saclarini-keserse-olecegine-inanan-adam-80-yildir-saclarini-kesmiyor-yikamiyor-taramiyor-110106574561`

**Comment by okiehsch** [comment]
Fixed.
