### ISSUE TITLE
osbot.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4586]
### Basic Information

**Test link:** `https://osbot.org/forum/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

**Comment by jspenguin2017** [comment]
(Pinged on Slack)
