### ISSUE TITLE
annabelle.ch

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4588]
### Basic Information

**Test link:** `https://www.annabelle.ch/leben/politik-umwelt/%C2%ABauch-schweiz-hat-ein-rassismusproblem%C2%BB-50362`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
**Extension:** Nano Defender 15.0.0.205

**Comment by okiehsch** [comment]
Fixed.
