### ISSUE TITLE
krposts.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4604]
### Basic Information

**Test link:** `https://krposts.com/level/easy-download-youtube-subtitles-chrome-new-method-spencer-coffman/ar-xzcDQr5-drGI`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

**Comment by llacb47** [comment]
also on `th-cam.com` and `trshow.info`

**Comment by mapx-** [comment]
fixed
