### ISSUE TITLE
unixmen.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4610]
### Basic Information

**Test link:** `https://www.unixmen.com/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

### Additional Message

placeholders

**Comment by DandelionSprout** [comment]
Submitted to EasyList at https://github.com/easylist/easylist/issues/6054, since I saw the potential for a generic entry for that page.

**Comment by jspenguin2017** [comment]
https://github.com/easylist/easylist/commit/39685a8000c5ee985110f65ea5d462dffc5a0e25
