### ISSUE TITLE
clipartmax.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4612]
### Basic Information

**Test link:** `https://www.clipartmax.com/middle/m2H7G6K9N4b1d3H7_owl-decorations-owls-decor-owl-png-baby-posters-corujas-lilas-png/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

### Additional Message

anti right click, countdown on click download button

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click.
