### ISSUE TITLE
audycje.tokfm.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#463]
### Basic Information

**Test link:** `https://audycje.tokfm.pl/podcast/Finansowy-zastrzyk-dla-Ekstraklasy-Jak-zmieni-sie-poziom-sportowy-rozgrywek/70363`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.81

**Comment by okiehsch** [comment]
Fixed.
