### ISSUE TITLE
loader.to

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4644]
### Basic Information

**Test link:** `https://loader.to/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

### Additional Message

put in any url (or leave blank)

click download

click the 2nd download button that appears

popup appears

**Comment by mapx-** [comment]
fake button ?
`loader.to##[href^="https://offer.adcampo.com/"]`

@ryanbr

**Comment by llacb47** [comment]
I was talking about this button
![image](https://user-images.githubusercontent.com/16567977/92348362-ed023580-f0a0-11ea-8719-f213ead79da3.png)

It opens an ad popup when downloading the file

**Comment by mapx-** [comment]
fixed
