### ISSUE TITLE
kzblow.info

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4653]
### Basic Information

**Test link:** `https://kzblow.info/clone/novak-djokovic/raqY2ojJf7KUrck.html`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

**Comment by okiehsch** [comment]
@dimisa-RUAdList
`kzblow.info##+js(set-constant, String.prototype.charCodeAt, trueFunc)`

**Comment by dimisa-RUAdList** [comment]
https://hg.adblockplus.org/ruadlist/rev/b58bf97f4a83

**Comment by llacb47** [comment]
another clone site: `https://id-card.info/label/nHraiKSDfoN5n3o/drake-kanye-west-lil-wayne-eminem-forever-explicit-version-official-music-video.html`

**Comment by jspenguin2017** [comment]
@llacb47 https://github.com/NanoMeow/QuickReports/issues/4666
