### ISSUE TITLE
realityblurb.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4657]
### Basic Information

**Test link:** `https://realityblurb.com/2020/09/07/candiace-dillard-denies-rhop-producers-sent-her-text-about-michael-and-explains-why-she-shared-the-rumor-with-gizelle-plus-monique-shades-candiace-and-gizelle-for-lake-house-behavior-as-candiace-fire/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
**Extension:** Nano Defender 15.0.0.205

**Comment by mapx-** [comment]
@pgl 

`||enormousearth.com^`

**Comment by pgl** [comment]
Added, thanks @mapx-.
