### ISSUE TITLE
vectorizer.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#466]
### Basic Information

**Test link:** `https://www.vectorizer.io/images/upload.html`
**Category:** anti-adblock
**Reported from:** South Africa
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
**Extension:** Nano Defender 15.0.0.81

**Comment by jspenguin2017** [comment]
Not ads placeholder, empty box exists even in guest mode, and no ads show inside it.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.vectorizer.io/images/upload.html`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 Edg/80.0.361.48
**Extension:** Nano Defender Pro 15.0.0.181

### Additional Message
