### ISSUE TITLE
cadviewer.softgateon.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4661]
### Basic Information

**Test link:** `http://cadviewer.softgateon.net/?state=%7B%22ids%22:%5B%221Lx4l9UxKTr3sfBxlX119njzLswcYNA-D%22%5D,%22action%22:%22open%22,%22userId%22:%22{userId}%22%7D`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

**Comment by okiehsch** [comment]
Fixed.
