### ISSUE TITLE
cbssports.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4662]
### Basic Information

**Test link:** `https://www.cbssports.com/fantasy/football/news/fantasy-football-rankings-2020-sleepers-from-advanced-simulation-that-nailed-derrick-henrys-huge-year/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
**Extension:** Nano Defender 15.0.0.205

### Additional Message

Anti-adblock powered by Admiral.

**Comment by krystian3w** [comment]
In uBO enable: `uBlock filters – Annoyances`.

Nano Adblocker may need copy to Nano Base: `cbssports.com##+js(abort-on-property-read, HTMLIFrameElement)` https://github.com/uBlockOrigin/uAssets/issues/7866

**Comment by jspenguin2017** [comment]
Already fixed in Peter Lowe's, but okay.

**Comment by jspenguin2017** [comment]
Already fixed in Peter Lowe's, but okay, adding an `$important` rule just in case.
