### ISSUE TITLE
id-card.info

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4666]
### Basic Information

**Test link:** `https://id-card.info/label/nHraiKSDfoN5n3o/drake-kanye-west-lil-wayne-eminem-forever-explicit-version-official-music-video.html`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.22 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by jspenguin2017** [comment]
@mapx- @okiehsch Did you got a chance to look at this? Looks like ads reinsertion is still not fixed.

**Comment by okiehsch** [comment]
I missed your first ping.
I will take a look at it.

**Comment by okiehsch** [comment]
Fixed.

**Comment by llacb47** [comment]
Another one: `https://ruplayers.com/tools/nIGFtsqanGOBnJ8/travis-scott-sicko-mode-ft-drake-official-video.html`

**Comment by llacb47** [comment]
Another one: `https://ukblow.info/chart/apple-september-2020-event-in-12-minutes/hX2bl7a8ptvSaLA.html`
