### ISSUE TITLE
fotodovana.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4675]
### Basic Information

**Test link:** `http://fotodovana.com/NwBsKIb`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36 OPR/70.0.3728.154
**Extension:** Nano Defender 15.0.0.205

**Comment by DandelionSprout** [comment]
Seems to be fixed in uAssets Main.
