### ISSUE TITLE
techmuzz.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4677]
### Basic Information

**Test link:** `https://www.techmuzz.com/how-to/autoplay-embedded-youtube-video-on-page-load/`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4255.0 Safari/537.36 Edg/87.0.634.0
**Extension:** Nano Defender Pro 15.0.0.205

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

**Comment by okiehsch** [comment]
Fixed.
