### ISSUE TITLE
eroclips.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#468]
### Basic Information

**Test link:** `http://www.eroclips.org/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.81

### Additional Message

Any videos from this website won't play as it detects adblocker and asks for it to be disabled.

**Comment by mapx-** [comment]
@okiehsch @jspenguin2017  $popunder does not work for me in firefox, could you reproduce the issue ?

**Comment by okiehsch** [comment]
@jspenguin2017 can you reproduce the unblocked popunders with Firefox beta?

**Comment by okiehsch** [comment]
Just fyi, the issue is fixed with Chrome and Firefox stable, but there could be an issue with unblocked popunders using Firefox beta.

**Comment by jspenguin2017** [comment]
So that means it's good for now?

**Comment by okiehsch** [comment]
Yes.
