### ISSUE TITLE
getfilmes.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4683]
### Basic Information

**Test link:** `https://www.getfilmes.net/en/serie?post=the-rain-2-temporada-2019`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.84 Safari/537.36
**Extension:** Nano Defender 15.0.0.205

### Additional Message

nanoadblock detected

**Comment by okiehsch** [comment]
Fixed.
