### ISSUE TITLE
wordreference.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4684]
### Basic Information

**Test link:** `https://www.wordreference.com/enfr/test`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.84 Safari/537.36
**Extension:** Nano Defender 15.0.0.205

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

They recently added a script that generate this warning banner with a random class name so it can not be hidden with a rule.

Screenshot : `https://i.snipboard.io/kmey1g.jpg`

Workaround, adding this dynamic rule solve it : `www.wordreference.com * inline-script block`

But I expect nano defender will take care of it with no need from any interventions from users.

**Comment by okiehsch** [comment]
Fixed.
