### ISSUE TITLE
simkl.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4686]
### Basic Information

**Test link:** `https://simkl.com/3176167/dashboard/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0
**Extension:** Nano Defender for Firefox 15.0.0.205

**Comment by DandelionSprout** [comment]
Seems to be fixed in uAssets Main.
