### ISSUE TITLE
ynetnews.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4690]
### Basic Information

**Test link:** `https://www.ynetnews.com/`
**Category:** other
**Reported from:** Hashemite Kingdom of Jordan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
**Extension:** Nano Defender 15.0.0.205

### Additional Message

Original URL: `https://www.ynetnews.com/article/r1tRAi5Ev`

It shows a banner of :
"You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page."

**Comment by okiehsch** [comment]
Fixed.
