### ISSUE TITLE
n-tv.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4698]
### Basic Information

**Test link:** `https://www.n-tv.de/mediathek/videos/panorama/Wasserkraft-bedroht-Europas-blaues-Herz-article22016839.html`
**Category:** breakage
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0
**Extension:** Nano Defender for Firefox 15.0.0.205

### Additional Message

Video fails to load with common filterlists enabled

**Comment by mapx-** [comment]
needing german ip but then is working fine on my end

**Comment by okiehsch** [comment]
I get pre-roll ads.

**Comment by okiehsch** [comment]
Fixed.
