### ISSUE TITLE
gearside.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#47]
### Basic Information

**Test link:** `https://gearside.com/using-server-side-google-analytics-sending-pageviews-event-tracking/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.40

**Comment by jspenguin2017** [comment]
@okiehsch Just an annoyance. Looks like `show_ads.js` bait.

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
Thanks. 

I still need to fix it on my side.
