### ISSUE TITLE
uploads.mobi

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4703]
### Basic Information

**Test link:** `https://uploads.mobi/7mtz59z85ufh`
**Category:** other
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36 OPR/70.0.3728.178
**Extension:** Nano Defender 15.0.0.205

### Additional Message

download speed limited

**Comment by okiehsch** [comment]
Fixed.
