### ISSUE TITLE
cpomagazine.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4706]
### Basic Information

**Test link:** `https://www.cpomagazine.com/data-privacy/fisa-court-approves-warrantless-surveillance-but-with-warning-to-fbi-about-following-privacy-rules/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

### Additional Message

`cpomagazine.com##+js(aopr, advads_passive_groups)`

**Comment by okiehsch** [comment]
Fixed.
