### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#471]
### Basic Information

**Test link:** `https://www.filmweb.pl/person/Saoirse+Ronan-381818`
**Category:** breakage
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.81

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.filmweb.pl/Requiem.Dla.Snu`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.90

### Additional Message

**Comment by jspenguin2017** [comment]
Still works fine with Polish regional filters enabled.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.filmweb.pl/film/London+Town-2016-606412`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.90

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.filmweb.pl/film/1920+Bitwa+Warszawska-2011-562632`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.90

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.filmweb.pl/film/Bohemian+Rhapsody-2018-619201`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
**Extension:** Nano Defender 15.0.0.90

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.filmweb.pl/film/Jeniec%3A+Tak+daleko+jak+nogi+ponios%C4%85-2001-93761?ref=ls_d_2_jeni`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.90

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.filmweb.pl/film/Destroyer-2018-810309`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
**Extension:** Nano Defender 15.0.0.90

### Additional Message

**Comment by krystian3w** [comment]
@jspenguin2017 possible disable "borken" script in addon?

https://github.com/MajkiIT/polish-ads-filter/issues/12017#issuecomment-463180961

Now website detect turned on Nano Defender and only disable addon fix problem on site.

**Comment by jspenguin2017** [comment]
I can't reproduce the problem, but the old rule is no longer needed, so I removed it.

**Comment by krystian3w** [comment]
I think we need a script that works for more than 2 days, and the creators of the site are using any exsisted filters as trap/bait.


*The website will probably come back to the well-known bad if the webmasters do not let go.*

**Comment by jspenguin2017** [comment]
@krystian3w If the website owner wants to keep fixing the solutions, script or not is not going to help.

**Comment by krystian3w** [comment]
OK, I understand.
