### ISSUE TITLE
cpu-world.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4713]
### Basic Information

**Test link:** `http://www.cpu-world.com/Sockets/Socket_1151_H4_LGA1151.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0
**Extension:** Nano Defender for Firefox 15.0.0.205

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#known-issues`

After viewing about 4 different CPU pages within the website, it somehow detected the ads being blocked.

I am using ublock origin, with nano-defender integration, and yes, I did the extra steps to work with ublock origin.  My browser is firefox, x-64 latest version.  I made sure to clear my cache in ublock origin and to reload all the rules, and the problem reoccurs.

What the website does after detecting ad blocking is to hide about 2/3rds of the information on the screen, and it puts a banner `.gif` file named `ab_z91.gif` at the top that contains the following text:
"!  We detected that oue ads are blocked by your computer.  Since we rely on advertisements, we cannot provide you the same level of access as we provide to rule-abiding visitors.  Which means some information on the page is no longer accessible.  To see it, please disable adblocking and then use Control-F5 key combo to refresh current page."

**Comment by okiehsch** [comment]
Fixed.
