### ISSUE TITLE
shoowbiz.ru

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4720]
### Basic Information

**Test link:** `https://shoowbiz.ru/songs/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

### Additional Message

Crap 3p - showing fake notification prompt

**Comment by mapx-** [comment]
`shoowbiz.ru##+js(aopr, Notification)`
or
`||vendigamus.com^$3p`

I guess should be added to RUAdList list

**Comment by dimisa-RUAdList** [comment]
https://hg.adblockplus.org/ruadlist/rev/8f690627ebf7
