### ISSUE TITLE
garyfeinbergphotography.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4723]
### Basic Information

**Test link:** `http://www.garyfeinbergphotography.com/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

### Additional Message

annoyance: anti-right click, autoplaying music

**Comment by okiehsch** [comment]
Fixed ant-right click.

For the music there is an on/off button on the site, so is this really worth fixing?

`garyfeinbergphotography.com##+js(nostif, jPlayer)`
disables the music but will also disable the functionality of the on/off button, i.e. you won't be able to hear the music even if you want to.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click.
