### ISSUE TITLE
xxxdan.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4724]
### Basic Information

**Test link:** `https://xxxdan.com/OjN0K/lo-mejor-de-love-randalin-knuckles-remix.html?ref=cd9176ea3e7da2d3cc928d29b71de819`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 10; SM-G960W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.101 Mobile Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

### Additional Message

Original URL: `chrome-extension://iojaoainolpgkpojokmeclhidjolocci/popup.html`

loud ads, no ads blocked

**Comment by okiehsch** [comment]
Fixed.
