### ISSUE TITLE
america.cgtn.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4727]
### Basic Information

**Test link:** `https://america.cgtn.com/livenews`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

### Additional Message

breakage and anti-adblock

```
engine.univtec.com##+js(set, Swal.fire, noopFunc)
@@||imasdk.googleapis.com/js/sdkloader/ima3$script,domain=engine.univtec.com
@@||pubads.g.doubleclick.net/ssai/$xhr,domain=engine.univtec.com
```

**Comment by mapx-** [comment]
(`baitClass` removed by EL today)
