### ISSUE TITLE
kyma.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4728]
### Basic Information

**Test link:** `https://kyma.com/live/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

### Additional Message

blocking stream

**Comment by mapx-** [comment]
fixed by https://github.com/uBlockOrigin/uAssets/commit/1fce764a0cd7f7936f52de0b330d5f0219db1f3d

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/1fce764a0cd7f7936f52de0b330d5f0219db1f3d
