### ISSUE TITLE
purposegames.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4737]
### Basic Information

**Test link:** `https://www.purposegames.com/game/microscope-labeling`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
**Extension:** Nano Defender 15.0.0.205

**Comment by okiehsch** [comment]
Fixed.
