### ISSUE TITLE
poptimesuk.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4739]
### Basic Information

**Test link:** `https://poptimesuk.com/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

### Additional Message

lots of (failed) connections to 3p, but one is not being blocked: `https://bolrookr.com/pfe/current/tag.min.js?z=3530833`

**Comment by okiehsch** [comment]
Fixed.
