### ISSUE TITLE
math.semestr.ru

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#474]
### Basic Information

**Test link:** `https://math.semestr.ru/math/diff.php`
**Category:** anti-adblock
**Reported from:** Russia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.81

### Additional Message

NanoDefender dont work on this site

**Comment by jspenguin2017** [comment]
Something's wrong with the Russian filter, `@@||math.semestr.ru^$generichide` works, but breaks if Russian filters are enabled.

**Comment by okiehsch** [comment]
I can't reproduce.

![image](https://user-images.githubusercontent.com/16838044/50388849-9b294880-0721-11e9-9228-ac48c10d0dab.png)

**Comment by jspenguin2017** [comment]
OK, it works with just the Adguard Russian filter, but if I enable `RUS: RU AdList`, it breaks.

**Comment by okiehsch** [comment]
I have both enabled.
![image](https://user-images.githubusercontent.com/16838044/50389020-6cf93800-0724-11e9-849a-b1d2f21950a3.png)

**Comment by jspenguin2017** [comment]
This works for me: 
```
semestr.ru#@##idbanner:style(max-height: 41px !important; opacity: 0 !important; pointer-events: none !important)
semestr.ru#@#.well-google:style(max-height: 41px !important; opacity: 0 !important; pointer-events: none !important)
semestr.ru#@#div[id^="bn_"]
```

I'm not sure why but I can consistently reproduce it. 
![image](https://user-images.githubusercontent.com/7283682/50389055-ddcb3080-06e1-11e9-9496-024cd27953c9.png)
