### ISSUE TITLE
thestar.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4743]
### Basic Information

**Test link:** `https://www.thestar.com/news/world/us/2020/09/23/republicans-argue-against-electronic-ohio-ballot-application.html`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4260.0 Safari/537.36 Edg/87.0.637.0
**Extension:** Nano Defender 15.0.0.205

### Additional Message

Banner pops up at the bottom of every Toronto Star article, "You are seeing this message because ad or script blocking software is interfering with this page"

**Comment by okiehsch** [comment]
Fixed.
