### ISSUE TITLE
nova.rs

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4749]
### Basic Information

**Test link:** `https://nova.rs/vesti/drustvo/preminuo-fotoreporter-srdan-suki-sulejmanovic/`
**Category:** breakage
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
**Extension:** Nano Adblocker 1.0.0.151

### Additional Message

getting white page instead of article

**Comment by okiehsch** [comment]
Broken in the regional - swedish - list.
@lassekongo83
`@@||nova.rs/wp-content/plugins/*/sassy-social-share-public.js$script,1p`
fixes the issue on my end.
