### ISSUE TITLE
phcorner.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4751]
### Basic Information

**Test link:** `https://phcorner.net/threads/9-25-20-update-udpteam-r-tm-noload-hyper-fast-no-stuck-sa-200-status-sockshttp-remodified-no-popup-timer.948822/`
**Category:** breakage
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 9; ASUS_X00TDB) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.101 Mobile Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

### Additional Message

When I click the Spoiler: APK+Config nothing shows. But if I disable the nanoadblocker it shows. It doesn't happen before. But now it never shows anything. Hope it could be fixed soon. Thanks Nano team.

**Comment by okiehsch** [comment]
Fixed.
