### ISSUE TITLE
databasegdriveplayer.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4755]
### Basic Information

**Test link:** `https://databasegdriveplayer.xyz/player.php?imdb=tt11127690`
**Category:** ads
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
**Extension:** Nano Defender for Firefox 15.0.0.205

### Additional Message

ads, fixed with

```
databasegdriveplayer.xyz##+js(acis, String.fromCharCode, btoa)
```

**Comment by okiehsch** [comment]
Fixed.
