### ISSUE TITLE
hdfilmcehennemi.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4756]
### Basic Information

**Test link:** `https://www.hdfilmcehennemi.net/2-raised-by-wolves-1-sezon-yabanci-dizi-izle/`
**Category:** ads
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 8.1.0; SM-G610F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.101 Mobile Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

### Additional Message

bet ad not removed  :(

**Comment by mapx-** [comment]
```
||hdfilmcehennemi.net/*skin$image
hdfilmcehennemi.net##[href^="https://bit.ly"]
||hdfilmcehennemi.net/wp-content/uploads/$media,1p
hdfilmcehennemi.net##[href="https://www.hdfilmcehennemi.net/metinreklam"]
hdfilmcehennemi.net###gotorek
hdfilmcehennemi.net##+js(nano-stb)
```

for `TUR: AdGuard Turkish`

**Comment by mapx-** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Changed old domain to new. https://github.com/AdguardTeam/AdguardFilters/commit/1107f5b63a89d6e012715a20d3844c8b134e2ae7

**Comment by jspenguin2017** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/1107f5b63a89d6e012715a20d3844c8b134e2ae7
