### ISSUE TITLE
poranny.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#476]
### Basic Information

**Test link:** `https://poranny.pl/trasa-niepodleglosci-w-bialymstoku-kolejne-kawalki-sa-udostepniane-kierowcom-zmiany-na-magnoliowej-popieluszki-pulaskiego-i-ul/ga/13752980/zd/32848746`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.75

**Comment by okiehsch** [comment]
Fixed.
@olegwukr fyi.

**Comment by okiehsch** [comment]
**Off-topic** @jspenguin2017 why do you think so many reported issues are not reproducible?

**Comment by jspenguin2017** [comment]
@okiehsch About 60% of issues are valid, which is good enough IMO. It's better than dealing with people who don't want to bother to fill the template.

**Comment by jspenguin2017** [comment]
If you think 60% is not good enough, you can always just wait for me to ping you.

**Comment by okiehsch** [comment]
Sorry if it sounded like a complaint, I really only asked out of curiosity.
I am not subscribed to this repo, so I would not be bothered anyway, I only check the issues manually from time to time.
