### ISSUE TITLE
universal-sci.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4773]
### Basic Information

**Test link:** `https://www.universal-sci.com/headlines/2016/12/7/how-strong-is-the-force-of-gravity-on-earth`
**Category:** breakage
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0
**Extension:** Nano Adblocker 1.0.0.151

### Additional Message

Blocks `images.squarespace-cdn.com` pictures included within the article

**Comment by okiehsch** [comment]
Fixed. The pictures will show up after a few seconds.
