### ISSUE TITLE
robot-forum.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4776]
### Basic Information

**Test link:** `https://www.robot-forum.com/robotforum/thread/15277-remote-vnc-connection-to-a-krc4-system/`
**Category:** anti-adblock
**Reported from:** Taiwan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.205

**Comment by okiehsch** [comment]
Fixed.
