### ISSUE TITLE
miomio.us

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4778]
### Basic Information

**Test link:** `https://miomio.us/gamecenter201001.html`
**Category:** ads
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0
**Extension:** Nano Adblocker 1.0.0.151

**Comment by Yuki2718** [comment]
I don't see ads, only placeholder.
