### ISSUE TITLE
uk.trustpilot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4780]
### Basic Information

**Test link:** `https://uk.trustpilot.com/users/connect`
**Category:** breakage
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
**Extension:** Nano Adblocker 1.0.0.151

### Additional Message

`cookielaw.org` must be allowed in the dynamic filtering panel to be able to login

**Comment by okiehsch** [comment]
Cookielaw is not blocked with a default setup.
