### ISSUE TITLE
arcadepunks.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4789]
### Basic Information

**Test link:** `https://www.arcadepunks.com/download-no-intro-rom-sets/`
**Category:** anti-adblock
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 Edg/85.0.564.63
**Extension:** Nano Defender Pro 15.0.0.205

**Comment by okiehsch** [comment]
Fixed.
