### ISSUE TITLE
fzmovies.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#479]
### Basic Information

**Test link:** `https://fzmovies.net/`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.85 Safari/537.36 Vivaldi/2.2.1388.34
**Extension:** Nano Defender 15.0.0.81

### Additional Message

anti adblock measures on this site kicks in despite nano defender being active

**Comment by KiLL4FuNK** [comment]
anti-adblock
