### ISSUE TITLE
midiplayer.ehubsoft.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4791]
### Basic Information

**Test link:** `http://midiplayer.ehubsoft.net/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
**Extension:** Nano Defender for Firefox 15.0.0.205

**Comment by okiehsch** [comment]
Fixed.
