### ISSUE TITLE
ilclubdellericette.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4794]
### Basic Information

**Test link:** `https://www.ilclubdellericette.it/ricetta/torta-di-rose-ricetta-originale/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0
**Extension:** Nano Defender for Firefox 15.0.0.205

**Comment by okiehsch** [comment]
Fixed + right click annoyance.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click.
