### ISSUE TITLE
emuenzen.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4795]
### Basic Information

**Test link:** `https://www.emuenzen.de/forum/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
**Extension:** Nano Defender Pro 15.0.0.205

### Additional Message

Original URL: `https://www.emuenzen.de/forum/threads/monaco-kms-2020-lust-und-frust-bei-der-bestellung.96193/page-28`

**Comment by okiehsch** [comment]
Fixed.
