### ISSUE TITLE
paraedu.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#48]
### Basic Information

**Test link:** `https://www.paraedu.id/2018/06/28/review-tenda-o3-dan-tp-link-cpe-220-lengkap/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.40

**Comment by jspenguin2017** [comment]
Need to remove generic FAB defuser, it simply does not work.

**Comment by okiehsch** [comment]
Looks like `AdBlock Notify` and not `FuckAdBLock`.

**Comment by jspenguin2017** [comment]
It also has FAB. Don't worry, it's my problem from here on. I need to patch ND.
