### ISSUE TITLE
pluspremieres.eu

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#480]
### Basic Information

**Test link:** `https://www.pluspremieres.eu/2017/10/chris-brown-fame-deluxe-version.html`
**Category:** anti-adblock
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.81

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/36e6f2df0c12af6223ace91e14ce989554e1b01f
