### ISSUE TITLE
seotechman.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4812]
### Basic Information

**Test link:** `https://www.seotechman.com/2019/01/cara-membuat-navigation-bar-keren.html`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.153

### Additional Message

Ad adbloker detected

**Comment by jspenguin2017** [comment]
`t: other`: Anti-select.
