### ISSUE TITLE
yespornplease.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#489]
### Basic Information

**Test link:** `https://yespornplease.com`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.81

**Comment by jspenguin2017** [comment]
Works fine for me.

**Comment by jspenguin2017** [comment]
@okiehsch Popup:
