### ISSUE TITLE
dallasobserver.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#49]
### Basic Information

**Test link:** `https://www.dallasobserver.com/restaurants/applebees-makes-a-desperate-expensive-attempt-to-not-be-americas-worst-restaurant-8288782`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
**Extension:** Nano Defender 15.0.0.40

**Comment by jspenguin2017** [comment]
Verified working.
