### ISSUE TITLE
clbfia.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#490]
### Basic Information

**Test link:** `https://clbfia.blogspot.com/2018/12/code-trang-dem-nguoc-mung-giang-sinh.html`
**Category:** anti-adblock
**Reported from:** Hong Kong
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.81

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
