### ISSUE TITLE
animedd.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#495]
### Basic Information

**Test link:** `https://animedd.xyz/403/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.82

**Comment by jspenguin2017** [comment]
@okiehsch Any idea how to deal with this one?

**Comment by mapx-** [comment]
https://github.com/easylist-thailand/easylist-thailand/issues

@easylist-thailand

**Comment by jspenguin2017** [comment]
Yea, this cleans the site up pretty nicely, but links don't work. 
```
||animedd.xyz/banner/$image,1p
||imgur.com^$image,domain=animedd.xyz
||picz.in.th^$image,domain=animedd.xyz
animedd.xyz##.slider-l
animedd.xyz##.slider-r
```

**Comment by DandelionSprout** [comment]
That site doesn't just need to remove a few ads. That thing is in need of a freaking exorcist, and my personal instinct is to run away from that site at full speed.

Here's my attempts at cleaning up that forsaken mess of a "website":

```
! https://animedd.xyz
animedd.xyz##.img-thumbnail:not([src^="https://animedd.xyz/"])
animedd.xyz##[href*="casino"]
animedd.xyz###floating_banner_top
||i.imgur.com$domain=animedd.xyz
animedd.xyz##[src="https://i.imgur.com/5Q894WW.jpg"]
animedd.xyz##.col_del:has-text(ปิดป้ายนี้)
animedd.xyz##div.panel-primary.panel:has-text(Text Link Ads)

! https://animedd.xyz/play/29875/attack-on-titan-season.html
animedd.xyz###link_h_movie_ad
||publish.iptvz.net$subdocument
```

Also the reason the links didn't work for you guys, is because Google's pop-up blocker was blocking them. Choosing to open in a new tab, bypasses that issue.

**Comment by DandelionSprout** [comment]
The entries I suggested above, seem to have been added to EasyList Thailand now, so I suppose that this issue too is resolved now.

**Comment by jspenguin2017** [comment]
That certainly helped a lot, but I wouldn't consider it to be fixed yet. I saw a fake notification prompt and links are not always working.

**Comment by okiehsch** [comment]
The links are blocked by Chrome's popup blocker.
````
anime-live.com,animedd.xyz##+js(abort-current-inline-script.js, RegExp, zfgloaded)
||cdn2.ufabet678.com/video.mp4$media,redirect=noopmp4-1s,domain=facebook.com
````
works on my end, does that fix every issue for you?

**Comment by okiehsch** [comment]
I am not sure if `EasyList Thailand` supports extended syntax and a redirection is the only way to fix the pre-roll ads, so I can add the fix to `uAssets` if necessary.

**Comment by DandelionSprout** [comment]
They seem to have a section designed to hold uBO-specific entries at https://github.com/easylist-thailand/easylist-thailand/blob/master/categories/ublock.txt.

I couldn't find a fix for the pre-roll ads on my own, and I'm honestly enough scared of the site that I don't want to test the link fix at https://github.com/NanoMeow/QuickReports/issues/495#issuecomment-470357546 myself, so I'll let you take care of those things as you see fit.

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
Alright let's just close this.
