### ISSUE TITLE
sledujfilmy.to

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#498]
### Basic Information

**Test link:** `https://www.sledujfilmy.to/filmy/the-lord-of-the-rings-the-two-towers`
**Category:** anti-adblock
**Reported from:** Slovakia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 Vivaldi/2.2.1388.37
**Extension:** Nano Defender 15.0.0.82

### Additional Message

needs to allow `https://www.sledujfilmy.to/assets_new/js/showads.js` in order to work

**Comment by jspenguin2017** [comment]
@okiehsch Requires Slovakia VPN. 

This rule confirmed working: 
```
@@||sledujfilmy.to/assets_new/js/showads.js$script,1p
```

![image](https://user-images.githubusercontent.com/7283682/50567025-8e968880-0cfd-11e9-886d-bdf8b8a4cd92.png)

**Comment by okiehsch** [comment]
Fixed, thanks.
