### ISSUE TITLE
aniwatcher.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#499]
### Basic Information

**Test link:** `https://aniwatcher.com/seishun-buta-yarou-wa-bunny-girl-senpai-no-yume-wo-minai-episode-13`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.82

### Additional Message

Still detecting adblock with Nano Defender + Nano Adblocker

**Comment by okiehsch** [comment]
Fixed a few hours ago.
https://github.com/uBlockOrigin/uAssets/commit/8e356f8ae17f8c3f5eefd1c9e1a1807350db9c75
https://github.com/uBlockOrigin/uAssets/commit/203f4fe417095de40bde506204f1b977094e9e86
