### ISSUE TITLE
blick.ch

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#5]
### Basic Information

**Test link:** `https://www.blick.ch/news/wirtschaft/zu-viel-milch-zu-wenig-fleisch-die-schweiz-hat-die-falschen-kuehe-id8744604.html`

**Category:** anti-adblock

**Reported from:** Switzerland

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.35

**Comment by jspenguin2017** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/44373784-37a7b980-a4a8-11e8-89a1-2759d0448ec3.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.blick.ch/`
**Category:** breakage
**Reported from:** Switzerland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Defender 15.0.0.156

### Additional Message

**Comment by jspenguin2017** [comment]
@okiehsch Content does not load properly when scrolled down. 
![image](https://user-images.githubusercontent.com/7283682/62002355-abdadc00-b0bf-11e9-941b-0c2a91826560.png)

**Comment by okiehsch** [comment]
Fixed.
