### ISSUE TITLE
emurom.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#500]
### Basic Information

**Test link:** `https://www.emurom.net/us/emulation/gameboy-roms/detail-63336-metroid.ii.-.return.of.samus.html#`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.82

### Additional Message

The anti-adblock text is in French but it basically refuses to let you use download links unless you disable your adblocker.

**Comment by okiehsch** [comment]
Fixed.
