### ISSUE TITLE
cda.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#501]
### Basic Information

**Test link:** `https://www.cda.pl/video/2894083e3?wersja=720p`
**Category:** ads
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 OPR/57.0.3098.106
**Extension:** Nano Defender 15.0.0.82

### Additional Message

no ads blocking

**Comment by jspenguin2017** [comment]
Fixed in Polish regional filters.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.cda.pl/video/186946ee`
**Category:** ads
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.90

### Additional Message

the ad plays

**Comment by jspenguin2017** [comment]
@okiehsch @MajkiIT FYI. Pre-roll ads.

**Comment by okiehsch** [comment]
`||r.dcs.redcdn.pl^$media,domain=cda.pl`

**Comment by MajkiIT** [comment]
@okiehsch @jspenguin2017 Thanks I will add
