### ISSUE TITLE
theodysseyonline.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#516]
### Basic Information

**Test link:** `https://www.theodysseyonline.com/lgbt-bicycle`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.85

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/50660696-f2b78780-0f5d-11e9-8bd9-f03020b848f1.png)
