### ISSUE TITLE
idroidbg.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#518]
### Basic Information

**Test link:** `https://idroidbg.com/forum/viewforum.php?f=110&sid=ddccac311505549e73106ee0a277893f`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
**Extension:** Nano Defender 15.0.0.85

### Additional Message

Ad blocker detected: Our website is made possible by displaying online advertisements to our visitors. Please consider supporting us by disabling your ad blocker on our website.

**Comment by mapx-** [comment]
maybe needing account

**Comment by jspenguin2017** [comment]
Requires account.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://idroidbg.com/forum/viewtopic.php?f=9&t=108&p=4922&sid=d7f88163f81a1d9d7fb487960e815d90#p4922`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
**Extension:** Nano Defender 15.0.0.85

### Additional Message

Ad blocker detected: Our website is made possible by displaying online advertisements to our visitors. Please consider supporting us by disabling your ad blocker on our website.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://idroidbg.com/forum/viewtopic.php?f=9&t=318&p=8873#p8873`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.106

### Additional Message

Cannot load Facebook SDK. Disable any adblocker or tracking protection and try again.

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/54001527-d4f6d200-4108-11e9-814b-adc3fbfd1452.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://idroidbg.com/forum/index.php`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.92

### Additional Message

Ad blocker detected: Our website is made possible by displaying online advertisements to our visitors. Please consider supporting us by disabling your ad blocker on our website.

**Comment by jspenguin2017** [comment]
Maybe requires account, otherwise cannot reproduce.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://idroidbg.com/forum/viewtopic.php?p=9533#p9533`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.92

### Additional Message

Cannot load tweet. Disable your adblocker and tracking protection.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://idroidbg.com/forum/index.php`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

Ad blocker detected: Our website is made possible by displaying online advertisements to our visitors. Please consider supporting us by disabling your ad blocker on our website.
