### ISSUE TITLE
zattoo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#519]
### Basic Information

**Test link:** `https://zattoo.com`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.85

**Comment by jspenguin2017** [comment]
Maybe requires account, otherwise cannot reproduce.

**Comment by okiehsch** [comment]
Fixed.
