### ISSUE TITLE
mylifetime.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#520]
### Basic Information

**Test link:** `https://www.mylifetime.com/shows/you/season-1/episode-10`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.85

### Additional Message

It kept detecting Nano Adblocker installed and wouldn't let me sign in without disabling it.

**Comment by jspenguin2017** [comment]
@okiehsch Requires USA VPN
![image](https://user-images.githubusercontent.com/7283682/50661020-06afb900-0f5f-11e9-9d2b-2af353b1509a.png)
