### ISSUE TITLE
outlook.live.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#525]
### Basic Information

**Test link:** `https://outlook.live.com/mail/inbox`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 Vivaldi/2.2.1388.37
**Extension:** Nano Defender 15.0.0.85

**Comment by jspenguin2017** [comment]
Works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://outlook.live.com/mail/deleteditems/id/AQQkADAwATM0MDAAMS1mNzcANC1hYQAwMS0wMAItMDAKABAAyGZiR5PTlEGnGm3t13D89w%3D%3D`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.127

### Additional Message

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://outlook.live.com/mail/inbox`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Adblocker 1.0.0.119

### Additional Message

Original URL: `about:newtab`

maybe `outlook.live.com##a[href="https://windows.microsoft.com/outlook/ad-free-outlook"]:nth-ancestor(4)` works

**Comment by jspenguin2017** [comment]
@okiehsch @mapx- Looks like this broke, current annoyance rules no longer work.

**Comment by okiehsch** [comment]
I don't have an account, are the current rules breaking something and I should remove them or are new rules needed?

**Comment by jspenguin2017** [comment]
Hum... I don't believe existing rules breaks anything but they are no longer needed.

**Comment by jspenguin2017** [comment]
The rule in the report works without the 4 existing rules.

**Comment by okiehsch** [comment]
Added.
