### ISSUE TITLE
firstonetv.live

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#526]
### Basic Information

**Test link:** `https://www.firstonetv.live/Live/United-Kingdom/E4-14`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.85

### Additional Message

It was working, today the site changed its tld from .net to .live and it broke. Thank you and have a great new year.

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/50661190-93f30d80-0f5f-11e9-811e-43976ec9c42b.png)
