### ISSUE TITLE
sports.qq.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#528]
### Basic Information

**Test link:** `https://sports.qq.com/nba/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.85

### Additional Message

Prevents you from viewing video for 30 seconds

**Comment by mapx-** [comment]
geo locked

**Comment by jspenguin2017** [comment]
Could be related to https://github.com/uBlockOrigin/uAssets/issues/4293
