### ISSUE TITLE
auto.ro

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#533]
### Basic Information

**Test link:** `http://www.auto.ro/cookie-wall/?referrer=http%3A%2F%2Fwww.auto.ro%2F`
**Category:** anti-adblock
**Reported from:** Romania
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.28 Safari/537.36
**Extension:** Nano Defender 15.0.0.85

### Additional Message

redirects to cookie wall unless you allow a cookie. after that it works with adblocker. clearing the site storage/cookies makes it re-display the cookie wall. not sure if this really is defenders' task, but submiting just in case.

**Comment by okiehsch** [comment]
Fixed.
