### ISSUE TITLE
saratogian.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#534]
### Basic Information

**Test link:** `https://www.saratogian.com/news/ballston-spa-man-charged-with-dwi/article_afc759f2-0de4-11e9-b941-c3b38b83cccf.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 OPR/57.0.3098.106
**Extension:** Nano Defender 15.0.0.85

**Comment by okiehsch** [comment]
Fixed.
