### ISSUE TITLE
movisubmalay.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#535]
### Basic Information

**Test link:** `https://movisubmalay.com/`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.85

**Comment by okiehsch** [comment]
Fixed.
