### ISSUE TITLE
sharedplaylists.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#536]
### Basic Information

**Test link:** `https://www.sharedplaylists.com/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 6.0; Mobile; rv:64.0) Gecko/64.0 Firefox/64.0
**Extension:** Nano Defender 15.0.0.85

### Additional Message

It doesn't work with this website
`www.sharedplaylists.com`
Thanks.

**Comment by okiehsch** [comment]
Fixed.
