### ISSUE TITLE
expertblogz.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#540]
### Basic Information

**Test link:** `http://expertblogz.com/sz6b1605-8566-4611-b085-0fea430a6525/3fde413b1d5f4877a7047aac46afabe7.aspx?d71480e9=69548-177-8d3cb5d27255&alt=1`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.85

### Additional Message

When I visited above given url, it does not do anything. Its showing black screen and not loading the video. It must be because javascript is blocked. However this was working earlier last week but now it stopped working. Please check this one.

**Comment by okiehsch** [comment]
I can't reproduce any breakage. 
I can reproduce an anti-adblock message.
