### ISSUE TITLE
wral.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#542]
### Basic Information

**Test link:** `https://www.wral.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.85

### Additional Message

Ask to turn of adblocker

**Comment by mapx-** [comment]
annoyance => click "`continue without sponsoring us`"
