### ISSUE TITLE
ievaphone.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#543]
### Basic Information

**Test link:** `https://ievaphone.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0
**Extension:** Nano Defender 15.0.0.85

**Comment by okiehsch** [comment]
Fixed.
