### ISSUE TITLE
okaeriworld.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#547]
### Basic Information

**Test link:** `https://okaeriworld.com/selamat-jalan-tatsuya-nomi-sang-bintang-ilusi-surga-daigo/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.85

**Comment by jspenguin2017** [comment]
Other: Anti-select and anti-right click
