### ISSUE TITLE
stadionowioprawcy.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#554]
### Basic Information

**Test link:** `http://stadionowioprawcy.pl/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.85

**Comment by theinstantmatrix** [comment]
@mapx- the website is now at `stadionowioprawcy.net`, breaking the generichide filter. update?

**Comment by mapx-** [comment]
fixed
