### ISSUE TITLE
nostalgie.fr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#556]
### Basic Information

**Test link:** `http://www.nostalgie.fr/webradios/nostalgie-tous-les-tubes-tous-les-styles`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/71.0.3578.98 Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.85

**Comment by okiehsch** [comment]
Fixed.
