### ISSUE TITLE
hpjav.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#562]
### Basic Information

**Test link:** `https://hpjav.tv/73981/hzgd-099`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.85

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://hpjav.tv/ja/84392/heyzo_1985`
**Category:** anti-adblock
**Reported from:** Taiwan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Defender 15.0.0.140

### Additional Message

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://hpjav.tv/121839/honb-165`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0
**Extension:** Nano Defender for Firefox 15.0.0.185

### Additional Message

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://hpjav.tv/125870/fc2ppv_1300657-a`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
**Extension:** Nano Defender for Firefox 15.0.0.194

### Additional Message

**Comment by jspenguin2017** [comment]
For https://github.com/NanoMeow/QuickReports/issues/562#issuecomment-599147748 : 
Can't reproduce anti-adblock.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://hpjav.tv/ja/`
**Category:** breakage
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message
