### ISSUE TITLE
paperio.club

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#563]
### Basic Information

**Test link:** `https://paperio.club/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; CrOS x86_64 11151.59.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.94 Safari/537.36
**Extension:** Nano Defender 15.0.0.85

### Additional Message

It has me disable my adblocker in order to play, extremely frustrating!

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
Other: Anti-right click

**Comment by SylveonBottle** [comment]
Domain unregistered, possible to remove this link?
