### ISSUE TITLE
pornbimbo.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#564]
### Basic Information

**Test link:** `http://pornbimbo.com/video/3514/princess-rene-brainwashed-to-obey-rene?play=true`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.85

**Comment by okiehsch** [comment]
Fixed.
