### ISSUE TITLE
naszraciborz.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#567]
### Basic Information

**Test link:** `https://www.naszraciborz.pl/site/art/1-aktualnosci/0-/71070-prokuratura-sprawdzi--czy-przy-budowie-hali-zsoms-moglo-dojsc-do-nieprawidlowosci-i-poswiadczenia-nieprawdy--.html`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.86

### Additional Message

Hello, there is an anti-adblock image instead of a plain text.

Image address: `https://www.naszraciborz.pl/img/baner_nie_przyslaniaja.jpg?t=094804012019`

**Comment by okiehsch** [comment]
Fixed.
