### ISSUE TITLE
paperio.club

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#584]
### Basic Information

**Test link:** `https://paperio.club/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.87

### Additional Message

Anti-adblock pop up prevents me from playing!!

**Comment by okiehsch** [comment]
Fixed.
