### ISSUE TITLE
flyingmag.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#587]
### Basic Information

**Test link:** `https://www.flyingmag.com/iridium-completes-constellation-replacement?cmpid=ene20190117&utm_source=internal&utm_medium=email&cid=46955&mid=405018335`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.87

### Additional Message

g00 / InstartLogic crap being loaded in firefox

**Comment by mapx-** [comment]
fixed
