### ISSUE TITLE
rawstory.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#593]
### Basic Information

**Test link:** `https://www.rawstory.com/2019/01/former-prosecutor-explains-giuliani-may-trying-devastatingly-bad-news-trump/?comments=disqus`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.88

### Additional Message

Recently added:

```
<script type="text/javascript">

console.log( 'Parsing ### ADMIRAL ### scripts ... ');

window.admiral = window.admiral || function() {(admiral.q = admiral.q || []).push(arguments)};

window.admiral( "after",
"measure.detected",
function({adblocking, whitelisted, subscribed }){
if (adblocking) {
// do something if a user has an enabled adblocker
console.log( "### ADMIRAL ### user is adblocking");
}
if (subscribed) {
// do something if a user has subscribed through Transact
console.log( "### ADMIRAL ### user is subscribed");
jQuery('.rs-advert').hide();
jQuery('.oratv-desktop-container').hide();
jQuery('#text-49').hide();
}
if (whitelisted) {
// do something if a user has disabled their adblocker after seeing Engage
console.log( "### ADMIRAL ### user is whitelisted");
}
});

window.admiral("addEventListener", "5B48EC52F956D22D43B023CC-m", function({details}){
console.log( '### ADMIRAL ### ' + details.subscribed );
```

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/52158659-e5beae80-2657-11e9-80a9-2532fd5a2e70.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.rawstory.com/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.154

### Additional Message

site is totally blocked

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.rawstory.com/2019/07/florida-reporter-drops-new-bombshell-on-epstein-while-blasting-resigning-acosta/`
**Category:** other
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.154

### Additional Message

Site loads as a blank page is Nano is enabled. There are no custom element blocks on that site for me.

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.rawstory.com/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.154

### Additional Message

All I get is a white page...
I get site with chrome browser but not firefox...

**Comment by jspenguin2017** [comment]
@LiCybora FYI.

**Comment by LiCybora** [comment]
I can no longer reproduce at the time this comment is writing after filter update.
![image](https://user-images.githubusercontent.com/40160522/61173452-1ec75b80-a5c6-11e9-85e6-7e107576ab5c.png)

I can reproduce with fresh Nano install without filter update, so please update your filters.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.rawstory.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.154

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.rawstory.com/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.154

### Additional Message

Enabling cosmetic filtering in nano defender on this site gives me an all white page for this site ...?

Disabling cosmetic filtering in nano defender fixes this issue ...

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.rawstory.com/2019/10/pence-allies-worried-hell-be-swept-up-in-trump-impeachment-inquiry-hes-not-going-to-come-out-of-this-squeaky-clean/amp/?__twitter_impression=true`
**Category:** breakage
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Comments blocked

**Comment by mapx-** [comment]
- for the comments just click "Leave a comment"
- to unblock a video on page:
`@@||cds.connatix.com/embed/$frame,domain=rawstory.com`
- ad placeholders:
`rawstory.com##.amp-unresolved`
