### ISSUE TITLE
roleplay.me

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#594]
### Basic Information

**Test link:** `http://www.roleplay.me/notice.php`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.87

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. Has some ads placeholders on some pages. 

Another test link: `https://www.roleplay.me/Brok3n`
