### ISSUE TITLE
gardenista.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#596]
### Basic Information

**Test link:** `https://www.gardenista.com/posts/urban-gardener-is-unfiltered-tap-water-safe-for-plants/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 Vivaldi/2.2.1388.37
**Extension:** Nano Defender 15.0.0.89

**Comment by okiehsch** [comment]
Already fixed in `uBO-annoyances`.
