### ISSUE TITLE
fuckadblock.sitexw.fr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#597]
### Basic Information

**Test link:** `https://fuckadblock.sitexw.fr/`
**Category:** anti-adblock
**Reported from:** Thailand
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.89

### Additional Message

many sites use it i think and they give the code away i think so its easy to patch and useful for this extension

**Comment by jspenguin2017** [comment]
It's not hard to patch, but people customize it a lot, so in the end, it needs to be handled on a case by case basis.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://fuckadblock.sitexw.fr/`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.120 Safari/537.36 Vivaldi/2.3.1440.57
**Extension:** Nano Defender 15.0.0.105

### Additional Message

**Comment by jspenguin2017** [comment]
Looks like they got a new demo...
