### ISSUE TITLE
zeeplay.online

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#600]
### Basic Information

**Test link:** `https://zeeplay.online/game`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.89

### Additional Message

I tried to bypass this site "Blocker adblock" with uBlock Origin and Nano defender, but the site breaks, them I unistalled everything and instaled Nano Adblock and Nano Defender, the site wont break anymore, but won't load either. 
Is a small site made to host a Flash game, I think it should be interessing to study his way of only blocking the Flashplayer of loading.

**Comment by okiehsch** [comment]
Fixed.
