### ISSUE TITLE
nhl.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#601]
### Basic Information

**Test link:** `https://www.nhl.com/tv/2018020766#`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.89

### Additional Message

"We have detected that you are using ad blocking software."

**Comment by okiehsch** [comment]
Needds an account, so some feedback is necessary.

Potential fix:
````
@@||nhlstatic.com/video/config/ads/advertise/*$xmlhttprequest,domain=nhl.com
@@||nhlstatic.com/nhl.com/builds/site-core/*/scripts$script,domain=nhl.com
````

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.nhl.com/tv/2018030155/221-2002957/67794503#game=2018030155,tfs=20190420_175250,game_state=preview`
**Category:** anti-adblock
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.132

### Additional Message

Happens on all game streams

**Comment by okiehsch** [comment]
Fixed.
