### ISSUE TITLE
cartoonmemories.netsons.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#607]
### Basic Information

**Test link:** `https://cartoonmemories.netsons.org/`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.89

**Comment by okiehsch** [comment]
Fixed.
