### ISSUE TITLE
mtsproducoes.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#616]
### Basic Information

**Test link:** `https://mtsproducoes.blogspot.com/2014/07/musicas-que-tocam-no-ultimo-programa-do.html`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 Vivaldi/2.2.1388.37
**Extension:** Nano Defender 15.0.0.89

**Comment by okiehsch** [comment]
Fixed.
