### ISSUE TITLE
zigforums.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#620]
### Basic Information

**Test link:** `https://zigforums.com/thread/11961929/politics/yep-this-is-going-in-my-anti-white-compilation.html`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.89

**Comment by jspenguin2017** [comment]
@okiehsch 

Click first search result. 
`https://www.google.ca/search?q=Yep.+This+is+Going+in+my+Anti-White+Compilation+site%3Azigforums.com&oq=Yep.+This+is+Going+in+my+Anti-White+Compilation+site%3Azigforums.com&aqs=chrome..69i57.2752j0j7&sourceid=chrome&ie=UTF-8`

I've seen something like this multiple times before...

**Comment by jspenguin2017** [comment]
OK, found it. https://github.com/uBlockOrigin/uAssets/issues/2628

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/bd63b6906eafb79a17182bd821d4917344b86e9f
