### ISSUE TITLE
animbro.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#622]
### Basic Information

**Test link:** `http://www.animbro.com/`
**Category:** anti-adblock
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.89

**Comment by okiehsch** [comment]
Fixed.
