### ISSUE TITLE
clik.pw

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#638]
### Basic Information

**Test link:** `http://clik.pw/GScNVz`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
**Extension:** Nano Defender 15.0.0.90

### Additional Message

It doesn't show the captcha and greys out 'Click here to continue' unless you disable adblock

**Comment by jspenguin2017** [comment]
Has a few ads placeholders and fake buttons, but can't reproduce anti-adblock.

**Comment by DandelionSprout** [comment]
`clik.pw##.adsbygoogle` seems like a good fit for NanoContrib.

`##a[href^="https://syndication.exdynsrv.com/splash.php"]` seems like something that could be submitted to EasyList (or alternately AdGuard Base), should any of us know how to submit entries to them.

**Comment by jspenguin2017** [comment]
@okiehsch @mapx- Fake buttons.

**Comment by okiehsch** [comment]
`clik.pw##.adsbygoogle` there is no `generichide` filter as far as I can see.

I will add 
`##a[href^="https://syndication.exdynsrv.com/splash.php"]`

**Comment by DandelionSprout** [comment]
Nano Defender Integration seems to have a `generichide` for it, apparently: 
![image](https://user-images.githubusercontent.com/22780683/53856109-ec32a400-3fd0-11e9-8eee-3d5d915f40ae.png)

Although `clik.pw##.adsbygoogle` has now been added to *Placeholder Buster* anyway.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/067db512f7a8836f23458df6f0c832b678f751de

**Comment by jspenguin2017** [comment]
Eh... Must be a legacy rule. Thanks for pointing that out.
