### ISSUE TITLE
filmozercy.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#64]
### Basic Information

**Test link:** `http://filmozercy.com/`
**Category:** ads
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
**Extension:** Nano Defender 15.0.0.42

### Additional Message

I see blu ads with "wspieraj naszą pracę. Wyłącz adblocka". I have tried averything

**Comment by ZaphodBeebblebrox** [comment]
@MajkiIT 
`filmozercy.com##a[href$="filmozercy.com/wspieraj-nasza-prace-wylacz-adblocka"]`

**Comment by jspenguin2017** [comment]
Resolved in Nano filters.
