### ISSUE TITLE
wholicab.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#642]
### Basic Information

**Test link:** `https://wholicab.com/5c5874b65011f`
**Category:** anti-adblock
**Reported from:** Armenia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.90

**Comment by okiehsch** [comment]
Fixed.
