### ISSUE TITLE
surviviohacks.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#643]
### Basic Information

**Test link:** `https://surviviohacks.com/?p=9267`
**Category:** anti-adblock
**Reported from:** Austria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 OPR/57.0.3098.116
**Extension:** Nano Defender 15.0.0.90

**Comment by okiehsch** [comment]
Fixed.
