### ISSUE TITLE
cuemovie.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#645]
### Basic Information

**Test link:** `http://www.cuemovie.com/column/zootopia-trivia/`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.90

**Comment by jspenguin2017** [comment]
@okiehsch Tried Japanese regional filters. 
![image](https://user-images.githubusercontent.com/7283682/52903252-de5edf80-31d7-11e9-82fd-940a8de2b97d.png)

**Comment by okiehsch** [comment]
Fixed.
