### ISSUE TITLE
download.ipeenk.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#647]
### Basic Information

**Test link:** `https://download.ipeenk.com/legend-zelda-breath-wild.html`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.90

### Additional Message

anti adblock

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/52903273-1534f580-31d8-11e9-8978-1b0297e3a9d8.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://download.ipeenk.com/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.168

### Additional Message

Adblocker detected! Please consider reading this notice.
We've detected that you are using AdBlock Plus or some other adblocking software which is preventing the page from fully loading.

We don't have any banner, Flash, animation, obnoxious sound, or popup ad. We do not implement these annoying types of ads!

We need money to operate the site, and almost all of it comes from our online advertising.

Please add download.ipeenk.com to your ad blocking whitelist or disable your adblocking software.

**Comment by jspenguin2017** [comment]
@okiehsch Hard `anOptions`.

**Comment by okiehsch** [comment]
Fixed.
