### ISSUE TITLE
theme-download.club

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#649]
### Basic Information

**Test link:** `https://www.theme-download.club/super-pro-multipurpose-powerpoint-template-bundle`
**Category:** anti-adblock
**Reported from:** Algeria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
**Extension:** Nano Defender 15.0.0.90

**Comment by okiehsch** [comment]
Fixed.
