### ISSUE TITLE
heidisql.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#656]
### Basic Information

**Test link:** `https://www.heidisql.com/download.php`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
**Extension:** Nano Defender 15.0.0.90

### Additional Message

press download button will prompt a warning

**Comment by jspenguin2017** [comment]
Can't reproduce, pressing download button directly downloads a file.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.heidisql.com/download.php`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.118

### Additional Message

Original URL: `chrome://newtab/`

**Comment by jspenguin2017** [comment]
@okiehsch Soft anti-adblock.

**Comment by okiehsch** [comment]
Fixed.
