### ISSUE TITLE
goalad.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#66]
### Basic Information

**Test link:** `http://goalad.com/annunci-italia/sega-circolare-teknico-come-titolo-vendo`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0
**Extension:** Nano Defender 15.0.0.42

### Additional Message

Per poter utilizzare tutte le funzionalità disattiva ad blocker!
goalAd è totalmente gratuito senza pubblicità invasive.

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/45257070-42de5e80-b35d-11e8-926d-4968de550c12.png)
