### ISSUE TITLE
yowi.tv

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#670]
### Basic Information

**Test link:** `https://yowi.tv`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
**Extension:** Nano Defender 15.0.0.91

### Additional Message

can't reproduce videos with any adblocker

**Comment by okiehsch** [comment]
Fixed.
