### ISSUE TITLE
novaplus.nova.cz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#672]
### Basic Information

**Test link:** `https://novaplus.nova.cz/porad/masterchef-cesko/epizoda/30454-5-dil-6-2-2019`
**Category:** anti-adblock
**Reported from:** Czechia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.90

**Comment by okiehsch** [comment]
Fixed.
