### ISSUE TITLE
chron.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#673]
### Basic Information

**Test link:** `https://www.chron.com/business/energy/article/Report-Texas-crude-oil-production-breaks-1970s-13606658.php`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.90

### Additional Message

IL/g00 crap loading on firefox

**Comment by mapx-** [comment]
fixed
