### ISSUE TITLE
hubzter.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#677]
### Basic Information

**Test link:** `https://hubzter.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
**Extension:** Nano Defender 15.0.0.93

### Additional Message

Unable browse site cause of adblock warning.

**Comment by okiehsch** [comment]
Fixed.
