### ISSUE TITLE
powforums.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#680]
### Basic Information

**Test link:** `https://powforums.com/thread/184659348/anime/5toubun-no-hanayome-73.html`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.93

### Additional Message

require to disable adblock to view page(compulsory)

**Comment by jspenguin2017** [comment]
@okiehsch Similar to https://github.com/NanoMeow/QuickReports/issues/620
`https://www.google.ca/search?q=%225toubun+no+Hanayome+73%22+site%3Apowforums.com&oq=%225toubun+no+Hanayome+73%22+site%3Apowforums.com&aqs=chrome..69i57.1402j0j7&sourceid=chrome&ie=UTF-8`

**Comment by okiehsch** [comment]
Fixed.
