### ISSUE TITLE
theglobeandmail.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#682]
### Basic Information

**Test link:** `https://www.theglobeandmail.com/canada/toronto/article-peel-police-dismayed-with-complaints-after-late-hour-of-amber-alert/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
**Extension:** Nano Defender 15.0.0.93

### Additional Message

Ads placeholders

**Comment by jspenguin2017** [comment]
Ads placeholders. Can be difficult due to the way CSS works on this website.

**Comment by DandelionSprout** [comment]
I can't find any placeholders there anymore.
