### ISSUE TITLE
protect.databird.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#685]
### Basic Information

**Test link:** `https://protect.databird.xyz/getlink?link=https://www.fshare.vn/file/NA8YWCQDDI5WU9E?token=1550321209`
**Category:** anti-adblock
**Reported from:** Singapore
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
**Extension:** Nano Defender 15.0.0.93

**Comment by okiehsch** [comment]
Fixed.
