### ISSUE TITLE
robloxscripts.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#686]
### Basic Information

**Test link:** `https://robloxscripts.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
**Extension:** Nano Defender 15.0.0.93

### Additional Message

Anti-AdBlock annoyance popup

**Comment by okiehsch** [comment]
Fixed.

**Comment by theinstantmatrix** [comment]
Anti-Adblock Script

![Screenshot_2020-01-01 Home](https://user-images.githubusercontent.com/24980766/71649619-62ca2c00-2cde-11ea-866a-99eff8366cef.png)

**Comment by okiehsch** [comment]
Fixed.
