### ISSUE TITLE
qaru.site

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#69]
### Basic Information

**Test link:** `http://qaru.site/questions/31161/gson-directly-convert-string-to-jsonobject-no-pojo`
**Category:** anti-adblock
**Reported from:** Kazakhstan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
**Extension:** Nano Defender 15.0.0.42

**Comment by okiehsch** [comment]
I don't think that this is fixed, but I don't speak russian and so not sure.
After I update `uBO-filters`.
![image](https://user-images.githubusercontent.com/16838044/45268653-f2135680-b47f-11e8-98fe-9780a125ac4f.png)

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/45269005-4d732380-b443-11e8-96c8-ac1f9b8750f1.png)

**Comment by jspenguin2017** [comment]
Yea, it's not fixed.
