### ISSUE TITLE
emathhelp.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#698]
### Basic Information

**Test link:** `https://www.emathhelp.net/calculators/algebra-2/parabola-calculator/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
**Extension:** Nano Defender 15.0.0.93

### Additional Message

"Sponsored" tab above calculator, seems to have a random name per refresh.

`https://i.imgur.com/xI3bcpz.png`

**Comment by okiehsch** [comment]
Fixed.
