### ISSUE TITLE
the-hermeneutic-of-continuity.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#699]
### Basic Information

**Test link:** `https://the-hermeneutic-of-continuity.blogspot.com/2019/02/the-value-of-learning-by-heart.html`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3700.0 Iron Safari/537.36
**Extension:** Nano Defender 15.0.0.89

### Additional Message

Ad blocking results in just a background issue showing.

**Comment by jspenguin2017** [comment]
@okiehsch FYI

**Comment by okiehsch** [comment]
Fixed.
