### ISSUE TITLE
androidcentral.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#701]
### Basic Information

**Test link:** `https://www.androidcentral.com/best-galaxy-s10-cases?utm_source=ac_tw&utm_medium=tw_card&utm_content=72648&utm_campaign=social`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.93

### Additional Message

It looks like you're using an ad blocker.
We use ads to keep our content free. Please support us by whitelisting us.

**Comment by okiehsch** [comment]
Fixed in annoyances.
