### ISSUE TITLE
secondnexus.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#707]
### Basic Information

**Test link:** `https://secondnexus.com/news/amy-berman-jackson-mueller-roger-stone/`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.95

### Additional Message

Displays message asking visitor to switch off adblocking for their site. Article can still be viewed by closing the message.

**Comment by mapx-** [comment]
it's fixed in ublock annoyances
