### ISSUE TITLE
eurogamer.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#709]
### Basic Information

**Test link:** `https://www.eurogamer.net/articles/digitalfoundry-2019-02-22-best-graphics-cards-2019-7001`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.96

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/53686898-91582e80-3cea-11e9-853f-178754958907.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.eurogamer.net/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.106

### Additional Message

**Comment by jspenguin2017** [comment]
Fixed ads placeholders (some are on home page).
