### ISSUE TITLE
veekyforums.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#71]
### Basic Information

**Test link:** `https://veekyforums.com/thread/205209910/video-games/alg-azur-lane-general-126.html`
**Category:** anti-adblock
**Reported from:** Ireland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
**Extension:** Nano Defender 15.0.0.42

**Comment by jspenguin2017** [comment]
@okiehsch 
Similar to https://github.com/uBlockOrigin/uAssets/issues/2628
Need to enter through Google to trigger: 
`https://www.google.ca/search?newwindow=1&source=hp&ei=yWOWW4WJLYXd8APng67QCw&q=%2Falg%2F+-+Azur+Lane+General+%23126&oq=%2Falg%2F+-+Azur+Lane+General+%23126&gs_l=psy-ab.3...910.910.0.1193.3.2.0.0.0.0.132.132.0j1.2.0....0...1c.1.64.psy-ab..1.1.99.6..35i39k1.100.p7XHFbANNkg`
