### ISSUE TITLE
eppingforestguardian.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#713]
### Basic Information

**Test link:** `https://www.eppingforestguardian.co.uk/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
**Extension:** Nano Defender 15.0.0.94

### Additional Message

Periodically has a notice at the bottom of the page saying to turn off the adblocker

**Comment by mapx-** [comment]
fixed as annoyance
