### ISSUE TITLE
travelchannel.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#714]
### Basic Information

**Test link:** `https://www.travelchannel.com/interests/national-parks/articles/what-to-do-at-zion-national-park-other-than-hike`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.97

**Comment by mapx-** [comment]
seems working:
```
@@||code.adsales.snidigital.com/conf/ads-config.js$script,domain=travelchannel.com
||code.adsales.snidigital.com/lib/*/sni-ads.min.js$script,domain=travelchannel.com
```

first => unbreaking the page
second => fixing annoyance anti adb message at the bottom

**Comment by jspenguin2017** [comment]
The anti-adblock is already caught in a generic filter in the Nano Defender Integration filter: `##.o-AdhesionNotifier`

Ads placeholder fixed in Placeholder Buster.
