### ISSUE TITLE
vipracing.icu

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#715]
### Basic Information

**Test link:** `http://vipracing.icu/channel/canal-35#`
**Category:** anti-adblock
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 YaBrowser/19.1.2.258 Yowser/2.5 Safari/537.36
**Extension:** Nano Defender 15.0.0.96

**Comment by okiehsch** [comment]
Fixed.
