### ISSUE TITLE
closeronline.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#718]
### Basic Information

**Test link:** `https://closeronline.co.uk/real-life/news/murdered-schoolgirl-danielle-jones-body-mum-linda-loose-women/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
**Extension:** Nano Defender 15.0.0.97

### Additional Message

Still detecting adblocker

**Comment by okiehsch** [comment]
Fixed.
