### ISSUE TITLE
spaste.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#72]
### Basic Information

**Test link:** `http://www.spaste.com/p/?c=yIZji74587`
**Category:** other
**Reported from:** Bangladesh
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
**Extension:** Nano Defender 15.0.0.42

### Additional Message

Instead of removing ads properly, it leaves an empty space on it's place, sometime saying ''loading...''

**Comment by jspenguin2017** [comment]
Hum... I'm not sure if blocking that would trigger anti-adblock.

**Comment by okiehsch** [comment]
I don't see a placeholder on my end.

**Comment by jspenguin2017** [comment]
You'll see it once you solved the captcha.

**Comment by okiehsch** [comment]
![unbenannt](https://user-images.githubusercontent.com/16838044/45388843-7bf72700-b61a-11e8-9001-1c156ae4a358.JPG)

**Comment by jspenguin2017** [comment]
Ah, I see, it's an old rule from AAK.

**Comment by jspenguin2017** [comment]
I still need to test to make sure I didn't blow anything up.

**Comment by jspenguin2017** [comment]
Looks good.
