### ISSUE TITLE
calculate.plus

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#721]
### Basic Information

**Test link:** `https://calculate.plus/en/categories/frequency/convert/hertz/to/nanometers-wavelengths`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
**Extension:** Nano Defender 15.0.0.97

### Additional Message

"wait 30 secs for result" prompt

**Comment by okiehsch** [comment]
Fixed.
