### ISSUE TITLE
play.nova.bg

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#723]
### Basic Information

**Test link:** `https://play.nova.bg/video/kato-dve-kapki-voda/season-7/kato-dve-kapki-voda-2019-02-25-1`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.99

### Additional Message

ad blocking is detected and player dosnt' run

**Comment by mapx-** [comment]
> This video is only available in All content access only from Bulgaria.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://play.nova.bg/video/dqvolskoto-gyrlo/season-1/dqvolskoto-gyrlo-2019-02-28`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
**Extension:** Nano Defender 15.0.0.104

### Additional Message

**Comment by jspenguin2017** [comment]
@okiehsch Comes up every time, tried Bulgarian regional filters. 
![image](https://user-images.githubusercontent.com/7283682/53687572-6e7e4800-3cf3-11e9-8584-8c5f3a78f6b5.png)
