### ISSUE TITLE
vejasp.abril.com.br

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#727]
### Basic Information

**Test link:** `https://vejasp.abril.com.br/cidades/apagao-e-buracos-enterramento-de-fios-causa-problemas-na-vila-olimpia/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.100

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. Ads placeholder removed in the contrib filter.
