### ISSUE TITLE
yellowbridge.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#729]
### Basic Information

**Test link:** `https://www.yellowbridge.com/chinese/dictionary.php`
**Category:** ads
**Reported from:** Ukraine
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.100

### Additional Message

This site detects nano adblocker/ublock origin (I'm currently using only nano adblocker+ nano defender). It doesn't work.
If you click on the little brush near hanji the alert window is popping up with the message: "This page is operating in a degraded mode. Please disable ad blocker to enable stroke order animation."

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. 

Bad whitelists from AAK removed.

**Comment by jspenguin2017** [comment]
This still needs some work.

**Comment by jspenguin2017** [comment]
Can't reproduce hard anti-adblock. Soft anti-adblock fixed.
