### ISSUE TITLE
beewits.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#730]
### Basic Information

**Test link:** `https://www.beewits.com/website-design-questionnaire/`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
**Extension:** Nano Defender 15.0.0.102

### Additional Message

Downloads are blocked when using an adblocker.

**Comment by okiehsch** [comment]
Fixed.
