### ISSUE TITLE
callstevens.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#732]
### Basic Information

**Test link:** `http://www.callstevens.com/botw-wallpaper-4k.html`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.89

**Comment by okiehsch** [comment]
Fixed.
