### ISSUE TITLE
gamekult.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#735]
### Basic Information

**Test link:** `https://www.gamekult.com/actualite/cd-projekt-confirme-le-retour-de-cyberpunk-2077-a-l-e3-2019-3050814377.html`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.102

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance. 
![image](https://user-images.githubusercontent.com/7283682/54076318-a80d0100-4267-11e9-8b9d-ea2c2371518e.png)

**Comment by okiehsch** [comment]
My french is really bad, so to be sure 
@smed79 if I add
`gamekult.com##+js(abort-on-property-read.js, SmartWallSDK)`
does that circumvent any paywall on that site or does it only dismiss the adblock notice?

**Comment by smed79** [comment]
Remove the paywall for premium account.

**Comment by jspenguin2017** [comment]
If that's the case, their paywall needs and emergency redesign.

**Comment by smed79** [comment]
I am ok to remove the "[anti-adblock notice](https://vgy.me/S1cTxz.png)" => [cb1cd4ad45d5](https://hg.adblockplus.org/antiadblockfilters/rev/cb1cd4ad45d5) in **[AWRL](https://adblockplus.org/fr/subscriptions#type_anti-adblock)** but I will leave the [paywall banner](https://vgy.me/PMANPP.png).

**Comment by jspenguin2017** [comment]
After a few visit, it changes to ads wall, which is not allowed. The cosmetic filter does not remove the ads wall.

**Comment by jspenguin2017** [comment]
Reclassified as hard anti-adblock.

**Comment by okiehsch** [comment]
> After a few visit, it changes to ads wall

I can reproduce
![image](https://user-images.githubusercontent.com/16838044/54078855-6c5a5180-42d0-11e9-9a44-55f9ea229e97.png)

I will add the filter.

**Comment by okiehsch** [comment]
Fixed.
