### ISSUE TITLE
rockpapershotgun.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#737]
### Basic Information

**Test link:** `https://www.rockpapershotgun.com/`
**Category:** anti-adblock
**Reported from:** Russia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.104

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.rockpapershotgun.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
**Extension:** Nano Defender 15.0.0.104

### Additional Message

Detects my adblocker and blocks me from the site

**Comment by jspenguin2017** [comment]
Has some empty ads placeholders, but can't reproduce anti-adblock. 
![image](https://user-images.githubusercontent.com/7283682/54076336-dee31700-4267-11e9-9f3c-208ed55fe1a4.png)

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/5ce67e0e7c70d23c7792d6886a181fe898574437
