### ISSUE TITLE
flacmusicfinder.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#740]
### Basic Information

**Test link:** `http://flacmusicfinder.com/d/?id=eTFzaGJsUlNtR0xsL0Z5K2N1TWcvS3N3MHY4dC9vMEhQSTlHMTlZbkhnQjBSM2RsVUM5S05GQlhhMUIzVFhodldFbE9XbTl2UjNaVGNFTTNTRm9yVUZWNU1GUndTbkpxTm1OdFQzUnFORkZJWW5OM2RXcEJNRmh1T0dkM04xUm8=`
**Category:** anti-adblock
**Reported from:** Iran
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
**Extension:** Nano Defender 15.0.0.104

### Additional Message

I get this message:
Error Adblock
You have enabled ad blocking, which prevents displaying a link to download the file. Turn off the lock (eg. Adblock or others) and reload the page to see the link

**Comment by jspenguin2017** [comment]
@okiehsch Go to `http://flacmusicfinder.com/`, click any download button, then click the green download button. 
![image](https://user-images.githubusercontent.com/7283682/53686087-37526b80-3ce0-11e9-8181-e37b706847d4.png)
