### ISSUE TITLE
teknomatch.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#742]
### Basic Information

**Test link:** `https://www.teknomatch.com/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
**Extension:** Nano Defender 15.0.0.106

**Comment by okiehsch** [comment]
Fixed.
