### ISSUE TITLE
alphaantileak.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#744]
### Basic Information

**Test link:** `https://alphaantileak.net/ads.html?port=1337`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
**Extension:** Nano Defender 15.0.0.106

**Comment by mapx-** [comment]
fixed
