### ISSUE TITLE
filmbit.ws

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#748]
### Basic Information

**Test link:** `http://filmbit.ws/kanal/81/eleven-sports-2`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
**Extension:** Nano Defender 0.0.105.0

### Additional Message

"Please turn off adblock" in free player on every channel on this site.

**Comment by okiehsch** [comment]
Fixed.
