### ISSUE TITLE
animeland.us

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#750]
### Basic Information

**Test link:** `https://www.animeland.us/black-clover-episode-70-english-dubbed`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.90

### Additional Message

side ads use to be block but arnt now

**Comment by okiehsch** [comment]
Fixed.
