### ISSUE TITLE
thehindu.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#751]
### Basic Information

**Test link:** `https://www.thehindu.com/sci-tech/upgraded-vikas-engine-will-soon-boost-isros-rockets/article24436241.ece`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.106

### Additional Message

Its detecting ad blocker.Pls add it to anti adblock

**Comment by okiehsch** [comment]
Fixed.
