### ISSUE TITLE
okdiario.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#753]
### Basic Information

**Test link:** `https://okdiario.com/`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.79
**Extension:** Nano Defender 15.0.0.106

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://okdiario.com/`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.79
**Extension:** Nano Defender 15.0.0.106

### Additional Message

**Comment by okiehsch** [comment]
Fixed.
