### ISSUE TITLE
momoniji.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#754]
### Basic Information

**Test link:** `http://momoniji.com/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.106

### Additional Message

nsfw ads placeholders

**Comment by DandelionSprout** [comment]
If it's the top banner the reporter was thinking of, `momoniji.com##iframe[src="http://momoniji.com/rss/momonijitopRSS.html"]` takes care of it. I can't find any more obvious placeholders at first glance.
