### ISSUE TITLE
porndish.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#76]
### Basic Information

**Test link:** `https://www.porndish.com/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
**Extension:** Nano Defender 15.0.0.42

**Comment by mapx-** [comment]
I get no anti adb stuff
