### ISSUE TITLE
svscomics.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#761]
### Basic Information

**Test link:** `https://svscomics.com/download/403119/illusion-koikatu-2018-new-game-eng`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.106

### Additional Message

clike tumbnails open scam popup ads

**Comment by jspenguin2017** [comment]
@okiehsch Popup.
