### ISSUE TITLE
hongfire.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#762]
### Basic Information

**Test link:** `http://www.hongfire.com/forum/forum/hentai-lair/hentai-game-discussion/5921249-illusion-koikatu-%E3%82%B3%E3%82%A4%E3%82%AB%E3%83%84%EF%BC%81-discussion-and-faq`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.90

**Comment by jspenguin2017** [comment]
@okiehsch Ads.

**Comment by okiehsch** [comment]
Fixed.
