### ISSUE TITLE
vinaurl.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#763]
### Basic Information

**Test link:** `https://vinaurl.net/BbWfc63eOl`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 YaBrowser/19.3.0.2485 Yowser/2.5 Safari/537.36
**Extension:** Nano Defender 15.0.0.106

### Additional Message

Turn off Adblock to continue

**Comment by jspenguin2017** [comment]
@okiehsch Anti-adblock (only) when Vietnamese regional filters enabled.
