### ISSUE TITLE
thegayuk.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#766]
### Basic Information

**Test link:** `https://www.thegayuk.com/leaving-neverland-when-is-the-michael-jackson-film-on-and-what-channel/`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.106

**Comment by okiehsch** [comment]
Fixed.
