### ISSUE TITLE
smarteasystudy.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#768]
### Basic Information

**Test link:** `https://smarteasystudy.com/VazEGw`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.106

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/fcdbf5ea187e60b8f54b0eeed577f1c2d0f20b3e
