### ISSUE TITLE
kissanime.si

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#777]
### Basic Information

**Test link:** `https://kissanime.si/Anime/Dragon-Ball-Kai-2014-Dub-KissAnime/Episode-067?id=137478`
**Category:** ads
**Reported from:** Israel
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.90

**Comment by okiehsch** [comment]
Fixed anti-adblock message.
