### ISSUE TITLE
thesimsresource.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#779]
### Basic Information

**Test link:** `https://www.thesimsresource.com/`
**Category:** anti-adblock
**Reported from:** Sweden
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

### Additional Message

Nanoblocker does not work

**Comment by jspenguin2017** [comment]
Has some empty ads placeholders, can't reproduce other issues.
