### ISSUE TITLE
ruwix.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#783]
### Basic Information

**Test link:** `https://ruwix.com/puzzle-scramble-generators/rubiks-cube-scrambler/`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.67 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance. Recommended rule: `||ruwix.com/noindex/whitelist/$subdocument`

**Comment by okiehsch** [comment]
Fixed in annoyances.
