### ISSUE TITLE
economictimes.indiatimes.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#784]
### Basic Information

**Test link:** `https://economictimes.indiatimes.com/news/international/world-news/at-least-13-killed-in-a-bar-shooting-in-violent-mexico-state/articleshow/68337714.cms`
**Category:** ads
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.67 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.92

**Comment by jspenguin2017** [comment]
Has some leftover ads placeholders.

**Comment by mapx-** [comment]
it's not about (only) ads PH, but entire ads section not marked by "ad" for any story

these filters should help
https://github.com/NanoMeow/QuickReports/issues/782#issuecomment-471273663
