### ISSUE TITLE
navbharattimes.indiatimes.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#785]
### Basic Information

**Test link:** `https://navbharattimes.indiatimes.com/business/business-news/consumers-facing-problems-after-trais-new-tariff-order/articleshow/68264046.cms`
**Category:** ads
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.67 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

**Comment by ghajini** [comment]
@mapx-
ads back 

from around the web

`https://navbharattimes.indiatimes.com/india/lockheed-says-f21-jets-will-not-be-sold-to-any-other-country-if-it-wins-iaf-deal/articleshow/69309911.cms`

![Screenshot (7)](https://user-images.githubusercontent.com/20338483/57644459-c41b7e80-75d9-11e9-8802-dab7a78e963c.png)

some are legit stories

**Comment by mapx-** [comment]
see
https://github.com/NanoMeow/QuickReports/issues/787#issuecomment-491941271

**Comment by ghajini** [comment]
Hello @mapx- 
This rule 
`indiatimes.com##+js(std, adBlockDetectionStart)` 

Causes `navbharattimes.indiatimes.com` to go blank.....articles do load but homepage is blank

**Comment by ghajini** [comment]
Besides that only `timesofindia.indiatimes.com` give Adblock detection.....I checked its affiliated sites,no Adblock detection.....so rule should be

`timesofindia.indiatimes.com##+js(std, adBlockDetectionStart)`
