### ISSUE TITLE
punemirror.indiatimes.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#786]
### Basic Information

**Test link:** `https://punemirror.indiatimes.com/news/india/india-withdraws-most-fovoured-nation-status-to-pakistan/articleshow/68005008.cms?utm_source=Articleshow&utm_medium=Organic&utm_campaign=Related_Stories`
**Category:** ads
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.67 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

**Comment by jspenguin2017** [comment]
Has some leftover ads placeholders.

**Comment by mapx-** [comment]
1. There is a wrong filter in easylist (all the stories are hidden - ad or non-ad)
we have to add `indiatimes.com#@#a[onclick*="/click.htm?"]`
@ryanbr
2. and the necessary filter
`indiatimes.com##[onclick] p:has-text(/Ad/):xpath(../../..)`
