### ISSUE TITLE
maharashtratimes.indiatimes.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#787]
### Basic Information

**Test link:** `https://maharashtratimes.indiatimes.com/business/business-news/gratutity-upto-20-lakhs-is-tax-free-important-decision-of-modi-government/articleshow/68300410.cms`
**Category:** ads
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.67 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

**Comment by ghajini** [comment]
@mapx-
Ads reappeared over here
`https://maharashtratimes.indiatimes.com/india-news/if-modi-comes-to-power-amit-shah-will-become-home-minsiter-predicts-kejriwal/articleshow/69261568.cms`
![IMG_20190513_231009](https://user-images.githubusercontent.com/20338483/57642199-3ecaa680-75a6-11e9-9719-077ec8bfeffa.jpg)
Some are legit content like those labelled `ad Maharashtratimes` or `ad timesprime` stories

**Comment by mapx-** [comment]
test 
`maharashtratimes.indiatimes.com##[onclick] p:matches-css-before(content:/Ad /):xpath(../..):not(p:has-text(MAHA)):not(p:has-text(Times))`

**Comment by mapx-** [comment]
test
`indiatimes.com##[onclick] p:matches-css-before(content:/Ad /):xpath(../..):not(p:has-text(/MAHA/i)):not(p:has-text(/Times/i))`

for both `sites maharashtratimes` & `navbharattimes`

and add (`:not` structures) whatever legit content still necessary

**Comment by ghajini** [comment]
above filter lose effectiveness when scrolling downwards and page tries to load new story ,at end of new story again ads are loaded...also if you scroll upwars to original 1st story i see again ads at end of 1st story .....
these are affected sites

https://telugu.samayam.com/latest-news/state-news/chiranjeevi-international-school-not-related-to-mega-star-family-says-school-management/articleshow/69314712.cms

https://eisamay.indiatimes.com/west-bengal-news/kolkata-news/lightning-strike-sets-rajarhat-vedic-village-on-fire/articleshow/69314141.cms

https://vijaykarnataka.indiatimes.com/news/govt-will-be-safe-says-hd-kumaraswamy/articleshow/69312505.cms

https://maharashtratimes.indiatimes.com/india-news/kamal-haasans-hindu-extremist-remark-stirs-row/articleshow/69313926.cms

https://malayalam.samayam.com/latest-news/kerala-news/congress-leader-anto-antony-criticises-polling-officers-in-pathanamthitta/articleshow/69311769.cms

https://navbharattimes.indiatimes.com/india/lockheed-says-f21-jets-will-not-be-sold-to-any-other-country-if-it-wins-iaf-deal/articleshow/69309911.cms

**Comment by mapx-** [comment]
yeah, appear & disappear, for me it's server side

however, last filters:
```
indiatimes.com,samayam.com##[onclick] p:matches-css-before(content:/Ad /):xpath(../..):not(p:has-text(/MAHA/i)):not(p:has-text(/Times/i))
samayam.com##:xpath(//span[(text()='Ad')]/../../..)
```

**Comment by ghajini** [comment]
Like this problem(ad appear-disappear)
https://upload-video.net/a1113cd2F05-noau

**Comment by mapx-** [comment]
yes, I can reproduce that behaviour. As I said it seems to be a site issue.

**Comment by ghajini** [comment]
Okay,it seems they(times India network Ltd) had upper hand....
Thanks
