### ISSUE TITLE
eisamay.indiatimes.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#788]
### Basic Information

**Test link:** `https://eisamay.indiatimes.com/nation/man-kills-wife-with-bricks-in-gurugram/articleshow/68339527.cms`
**Category:** ads
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.67 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

**Comment by jspenguin2017** [comment]
Fixed by https://github.com/uBlockOrigin/uAssets/commit/516ea7d12348595592ed47b7e770a5d7d2a52ab1
