### ISSUE TITLE
realstream.pw

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#791]
### Basic Information

**Test link:** `http://www.realstream.pw/en/player/5c84df7cacbf0392142070/14/163/5c8538f0a219d/c3b6f877c5e5862da6f88d76dfa9c6f7`
**Category:** other
**Reported from:** Netherlands
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.92

### Additional Message

The adblocker stops the stream from playing. When turning the adblocker off, the stream starts playing again.

**Comment by jspenguin2017** [comment]
@okiehsch Breakage.
