### ISSUE TITLE
m.timesofindia.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#792]
### Basic Information

**Test link:** `https://m.timesofindia.com/articleshow_comments/68263251.cms`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 9; Mobile; rv:65.0) Gecko/65.0 Firefox/65.0
**Extension:** Nano Defender 15.0.0.106

**Comment by jspenguin2017** [comment]
Works fine for me. Can't reproduce anti-adblock. 
![image](https://user-images.githubusercontent.com/7283682/54088800-70658e00-4327-11e9-8c3c-b0bc0859a719.png)

**Comment by ghajini** [comment]
https://github.com/uBlockOrigin/uAssets/commit/397abe9b7e5f26471286870f8a016743d26e80d5

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://m.timesofindia.com/videos/sports/cricket/clash-breaks-out-between-pakistan-and-afghanistan-fans-at-headingley/videoshow/70004499.cms`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Linux; Android 9; ZB601KL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.101 Mobile Safari/537.36
**Extension:** Nano Defender 15.0.0.153

### Additional Message

Nano defender adblock detected.

**Comment by jspenguin2017** [comment]
@okiehsch Only affects mobile it seems. 
![image](https://user-images.githubusercontent.com/7283682/60405337-a647b000-9b6c-11e9-9b27-ac45f73095ba.png)

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/d6f4c57e5eabde35d9f60ff247373e0c6baffc71
