### ISSUE TITLE
indiatimes.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#793]
### Basic Information

**Test link:** `https://www.indiatimes.com/news/india/former-navy-chief-writes-to-election-commission-to-stop-misuse-of-armed-forces-in-polls-363444.html`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.67 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

**Comment by ghajini** [comment]
Which type of ads?

**Comment by mapx-** [comment]
I guess those 2-3 on the right side (see the colombia icon)

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/884f2b870ce018e02cfc935f5becd2ba5d5025f8

**Comment by ghajini** [comment]
I think there are ads under `you may like` on Firefox android too....
`https://m.indiatimes.com/news/india/former-navy-chief-writes-to-election-commission-to-stop-misuse-of-armed-forces-in-polls-363444.html`

**Comment by ghajini** [comment]
By the way @jspenguin2018, nanomeow doesn't show screenshot unlike adguard-bot

**Comment by mapx-** [comment]
works for me, test on your side

**Comment by jspenguin2017** [comment]
@ghajini I can add that if there's a need for it. I don't feel like screenshots would really help.

**Comment by ghajini** [comment]
Helpful for distinguish between ads and legit content in languages other than english

**Comment by jspenguin2017** [comment]
Allowing screenshots will make moderation costs higher since NanoMeow needs to upload the screenshots to GitHub so I'm responsible for the content of the screenshots. 

I assume AdGuard has full-time staff to screen the reports that come through, but we don't. I checked AdGuard bot's posts and I don't think the screenshots are very useful.

**Comment by jspenguin2017** [comment]
I do think gathering part of the settings with the report will be helpful though. Things like enabled filters, whether advanced settings was touched, etc.
