### ISSUE TITLE
sevenforums.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#8]
### Basic Information

**Test link:** `https://www.sevenforums.com/hardware-devices/366116-wd-2tb-external-drive-unknown-not-initialized-unallocated.html`

**Category:** anti-adblock

**Reported from:** United States

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.35

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/44373836-86555380-a4a8-11e8-87df-2444a0c76120.png)

**Comment by okiehsch** [comment]
Fixed in `uBO-annoyances`
