### ISSUE TITLE
nbcnews.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#800]
### Basic Information

**Test link:** `https://www.nbcnews.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

### Additional Message

First, clear all cookies for "nbcnews" as this anti-adblocker does not show up every single time you visit the website.

Getting msg "Welcome to NBC News. Please support our journalism by allowing ads.
With support from readers like you, we can continue to deliver the best in breaking news, politics, culture, opinion and more. You can support us for free by allowing ads."

Powered by Admiral

**Comment by okiehsch** [comment]
Already fixed in annoyances.

**Comment by jspenguin2017** [comment]
I have to say that I'm quite disappointed. I'm fine with you guys adding soft anti-adblock solutions to the annoyance filter, but specifically whitelisting anti-adblock scripts and open up third-party connections? So much for "wide-spectrum" content blocker, huh.

**Comment by okiehsch** [comment]
https://twitter.com/gorhill/status/1072990091625328641

The reasoning behind it is that the sites should have the ability to ask their users to disable their adblockers in a non intrusive way.
I can see your point about third-party connections.

**Comment by jspenguin2017** [comment]
The policy @gorhill posted on Twitter is OK. Although I don't entirely agree, I can accept. But why is up to uAssets to enforce the policy for other filter lists? Aren't the limited volunteers at uAssets already busy enough? Not to mention that "soft" anti-adblock is pretty intrusive, full screen overlay with a tiny link to close.

**Comment by okiehsch** [comment]
Well, we are not actively searching for such sites, but if one opens an issue a `uAssets`.
````
https://github.com/uBlockOrigin/uAssets/issues/4350
https://github.com/uBlockOrigin/uAssets/issues/4957
````

**Comment by jspenguin2017** [comment]
If one opens an issue at uAssets, tell him to forward his complains to Peter Lowe.

**Comment by okiehsch** [comment]
What I did was asking gorhill how he wants tò handle such issues considering his tweet and he made it clear in
````
https://github.com/uBlockOrigin/uAssets/issues/4350
````
how he wants too handle such issues.

**Comment by gorhill** [comment]
What maybe we could improve is using `badfilter` instead, such that those using Annoyances are not connecting to Admiral's servers, i.e.:

"uBO filters":

    ||squirrelhands.com^$badfilter
    ||squirrelhands.com^$domain=~nbcnews.com

"uBO Annoyances":

    ||squirrelhands.com^$script,domain=nbcnews.com

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/cdb020350002c0e6eada6242ff7c47dceb37e325
