### ISSUE TITLE
bitvin.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#802]
### Basic Information

**Test link:** `https://bitvin.org/en/search/Kanye+west+graduation`
**Category:** anti-adblock
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 YaBrowser/19.3.0.2485 Yowser/2.5 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

### Additional Message

This site detects the Adblock yet, i'm using Nano Defender + uBlock Origin.

Thank you for your great work!

**Comment by okiehsch** [comment]
Fixed.
