### ISSUE TITLE
papers.gceguide.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#805]
### Basic Information

**Test link:** `https://papers.gceguide.com/A%20Levels/Mathematics%20(9709)/`
**Category:** anti-adblock
**Reported from:** Pakistan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.92

### Additional Message

Disable adblock banner

**Comment by okiehsch** [comment]
Fixed.
