### ISSUE TITLE
viafree.no

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#808]
### Basic Information

**Test link:** `https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-11/episode-1`
**Category:** anti-adblock
**Reported from:** Norway
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

### Additional Message

It didnt block ads.

**Comment by okiehsch** [comment]
@DandelionSprout could you have a look?
I get an anti adblock message.
![image](https://user-images.githubusercontent.com/16838044/54328620-ea8b6080-460e-11e9-87a7-d8f1187772f6.png)


`@@||fwmrm.net/crossdomain.xml$xhr,domain=viafree.dk|viafree.no`
seems to fix it on my end but I am geo blocked, so I can't tell if more filters are needed.

**Comment by DandelionSprout** [comment]
I can confirm that your suggested entry works.

I'm also puzzled to learn that Paradise Hotel is geo-blocked, due to it being a native Viasat production, but fair enough.
