### ISSUE TITLE
databird.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#809]
### Basic Information

**Test link:** `https://databird.xyz/`
**Category:** anti-adblock
**Reported from:** Hong Kong
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

**Comment by okiehsch** [comment]
Fixed.
