### ISSUE TITLE
mlb.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#810]
### Basic Information

**Test link:** `https://www.mlb.com/`
**Category:** anti-adblock
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.92

### Additional Message

Unable to load videos seems to block this...

**Comment by okiehsch** [comment]
Fixed.
