### ISSUE TITLE
safelinkunited.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#811]
### Basic Information

**Test link:** `https://safelinkunited.blogspot.com/p/convert.html?url=IyNfTGllbSUwN0FKR0UlMDYlNUNBJTVETENGQUQlMDclMDclMTIlNUJYJTVDJTVDJTQwIyM%3D`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

**Comment by okiehsch** [comment]
Fixed.
