### ISSUE TITLE
polsatsport.pl

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#812]
### Basic Information

**Test link:** `https://www.polsatsport.pl/wiadomosc/2019-03-13/mioduski-nigdy-nie-zwatpilem-w-projekt-sa-pinto-on-wciaz-sie-aklimatyzuje/?ref=liga`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

**Comment by okiehsch** [comment]
Fixed.
