### ISSUE TITLE
oladblock.services

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#816]
### Basic Information

**Test link:** `https://oladblock.services/f/PvawPTS9HpU/`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ac0c265ad91d2f8a8361dafcd6d2d5341eb301c5
