### ISSUE TITLE
gogoanime.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#820]
### Basic Information

**Test link:** `https://www1.gogoanime.io/`
**Category:** breakage
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/72.0.3626.121 Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.92

**Comment by jspenguin2017** [comment]
Can't reproduce breakage. There's an ads placeholder though. 
![image](https://user-images.githubusercontent.com/7283682/54730428-873d8900-4b4e-11e9-80b4-2584e24f65c9.png)

**Comment by DandelionSprout** [comment]
Placeholder:
```
! https://www19.gogoanime.io/
gogoanime.*##.adsverting:upward(1)
```
