### ISSUE TITLE
derbyshiretimes.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#823]
### Basic Information

**Test link:** `https://www.derbyshiretimes.co.uk/news/health-and-safety-executive-issues-statement-after-cows-slaughtered-at-derbyshire-farm-1-9643023`
**Category:** ads
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

**Comment by okiehsch** [comment]
Fixed.
