### ISSUE TITLE
nulledforums.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#824]
### Basic Information

**Test link:** `https://nulledforums.net/resources/`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3734.0 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.92

**Comment by jspenguin2017** [comment]
Another test link: `https://nulledforums.net/resources/permissiontimer.62/`
