### ISSUE TITLE
cutestat.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#828]
### Basic Information

**Test link:** `https://www.cutestat.com/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.108

### Additional Message

ads placeholders

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
`cutestat.com##.top_banner` (Don't add `www.` in front of it.)
