### ISSUE TITLE
telegraph.co.uk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#829]
### Basic Information

**Test link:** `https://www.telegraph.co.uk/news/politics/ed-miliband/11550245/Ed-Miliband.html`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.109

### Additional Message

ads placeholders

**Comment by jspenguin2017** [comment]
Ads placeholders.

**Comment by DandelionSprout** [comment]
The linked-to article is simply too old to get reliable indications on which elements that are truly placeholders and which ones that are simply trying to load outdated things.

Should that page be taken at face value, then these things could be blocked, but I don't really feel brave enough to add them to NanoContrib myself:

```
||renderer.qmerce.com$subdocument
telegraph.co.uk##div.gutterUnder.summaryMedium:has-text(More from the web)
```

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.telegraph.co.uk/news/2019/06/27/concern-angela-merkels-health-german-chancellor-seen-shaking/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.153

### Additional Message

video takes about 15 seconds to load, maybe a timer for an ad to play that could be boosted to just load the video immediately?

**Comment by jspenguin2017** [comment]
They do take a bit of time to load, but not 15 seconds for me. Maybe their servers are just slow.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.telegraph.co.uk/news/2020/03/14/italians-80-will-left-die-country-overwhelmed-coronavirus/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

```
www.telegraph.co.uk##.commercial-unit
www.telegraph.co.uk##.more-stories
```
