### ISSUE TITLE
bharian.com.my

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#834]
### Basic Information

**Test link:** `https://www.bharian.com.my/berita/nasional/2019/03/541975/eksklusif-siswa-miskin-ikat-perut?fbclid=IwAR33zhGpscxxV5w_izF51pXaUInGDAbPFjarjDhiOkR3WcfJXmtWJElP87s`
**Category:** anti-adblock
**Reported from:** Malaysia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.109

**Comment by okiehsch** [comment]
Fixed.
