### ISSUE TITLE
lebahkaca.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#837]
### Basic Information

**Test link:** `https://lebahkaca.com/`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.109

**Comment by okiehsch** [comment]
Fixed.

**Comment by bogachenko** [comment]
@okiehsch nope
![1](https://user-images.githubusercontent.com/8535285/54506946-e2952e80-4936-11e9-9688-3e79b60bbc59.gif)

```
lebahkaca.com##+js(abort-on-property-write.js, adBlockDetected)
lebahkaca.com##.blocker
lebahkaca.com##[href*="//bit.ly/"]
```

**Comment by okiehsch** [comment]
It's an Indonesian website, so I tested with the regional indonesian list enabled.
![image](https://user-images.githubusercontent.com/16838044/54507178-77505a00-4940-11e9-8ce9-bbcf3c77ff64.png)

With that list + the filters I added the issue is fixed on my end.

**Comment by bogachenko** [comment]
fuck/
