### ISSUE TITLE
derstandard.at

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#839]
### Basic Information

**Test link:** `https://derstandard.at`
**Category:** anti-adblock
**Reported from:** Austria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.109

### Additional Message

Shows "deactivate Adblocker" or "create a subscription".
Thank you for processing!

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://derstandard.at/`
**Category:** anti-adblock
**Reported from:** Austria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.112

### Additional Message

**Comment by jspenguin2017** [comment]
Can't reproduce, navigated through 20 articles. 
![image](https://user-images.githubusercontent.com/7283682/55663120-daaf0880-57d7-11e9-939d-3c78d4c34f17.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://derstandard.at/2000103404528/Sebastian-Kurz-hat-doch-noch-das-Notwendige-getan`
**Category:** anti-adblock
**Reported from:** Austria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.95
**Extension:** Nano Defender 15.0.0.146

### Additional Message

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://derstandard.at`
**Category:** anti-adblock
**Reported from:** Austria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.149

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

Site detects adblocker when using Windows 10, doesn't detect it when using Linux.

**Comment by jspenguin2017** [comment]
Tested on Windows 10 device, can't reproduce.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://derstandard.at`
**Category:** anti-adblock
**Reported from:** Austria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.154

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

thanks for the good work!

**Comment by jspenguin2017** [comment]
@okiehsch Looks like something changed. Anti-adblock triggers after ~5 navigations. 
![image](https://user-images.githubusercontent.com/7283682/61174972-0a06ab80-a565-11e9-9868-6745a53f49d2.png)

**Comment by okiehsch** [comment]
They completely revamped the site.
Fixed.
