### ISSUE TITLE
fantricks.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#840]
### Basic Information

**Test link:** `https://fantricks.com/%DA%86%DA%AF%D9%88%D9%86%DA%AF%DB%8C-%D9%BE%D8%A7%DA%A9-%DA%A9%D8%B1%D8%AF%D9%86-%D9%84%DA%A9%D9%87-%DB%8C%D9%82%D9%87-%D9%BE%DB%8C%D8%B1%D8%A7%D9%87%D9%86-%D9%85%D8%B1%D8%AF%D8%A7%D9%86%D9%87/`
**Category:** anti-adblock
**Reported from:** Iran
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.109

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
`t: other`: Anti-right-click and anti-select.
