### ISSUE TITLE
pornstreams.eu

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#841]
### Basic Information

**Test link:** `https://pornstreams.eu/`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.109

### Additional Message

(NSFW) popups on right click open in new tab or clicking play on video

**Comment by okiehsch** [comment]
Fixed.
