### ISSUE TITLE
laradiobbs.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#850]
### Basic Information

**Test link:** `http://www.laradiobbs.net/sygic/65415-android-sygic_gps_navigation-v-14-0-3-iberia-2014-03-radares-hud-loquendotts.html`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.107
**Extension:** Nano Defender 15.0.0.109

**Comment by okiehsch** [comment]
Fixed.
