### ISSUE TITLE
yoututosjeff.es

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#852]
### Basic Information

**Test link:** `https://www.yoututosjeff.es/`
**Category:** anti-adblock
**Reported from:** Peru
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.109

**Comment by jspenguin2017** [comment]
@okiehsch Anti-right click annoyance.

**Comment by okiehsch** [comment]
I don't see how to fix it , it is at the top of the document.

**Comment by jspenguin2017** [comment]
Interesting... For some unknown reason, redefining the property doesn't update the event handler.

**Comment by okiehsch** [comment]
I can fix it for Firefox and also there is an anti adblock message with Firefox only on my end.

**Comment by okiehsch** [comment]
Done.

**Comment by jspenguin2017** [comment]
New script snippet. Only accepts `null`, `true`, and `false` for now, will expand when needed.

**Comment by jspenguin2017** [comment]
We're getting so many reports now... From about 4 per day to about 8 per day. Interestingly the percentage of valid reports is still above 60%.

**Comment by okiehsch** [comment]
Maybe your user base doubled too but I have to say I would guess the daily issue reports at uAssets increased by a factor of 6 or 7 atleast since I started commiting, so who knows.
