### ISSUE TITLE
konten.co.id

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#855]
### Basic Information

**Test link:** `https://www.konten.co.id/2019/03/tagar-inaelectionobserversos-jadi-trending-dunia.html`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.109

### Additional Message

anti adblock pop up

**Comment by okiehsch** [comment]
Fixed.
