### ISSUE TITLE
farsondigitalwatercams.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#856]
### Basic Information

**Test link:** `https://www.farsondigitalwatercams.com/ad-blocker`
**Category:** anti-adblock
**Reported from:** United Kingdom
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.109

**Comment by okiehsch** [comment]
Fixed.
