### ISSUE TITLE
cazahoax.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#857]
### Basic Information

**Test link:** `https://cazahoax.com/hoax-mentira/trump-usa-esv%C3%A1stica-nazi-su-logo`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.122 Safari/537.36 Vivaldi/2.3.1440.61
**Extension:** Nano Defender 15.0.0.109

### Additional Message

Defender don't work in this page

**Comment by okiehsch** [comment]
Fixed.
