### ISSUE TITLE
denverpost.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#860]
### Basic Information

**Test link:** `https://www.denverpost.com/2019/03/15/denver-snow-sidewalk-shoveling-enforcement/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.109

**Comment by okiehsch** [comment]
Fixed.
