### ISSUE TITLE
nhentai.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#861]
### Basic Information

**Test link:** `https://nhentai.net/g/266687/2/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.109

### Additional Message

popup

**Comment by jspenguin2017** [comment]
Works fine for me, can't reproduce popup.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://nhentai.net/g/271272/`
**Category:** ads
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.106

### Additional Message

popup

**Comment by jspenguin2017** [comment]
@okiehsch Popup, kind of hard to reproduce. Can you have a look?

**Comment by jspenguin2017** [comment]
Hum... Could it be race condition?

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by jspenguin2017** [comment]
OK, I'll enforce the `open` filter with ND and watch for further reports.
