### ISSUE TITLE
dallas.culturemap.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#862]
### Basic Information

**Test link:** `http://dallas.culturemap.com/news/restaurants-bars/03-19-19-new-ramen-restaurant-jinya-victory-park/?utm_source=Instagram&utm_medium=Feed&utm_campaign=Edit`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Defender 15.0.0.109

**Comment by okiehsch** [comment]
Fixed.
