### ISSUE TITLE
ebay.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#872]
### Basic Information

**Test link:** `https://www.ebay.com/sch/i.html?_from=R40&_nkw=surface+book+&_sacat=0&rt=nc&LH_Complete=1`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.97

### Additional Message

All the listings disappear

**Comment by okiehsch** [comment]
Fixed.
