### ISSUE TITLE
sdfgdf.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#875]
### Basic Information

**Test link:** `http://sdfgdf.xyz/`
**Category:** anti-adblock
**Reported from:** United Arab Emirates
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.112

**Comment by okiehsch** [comment]
Fixed.
