### ISSUE TITLE
dragons.com.au

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#880]
### Basic Information

**Test link:** `https://www.dragons.com.au/news/2019/03/25/should-i-pick-you-in-fantasy-football/`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:65.0) Gecko/20100101 Firefox/65.0
**Extension:** Nano Defender 15.0.0.112

**Comment by okiehsch** [comment]
Fixed.
