### ISSUE TITLE
alghad.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#881]
### Basic Information

**Test link:** `https://alghad.com/%D8%A7%D9%84%D8%BA%D8%A7%D8%B1%D9%85%D8%A7%D8%AA/?fbclid=IwAR1g4G2fa1SnAjhGvj9fgxPJ3BCJ0YLKT8n2-Hee0kBELkcwJbsSGiozvuA`
**Category:** anti-adblock
**Reported from:** Israel
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.112

**Comment by okiehsch** [comment]
Fixed.
