### ISSUE TITLE
apkify.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#883]
### Basic Information

**Test link:** `https://apkify.com/manga-rock-premium-apk/`
**Category:** anti-adblock
**Reported from:** India
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.112

### Additional Message

DO somethins still detects ad-blocker

**Comment by okiehsch** [comment]
Fixed.
