### ISSUE TITLE
vemai.org

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#884]
### Basic Information

**Test link:** `https://vemai.org/ta-no-ar-a-tv-na-tv/`
**Category:** anti-adblock
**Reported from:** Brazil
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.112

**Comment by okiehsch** [comment]
Fixed.
