### ISSUE TITLE
architetturaecosostenibile.it

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#887]
### Basic Information

**Test link:** `https://www.architetturaecosostenibile.it/architettura/criteri-progettuali/materiali-coibentazione-edifici`
**Category:** anti-adblock
**Reported from:** Italy
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.112

**Comment by okiehsch** [comment]
Fixed.
