### ISSUE TITLE
nhk.or.jp

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#893]
### Basic Information

**Test link:** `https://www3.nhk.or.jp/nhkworld/en/news/videos/20190329121916265/`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.113

### Additional Message

Video won't play

**Comment by okiehsch** [comment]
Fixed.
