### ISSUE TITLE
go.bucketforms.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#894]
### Basic Information

**Test link:** `https://go.bucketforms.com/sf/fdb8b4e6`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.113

**Comment by okiehsch** [comment]
Fixed.
