### ISSUE TITLE
optifine.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#900]
### Basic Information

**Test link:** `https://optifine.net/adloadx?f=OptiFine_1.13.2_HD_U_E7.jar`
**Category:** ads
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3751.0 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.97

**Comment by okiehsch** [comment]
Fixed.
