### ISSUE TITLE
lavoixdux.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#906]
### Basic Information

**Test link:** `https://www.lavoixdux.com/2018/02/24/lart-du-deepthroat/`
**Category:** anti-adblock
**Reported from:** Tunisia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.117

**Comment by okiehsch** [comment]
Fixed.
