### ISSUE TITLE
phlame.pw

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#908]
### Basic Information

**Test link:** `http://phlame.pw/URRlDDGd`
**Category:** anti-adblock
**Reported from:** Vietnam
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
**Extension:** Nano Defender 15.0.0.117

### Additional Message

When open link a popup said disable adblock

**Comment by okiehsch** [comment]
Fixed.
