### ISSUE TITLE
vtm.be

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#911]
### Basic Information

**Test link:** `https://vtm.be/vtmgo/tegen-de-sterren-op~p537f5d0a-0ae7-44f6-a322-0084a124284c/seizoen-6/aflevering-1/99762611-9654-47fe-ac7b-ace4680fdb9e/afspelen`
**Category:** anti-adblock
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.118

### Additional Message

its a new tv site launched in belguim by tv corp VTM  it says to disable adblocker in dutch than 

the normal site `https://vtm.be/vtmgo`

Requires a account login is at the right top click on it then click on aanmelden first mail than pass

```
Test account redacted. See: https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/40
```

could you fix this? thanks

**Comment by jspenguin2017** [comment]
@okiehsch @mapx- If you guys want to access the secret issues tracker, post your GitLab ID here.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://vtm.be/vtmgo/allo-allo~p6c27ffbc-4fa5-406b-bfe5-6e97070497ca/seizoen-1/aflevering-1/db7af7ea-d4fd-4a1b-892e-f1d37dff20bb/afspelen`
**Category:** anti-adblock
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.118

### Additional Message

Anti-adblock still works on all videos on vtmgo.

**Comment by okiehsch** [comment]
>  post your GitLab ID here.

okiehsch

**Comment by jspenguin2017** [comment]
OK, you should have access now.

**Comment by okiehsch** [comment]
Yes.

**Comment by okiehsch** [comment]
The anti adblock message is fixed.

**Comment by jspenguin2017** [comment]
Are there other issues?

**Comment by okiehsch** [comment]
Pre roll ads, if you can find a way to disable them without breaking the player 👍

**Comment by jspenguin2017** [comment]
Yea, preroll ads confirmed. Is it SSAI?

**Comment by sonicwolfsdutch** [comment]
could you explain what SSAI stands for?

**Comment by mapx-** [comment]
> could you explain what SSAI stands for?

https://www.reddit.com/r/uBlockOrigin/comments/5fn9c7/serverside_ad_insertion_and_ad_blockers/

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://vtm.be/vtmgo/afspelen/ebde34f1c-4d6e-4cca-bb2a-61ff389905c8`
**Category:** anti-adblock
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36 OPR/63.0.3368.107
**Extension:** Nano Adblocker 1.0.0.127

### Additional Message

**Comment by jspenguin2017** [comment]
For https://github.com/NanoMeow/QuickReports/issues/911#issuecomment-539060260 : 
Requires account.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://vtm.be/vtmgo/afspelen/e126933c0-09d9-4cad-9076-e8859d66283a`
**Category:** anti-adblock
**Reported from:** Belgium
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.140

### Additional Message

You can hear the video playing in the background, but a screen is displayed on top.

**Comment by okiehsch** [comment]
Fixed.

**Comment by okiehsch** [comment]
I don't  get any pre-roll ads anymore by the way.
