### ISSUE TITLE
express.de

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#912]
### Basic Information

**Test link:** `https://www.express.de/sport/motorsport/vor-den-augen-von-mama-corinna-mick-schumacher-duepiert-im-ferrari-die-stars-32312576`
**Category:** anti-adblock
**Reported from:** Germany
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.75 Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.117

**Comment by okiehsch** [comment]
Fixed.
