### ISSUE TITLE
rogerk.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#913]
### Basic Information

**Test link:** `https://www.rogerk.net/forum/index.php?topic=32913.0`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.117

### Additional Message

use Cloudflare app named "AdBlock Minus"

`https://www.cloudflare.com/apps/ngqhM7rZolNP/install?version=1.0.2`

**Comment by jspenguin2017** [comment]
Looks like I need to repurpose my generic NoAdBlock defuser.
