### ISSUE TITLE
baskino.me

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#92]
### Basic Information

**Test link:** `http://baskino.me/films/boevie-iskustva/3039-oldboy.html`
**Category:** breakage
**Reported from:** Armenia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
**Extension:** Nano Defender 15.0.0.45

**Comment by jspenguin2017** [comment]
@ZaphodBeebblebrox are you sure you referenced the right issue?

**Comment by jspenguin2017** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/45578973-ca3a3f00-b841-11e8-9c7b-530d4c2ee520.png)

**Comment by ZaphodBeebblebrox** [comment]
Yeah, I referenced the wrong issue

**Comment by okiehsch** [comment]
> Works fine for me

Did you try with `RU AdList` enabled?

**Comment by jspenguin2017** [comment]
Yea, broken by the regional filter.

**Comment by okiehsch** [comment]
Fixed.
