### ISSUE TITLE
mobilinks.info

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#920]
### Basic Information

**Test link:** `https://mobilinks.info/?naippKhuZGOqpKGjlpinladimKOiY66tZWWWamlnap%2BhaA%3D%3D`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.120

### Additional Message

detects ad-blocker

**Comment by jspenguin2017** [comment]
Has an empty ads placeholder, but can't reproduce anti-adblock.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mobilinks.info/?naippG9jZKGWpp6ilmGXp2Oop52lo5limKOiY4GVqKiKpJmVqZl5lamZdqKZfJqgpWKprKk%3D`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.120

### Additional Message

Dont use AdBlock or you wont be able to see Download link!

**Comment by jspenguin2017** [comment]
Still can't reproduce anti-adblock.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mobilinks.info/?naippG9jZJaeqGOgrmNngHiMbX%2Bj`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.121

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mobilinks.info/?naippKhuZGOYoKSpmWKilZ6gY6aqY6Wpl6Cel2R1p21pY591l3iXgKZ7aQ%3D%3D`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.121

### Additional Message

**Comment by jspenguin2017** [comment]
Still can't reproduce anti-adblock.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mobilinks.info/?naippKhuZGOlo6ionqGcYpiXZJ2ilZyZZGyho6ChbqyfrmQ%3D`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.121

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mobilinks.info/?naippKhuZGOWoqSim52hmWOXpKFkZWpll5WYZmaiZWOjo6mZqJOloGyTr52l`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mobilinks.info/?naippKhuZGOsq6xir5mplWKppaCklZmZp2KYo6JjmqdkZWxoamZnaW5naA%3D%3D`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

Dont use AdBlock or you wont be able to see Download link!

**Comment by jspenguin2017** [comment]
Still can't reproduce anti-adblock. May need referrer, they may serve a decoy page when directly accessed.

**Comment by llacb47** [comment]
Here: `https://www.mobilneforum.pl/showthread.php?76564-MX-Player-Pro/page151#post_1596429`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://mobilinks.info/?naippKhuZGOYoKSpmWKilZ6gY6aqY6Wpl6Cel2RqeZWFY5h8qp2bdaemrQ%3D%3D`
**Category:** anti-adblock
**Reported from:** Bulgaria
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.123

### Additional Message

Non utilizzare AdBlock perchè impedisce di vedere il link per il Dowlnoad 
Dont use AdBlock or you wont be able to see Download link!

**Comment by jspenguin2017** [comment]
@okiehsch @mapx- Any update on this?

**Comment by mapx-** [comment]
I get no anti adb behavior

**Comment by jspenguin2017** [comment]
That's weird... I can reproduce. 
![image](https://user-images.githubusercontent.com/7283682/62490186-f1fe0280-b785-11e9-9970-0c3f986ba97a.png)
