### ISSUE TITLE
oms.veuclips.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#922]
### Basic Information

**Test link:** `http://oms.veuclips.com/player/html/8Fhzf9c254?popup=yes&autoplay=1`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.120

**Comment by okiehsch** [comment]
Fixed.
