### ISSUE TITLE
medicinenet.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#926]
### Basic Information

**Test link:** `https://www.medicinenet.com/malaria_facts/article.htm`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.120

### Additional Message

part of g00 ads are loading

the empty ad block `::after` pseudoclass is loading the image as background: 
`https://c-7npsfqifvt34x24jnbhftx2enfejdjofofux2edpn.g00.medicinenet.com/g00/3_c-7x78x78x78.nfejdjofofu.dpn_/c-7NPSFQIFVT34x24iuuqtx3ax2fx2fjnbhft.nfejdjofofu.dpnx2fjnbhftx2fbetx2fsjhiube_upqusbotqbsfou.hjgx3fj21d.nbslx3dopuIUNM_$/$/$/$`

**Comment by okiehsch** [comment]
That is Instart Logic, @jspenguin2017 don't you include `uBO-extra` in Nano?

**Comment by jspenguin2017** [comment]
Yes, uBO-Extra is included in ND, but not in the Firefox port.
