### ISSUE TITLE
m.kuku.lu

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#927]
### Basic Information

**Test link:** `https://m.kuku.lu/index.php`
**Category:** anti-adblock
**Reported from:** Peru
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.120

### Additional Message

It detects adblock when you try to use the function "Create address with expiration"

Screenshot:

`https://pbs.twimg.com/media/D3SZA_fWwAANVzC.png`

Regards

**Comment by okiehsch** [comment]
Fixed.
