### ISSUE TITLE
turkseed.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#932]
### Basic Information

**Test link:** `http://turkseed.com/index.php`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.121

### Additional Message

blockadblock content

**Comment by jspenguin2017** [comment]
Has a few empty ads placeholders, but can't reproduce anti-adblock.

**Comment by DandelionSprout** [comment]
Placeholders:
```
! https://turkseed.com/index.php
||i.ibb.co^$image
turkseed.com##.pluginWrapper:last-of-type
```

**Comment by llacb47** [comment]
`ibb.co` is a legit imagehost...

**Comment by DandelionSprout** [comment]
I suppose I can narrow it down to `||i.ibb.co/*reklam-*.gif^$domain=turkseed.com` then. Thanks for the feedback.
