### ISSUE TITLE
nrj-play.fr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#934]
### Basic Information

**Test link:** `https://www.nrj-play.fr/nrj12/direct`
**Category:** anti-adblock
**Reported from:** France
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.75 Chrome/73.0.3683.75 Safari/537.36
**Extension:** Nano Defender 15.0.0.121

**Comment by okiehsch** [comment]
An account is needed for the video to play, so I can't be sure this fixes all issues.

**Comment by jspenguin2017** [comment]
Let's call it good and wait for further reports.
