### ISSUE TITLE
boo.tw

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#939]
### Basic Information

**Test link:** `http://boo.tw/lcXV1`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.61 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.101

### Additional Message

button doesn't show

**Comment by mapx-** [comment]
**nsfw** for the final destination
