### ISSUE TITLE
muzlan.top

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#943]
### Basic Information

**Test link:** `https://muzlan.top/en/search/Kat+Roman+Kostrzewski`
**Category:** anti-adblock
**Reported from:** Poland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.121

**Comment by mapx-** [comment]
or
```
@@||muzlan.top^$xhr,1p
@@||muzlan.top^$generichide
```
