### ISSUE TITLE
kinozal-tv.appspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#951]
### Basic Information

**Test link:** `https://kinozal-tv.appspot.com/`
**Category:** breakage
**Reported from:** Ukraine
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.61 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

white screen

**Comment by mapx-** [comment]
blocked by `ruadlist` for some reason
`$domain=a-dot-kinozal-tv.appspot.com|kinozal-me.appspot.com|kinozal-tv.appspot.com`

@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Appspot-mirrors kinozal.tv are created by private individuals and have no relation to the source site. They block access to the site to those who block ads. And to change the rules in the filters react very quickly.

Ultimately, I completely blocked them: 
https://hg.adblockplus.org/ruadlist/rev/37a3ad04eda0
https://hg.adblockplus.org/ruadlist/rev/234b6801940f

Use official sites and their mirrors:
kinozal.tv
kinozal.guru
kinozal.website

**Comment by jspenguin2017** [comment]
Can you change it to: 
```
||a-dot-kinozal-tv.appspot.com^
||kinozal-me.appspot.com^
||kinozal-tv.appspot.com^
```

So it triggers strict blocking screen?

**Comment by jspenguin2017** [comment]
`t: other`: Malicious websites

**Comment by dimisa-RUAdList** [comment]
https://hg.adblockplus.org/ruadlist/rev/686e00a57795
