### ISSUE TITLE
davidstea.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#952]
### Basic Information

**Test link:** `https://www.davidstea.com/ca_en/tea/loose-leaf-tea/oolong/`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

the buttons on the site are not clickable.

**Comment by okiehsch** [comment]
Fixed.
