### ISSUE TITLE
technicalguru.us

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#953]
### Basic Information

**Test link:** `https://technicalguru.us/angular-nodejs-mean-stack-guide-udemy/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.124

### Additional Message

adblocker detected

**Comment by okiehsch** [comment]
Fixed.
