### ISSUE TITLE
kzstock.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#958]
### Basic Information

**Test link:** `https://kzstock.blogspot.com/2019/04/edge-20190408.html`
**Category:** breakage
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.61 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

**Comment by jspenguin2017** [comment]
@okiehsch False positive. Tried regional filters. 
![image](https://user-images.githubusercontent.com/7283682/56473934-9fdfde00-642f-11e9-88db-6f7d0d382abe.png)

**Comment by okiehsch** [comment]
Thanks.
