### ISSUE TITLE
slimes.io

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#96]
### Basic Information

**Test link:** `https://slimes.io/`
**Category:** anti-adblock
**Reported from:** Singapore (Opera VPN Datacenter)
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 OPR/55.0.2994.61
**Extension:** Nano Defender 15.0.0.45

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/45598373-29aa6300-b998-11e8-9760-47a7be531aff.png)

**Comment by okiehsch** [comment]
Fixed.
