### ISSUE TITLE
dausel.co

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#961]
### Basic Information

**Test link:** `https://dausel.co/AZRSq`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Defender 15.0.0.125

### Additional Message

Doesn't let you progress to the next page or show captcha until disable adblock

**Comment by jspenguin2017** [comment]
@okiehsch Captcha doesn't load, also has a small ads placeholder.
