### ISSUE TITLE
kbb.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#964]
### Basic Information

**Test link:** `https://www.kbb.com/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

Im having problems while trying to open any links on kbb.com doesnt want to load to next screen while trying to see a cars value and basically any other action on the site it doesnt want to load the next screen while nano block is active.

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/56474259-89885100-6434-11e9-8875-fa287b8dca7e.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.kbb.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0
**Extension:** Nano Defender 15.0.0.153

### Additional Message

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.kbb.com/`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.124

### Additional Message

Original URL: `https://www.kbb.com/new-cars/`

**Comment by jspenguin2017** [comment]
@okiehsch Anti-adblock on original URL. Triggers when scrolling down. 
![image](https://user-images.githubusercontent.com/7283682/64067767-e538c700-cbea-11e9-922b-87abd58b2b54.png)
