### ISSUE TITLE
mlbstreams.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#965]
### Basic Information

**Test link:** `http://mlbstreams.net/toronto-blue-jays-mlb-live-stream/`
**Category:** other
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.124

### Additional Message

Fake "watch now" button at top of page

`||nbastream.net/wp-content/uploads/2017/06/btn2.png$image` fixes the issue

**Comment by jspenguin2017** [comment]
@okiehsch Fake button
![image](https://user-images.githubusercontent.com/7283682/56474282-f1d73280-6434-11e9-9e7c-97c1b015b2ca.png)

**Comment by jspenguin2017** [comment]
Also `pl.allsports4free.club` badware risk?

**Comment by okiehsch** [comment]
Fixed.
