### ISSUE TITLE
vsthouse.ru

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#966]
### Basic Information

**Test link:** `http://vsthouse.ru/`
**Category:** anti-adblock
**Reported from:** Czechia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.124

### Additional Message

just loaded also Russian & Polish filters but the Ant-adblock still remains active

**Comment by okiehsch** [comment]
Fixed.

**Comment by dimisa-RUAdList** [comment]
https://hg.adblockplus.org/antiadblockfilters/rev/35356f355144
https://hg.adblockplus.org/ruadlist/rev/429f3038d0db#l1.13
