### ISSUE TITLE
mylink.how

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#968]
### Basic Information

**Test link:** `https://mylink.how/`
**Category:** anti-adblock
**Reported from:** Denmark
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

Original URL: `https://mylink.how/v/2/cash`

anti-adblock dont work

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/aeafa588f29724c896fee8b86781c807d79a3350
