### ISSUE TITLE
worldnovel.online

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#969]
### Basic Information

**Test link:** `https://www.worldnovel.online/solo-leveling-chapter-140-indo/`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.105 Safari/537.36 Vivaldi/2.4.1488.38
**Extension:** Nano Adblocker 1.0.0.103

**Comment by okiehsch** [comment]
Fixed.
