### ISSUE TITLE
knshow.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#97]
### Basic Information

**Test link:** `https://www.knshow.com/`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
**Extension:** Nano Defender 15.0.0.42

**Comment by jspenguin2017** [comment]
Also anti-copy, anti-select, and anti-right-click.

**Comment by jspenguin2017** [comment]
@okiehsch Do you want to fix anti-copy, anti-select, and anti-right-click in uBlock annoyance filter?

**Comment by okiehsch** [comment]
Added, thx.
