### ISSUE TITLE
techradar.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#971]
### Basic Information

**Test link:** `https://www.techradar.com/reviews/tp-link-archer-c5400-v2`
**Category:** anti-adblock
**Reported from:** Switzerland
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.125

**Comment by jspenguin2017** [comment]
Has a few small ads placeholders. Can't reproduce anti-adblock. 
![image](https://user-images.githubusercontent.com/7283682/56474363-0ec03580-6436-11e9-88cc-47115e1bb437.png)

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.techradar.com/news/a-technical-glitch-has-broken-everyones-firefox-extensions`
**Category:** anti-adblock
**Reported from:** South Africa
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.139

### Additional Message

Website still detecting ad-blocker (uBlock Origin for Firefox)

**Comment by jspenguin2017** [comment]
Still can't reproduce anti-adblock.
