### ISSUE TITLE
imtranslator.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#972]
### Basic Information

**Test link:** `http://imtranslator.net/Translator-for-Opera-Imtranslator.asp`
**Category:** anti-adblock
**Reported from:** Spain
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36 OPR/60.0.3255.27
**Extension:** Nano Defender 15.0.0.125

### Additional Message

`http://imtranslator.net/Translator-for-Opera-Imtranslator.asp`

**Comment by okiehsch** [comment]
Fixed.
