### ISSUE TITLE
autosmdeisy.ltd

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#973]
### Basic Information

**Test link:** `https://autosmdeisy.ltd/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.124

### Additional Message

Original URL: `https://autosmdeisy.ltd/faucet.php?&address=DBpT97kkGanUjx42TjMWdG3KCdqCBbsHqn&currency=DOGE&key=56bc78e687d4eade08860ec25a60ca64&sl=faIjgCQzuh`

**Comment by okiehsch** [comment]
Fixed.
