### ISSUE TITLE
faucetspro.xyz

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#974]
### Basic Information

**Test link:** `https://faucetspro.xyz/security/pages/adblocker-detected.php`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
**Extension:** Nano Defender 15.0.0.124

**Comment by okiehsch** [comment]
Fixed.
