### ISSUE TITLE
drive.klop.me

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#981]
### Basic Information

**Test link:** `https://drive.klop.me/file/432e05`
**Category:** ads
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

not blocking some ads

**Comment by okiehsch** [comment]
Fixed.
