### ISSUE TITLE
getcoin.site

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#984]
### Basic Information

**Test link:** `https://getcoin.site/bitcoin/`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0
**Extension:** Nano Defender 15.0.0.124

**Comment by okiehsch** [comment]
Fixed.
