### ISSUE TITLE
kharisma-adzana.blogspot.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#990]
### Basic Information

**Test link:** `https://kharisma-adzana.blogspot.com/2018/07/cara-mengatasi-welcome-page-wifi-id-tidak-muncul.html?m=1`
**Category:** anti-adblock
**Reported from:** Indonesia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Android 6.0.1; Mobile; rv:66.0) Gecko/66.0 Firefox/66.0
**Extension:** Nano Defender 15.0.0.124

**Comment by okiehsch** [comment]
Fixed.
