### ISSUE TITLE
cdnperf.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#991]
### Basic Information

**Test link:** `https://www.cdnperf.com/`
**Category:** breakage
**Reported from:** Canada
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

graph not showing

**Comment by mapx-** [comment]
fixed
