### ISSUE TITLE
banggood.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#992]
### Basic Information

**Test link:** `https://www.banggood.com/2500mW-A3-30x40cm-Desktop-DIY-Violet-Laser-Engraver-Picture-CNC-Printer-Assembling-Kits-p-1003863.html?rmmds=category`
**Category:** breakage
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
**Extension:** Nano Adblocker 1.0.0.103

### Additional Message

pricing doesnt work

**Comment by mapx-** [comment]
@ryanbr
