### ISSUE TITLE
hackingwithreact.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#994]
### Basic Information

**Test link:** `http://www.hackingwithreact.com/read/1/40/linting-react-using-airbnbs-eslint-rules`
**Category:** anti-adblock
**Reported from:** Australia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
**Extension:** Nano Defender 15.0.0.126

**Comment by mapx-** [comment]
fixed
