### ISSUE TITLE
solarmoviez.run

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#997]
### Basic Information

**Test link:** `https://solarmoviez.run/film/alpha/1PSNL`
**Category:** ads
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.127

### Additional Message

REDIRECTS NOT BEING BLOCKED

**Comment by mapx-** [comment]
fixed
