### ISSUE TITLE
javgay.co

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#999]
### Basic Information

**Test link:** `https://www.javgay.co/?alobaidi_detect_adblock=true`
**Category:** anti-adblock
**Reported from:** Japan
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
**Extension:** Nano Defender 15.0.0.127

**Comment by mapx-** [comment]
**NSFW**

**Comment by jspenguin2017** [comment]
Hum... Looks like the website is blacklisted by Google.
